### ISSUE TITLE
remove more optional tags

### ISSUE THREAD

**Issue by paulirish** [kangax/html-minifier#1]
these are probably the safest to add to the list:

```
</li>, </dt>, </dd>, </img>, </source>
```

**Comment by kangax** [comment]
Thanks for suggestions! From what I can see, `img` element has EMPTY content model, so can not have end tag. Ditto for `source` element (although as of now, I've really only targeted HTML 4.01). Removing `</li>`, `</dt>` and `</dd>` is theoretically safe, but I see that some browsers engage in some weird error-correction. For example, _invalid_ markup like this — `<ul><li>foo</li>x<li>bar</li>x</ul>` — renders in FF3.6 as a list of 2 elements with "x" char following each item _on a new line_ (making a list of 4 rows). If we were to remove `</li>` tags, the list would consist of 2 rows only, with "x" character appended right after "foo" and right after "bar". On the other hand, tolerating such invalid markup is probably not a good idea in the first place.

**Comment by mathiasbynens** [comment]
All these are optional:

```
</html>
</head>
</body>
</p>
</dt>
</dd>
</li>
</option>
</thead>
</th>
</tbody>
</tr>
</td>
</tfoot>
</colgroup>
```

Some of them are already being removed by the minifier.

I’m not aware of any problems with omitting the closing table elements like `</td>`. Anyone?

I agree tolerating invalid markup is not a good idea. The HTML minifier should expect valid, conforming markup.

**Comment by mathiasbynens** [comment]
> From what I can see, `img` element has EMPTY content model, so can not have end tag. 

Well, it can in (proper) XHTML.

**Comment by SunboX** [comment]
https://developers.google.com/speed/articles/optimizing-html?hl=de&csw=1

**Comment by kangax** [comment]
I've added remaining optional tags from @mathiasbynens list, except `</p>` and `</li>` to play it safe for now (no time to test edge/complex cases with unclosed `<p>` / `<li>`, but I'm all ears if anyone finds something)
