### ISSUE TITLE
version 0.5.5?

### ISSUE THREAD

**Issue by thesamet** [kangax/html-minifier#100]
Is there a plan to release a new minor version? I am looking forward for the fix of #91 so I can use removeAttributeQuotes again...

**Comment by kangax** [comment]
Sure, can you send PR? I'll `npm publish` it.

**Comment by XhmikosR** [comment]
:+1: 

I'm mostly interested in PR #94 which makes the plugin unusable since Jekyll outputs HTML this way.

**Comment by thesamet** [comment]
@kangax sorry for not getting into this - I am traveling right now so I'd suggest asking someone else.

**Comment by kangax** [comment]
Pushed 0.5.5

**Comment by XhmikosR** [comment]
Awesome, thanks!
