### ISSUE TITLE
Doesn't seem to compress from CLI

### ISSUE THREAD

**Issue by vermiculus** [kangax/html-minifier#1019]
I can't imagine this is not an issue with my own environment, but I can't figure out what's going on.

```sh
$ echo '<html>   <p>      hello, world </p>    </html>' | html-minifier
<html>   <p>      hello, world </p>    </html>
```
As you can see, passing valid, messy HTML through the minifier on stdio isn't actually presenting any change. I've also tried the `html-minifier [input-file [-o output-file]]` pattern with similar results.

I'm using html-minifier for the messy output of a static site generator (Hugo); while I could probably answer any question about the database and other pieces of the tech stack I use at work, we don't have much use for web sites / node, so I'm not very familiar with these tools at all ☹️

Version information – let me know what else I can provide. I know this isn't a lot to go on.
```sh
$ html-minifier --version
4.0.0
$ npm --version
6.7.0
$ node --version
v11.11.0
```

---

If it's of any consequence, using `html-minifier --input-dir messy --output-dir clean` gives me a *lot* of garbage output (at least not human-readable) and generated `clean` that appears to just be a copy of `messy` – HTML content is similarly unaltered.

Thanks for any help – I really appreciate it.

**Comment by DamonHD** [comment]
Do you need to explicitly specify  --collapse-whitespace?

The full set of options I use is in the script at:

http://earth.org.uk/script/html5-minify.sh

Rgds

Damon

**Comment by vermiculus** [comment]
I don't know what about my environment changed (I have restarted my shell since, but I'm not sure if anything else changed), but it's working now. I don't even need to supply `--collapse-whitespace`.

Thank you!
