### ISSUE TITLE
Parser should ignore comments

### ISSUE THREAD

**Issue by speedyhoon** [kangax/html-minifier#1021]
The parser doesn't ignore malformed HTML wrapped in comments.

`<!-- htmlmin:ignore --><input{{a " autofocus" .isAutoFocus}}><!-- htmlmin:ignore -->`

Output:
`Minification error:
Parse Error: <input{{a " autofocus" .isAutoFocus}}>`

Expected:
`<input{{a " autofocus" .isAutoFocus}}>`

**Comment by alexlamsl** [comment]
Working as expected with latest version of `html-minifier`:
```sh
$ cat test.html
<!-- htmlmin:ignore --><input{{a " autofocus" .isAutoFocus}}><!-- htmlmin:ignore -->

$ html-minifier test.html
<input{{a " autofocus" .isAutoFocus}}>
```
[Online version](https://kangax.github.io/html-minifier/) also works.
