### ISSUE TITLE
Which option will strip the whitespace.

### ISSUE THREAD

**Issue by nsisodiya** [kangax/html-minifier#1024]
input 

```html
<h1 style=margin:0><a aria-current=page style=color:white;text-decoration:none href=/ >Rivigo | Home</a></h1>
```

output needed
```html
<h1 style=margin:0><a aria-current=page style=color:white;text-decoration:none href=/>Rivigo | Home</a></h1>
```

I tried few options, but unable to reach from `href=/ >Rivigo` to `href=/>Rivigo`

**Comment by nsisodiya** [comment]
Here is the code
```js
var minify = require('html-minifier').minify;
var input =
  '<h1 style="margin:0"><a aria-current="page" style="color:white;text-decoration:none" class="" href="/">Rivigo | Home</a></h1>';
var output = minify(input, {
  useShortDoctype: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  collapseBooleanAttributes: true,
  minifyJS: true,
  collapseWhitespace: true,
  removeEmptyAttributes: true,
  removeTagWhitespace: true,
  removeAttributeQuotes: true
});
```

If I remove `removeAttributeQuotes: true` then I stop getting the space but I need `removeAttributeQuotes: true` to trim down html.

**Comment by nsisodiya** [comment]
Adding  `sortAttributes: true` Fixed this issue.

**Comment by DamonHD** [comment]
Note that / immediately before a > tag close is ambiguous and looks like a self-closing tag, eg
<br/>

To avoid this problem, if the final character of the attribute value is / then the value needs to be quoted, or have a space after it, or the attribute moved to somewhere other than final.

In other words:

    ... href=/>

probably doesn't mean what you want it to.

Rgds

Damon
