### ISSUE TITLE
with nunjuck template parse error

### ISSUE THREAD

**Issue by lcat** [kangax/html-minifier#1029]
```html
<!-- template -->
<div>{% if index < 10 %}{% endif %}</div>
```

result:
Error: Parse Error: < 10 %}{% endif %}</div>

hey guy, I want parse html with nunjucks to nodejs. But if hav `<` will parse error. How should I solve it?

**Comment by alexlamsl** [comment]
Convert `<` to `&lt;`, or use `continueOnParseError`
