### ISSUE TITLE
collapseWhitespace can drop spaces between words

### ISSUE THREAD

**Issue by olegjs** [kangax/html-minifier#103]
For example:

```
<p>
[tab]line1
[tab]line2
</p>
```

(where [tab] is an actual tab and there are no whitespace characters at line ends) will end up as 

```
<p>line1line2</p>
```

**Comment by XhmikosR** [comment]
Did you try the latest master? I think it is related to https://github.com/kangax/html-minifier/pull/94

**Comment by kangax** [comment]
Yep, just checked and it works in master.
