### ISSUE TITLE
Running on browser

### ISSUE THREAD

**Issue by angrykoala** [kangax/html-minifier#1030]
Due to a tool I'm working on, I would need to minify a portion of HTML code in the browser. However, I'm not able to make this library work due to dependencies with `fs`

Is there a way to use this library (or an alternative) in browser?

**Comment by alexlamsl** [comment]
[First link](https://kangax.github.io/html-minifier/) under `README.md` :wink:

Usable code is stored under `/dist`

**Comment by angrykoala** [comment]
Thanks, A note in the README of this point could be helpful
