### ISSUE TITLE
Switch default JS minifier to Terser?

### ISSUE THREAD

**Issue by dead-claudia** [kangax/html-minifier#1034]
Terser, a fork of `uglify-es`, has been stable for roughly a year, and provides ES6+ support by default, making it suitable to minify inline `<script type="module">`. It has a nearly 100% compatible API, and based on looking at the code base, swapping it out initially seems to be a 10-line change that's exclusively just changing names.

Could this change be made? It'd also unblock minifying code in `<script type="module">` bodies.

**Comment by dead-claudia** [comment]
Do note that they dropped Node support < 4 and that their optimizations are founded on a few more assumptions than Uglify's.

**Comment by alexlamsl** [comment]
Not in the foreseeable future, sorry.
