### ISSUE TITLE
<p>111<222</p> is error

### ISSUE THREAD

**Issue by MrLeeGit** [kangax/html-minifier#1039]
Error: Parse Error: <222</p><p> </p>

**Comment by DamonHD** [comment]
Yes, it is an error.

Did you mean 111&amp;lt;222 by any chance?

Rgds

Damon

**Comment by MrLeeGit** [comment]
Yes. It happens every time. Could you please do me a favor? Is there any solutions?

Rgds
Li

**Comment by DamonHD** [comment]
I don't understand your question.

Don't use raw '&lt;' in HTML text, ie always escape it?

Rgds

Damon

**Comment by MrLeeGit** [comment]
oh! silly me!
Got it!  There's something wrong with '<' in HTML text.
Thank you so much.
Rgds
Li
