### ISSUE TITLE
issue with uglify-js and require.resolve

### ISSUE THREAD

**Issue by DanielRuf** [kangax/html-minifier#1048]
I get `require.resolve is not a function` when using the latest version of html-minifier for https://github.com/foundation/foundation-web-inliner

Wouldn't be terser even better than the unmaintained uglify-js?

**Comment by DanielRuf** [comment]
See also https://github.com/browserify/browserify/issues/1832

**Comment by alexlamsl** [comment]
Not even sure if you are serious or trolling.

**Comment by DanielRuf** [comment]
This is a legit bugreport.

Not sure what you mean with trolling.

**Comment by DanielRuf** [comment]
But I will keep that in mind that you are not interested to point to a solution or fix that for browserify =)
