### ISSUE TITLE
<!doctypehtml>

### ISSUE THREAD

**Issue by timovn** [kangax/html-minifier#1053]
Hi all,

Trying in this tool : https://kangax.github.io/html-minifier/

I tried minimizing the source-code of that same page. The minimized code does not [validate](https://validator.w3.org/nu/#textarea).
Particularily, the `<!DOCTYPE html>` is reduced to `<!doctypehtml>`, which is not okay.

_To reproduce:_
- Copy this minimal HTML code:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>Page</title>
</head>
<body>
	<div class="mydiv">Stuff</div>
</body>
</html>
```

- paste it on that same page
- minify it
- try to [validate](https://validator.w3.org/nu/#textarea) the minified code.

**Result:**

Minified code is 
```
<!doctypehtml><html lang=en><meta charset=UTF-8><title>Page</title><div class=mydiv>Stuff</div>
```
Which is not valid:

> Error: Missing space before doctype name.
> At line 1, column 10

**Expectation:**

Minified code should be valid, ie be atleast this:
```
<!doctype html><html lang=en><meta charset=UTF-8><title>Page</title><div class=mydiv>Stuff</div>
```

**End notes**

This is the only error on my minimal HTML code example.
If you try minifying the HTML of the online tool itself, you’ll find another error, most similar.

Appart from that it seems to do the job. Thanks for that all!

**Comment by DamonHD** [comment]
It is known to work, even if not strictly valid; please see previous discussion.

There is presumably a flag to turn this behaviour off if you don't want it.

Rgds

Damon

**Comment by Yash-Singh1** [comment]
Yes, I have tested `<!doctypehtml>` and it works. You can use the configuration to remove short `doctype` on minification.

**Comment by j9t** [comment]
> Minified code should be valid

I second that. Is this still being looked at?

**Comment by R4356th** [comment]
> 
> 
> > Minified code should be valid
> 
> I second that. Is this still being looked at?

Disabling this is as simple as disabling ``useShortDoctype``.

**Comment by j9t** [comment]
> Disabling this is as simple as disabling `useShortDoctype`.

That doesn’t look like a solution, but like a hack. It doesn’t make sense for an HTML minifier not to output valid HTML, and that’s why minified documents (especially when already valid) should stay valid. That includes keeping a valid DOCTYPE.

**Comment by R4356th** [comment]
> > Disabling this is as simple as disabling `useShortDoctype`.
> 
> That doesn’t look like a solution, but like a hack. It doesn’t make sense for an HTML minifier not to output valid HTML, and that’s why minified documents (especially when already valid) should stay valid. That includes keeping a valid DOCTYPE.

This is an official solution, whether or not you consider it a hack is up to you but the config is disabled by default (except in the website).

**Comment by XhmikosR** [comment]
Happy to include a PR to change this behavior to be valid HTML. Please make sure there are tests :)

**Comment by mathiasbynens** [comment]
See https://github.com/kangax/html-minifier/pull/970. This is a feature, not a bug!

**Comment by XhmikosR** [comment]
~~Sorry, I personally don't see it as a feature, unless the validator doesn't follow the specs. In which case, we can open an upstream issue, otherwise, saving one space is not worth outputting invalid HTML.~~

Thought about it more and it's OK after all, since the option to remove inline whitespace is also needed.

**Comment by mathiasbynens** [comment]
> Sorry, I personally don't see it as a feature, unless the validator doesn't follow the specs. In which case, we can open an upstream issue, otherwise, saving one space is not worth outputting invalid HTML.

We do follow the spec. #970 points to the relevant section in the spec that describes exactly this situation: https://html.spec.whatwg.org/multipage/parsing.html#parse-error-missing-whitespace-before-doctype-name

If you want valid HTML, you need to disable the `removeTagWhitespace` option.

**Comment by XhmikosR** [comment]
Yeah, I edited my comment, all good :)

**Comment by j9t** [comment]
Just for understanding, is the thinking here that `removeTagWhitespace` [because that needs to be enabled just like `useShortDoctype `] leads to invalid output anyway, so let’s accept that for the DOCTYPE? (That seems to check out.)

**Comment by XhmikosR** [comment]
Yup :)

**Comment by XhmikosR** [comment]
I'm going to disable `removeTagWhitespace` on the website  by default. Currently it's enabled.

**Comment by mathiasbynens** [comment]
IMHO, validating minified HTML is like trying to lint minified JavaScript code — you're validating the wrong thing! We should be validating the authored, unminified HTML, and then ideally trusting the HTML minifier to do its job.

**Comment by XhmikosR** [comment]
Yeah, but it's unsafe and we do have other unsafe options disabled by default. Disabling `removeTagWhitespace` on the website too brings things on par with the CLI :)

**Comment by j9t** [comment]
> IMHO, validating minified HTML is like trying to lint minified JavaScript code — you're validating the wrong thing! We should be validating the authored, unminified HTML, and then ideally trusting the HTML minifier to do its job.

I’d beg to differ (largely because of [the current shape of frontend dev](https://meiert.com/en/blog/critical-frontend-development/)) but it’s an interesting conversation to be had. Probably not here though?
