### ISSUE TITLE
No support for ES6 features

### ISSUE THREAD

**Issue by pPanda-beta** [kangax/html-minifier#1054]
I guess the version of uglifyjs doesn’t support es6.

Minimalistic test data : 

```html
<script>
const x = 123;
const y = () => {
    console.log("Nothing");
};
</script>
```

Expected output: 
```html
<script>const x=123,y=()=>{console.log("Nothing")};</script>
```

Suggestions: Please use **babel-minify** along with **uglifyjs**.

**Comment by DanielRuf** [comment]
Please see https://github.com/kangax/html-minifier/issues/1040

**Comment by DanielRuf** [comment]
> **uglifyjs**.

This does not support ES6. And uglify-es has also many issues. `terser`is the new solution now.

**Comment by XhmikosR** [comment]
Closing as duplicate of #1040.
