### ISSUE TITLE
Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by elite174** [kangax/html-minifier#1058]
I'm trying to use html-minifier in node (via require). 
![image](https://user-images.githubusercontent.com/13636224/72718425-f7f66d00-3b86-11ea-8c4c-55b853723b55.png)

I also use typescript and webpack for my project.
![image](https://user-images.githubusercontent.com/13636224/72718478-13617800-3b87-11ea-8416-43dcd0135d98.png)

![image](https://user-images.githubusercontent.com/13636224/72718493-1d837680-3b87-11ea-92fc-7dfd6249c68e.png)

The bundle file produces this error after bundling: 
![image](https://user-images.githubusercontent.com/13636224/72718568-3e4bcc00-3b87-11ea-9549-091b1b26d6ad.png)

@kangax, please, help! I don't get what am I doing wrong.

**Comment by Poweranimal** [comment]
I'm getting the exact same error...
Did you find a solution?

**Comment by Poweranimal** [comment]
Ok, I found the solution for the issue.
Since you (and me) are using es6, we need to install:
`html-minifier-terser`
