### ISSUE TITLE
HTMLMinifier will delete <canvas> tags - fix?

### ISSUE THREAD

**Issue by hirschferkel** [kangax/html-minifier#1060]
`<canvas> `tag will be erased with HTMLMinifier but it should not! Working e.g. with chart.js needs the `<canvas> `tag to draw the chart. Is it possible to fix it?

**Comment by DanielRuf** [comment]
It should be supported, see https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L419

Can you provide a reproducible testcase?

<img width="617" alt="Bildschirmfoto 2020-02-02 um 15 48 07" src="https://user-images.githubusercontent.com/827205/73610018-74e80480-45d3-11ea-9da4-8312d6bb6f80.png">

**Comment by hirschferkel** [comment]
@Daniel: here is my example. **div htmllegend and canvas element** will vanish in sublime (although it will work online on https://kangax.github.io/html-minifier/):

```
<!DOCTYPE html><head>
</head>
<body>
	 <div class="chartcontainer">
	   <h1>Economic</h1>
	   <h2>Gross</h2>
	   <div id="htmllegend"></div>
		 <canvas id="Macro 1"></canvas>
<!--  <button id="hideLEgend">Hide/Show Legend</button>-->
    </div>      
       	<script src="papaparse.min.js"></script>     
 		<script type="text/javascript" src="EcoIndscript"></script>
    </body>
</html>
```
will get
```
<div class=chartcontainer><h1>Economic</h1><h2>Gross</h2></div><script src=papaparse.min.js></script><script src=EcoIndscript></script>
```

**Comment by DanielRuf** [comment]
> will vanish in sublime

What is used in sublime? I've never seen html-minifier there. How do you use it there?

**Comment by hirschferkel** [comment]
It's used together with Formatter: https://github.com/bitst0rm-pub/Formatter
![Html-Minifier](https://user-images.githubusercontent.com/16016422/73658883-711cb680-4695-11ea-8fde-73a6ee690a32.gif)

**Comment by DanielRuf** [comment]
Well, there is an option enabled in Formatter which removes empty elements:

https://github.com/bitst0rm-pub/Formatter/blob/27dea0804c73b0d2ef43ed6cc25a98ba0399d41e/config/htmlminifierrc.json#L35

`"removeEmptyElements": true,`

![grafik](https://user-images.githubusercontent.com/827205/73666870-bea02000-46a3-11ea-852f-62ba0d5b8bbf.png)

So please report this at https://github.com/bitst0rm-pub/Formatter

**Comment by DanielRuf** [comment]
In general this is a weird commit: https://github.com/bitst0rm-pub/Formatter/commit/27dea0804c73b0d2ef43ed6cc25a98ba0399d41e#diff-c83bec9c4cde8e1a7d2ebe3d697b73bd

"code audit" is something totally different for me and commits should not be so huge

**Comment by hirschferkel** [comment]
Oh you made it! GREAT. With these settings it's even possible to get Minifyer to keep attributes which contain spaces. Perfect.
` "removeEmptyAttributes": false,`

thus
```
<div id="htmllegend"></div>
<canvas id="Macro "></canvas>
```

will get 
`<div id=htmllegend></div><canvas id="Macro "></canvas>`

that's exactly what it should. thanx a lot.
