### ISSUE TITLE
For loop in pre tag, compression failed

### ISSUE THREAD

**Issue by wukang0718** [kangax/html-minifier#1063]
```html
<pre>
  for (var i = 0; i < 10; i++) {
    console.log(i)
  }
</pre>
```

![image](https://user-images.githubusercontent.com/42261663/76186539-9315d580-620d-11ea-9f4e-72da2b371c1a.png)

**Comment by DanielRuf** [comment]
You might want to try the following:
```html
<pre>
for (var i = 0; i &lt; 10; i++) {
console.log(i)
}
</pre>
```

Also see https://github.com/kangax/html-minifier#ignoring-chunks-of-markup

> If you have chunks of markup you would like preserved, you can wrap them `<!-- htmlmin:ignore -->`.

**Comment by DanielRuf** [comment]
Because the `<` is seen as the start of a new tag you have to encode or ignore it.

**Comment by XhmikosR** [comment]
Yup, such characters need to be encoded.
