### ISSUE TITLE
Incorrectly minified rgba(0,0,0,90%)

### ISSUE THREAD

**Issue by GBognar** [kangax/html-minifier#1064]
Sample HTML file:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Test</title>
    <meta charset="utf-8">
  <style>
  .test {
    background-color: rgba(0,0,0,90%);
  }
  </style>
  </head>
  <body class="test">
    <p>Something</p>
  </body>
</html>
```
Sample configuration file:

```json
{
  "minifyCSS": true
}
```

Actual result:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Test</title>
    <meta charset="utf-8">
  <style>.test{background-color:rgba(0,0%,0%,90%)}</style>
  </head>
  <body class="test">
    <p>Something</p>
  </body>
</html>
```

**Note the `0%` at the 2nd and 3rd parameter of the `rgba(...)` function**

Expected result:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Test</title>
    <meta charset="utf-8">
  <style>.test{background-color:rgba(0,0,0,90%)}</style>
  </head>
  <body class="test">
    <p>Something</p>
  </body>
</html>
```

**Note the lack of `%` at the 2nd and 3rd parameter of the `rgba(...)` function**

`html-minifier` version used: `4.0.0`

**Comment by DanielRuf** [comment]
> Note the lack of `%` at the 2nd and 3rd parameter of the

For CSS you can use the unit-less variant for 0. 0% = 0. So this is not a bug.
See https://github.com/CSSLint/csslint/wiki/Disallow-units-for-zero-values for further information.

**Comment by DanielRuf** [comment]
Probably a bug in the used css minifier. See https://github.com/jakubpawlowicz/clean-css/issues/924 and other issues over there.

**Comment by DanielRuf** [comment]
csso works much better

<img width="944" alt="Bildschirmfoto 2020-04-20 um 21 14 07" src="https://user-images.githubusercontent.com/827205/79790393-f0905c80-834b-11ea-9d50-bcc6454667d5.png">

https://github.com/DanielRuf/html-minifier-terser/issues/38

**Comment by GBognar** [comment]
O.K., thanks.

For others facing the same issue:  As a workaround, using `rgba()` *without* a `%` sign (e.g. `rgba(0,0,0,0.9)` instead of `rgba(0,0,0,90%)` works fine).
