### ISSUE TITLE
How can I set 'input' remove from selfClosingInlineTags?

### ISSUE THREAD

**Issue by tyonly** [kangax/html-minifier#1065]
source code:
`<input></input>`

expect output:
`<input></input>`

actual output:
`<input>`

How can I set in config attr?

**Comment by DanielRuf** [comment]
Hi @tyonly, in html and in general `input` does not have a closing tag as it is a void element. Your expected result would be invalid HTML.

https://www.w3.org/TR/2011/WD-html-markup-20110405/syntax.html#syntax-elements
> A void element is an element whose content model never allows it to have contents under any circumstances. Void elements can have attributes.
>
> The following is a complete list of the void elements in HTML:
>
>    area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr

**Comment by tyonly** [comment]
> 
> 
> Hi @tyonly, in html and in general `input` does not have a closing tag as it is a void element. Your expected result would be invalid HTML.
> 
> https://www.w3.org/TR/2011/WD-html-markup-20110405/syntax.html#syntax-elements
> 
> > A void element is an element whose content model never allows it to have contents under any circumstances. Void elements can have attributes.
> > The following is a complete list of the void elements in HTML:
> > area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr

I see what you write. And I use html-minifier in wechat miniapp source code. In the app source.`input` is a closing tag,so I request how can set config for this special code.

**Comment by DanielRuf** [comment]
You can not remove it from there as it is hardcoded.

See
https://github.com/kangax/html-minifier/blob/51ce10f4daedb1de483ffbcccecc41be1c873da2/src/htmlminifier.js#L71
https://github.com/kangax/html-minifier/blob/51ce10f4daedb1de483ffbcccecc41be1c873da2/src/htmlparser.js#L71

You can see all options on the right side at http://kangax.github.io/html-minifier/

> In the app source.`input` is a closing tag

This is invalid html. If you want to tell html-minifier that it should not touch this part see https://github.com/kangax/html-minifier#ignoring-chunks-of-markup

Also keep in mind that invalid markup will produce issues: https://github.com/kangax/html-minifier#working-with-invalid-markup

**Comment by DanielRuf** [comment]
So in this case you might have to adjust / change the content of html-minifier.js in your project ("patch" it).

**Comment by tyonly** [comment]
> 
> 
> You can not remove it from there as it is hardcoded.
> 
> See
> 
> https://github.com/kangax/html-minifier/blob/51ce10f4daedb1de483ffbcccecc41be1c873da2/src/htmlminifier.js#L71
> 
> https://github.com/kangax/html-minifier/blob/51ce10f4daedb1de483ffbcccecc41be1c873da2/src/htmlparser.js#L71
> 
> You can see all options on the right side at http://kangax.github.io/html-minifier/
> 
> > In the app source.`input` is a closing tag
> 
> This is invalid html. If you want to tell html-minifier that it should not touch this part see https://github.com/kangax/html-minifier#ignoring-chunks-of-markup
> 
> Also keep in mind that invalid markup will produce issues: https://github.com/kangax/html-minifier#working-with-invalid-markup

Yes ,as in my project ,I have adjust codes ,Line 71 in 51ce10f And then it works fine. thks
