### ISSUE TITLE
Re-design build system

### ISSUE THREAD

**Issue by XhmikosR** [kangax/html-minifier#107]
@kangax: I wonder if you are interested in switching to [Grunt](http://gruntjs.com/) for building. This will make things truly cross-platform and will allow us to add proper support for JSHint, uglify-js etc.

I can provide a patch if needed.

**Comment by kangax** [comment]
@XhmikosR I'm indifferent to it. The project is very small and doesn't need much orchestration, so I never felt the need for Grunt.

In a long term it might makes sense.

Right now the build is as simple as `cat src/htmlparser.js src/htmlminifier.js src/htmllint.js > dist/all.js`, testing is done via standard `npm test` (which also lints and builds the source).

I just broke `npm test` into multiple scripts for convenience:

``` sh
npm run-script lint
npm run-script build
npm run-script test
```

**Comment by XhmikosR** [comment]
I still feel Grunt is worth. Because then we can easily add more stuff like uglify etc.

**Comment by XhmikosR** [comment]
Oh, also `cat` isn't cross platform so it's not a matter of `npm run script` only.

**Comment by XhmikosR** [comment]
Regardless, I offer to make the switch, will you accept the patch?

**Comment by kangax** [comment]
> I still feel Grunt is worth. Because then we can easily add more stuff like uglify etc.

It's easy to add another script to `package.json` (I just added `minify` command which uses uglify).

What other advantages of Grunt are there besides windows compatibility?

**Comment by XhmikosR** [comment]
I see no reason to reinvent the wheel. Scripts are nice and all but limited.

Grunt is simple to add, cross platform and fully extensible system.

**Comment by XhmikosR** [comment]
@kangax: So should I go ahead with this?

**Comment by kangax** [comment]
@XhmikosR I still don't see _much_ benefit... but sure, go ahead :)

**Comment by dashed** [comment]
Alternatively, I may suggest gulp: https://github.com/gulpjs/gulp

**Comment by XhmikosR** [comment]
@kangax: I will take care of this in the next days then.

@Dashed: I have tried gulp, but couldn't do the stuff I wanted the way I wanted back then. For the time being, Grunt feels more natural to me.

**Comment by kangax** [comment]
Closing now that grunt port is being tracked in #114
