### ISSUE TITLE
An empty pair of angle brackets inside <code> causes a parsing error

### ISSUE THREAD

**Issue by madooei** [kangax/html-minifier#1072]
It seems that an empty pair of angle brackets inside code causes a parsing error. 

The error can easily be produced at https://kangax.github.io/html-minifier/
Here is an example:

```html
<pre><code>List<Integer> numbers = new ArrayList<>();</code></pre>
```

It results in

```
Error: Parse Error: <>();</code></pre>
```

The issue is `<>`, the empty pair proceeding `ArrayList` (which you would see very commonly used in Java).

I would have expected everything inside `<code></code>`  to be escaped but it does not seem to be the case. 
Nonetheless, it looks like a bug (since `<Integer>` works just fine). 

At the moment, unfortunately, I don't have the time to dig further into the source to pinpoint the issue. I would really appreciate it if someone who is intimately familiar with the source code can point to where the issue is most likely originated.

**Comment by mdmower** [comment]
`<code>` and `<pre>` contents must be HTML escaped just like any other element. https://www.w3.org/International/questions/qa-escapes#use . In other words, you cannot feed invalid HTML to a minifier and expect it to fix your syntax. See https://github.com/kangax/html-minifier#working-with-invalid-markup .

**Comment by madooei** [comment]
Thanks, @mdmower - I didn't know code content must be HTML escaped. That makes sense.
