### ISSUE TITLE
How to not remove extra closing tags?

### ISSUE THREAD

**Issue by rationalthinker1** [kangax/html-minifier#1074]
For example, if I want to minify the html below, the output is always without  the ```</div>```  in the beginning, regardless of what settings I use.
```
</div>
<h1>Hello World!</h1>
<p>Hi There</p>
```
You can try it out here. https://kangax.github.io/html-minifier/

**Comment by DanielRuf** [comment]
For me it looks like this:
<img width="572" alt="Bildschirmfoto 2020-08-26 um 20 27 34" src="https://user-images.githubusercontent.com/827205/91341945-9ceebd80-e7da-11ea-946d-b74da03d6034.png">

The closing p tag is optional and automatically removed. See https://www.w3.org/TR/html52/syntax.html#optional-tags

<img width="799" alt="Bildschirmfoto 2020-08-26 um 20 46 49" src="https://user-images.githubusercontent.com/827205/91343803-577fbf80-e7dd-11ea-8fe5-51dbf820856a.png">

**Comment by rationalthinker1** [comment]
Oh shoot, I'm sorry, I meant ```</div>```

**Comment by DanielRuf** [comment]
This is the same. Please see what happens / changes when you change the "optional closing tags" option.

**Comment by DanielRuf** [comment]
This is the same. Please see what happens / changes when you change the "optional closing tags" option. Also you did not write any `</div>`.

**Comment by DanielRuf** [comment]
Regarding your updated example, a closing `div` without an opening one is basically invalid.

**Comment by DanielRuf** [comment]
Read the relevant part in the documentation:

https://github.com/kangax/html-minifier#working-with-invalid-markup

But you can tell html-minifier to ignore this single tag:

https://github.com/kangax/html-minifier#ignoring-chunks-of-markup

Try the following:

```html
<!-- htmlmin:ignore --></div><!-- htmlmin:ignore -->
<h1>Hello World!</h1>
<p>Hi There</p>
```

This is the result:
![Screenshot_20200826-215535](https://user-images.githubusercontent.com/827205/91350437-fceb6100-e7e6-11ea-8e9d-fdcaaf6566c4.jpg)

**Comment by rationalthinker1** [comment]
Thank you for the investigation, @DanielRuf. I really appreciate it. I will use this tag.
