### ISSUE TITLE
Meta tags without attributes quotes don't work on WhatsApp

### ISSUE THREAD

**Issue by gbdematos** [kangax/html-minifier#1078]
The links of my website weren't getting fetched in WhatsApp mobile (only web). Spent all morning trying to figure out why, and turns out it was just because of the attributes quotes removal.

This does not work:
`<meta property=og:description content="Website description...">`

Changed to this and it's working properly:
`<meta property="og:description" content="Website description...">`

**Comment by DamonHD** [comment]
That looks like an error on WhatApp's part, if the quotes there make a different.

I find that Twitter is over-sensitive (eg rejecting semantically-correct stuff) when attributes are re-ordered, so I avoid attribute sorting.

Rgds

Damon

**Comment by XhmikosR** [comment]
Yeah, no quotes is perfectly valid HTML.
