### ISSUE TITLE
Case where the value of the `<input type="radio">` is empty

### ISSUE THREAD

**Issue by SaekiTominaga** [kangax/html-minifier#1083]
The initial value of the value of `<input type="radio">` is "on".

> The value IDL attribute is in mode default/on.

https://html.spec.whatwg.org/multipage/input.html#radio-button-state-(type=radio)

Therefore, the following two are different.
- `<input type="radio" name="foo">`
- `<input type="radio" name="foo" value="">`

However, if you enable the [removeEmptyAttributes](http://perfectionkills.com/experimenting-with-html-minifier/#remove_empty_or_blank_attributes) option,
`<input type="radio" name="foo" value="">`
↓
`<input type="radio" name="foo">`
The value to be sent will change from "" to "on".

Is it possible to exclude it from the deletion process like `<img alt="">` ?

**Comment by DanielRuf** [comment]
See the third option (Function).

Option | Description | Default
-- | -- | --
removeEmptyAttributes | Remove all attributes with whitespace-only values | false (could be true, Function(attrName, tag))

**Comment by SaekiTominaga** [comment]
Thanks for the reply.
I thought it would be good to exclude the value attribute with the default setting of `html-minifier`, but I understood that the user needs to set it individually.
