### ISSUE TITLE
npm package: include browser build too

### ISSUE THREAD

**Issue by aiden271828** [kangax/html-minifier#1094]
My code is going to run in the browser , and I use Webpack for my development environment.

```js
// index.js
import htmlMinifier from 'html-minifier';
var minify = htmlMinifier.minify;
var result = minify('<p title="blah" id="moo">foo</p>', {
  removeAttributeQuotes: true
});
```
error
```
 fs.readFileSync is not a function
```

**Comment by XhmikosR** [comment]
We do have a build, but apparently we are not shipping in the npm package.

**Comment by MarkoCen** [comment]
yes, please include the dist folder when publishing to npm

**Comment by MarkoCen** [comment]
current workaround, load `htmlminifier.min.js` using jsDeliver with script tag
```
<script src="https://cdn.jsdelivr.net/gh/kangax/html-minifier/dist/htmlminifier.min.js"></script>
```

**Comment by TheSecurityDev** [comment]
Any other solutions for this?
