### ISSUE TITLE
css declaration removed in <style> tag after css minify

### ISSUE THREAD

**Issue by johannchopin** [kangax/html-minifier#1096]
Hey team 👋 First thanks for all the work put on this project.

I want to minify a svg that contain a `<style>` tag:

```html
<svg version="1.1" baseProfile="full" width="300" height="86" viewBox="0 0 300 86" preserveAspectRatio="xMinYMin meet" xmlns="http://www.w3.org/2000/svg">
  <style>
    text {
      fill: #EAEAEA;
      font: 500 12px 'Segoe UI', Ubuntu, Sans-Serif;
    }
    .username {
      font-weight: 500;
      font-size: 16px;
    }
    .reputation {
      font-weight: 600;
      font-size: 14px;
    }
    .website, .location {
      font-size: 10px;
    }
    .badgecount circle {
      cx: 0;
      cy: -4;
      r: 4;
    }
    .website {
      fill: #81C4F8;
    }
  </style>

  <rect 
    x="0"
    y="0"
    rx="5"
    ry="5"
    width="300"
    height="86"
    fill="#2D2D2D"
    stroke-width="2"
    stroke="#F48024"
  ></rect>
</svg>
```

But when I minify it on [the website](https://kangax.github.io/html-minifier/)v4.0.0, the css declaration for `.badgecount circle` is removed:

```html
<svg baseProfile=full height=86 preserveAspectRatio="xMinYMin meet" version=1.1 viewBox="0 0 300 86" width=300 xmlns=http://www.w3.org/2000/svg><style>text{fill:#eaeaea;font:500 12px 'Segoe UI',Ubuntu,Sans-Serif}.username{font-weight:500;font-size:16px}.reputation{font-weight:600;font-size:14px}.location,.website{font-size:10px}.website{fill:#81c4f8}</style><rect fill=#2D2D2D height=86 rx=5 ry=5 stroke=#F48024 stroke-width=2 width=300 x=0 y=0></rect></svg>
```

Any idea why it's happening?

**Comment by DanielRuf** [comment]
This is probably an issue with `clean-css` which is used for minifying css.
The question should be probably asked at https://github.com/jakubpawlowicz/clean-css/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by DanielRuf** [comment]
This is probably an issue with `clean-css` which is used for minifying css.
The question should be probably asked at https://github.com/jakubpawlowicz/clean-css/issues

**Comment by johannchopin** [comment]
@DanielRuf Sadly if I minify the css only with clean-css the output contains the `.badgecount circle`:

```css
text{fill:#EAEAEA;font:500 12px 'Segoe UI',Ubuntu,Sans-Serif}.username{font-weight:500;font-size:16px}.reputation{font-weight:600;font-size:14px}.location,.website{font-size:10px}.badgecount circle{cx:0;cy:-4;r:4}.website{fill:#81C4F8}
```

It seems to be an issue with html-minifier in this case 🤔

**Comment by DanielRuf** [comment]
Which version of clean-css do you use? html-minifier uses clean-css 4: https://github.com/kangax/html-minifier/blob/gh-pages/package.json#L58

Is the problem reproducible with clean-css 4?
The current available version is clean-css 5: https://www.npmjs.com/package/clean-css

**Comment by johannchopin** [comment]
@DanielRuf You are right 👍 The problem occurs with the version `v4.2.1` as you can see here:

[![Edit frosty-morning-9nkgb](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-morning-9nkgb?fontsize=14&hidenavigation=1&theme=dark)

Version `^5.0.0` seems to fix it so is it be possible to update this package? 😄 Should I do it and open a PR?

**Comment by DanielRuf** [comment]
Not sure if version 5 introduces breaking changes.
A PR is very welcome for html-minifier and also html-minifier-terser at https://github.com/terser/html-minifier-terser (a fork with some changes to support ES6 and newer).
