### ISSUE TITLE
[website] Add dropzone to minify a HTML file

### ISSUE THREAD

**Issue by johannchopin** [kangax/html-minifier#1101]
Hey team 👋  First thanks a lot for the work put on this project 👍 

It would be really nice to have a dropzone in the website so that you could just drop a file to minify it.

However implementing such a feature in pure html and vanilla js could be a vaste of time and woulf be hard to maintain. I refactored the website of [clean-css](https://github.com/jakubpawlowicz/clean-css) a few weeks ago to use [svelte](https://svelte.dev/). Having it build on top of that make the implementation of new feature really easy. 

So I wanted to know if you would be interrested to modernize your website with svelte and have this new feature implemented.

**Comment by boehs** [comment]
With all respect svelte or other frameworks are not at all required for a modern website, and for a simple website like this one I don't see the need, especially with all the overhead svelte adds. Being said I presume a stylesheet update would be welcome

**Comment by johannchopin** [comment]
Yeah completely understand your opinion 👍
