### ISSUE TITLE
Issue with < > symbol in content

### ISSUE THREAD

**Issue by tatva122** [kangax/html-minifier#1105]
```js
var minify = require('html-minifier').minify;
var result = minify("<ul>Customers entering at age <36 Years can get 10% Renewal Discount  after Age>=40 Years as Reward</li>");
console.log(result);
```

Getting below error
`Error: Parse Error: <36 Years can get 10% Renewal Discount  after Age>=40 Years as Reward</li>`

**Comment by DamonHD** [comment]
You should escape a bare '<' (or '&' for example) in content, eg as `&lt;`.

The error is being reported correctly IMHO.

Rgds

Damon

**Comment by DanielRuf** [comment]
Try the html entities like `&lt;` and `&gt;`.

**Comment by XhmikosR** [comment]
Like the previous commenters mentioned, you need to properly escape these characters.

**Comment by courtens** [comment]
How would I do this in a .js (javascript) file?

```
if (tG<1 && tG !== 0){
	document.getElementById(t+'G'+f).innerHTML = 1;
} else {
	document.getElementById(t+'G'+f).innerHTML = (Math.round(tG * 100) / 100).toFixed(0);
}
```

**Comment by R4356th** [comment]
Use ``encodeURI``.

**Comment by courtens** [comment]
> Use `encodeURI`.

I am not sure I understand what you are suggesting. How would you use `encodeURI`? It is a .js file I'd like to minimize, not a URL string.
