### ISSUE TITLE
Extra space after start tag (with aggressive minification)

### ISSUE THREAD

**Issue by kangax** [kangax/html-minifier#111]
``` html
<div>
  <b>foo</b>
  bar
</div>
```

produces:

``` html
<div><b>foo</b> bar</div>
```

bar shouldn't have space in front

**Comment by dashed** [comment]
This is expected behaviour.

Both should output: `foo bar`.

**Comment by dashed** [comment]
To elaborate, both of the following output differently due to the fact that newlines act like spaces:

``` html
<div>
  <b>foo</b>
bar
</div>
```

``` html
<div>
  <b>foo</b>bar
</div>
```

**Comment by kangax** [comment]
Good point. Forgot about this :)
