### ISSUE TITLE
php tag in html tag error

### ISSUE THREAD

**Issue by hugsbrugs** [kangax/html-minifier#112]
Hi there !

this line : 

```
<a href='http://<?= $_SERVER['SERVER_NAME'] ?>/php/php/auth/Authentications.php?provider=facebook' title="<?= _('Connexion avec votre compte').' '._('Facebook') ?>"><span class="fa fa-facebook-square fa-3x"></span></a>
```

sends me a parse error. From my tests it's caused by <?= tag inside <a tag.
Any ideas to make it ?

Thanks, Hugo

**Comment by kangax** [comment]
You have single quotes inside single quotes. That's why it doesn't work.

**Comment by hugsbrugs** [comment]
Yeah ! Thanks !!!!

**Comment by hugsbrugs** [comment]
Another error I can't figure out : 

```
<input type="checkbox" <?= $UserCustomTastingChecked ?>></div></label>
```

I have tested : 

```
<input type="checkbox" "<?= $UserCustomTastingChecked ?>"></div></label>
```

but still "Parse Error",

I've tried this online HTML minifier : http://www.willpeavy.com/minifier/ to see if I have more explanations on error to pass through but it doesn't generate this error. What advise would youy give me to have more info for debugging ? Thanks

**Comment by hugsbrugs** [comment]
I've seen your online testing page : http://kangax.github.io/html-minifier/
trying to remove all options still give me error on same line ...

**Comment by hugsbrugs** [comment]
What is strange is that : 

```
<input type="checkbox" checked>
```

pass test (with all options activated) and gives : 

```
<input type=checkbox checked>
```

Obviously my : 

```
<?= $UserCustomTastingChecked ?>
```

sets "checked" or not.
I had the idea to put : 

```
<input type=checkbox checked=" <?= $UserCustomTastingChecked ?>">
```

but since a "no-checked" option doesn't exist, I can't do this way ...

**Comment by Grawl** [comment]
Agree. A lot of errors (including silent feeeze) with PHP minifining.
