### ISSUE TITLE
Spaces around inline elements in text are removed

### ISSUE THREAD

**Issue by zefir-git** [kangax/html-minifier#1120]
The following source HTML
```html
<div>
    <p>Foo <a href="#">bar</a> baz.</p>
</div>
```
Produces
```html
<div><p>Foo<a href="#">bar</a>baz.</p></div>
```

Except for using `conservativeSpaces`, is there a way to fix this? I want unneeded spaces removed. Spaces in text are clearly needed.

**Comment by zefir-git** [comment]
This issue was caused by using @node-minify with @node-minify/html-minifier. I have resolved it by using this package directly without @node-minify.

**Comment by fseitun-globant** [comment]
Hi @williamd5 ! Could you please expand on your solution? I think I might have been bitten by the same issue. How do you use 
> this package directly without @node-minify.

?

**Comment by zefir-git** [comment]
> Hi @williamd5 ! Could you please expand on your solution? I think I might have been bitten by the same issue. How do you use
> 
> > this package directly without @node-minify.
> 
> ?

I was using a different package ([@node-minify](https://www.npmjs.com/package/node-minify)) which provides something like a wrapper around this (@html-minifer) and some other minify packages bundled together.

The way to control this behaviour in @html-minifier is with the [`collapseInlineTagWhitespace` option](https://github.com/kangax/html-minifier#options-quick-reference).
