### ISSUE TITLE
Text content with an angle bracket seems to always throw a parse error.

### ISSUE THREAD

**Issue by albell** [kangax/html-minifier#113]
Markup:

```
<!doctype html>
<html>
<head></head>
<body><p>Did you know that 1 < 2 ?</p></body>
</html>
```

throws:

```
Parse Error: < 2 ?</p> </body> </html>
```

Perhaps there is some way to handle this gracefully, especially when the bracket is surrounding by spaces on both sides? E.g. I don't think anybody writes tags with spaces on both sides of the element name:

```
< div >
```

Thanks for an awesome tool.

**Comment by kangax** [comment]
This is because "<" is unescaped (should be "&lt;")
