### ISSUE TITLE
Support for html fragments

### ISSUE THREAD

**Issue by wheresrhys** [kangax/html-minifier#118]
I'm running html minifier over some mustache templates. The opening `</html>` tag is in `header.mustache` and the closing `</html>` tag is in `footer.mustache`. html-minifier inserts the closing tag at the end of header.mustache and removes it from footer.mustache. 

Would be nice to be able to pass in a flag to specify that a file that's being processed is a possibly invalid html fragment.

**Comment by kangax** [comment]
Can you please paste chunk of html that shows this issue?

**Comment by wheresrhys** [comment]
``` html
<!DOCTYPE html>
<!--[if IE 7]><html class="o-hoverable-on no-js o-useragent-ie7"><![endif]-->
<!--[if IE 8]><html class="o-hoverable-on no-js o-useragent-ie8"><![endif]-->
<!--[if gt IE 8]><!--><html class="o-hoverable-on no-js"><!--<![endif]-->
```

and

``` html
    {{> /views/origami-templates/o-ft-footer/main}}
    {{> /views/common/scripts}}
</body>
</html>
```

**Comment by kangax** [comment]
Hm, I don't think there's much we can do about this, since minifier really needs to be context aware and can't understand what to do with arbitrary, _partial_ chunk of html.

**Comment by mfregoe** [comment]
Just wanted to leave this here for anyone else who came upon this issue:

I had the same problem (with handlebars templates) but only when using the `processScripts` option.

My current workaround is using two separate htmlmin tasks (using [grunt-contrib-htmlmin](https://github.com/gruntjs/grunt-contrib-htmlmin)). One task for templates that have open tags (not utilizing `processScripts`), and another task for templates without open tags (utilizing `processScripts`).
