### ISSUE TITLE
String that causes an infinite loop in html-minifier

### ISSUE THREAD

**Issue by alexander-marquardt** [kangax/html-minifier#119]
I realize that this is probably a corner case, but the following string causes infinite loop in the html-minifier.

```
<a HREF="javascript:confirm_decision('{% trans " Are you sure you want to eliminate your profile?"%}'">click here </a>
```

Note: the raw snippet is invalid html (has a double quote embedded inside another double quote) - but this particular html snippet is intended to be pre-processed by the django templating system before sending to the client, at which point the interior double quotes are removed to create valid html.

**Comment by kangax** [comment]
Yeah, I'm not sure we can do anything about this... What about escaping inside quotes (as "&amp;quot;")?

**Comment by alexander-marquardt** [comment]
Hey, thanks for the response. I found a work-around - but I thought it
might be interesting as a test case, or just to know about in case it
indicated an error in the code.
