### ISSUE TITLE
Experiment with web workers (to avoid freezing browser)

### ISSUE THREAD

**Issue by kangax** [kangax/html-minifier#12]

**Comment by alexlamsl** [comment]
I use Web Workers quite extensively in my current project, so may be I could be of service.

OTOH, Node.js have stalled on the decision to include Web Worker or any APIs similar to it. So what is your thinking on this feature exactly?

**Comment by kangax** [comment]
My thinking was to experiment with them on a client only (since we have a web interface). But I think this whole thing is largely moot at this point — I doubt anyone uses web interface and if Node doesn't support them, I wouldn't bother. We're better off spending time on integrating a modern HTML5 parser which would improve perf, reliability, maintenance everywhere.
