### ISSUE TITLE
Parse Error when minifying html that has a custom tags

### ISSUE THREAD

**Issue by kenilam** [kangax/html-minifier#123]
Hi,

I would like to say thank you for making this amazing task for Grunt.

I have a project that use angular where I have created some custom tags, look like:

Unfortunately, it break the minifying process.

I know it is not a standard HTML standard with such custom tag, but I would like to see if the html-minifier would take that as one of the acceptable cases?

**Comment by kangax** [comment]
Make sure you're using latest version as we had a lot of Angular-related changes.
