### ISSUE TITLE
html minifier strips closing slash on <div />

### ISSUE THREAD

**Issue by corbanbrook** [kangax/html-minifier#127]
This results in an open div tag left in the page that causes a lot of problems.

**Comment by kangax** [comment]
Why do you have `<div />` in the first place?

**Comment by corbanbrook** [comment]
Coming from angular we will often /> directives that don't transclude.
For instance something like this toggle button directive:

``` html
<span toggle-checkbox ng-model="model.enabled" />
```

**Comment by kangax** [comment]
But you can just as well use `<span toggle-checkbox ng-model="model.enabled"></span>`, right?

**Comment by corbanbrook** [comment]
Correct, and I question the validity of closing non-void elements this way.

**Comment by corbanbrook** [comment]
I beleive `<div />` is only valid in XML or XHTML

**Comment by kangax** [comment]
It's hard to justify this, since it's an invalid HTML4 (or HTML5). There could be all sorts of "invalid" shortcuts like this and it'd probably be unwise to make exceptions for all of them.

**Comment by corbanbrook** [comment]
Agreed, thanks for your time.

**Comment by kangax** [comment]
We actually did add an option to preserve xml-esque trailing slash, even though underlying parser is strictly HTML4/5 — https://github.com/kangax/html-minifier/blob/gh-pages/tests/minifier.js#L623-L625

Maybe you could utilize that.

**Comment by corbanbrook** [comment]
Ok, great, looks like that was added last week, ill look forward to the next tagged release.
