### ISSUE TITLE
Refactor source files

### ISSUE THREAD

**Issue by XhmikosR** [kangax/html-minifier#138]
Currently the source files are a bit weird. Unfortunately, GitHub pages does not allow us to use a custom source dir. But we can use custom dirs for the JS, css etc files.

Maybe

```
web/assets/css
web/assets/js
```

Also, is v8 folder used? Perhaps also move all the tests into a common folder?

**Comment by kangax** [comment]
Agreed about assets dirs.

As for v8... hm, I think I used it to benchmark minifier using v8 and it was god knows how long ago (modified date — Aug 11, 2011 — damn, almost 3 years ago...). Test page seems to be source of amazon.com. I would leave it for benchmarking purposes, probably switching to Node. We could also create a proper benchmark — similar to that of clean-css — using different test pages (the ones from minifier-tests, for example) to show compression, time, etc.

**Comment by kangax** [comment]
@XhmikosR moved js, css to assets. Renamed minifier-tests to benchmarks but didn't actually get to start working on proper benchmarks script/page yet.

**Comment by XhmikosR** [comment]
Thanks, looks good. We could even go one step further later and create assets/css, js etc.
