### ISSUE TITLE
Minifying html templates inside script tags(angularjs/handlebars/etc templates)

### ISSUE THREAD

**Issue by fxck** [kangax/html-minifier#139]
Continuing from https://github.com/kangax/html-minifier/issues/56#issuecomment-37908224 & https://github.com/kangax/html-minifier/issues/88 which was wrongly closed as a duplicate.

I had an idea, where you'd define which script `type`s _not_ to ignore in an option

like so

``` javascript
{
  processScripts: ["text/x-handlebars-template", "text/ng-template"]
}
```

In most cases you will only need one(I can't really see anyone having more than one templating engine), so it could be a string instead of array, but why be shortsighted I guess..

**Comment by unbug** [comment]
+1 @fxck This is what I am looking for,all my projects use logic-less template engine,looking forward the next version of html-minifier which has got rid of this issue :)

**Comment by fxck** [comment]
@kangax have you had a chance to look into it, if it's gonna be a problem or not?

**Comment by kangax** [comment]
@fxck Just moved this to the upcoming 0.6 milestone. Will try to look into it soon, but any help is very welcome as always!
