### ISSUE TITLE
escaped script closing tags are mistakenly being promoted to unescaped

### ISSUE THREAD

**Issue by albell** [kangax/html-minifier#142]
Years ago, a <a href="http://css-tricks.com/snippets/jquery/fallback-for-cdn-hosted-jquery/">popular pattern for local fallbacks</a> was:

```
<script>
if (typeof jQuery == 'undefined') {
    document.write(unescape("%3Cscript src='jquery.js' %3E%3C/script%3E"));
}
</script>
```

This kind of heavy duty escaping survives well in the minifier as it stands.

But two newer popular escape patterns (both from HTML5 boilerplate) currently break in the minifier. The following pattern, by Mathias Bynens, is in <a href="https://github.com/h5bp/html5-boilerplate/issues/359">an older build</a>:

```
<script>
window.jQuery || document.write('<script src="jquery.js">\x3C/script>')
</script>
```

Finally, this third pattern is the current HTML5BP.

```
<script>
window.jQuery || document.write('<script src="jquery.js"><\/script>')
</script>
```

With both of these newer patterns, the minifier currently changes the 'internal' closing tag to unescaped. In the browser, the closing parenthesis (and possibly a semicolon) then gets dumped out into the page as text.

**Comment by kangax** [comment]
From what I can see, this happens only when "minifyJS" is on, right?

**Comment by albell** [comment]
Yep, it looks like turning off "minifyJS" preserves the closing script tag. Still, this could be a stumbling block for users. These one-liner snippets are typically left inline to avoid an http request. Maybe the integrated JS minifier should preserve them by default? Just a thought.

**Comment by XhmikosR** [comment]
There's an option we might need to turn on `inline-script`.

https://github.com/mishoo/UglifyJS2#beautifier-options

This fixes the issue; not sure if there are any side effects or not though.
