### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by kangax** [kangax/html-minifier#143]
Possibly using files from /minifier-tests, benchmarks would:
- test speed
- test size
- serve as a nice regression testing (our unit tests only check small chunks of markup; it would be nice to have large functional tests of entire pages like Amazon, MSN, etc.)

/cc @XhmikosR

**Comment by XhmikosR** [comment]
I totally want to have this in a nice page :)

But I think we should take this opportunity and refactor the source files before the source tree becomes more messy :P

As for the benchmark itself, as long as you can add some code to output to a yml file, we can use that data with Jekyll directly. See: https://github.com/twbs/ratchet/blob/master/docs/_data/ratchicons.yml and http://jekyllrb.com/docs/datafiles/

**Comment by kangax** [comment]
All good points! What are you thinking to use as a data in yml though? File names? I was thinking benchmark would need to read all files in a directory (perhaps following some convention for file name/dirname) and output size & time taken for each of them. I haven't thought much about all this though.

**Comment by XhmikosR** [comment]
I think we should have /benchmarks/input and benchmarks/output. Then have a simple script which would run the benchmark and output to 2 json files in  _data/. Then we can use that data with Jekyll itself.

I suggest you make a new branch for this and I can push any changes there too; when we are done we merge the branch into gh-pages.

**Comment by kangax** [comment]
Feel free to create a branch as I'm not sure when I'll be able to get to it.
