### ISSUE TITLE
Allow passing clean-css and uglify-js options

### ISSUE THREAD

**Issue by XhmikosR** [kangax/html-minifier#146]

**Comment by kangax** [comment]
I'm thinking perhaps to support a signature like this:

```
minifyJS: { true | false | Object }
minifyCSS { true | false | Object }
```

So to pass options, one could do:

```
minifyJS: { option: value }
```

What do you think?

**Comment by XhmikosR** [comment]
Yeah, that sounds perfect!

**Comment by XhmikosR** [comment]
Awesome, thanks! I think now it should be possible to make browser tests pass too. Also maybe we could add a more extensive example in README.md ?

**Comment by kangax** [comment]
Sure, feel free too. Also a specific test could be good to have but I have no time atm.

**Comment by XhmikosR** [comment]
For some reason, browser tests fail for me even after setting `mangle: false` while in node they pass.

It's like the extra options aren't being passed for uglifyjs in the browser.

**Comment by kangax** [comment]
Ah, I had a feeling this might happen. Need to pass options in browser
branch of minifyJS (not just output options). I wasn't sure which
constructor to pass it in; there's so many of them there.

**Comment by XhmikosR** [comment]
I think we can just check for mangle and if not false then do `compressedAst.mangle_names();`.

**Comment by XhmikosR** [comment]
Nvm, what I suggested was just gonna fix the tests...

**Comment by XhmikosR** [comment]
Anyway here is what I did https://github.com/XhmikosR/html-minifier/compare

I left one test with mangling intact.

**Comment by kangax** [comment]
Looks good. Thanks!
