### ISSUE TITLE
Can with Smarty .tpl files? How to use with Grunt

### ISSUE THREAD

**Issue by piercemcgeough** [kangax/html-minifier#152]
I was looking on http://kangax.github.io/html-minifier/ and it seems to work ok with smarty .tpl files.

I am looking at the readme but I cannot figure out how to use it. Can I use it with Grunt and are there step by step instructions for use.

**Comment by kangax** [comment]
There's a grunt plugin somewhere on GitHub. There's also a link to it in readme.
