### ISSUE TITLE
Shorten URLs

### ISSUE THREAD

**Issue by stevenvachon** [kangax/html-minifier#153]
I'm currently finishing [relateurl](https://github.com/stevenvachon/relateurl) which can help to further minify HTML. Let me know what you may need.

**Comment by stevenvachon** [comment]
I finished the library. It's not 100%, but the only thing remaining are ridiculously invalid URLs (such as `://website.com:abc/`). I see that you've marked this as a possible feature; might I ask why it's only "possible"? I can help implement it if I know what you are for and against.

**Comment by kangax** [comment]
I marked it as "possible feature" because it seems that changing to relative urls would give very small decrease of markup (although i'm guessing it could make sense on pages with lots of urls). Also because I'm not yet sure if it's an absolutely safe thing to do and how easy it'd be to implement this on both client and server (since minifier needs to work on both).

**Comment by stevenvachon** [comment]
It saves about the same as removing white space, I've found through my old [PHP-based HTML minifier](https://github.com/stevenvachon/html-minify). There are quite a few URLs in an HTML document that you may not have thought of, such as those found in `<form>`,`<img>`,`<script>`,`<style>` tags.

It's safe. I've thoroughly tested it. Just like with minifying HTML, if the input is correct (or mostly correct), the output will be correct.

Regarding client-side support, ~~URL shortening could always be reserved for only server-side. Also, I could switch from Node's `url.parse` to [this](https://github.com/kevincox/url.js) to bring support to the client.~~ browserify works nicely.

**Comment by kangax** [comment]
@stevenvachon just got a link to this http://www.thespanner.co.uk/2014/03/21/rpo/ on twitter. you might be interested.

**Comment by stevenvachon** [comment]
Interesting. Fortunately, root-relative URLs aren't vulnerable, with which we could assume that scheme-relative URLs are also safe. Anyone concerned with this could set the [output type](https://github.com/stevenvachon/relateurl#optionsoutput) to root-relative. Moving forward, I hope that IE12 corrects this.

Additionally, RelateUrl doesn't just convert from absolute to path-relative; it also removes unnecessary parts of the URL. All customizable.

**Comment by kangax** [comment]
Well, feel free to send a PR then, whenever you get a chance.

**Comment by stevenvachon** [comment]
~~I'd probably use cheerio to traverse tags. I'm not sure how integrated that would be with your code. Just make it a separate component? And there's also the subject of client-side support.~~

**Comment by kangax** [comment]
It would make sense to tap into minifier.js that we use, since it already does traversal.

**Comment by stevenvachon** [comment]
Cool. I'll try to get to it in the coming weeks. ~~It may also be best to wait for a few new features before starting.~~

**Comment by stevenvachon** [comment]
Would you prefer the option and function to be `minifyURLs` or `minifyURIs`? Technically, only URLs are minified while URIs are ignored.
