### ISSUE TITLE
This snippet crashes the minifier

### ISSUE THREAD

**Issue by noducks** [kangax/html-minifier#154]
I realise this HTML isn't valid, but it threw the html-minifier into an infinite loop without throwing any errors. Cmd-C wouldn't kill it. I was using it with the Grunt plugin. 

```
<input type="text" class="form-control" name="source" data-ng-maxlength="140"
placeholder="Title (Optional)"<br>
```

**Comment by kangax** [comment]
Yeah, that's what happens with invalid markup. Parser could choke on and get into an infinite loop.
