### ISSUE TITLE
Bug with fontello ?

### ISSUE THREAD

**Issue by vcialdella** [kangax/html-minifier#158]
I'm developing a web app with yeoman (yo, grunt and bower).
I'm using Fontello and when I run "grunt serve" I don't have any problem.
However, when I run grunt build, the htmlmin task creates problems in the rendered html.

Before the htmlmin task, the html code looks like this :
`<div class="home-left-savings">
                <h3 class="light"><img class="money" src="images/money.png" /> dépenses</h3>
                <div class="navSavings"> <i class="icon-left light-green" ng-click="prevMonth()"></i>
                    1 au 22 <span ng-bind="months[currMonth].value"></span> 2014
                    <i class="icon-right light-green" ng-click="nextMonth()"></i>
                </div>
                <div class="home-savings-left middle-green">
                    <span class="savings-devise-size-xlarge" ng-bind="months[currMonth].key"></span><span class="devise-xlarge">€</span>
                </div>
            </div>`

And after, it looks like this :
`<div class="home-left-savings"><h3 class="light"><i class="icon-down right deep-green"><i class="icon-up right deep-green"><img class="money" src="images/money.png"> dépenses</i></i></h3><div class="navSavings"><i class="icon-down right deep-green"><i class="icon-up right deep-green"><i class="icon-left light-green" ng-click="prevMonth()"></i> 1 au 22 <span ng-bind="months[currMonth].value" class="ng-binding">Février</span> 2014 <i class="icon-right light-green" ng-click="nextMonth()"></i></i></i></div><div class="home-savings-left middle-green"><i class="icon-down right deep-green"><i class="icon-up right deep-green"><span class="savings-devise-size-xlarge ng-binding" ng-bind="months[currMonth].key">230</span><span class="devise-xlarge">€</span></i></i></div></div>`

As you can see many tags <i class="icon-down right deep-green"> wrap some other code

**Comment by kangax** [comment]
Works for me in http://kangax.github.io/html-minifier/
