### ISSUE TITLE
Can you please add a command line interface ?

### ISSUE THREAD

**Issue by tssajo** [kangax/html-minifier#160]
Can you please add a command line interface to html-minifier ? It would be nice that after an `npm -g install html-minifier` , we could use a command something like:
`html-minifier [--options] inputfile.html outputfile.html`
UglifyJS provides such an interface too for minifying Javascript files.

**Comment by kangax** [comment]
Good idea. Will do.

**Comment by tssajo** [comment]
Excellent. Thanks!

**Comment by XhmikosR** [comment]
Fixed in #171.
