### ISSUE TITLE
Attribute bug in FF

### ISSUE THREAD

**Issue by kangax** [kangax/html-minifier#161]
https://github.com/kangax/html-minifier/commit/4d5431d5a244938c60ed81d94e4cad5869212b10#commitcomment-6087126

**Comment by XhmikosR** [comment]
Same issue with FF 30.

**Comment by XhmikosR** [comment]
FYI, we are now up to 3 failing tests on FF 31. :/

Chrome and IE11 work fine.

**Comment by kangax** [comment]
FF folks still haven't gotten around to it :/ so we might as well just fix
it in minifier

**Comment by XhmikosR** [comment]
Even more on FF nightly and latest master

```
Mozilla/5.0 (Windows NT 6.1; rv:32.0) Gecko/20100101 Firefox/32.0

Tests completed in 172 milliseconds.
428 assertions of 433 passed, 5 failed.
```

**Comment by kangax** [comment]
@XhmikosR any change you could take care of these? Not sure when I'll be able to find time (but will try)

**Comment by XhmikosR** [comment]
I'm not sure when I'll have some time, but I can try having a look, sure :)

**Comment by kangax** [comment]
Fixed via https://github.com/kangax/html-minifier/commit/465e3a736614ff639e415e169cbeb3da807e3b9b

**Comment by XhmikosR** [comment]
Awesome, thanks!
