### ISSUE TITLE
JS double to single quote conversion causes problems

### ISSUE THREAD

**Issue by TallGuy789** [kangax/html-minifier#162]
Hi there. I had the following HTML that I was trying to minify (with default options):

```
<button type="button" name="startButton" id="startButton" onclick="$('head').append('<div>hello<\/script>');">Start</button>
```

Turned out like this:

```
<button type=button name=startButton id=startButton onclick="$("head").append("<div>hello<\/script>")">Start</button>
```

Note that the single quotes in the embedded JavaScript have been converted to double quotes and this breaks the HTML. I realise that using onclick in this manor is not recommended, but in this particular case it was unavoidable.

**Comment by XhmikosR** [comment]
This seems an issue with uglify to me. If you go to http://lisperator.net/uglifyjs/ and enter this sample JS code

``` js
$('head').append('<div>hello<\/script>');
```

you will end up with

``` js
$("head").append("<div>hello<\/script>")
```

assuming you choose to escape `</script>` in codegen options.

**Comment by kangax** [comment]
Yeah... and I don't see any option in Uglify to change that.

**Comment by XhmikosR** [comment]
Maybe @mishoo can shed some light.

**Comment by mishoo** [comment]
Guys, even if there were an option to keep the original quotes (but there isn't), you should _not_ assume that the raw output from UglifyJS can be safely placed in an attribute value.  HTML-encode your attributes.

**Comment by kangax** [comment]
@mishoo good point
