### ISSUE TITLE
Code not removing comments nor whitespace within JS

### ISSUE THREAD

**Issue by cloudgifts** [kangax/html-minifier#164]
Using these options:

var minifyOptions = {
    'removeComments' : true,
    'collapseWhitespace' : true,
    'keepClosingSlash' : true,
    'caseSensitive' : true,
    'minifyJS' : true,
};

The code does NOT remove JS comments nor whitespace

**Comment by kangax** [comment]
Are you using the latest version? Also, please provide exact markup you're checking against.

**Comment by cloudgifts** [comment]
My exact code is here with a very simple HTML example below, as you can see the JS comments and white-space are left untouched, ideally this HTML file would all be one line without any comments.  For the JS, the only thing I would like is comment and white-space removal (nothing fancy):

```
var fs = require('fs');
var minify = require('html-minifier').minify;
var minifyOptions = {
    'removeComments' : true,
    'collapseWhitespace' : true,
    'keepClosingSlash' : true,
    'caseSensitive' : true,
    'minifyJS' : true
};
var fileData = fs.readFileSync(__dirname + '/../../test/bp.html', {'encoding' : 'utf8'});
var updatedFileData = minify(fileData, minifyOptions);
fs.writeFileSync(__dirname + '/../../test/bp-min.html', updatedFileData, {'encoding' : 'utf8'});
```

Input HTML file:

```
<!doctype html>
<html>
    <head>
        <script>
            // Some JS code
            var test1 = 1;
            var test2 = 2;
            // The sum
            var test3 = test1 + test2;
            console.log(test3);
        </script>
    </head>
    <body>
    </body>
</html>
```

Output HTML file:

```
<!doctype html><html><head><script>// Some JS code
            var test1 = 1;
            var test2 = 2;
            // The sum
            var test3 = test1 + test2;
            console.log(test3);</script></head><body></body></html>
```

**Comment by XhmikosR** [comment]
The CSS/JS minification support is only added in the current HEAD, i.e. there's no npm release with this feature yet.

**Comment by kangax** [comment]
Yeah, it works for me on http://kangax.github.io/html-minifier/

`<!DOCTYPE html><html><head><script>var test1=1,test2=2,test3=test1+test2;console.log(test3);</script><body>`
