### ISSUE TITLE
img alt="" removal please

### ISSUE THREAD

**Issue by tomByrer** [kangax/html-minifier#165]
I have html with `alt=""` for some reason.  Would be nice if removed :)

**Comment by kangax** [comment]
Actually we don't remove "alt" on purpose as it is a required attribute in HTML4/5 — http://perfectionkills.com/experimenting-with-html-minifier/#remove_empty_or_blank_attributes

**Comment by tomByrer** [comment]
Ah, I thought it might be dropped in HTML5[.1] in favor for ARIA, but I [guess not](http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#alt).
cheers
