### ISSUE TITLE
disable minification?

### ISSUE THREAD

**Issue by lhwparis** [kangax/html-minifier#167]
is there a way to just use the cleanup options like removeEmptyElements without minifiying the html? i want a pretty printed html but use the cleanup options your tool provides

**Comment by kangax** [comment]
Yep, there's a lot of options to satisfy any needs — https://github.com/kangax/html-minifier#options-quick-reference

**Comment by lhwparis** [comment]
sorry for aksing again i know that page but which one disables minification? am i blind :/ ?

**Comment by kangax** [comment]
`collapseWhitespace`
