### ISSUE TITLE
Whitespace removed incorrectly

### ISSUE THREAD

**Issue by paulirish** [kangax/html-minifier#17]
```
:) <a href="http://example.com">link</a>
```

In this example the space between the smiley and the link will be lost.

**Comment by robogeek** [comment]
Yes, I was about to report this.  I am using this module via the [minify](https://github.com/coderaiser/minify) module in case that makes any difference.

**Comment by nfriedly** [comment]
+1

**Comment by kangax** [comment]
This works as expected. Added test.
