### ISSUE TITLE
Incorrect minification

### ISSUE THREAD

**Issue by pallix** [kangax/html-minifier#172]
Hello.

The content of this template:

   &lt;div ui-view=''&gt;<br/>     &lt;h1&gt;{{title}}&lt;/h1&gt;<br/>     &lt;p class='introduction' translate='lican.intro.text'&gt;&lt;/p&gt;<br/>      &lt;form ng-submit='startAnalysis()'&gt;<br/>        &lt;button class='btn btn-default' translate='lican.intro.start' type='submit'&gt;    &lt;/button&gt;<br/>      &lt;/form&gt;<br/>    &lt;/div&gt;<br/>

is incorrectly minified to:

```
"<div ui-view><h1>{{title}}</h1><p class=introduction translate></p><form ng-submit=startAnalysis()><button class=\"btn btn-default\" translate type=submit></button></form></div>"
```

The translate attribute loses its value.

I had the bug from grunt html2js and putting some log shows a problem in the minify function. See also https://github.com/karlgoldstein/grunt-html2js/issues/42

**Comment by kangax** [comment]
Looking at this closer, I see that attribute value is being removed because translate is a boolean attribute and so empty value is the same as a "yes" string.

> The attribute's keywords are the empty string, yes, and no. The empty string and the yes keyword map to the yes state. The no keyword maps to the no state. In addition, there is a third state, the inherit state, which is the missing value default (and the invalid value default).

http://www.whatwg.org/specs/web-apps/current-work/multipage/elements.html#the-translate-attribute

**Comment by kangax** [comment]
So the question is: why is there "lican.intro.start" value, if browser only understands "yes", "no", and empty string.

**Comment by pallix** [comment]
It's because of the angular translate plugin. http://angular-translate.github.io/

**Comment by lggwettmann** [comment]
I think i found same problem here https://gist.github.com/lggdance/ac6b052292100c95a2e9 - check the view-checkin.html which's <signup> directive loses the value of the open-attribute from

``` html
<signup ng-show="openit" name="{{input}}" open="openit" guest="guest" on-signup="addGuest()"></signup>
```

to

``` html
<signup ng-show="openit" name="{{input}}" open guest="guest" on-signup="addGuest()"></signup>
```

.

Any solutions to that yet?

**Comment by kangax** [comment]
Well, one way is not to use "collapse boolean attributes" — http://kangax.github.io/html-minifier/

**Comment by lggwettmann** [comment]
Thanks for pointing that out :)

**Comment by schmod** [comment]
From my reading of the spec, `<elem translate>` is equivalent to `<elem>`

`translate` only has an effect when you specify the string values `"yes"` or `"no"`.

As such, `translate` is **not** a boolean attribute, and the minifier should not treat it as such.

From the [spec](http://www.whatwg.org/specs/web-apps/current-work/multipage/elements.html#the-translate-attribute) (emphasis mine):

> The attribute's keywords are the empty string, yes, and no. The empty string and the yes keyword map to the yes state. The no keyword maps to the no state. **In addition, there is a third state, the inherit state, which is the missing value default (and the invalid value default)**.
> 
> Each element (even non-HTML elements) has a translation mode, which is in either the translate-enabled state or the no-translate state. If an HTML element's translate attribute is in the yes state, then the element's translation mode is in the translate-enabled state; otherwise, if the element's translate attribute is in the no state, then the element's translation mode is in the no-translate state. **Otherwise, either the element's translate attribute is in the inherit state, or the element is not an HTML element and thus does not have a translate attribute; in either case, the element's translation mode is in the same state as its parent element's**, if any, or in the translate-enabled state, if the element is a root element.

**Comment by kangax** [comment]
This is fixed now
