### ISSUE TITLE
It removed my self-closing slashes

### ISSUE THREAD

**Issue by mightyiam** [kangax/html-minifier#173]
Hi and thank you for very useful software.

It seems to remove trailing slashes by default, which seems kind of strange to me because that would produce invalid HTML in document types which require closing of tags.

Perhaps not a smart default minification?

Or perhaps this could be conditional, depending on the document type declaration?

**Comment by kangax** [comment]
99% (if not more) of documents on the web are served as HTML. I think it's a sensible default.

**Comment by JakobJingleheimer** [comment]
This breaks SVGs.

**Comment by kangax** [comment]
Use `keepClosingSlash` option
