### ISSUE TITLE
Minifier removes relevant whitespace in collapseWhitespace mode (e. g., nbsp)

### ISSUE THREAD

**Issue by addaleax** [kangax/html-minifier#178]
When presented with HTML content like `<span>12 %</span>` (notice that the space between 12 and % is in fact U+00A0, the non-breaking space otherwise known as `&nbsp;`), collapseWhitespace() removes it and replaces it with a normal space (U+0020).

There is quite a [zoo](https://www.cs.tut.fi/~jkorpela/chars/spaces.html) of special whitespace characters which should – imho – not be modified by the minifier.

As far as I can tell, this problem could mostly be solved by using `/[\t\n\r]+/g` as the regular expression in collapseWhitespace().

**Comment by kangax** [comment]
Hm, yeah. I suppose removing `\t`, `\n`, `\r`, and `' '` (U+0020) would make sense there. Please send a PR if you have a chance! :)
