### ISSUE TITLE
Issue with reducing <input type="text" ...> to just <input ...>

### ISSUE THREAD

**Issue by EdBoucher** [kangax/html-minifier#188]
If you're styling forms, this reduction will break any CSS that targets text inputs. I may be missing something but I've yet to find the code that makes this conditional on finding a selector in a CSS file. Should this be an configuration option, or just removed?

JSFiddle: http://jsfiddle.net/jeanpaulsoftware/4P5R7/

**Comment by kangax** [comment]
Yes, it's optional of course — http://perfectionkills.com/experimenting-with-html-minifier/#remove_redundant_attributes
