### ISSUE TITLE
Add support for parsing {{ and }} in attributes

### ISSUE THREAD

**Issue by khmelevskii** [kangax/html-minifier#189]
`<a {{IF rel}}rel="{{rel}}"{{END IF}} href="{{address}}">{{name}}</a>`

how minify this?

**Comment by kangax** [comment]
Unfortunately we can't parse it, since it's not valid HTML4/5

**Comment by khmelevskii** [comment]
And what to do? An elementary example

```
<input {{readonly}} name="bar" value="foo">
```

not minify. html-minifier not possible to use in templates? 
How can I solve this problem?

**Comment by kangax** [comment]
I'll try to add support for this soon

**Comment by khmelevskii** [comment]
Thanks a lot!

**Comment by khmelevskii** [comment]
not work for me.

```
git clone git://github.com/kangax/html-minifier.git
cd html-minifier
npm link .
grunt

html-minifier test.tpl

Error: Minification error%
```

**Comment by khmelevskii** [comment]
through node api doesnt work too

**Comment by duncanbeevers** [comment]
@khmelevskii There is no CLI access to this alternative attribute parsing. Please see the included tests for how the functionality works.

The API expects RegExp objects passed as `customAttrOpen` and `customAttrClose` properties. If these are not provided, the behavior is exactly the same as before this commit.

With those properties supplied, the html parser recognizes non-HTML-compliant markup surrounding HTML element attributes.

For example, in my usage of the library I supply these very lenient opening and closing rules

``` javascript
{
  customAttrOpen: /\{\{#[^\}]+\}\}/,  // recognizes {{#stuff...}} before element attribute
  customAttrClose: /\{\{\/[^\}]+\}\}/ // recognizes {{/stuff}} after element attribute
}
```

I don't know the best way to introduce these options to CLI usage of the library, or even whether it's appropriate to try to do so.

@kangax Do you have any opinions on how this functionality should be exposed?

**Comment by kangax** [comment]
@duncanbeevers @khmelevskii We can pass these similar to the way we pass, say, `ignoreCustomComments` — https://github.com/kangax/html-minifier/blob/gh-pages/cli.js#L73

It's usually best to specify this via config file, similar to how we do it with benchmarks (using CLI underneath) — https://github.com/kangax/html-minifier/blob/gh-pages/benchmark.conf

**Comment by khmelevskii** [comment]
@duncanbeevers @kangax `customAttrOpen` and `customAttrClose` + config file is ok for me. I will test it in my project.

@kangax, when will new release html-minifier be available in `npm`?
