### ISSUE TITLE
template script not compress correct

### ISSUE THREAD

**Issue by kingnight** [kangax/html-minifier#191]
in html file include dom and script 
    <div>

   </div>
   <script type="text/x-kendo-tmpl" id="contacts-template">  
        <a href="#contact-detail-view?contactId=#=employeeId#">#=name#</a>
   </script>

run html-minifier, only dom part compress success

option :minifyJS set true

use in node.js grunt-contrib-htmlmin 0.3.0

**Comment by kangax** [comment]
Make sure to use latest version

**Comment by kingnight** [comment]
grunt-contrib-htmlmin v0.3.0 is  already the newest
