### ISSUE TITLE
More descriptive parsing errors

### ISSUE THREAD

**Issue by ghost** [kangax/html-minifier#192]
The minifier simply reports "minification error" whenever something goes wrong, which is extremely unhelpful for debugging.

**Comment by kangax** [comment]
Can you give an example of input that errors out?

**Comment by ghost** [comment]
```
<a href="#"{% if new_tab %} target="_blank"{% endif %}>link</a>
```

This particular instance could be solved by #83, but simply printing `Error: Minification error` without any guidance in any case is less than helpful.

**Comment by kangax** [comment]
The error is coming from html parser that we're relying on. I'll see if I can try to make it more descriptive but can't promise anything.

**Comment by ghost** [comment]
Also, I've gotten the minification error with the `--lint` flag even for valid HTML, where it only shows up with the `--lint` tag. Unsure what that error is either.

**Comment by kangax** [comment]
Hm, strange. Please file a separate ticket for that though.

**Comment by ghost** [comment]
Okay, although it's hard to fix that error without proper error reporting.

**Comment by alexlamsl** [comment]
HTMLParser already points to the location where the error is: https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlparser.js#L236

I am not sure what more we can do beyond that, as even the parser is just hitting a brick wall here (of negative pattern matches).

**Comment by alexlamsl** [comment]
Closing for now. Feel free to reopen if there are any concrete suggestions.
