### ISSUE TITLE
--lint always fails

### ISSUE THREAD

**Issue by ghost** [kangax/html-minifier#197]
Try: `echo '<html></html>' | html-minifier --lint`

**Comment by kangax** [comment]
Confirmed

**Comment by XhmikosR** [comment]
When I run this I just get the html file contents output on screen. Is that the same issue?

**Comment by NikolaySl** [comment]
https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L533 - here lint is read from options which is true or false
and here https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L584 code try to call Lint method on boolean value
The object instantiation is missing.

Also there is no Lint log output.

Fix - https://github.com/kangax/html-minifier/pull/296
