### ISSUE TITLE
caseSensitive: true does not work (completely)

### ISSUE THREAD

**Issue by JakobJingleheimer** [kangax/html-minifier#198]
Tag names are always converted to lowercase irrespective of this flag:

[`L466`](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L466) `tag = tag.toLowerCase();`

[`L466`](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L466) `buffer.push('</', tag.toLowerCase(), '>');`

**Comment by JakobJingleheimer** [comment]
Changing

[`L466`](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L466) `tag = tag.toLowerCase();`
→ `tag = options.caseSensitive ? tag : tag.toLowerCase();`

[`L522`](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L522) `buffer.push('</', tag.toLowerCase(), '>');`
→ `buffer.push('</', options.caseSensitive ? tag : tag.toLowerCase(), '>');`

Resolves this.

**Comment by kangax** [comment]
Thanks! Can you please submit a PR (ideally, with a test case)?

**Comment by JakobJingleheimer** [comment]
Yep. I'll do it tonight when i get home from work.

**Comment by JakobJingleheimer** [comment]
Grr. I kid you not—just as I run `git push`, my home internet died.

What testing framework does this use? It was simple enough to update the exisiting tests for caseSensitive, but I'd like to run it just to be sure.
