### ISSUE TITLE
strip space between quoted attributes

### ISSUE THREAD

**Issue by stoyan** [kangax/html-minifier#2]
see yandex.ru for an example

&lt;link rel=alternate type="application/rss+xml"title="Блог Яндекса"href="http://company.yandex.ru/blog/index.rss"&gt;

**Comment by kangax** [comment]
Ah, good call! :) I'll try to tackle it some time soon.

**Comment by alexlamsl** [comment]
I see a possible implementation for this.

Question: do we need an extra flag to enable/disable this feature?

**Comment by kangax** [comment]
I would want an extra flag, yes. Thank you!

**Comment by kangax** [comment]
This is now implemented!
