### ISSUE TITLE
remove comments from <script> and <style> does not work

### ISSUE THREAD

**Issue by vvo** [kangax/html-minifier#20]
The webpage demo doesn't do it as well, http://kangax.github.com/html-minifier/

**Comment by kangax** [comment]
It actually removes HTML comments from scripts. See, for example, corresponding tests:

```
test('remove comments from scripts', function(){
  input = '<script><!--alert(1)--><\/script>';
  output = '<script><\/script>';
  equals(minify(input, { removeCommentsFromCDATA: true }), output);

  input = '<script><!--alert(1)<\/script>';
  output = '<script><\/script>';
  equals(minify(input, { removeCommentsFromCDATA: true }), output);

  input = '<script type="text/javascript"> <!--\nalert("-->"); -->\n\n   <\/script>';
  output = '<script type="text/javascript">alert("-->");<\/script>';
  equals(minify(input, { removeCommentsFromCDATA: true }), output);

  input = '<script> //   <!--   \n  alert(1)   //  --> <\/script>';
  output = '<script>  alert(1)<\/script>';
  equals(minify(input, { removeCommentsFromCDATA: true }), output);
});
```

**Comment by vvo** [comment]
Ah well ok, I thought it should remove comments like /**/ and // from 
    <script> and <style>

I've found this :
http://james.padolsey.com/javascript/removing-comments-in-javascript/
And I already added it to my custom html minifier (yours + my mods).

Perhaps you do not want it to be included in the "html minifier" ? Thanks

**Comment by kangax** [comment]
The reason I didn't work on removing JS comments from inline script elements is because I wanted them to be removed by another app — as part of minification process (using yui compressor, google closure compiler, etc.)
