### ISSUE TITLE
Add max line length option

### ISSUE THREAD

**Issue by HugoHeneault** [kangax/html-minifier#203]
Hello, 

I use html-minifier for emails, and some mail servers automatically add a new line after 1000 caracters. This behaviour breaks html structure.

For example :

``` `
 <table border="0" cellpaddin
 g="10" 
```

It could be great if we can add an option to limit the line size without breaking the html. 
Do you think this is possible ?

Thanks.

**Comment by duncanbeevers** [comment]
@In4matik I knocked out a super-basic version of this functionality [here](https://github.com/duncanbeevers/html-minifier/tree/limit-line-length).

It's a bit kludgy though I have some ideas about how to improve it, but it should basically accomplish what you're after.

I tested it against the source of [this page](https://github.com/chriso/cli) with a `maxLineLength` setting of 900, and `collapseWhitespace` true, and [this](https://gist.github.com/duncanbeevers/c8c8ba125a730693861e) was the result.

**Comment by kangax** [comment]
@duncanbeevers Looks pretty good! I'm only concerned about performance implications. Could you run `node ./benchmark.js` locally, and compare average time (reported at the end)?

**Comment by HugoHeneault** [comment]
Wow. Seems great @duncanbeevers !

I haven't time to test it, but I will ! Thanks.

**Comment by duncanbeevers** [comment]
@kangax 
[Benchmark output here](https://gist.github.com/duncanbeevers/1070dd250d2c541038bd) run with `gh-pages` as-is, then with `limit-line-length` but not limiting lines, and finally with a `maxLineLength` of 500.

Speed looks pretty stable, variance seems insignificant.

**Comment by kangax** [comment]
Ok, let's get it in. Can you send a PR? Thanks.

**Comment by duncanbeevers** [comment]
Sure. I was thinking of poking at this some more to get better-compressed results.

For example, right now it maximally-compresses

``` html
<a class="hey">link link</a>
```

to this

``` html
<a
 class="hey">
link link
</a>
```

I think the best we can hope for is this:

``` html
<a
class
=
"hey"
>
link
link
</a
>
```

But that's a fish to fry another day!

**Comment by duncanbeevers** [comment]
I think this issue can be closed. If we want to pursue more aggressive splitting, I suggest we address that with another more-focused PR.

**Comment by revelt** [comment]
For posterity, let me clarify a bit the issue regarding "some servers". The SMTP spec RFC 821, defined back in 1982 ([source](https://www.ietf.org/rfc/rfc0821.txt)) says:

> The maximum total length of a text line including the <CRLF> is 1000 characters (but not counting the leading dot duplicated for transparency).

As far as raw email source vs. line length is concerned, there are other factors in play, such as encoding (which can vary), for example quoted-printable is often used and it will encode limiting line length to 76 and so on. But as far as this 1000 character limiter is concerned, I'm pretty sure it's coming from this RFC 821 spec interpretation.
