### ISSUE TITLE
Parse Error with WebComponent / Polymer html syntax

### ISSUE THREAD

**Issue by jmatsushita** [kangax/html-minifier#208]
Hello,

I am trying to run html-minifier on a [Web Component](http://webcomponents.org/) [Polymer](http://www.polymer-project.org/) project and the following syntax is not recognized and gives a `Parse Error`:

```
<div id="mainContainer" flex?="{{mode !== 'cover'}}" on-scroll="{{scroll}}">
<content id="mainContent" select="*"></content>
</div>
```

Not sure where this syntax is documented so I've filed a question on the Polymer repo as well Polymer/polymer#650.

Cheers,

Jun

**Comment by duncanbeevers** [comment]
@jmatsushita This is another issue related to the markup not being valid HTML. Specifically, the `flex?=""` attribute syntax is invalid HTML.

I made some changes to the HTML parser to allow it to parse handlebars conditionals surrounding attributes like `<input type="checkbox" {{#if condition}}checked{{/if}}>`. Your use case is slightly different in that it involves parsing the markup joining the two attribute parts (attribute name, and attribute value).

Making this work would require a similar change to the html parser.
