### ISSUE TITLE
missing a mention of which function to call for programmatic use

### ISSUE THREAD

**Issue by Pomax** [kangax/html-minifier#209]
When using html-minifier in node.js, what's the actual way to call it? The README.md only mentions `require('html-minifier')` but then doesn't show another three or four lines of example code for turning an input string into a minified output string. Based on the code, would this be enough?

```
var htmlMinifier = require('html-minifier');
var data = "<!doctype html><html> ... </html>";
var minified = htmlMinifier.minify(data, { options from README.md });
```

(for node.js purposes it might also make sense if there was a third optional `callback` (or `next` or whatever) arg so that programmatically it can be called asynchronously)

**Comment by kangax** [comment]
Thanks, made it more explicit
