### ISSUE TITLE
html tree breaks

### ISSUE THREAD

**Issue by vvo** [kangax/html-minifier#21]
Using http://kangax.github.com/html-minifier/ if I try to minify :

``` html
<a href="test.html"><div>hey</div></a>
```

I get :

``` html
<a href="test.html"></a><div>hey</div>
```

Yes having `<div>` in a `<a>` is strange but it works in browsers (is this valid html5?)

**Comment by kangax** [comment]
Block elements inside `<a>` are valid in HTML5, afaik, but not in HTML4.01. And parser follows HTML4.01 behavior, which is why `<a>div></div></a>` is invalid and breaks.

**Comment by kswedberg** [comment]
Any update on this? Is there any chance that the parser could be updated to allow for HTML5 block elements inside `<a>`?

**Comment by kangax** [comment]
This now works. Added corresponding test.
