### ISSUE TITLE
minifyJS doesn't work

### ISSUE THREAD

**Issue by totty90** [kangax/html-minifier#211]
I've tried `minifyJS:true` or passing options and doesn't work.
Original HTML `<script type="text/javascript">if(typeof DEBUG === 'undefined'){ DEBUG = true; if(true) console.log(1)}</script>` and output html `<script type=text/javascript>if(typeof DEBUG === 'undefined'){ DEBUG = true; if(true) console.log(1)}</script>`

Notice that the `if(true)` has not been removed from the HTML, which is what Uglify2 does.

**Comment by kangax** [comment]
Works for me on http://kangax.github.io/html-minifier/
Make sure you're using the latest version.
