### ISSUE TITLE
Make comment removal happen before whitespace collapsing

### ISSUE THREAD

**Issue by rbro** [kangax/html-minifier#215]
When running html-minifier, I noticed the following minor behavior.

Running

```
html-minifier --remove-comments --collapse-whitespace --conservative-collapse
```

the html:

```
<html>

<!--test-->

</html>
```

is translated into `<html>  </html>`.  Note, there are 2 spaces between the html tags.  Should there be 1 space instead?  It looks like the extra space is because of the comment that was removed.

Is it possible for the comments to be stripped first and then the whitespace collapsed?

Thanks for your help.

**Comment by kangax** [comment]
Hm, when I run it through http://kangax.github.io/html-minifier/ I get 1 space only, but probably shouldn't be any at all.

**Comment by rbro** [comment]
I was expecting 1 space because of the option --conservative-collapse.

If I remove the comment on my own first , then I get 1 space.  Since I'm running --remove-comments, I was expecting the same 1 space since comments should be removed and then whitespace collapsed.

I was able to get 2 spaces on http://kangax.github.io/html-minifier with these options:
- Remove comments
- Collapse whitespace
- Conservative whitespace collapse

**Comment by stevenvachon** [comment]
Additionally, `--conservative-collapse` should remove whitespace within `<head>`.

**Comment by c-vetter** [comment]
+1
I ran into this issue today as well.

@stevenvachon 
That suggestion is probably better placed in a new ticket.

@rbro
It might be a good idea to rename the ticket to something like "Make comment removal happen before whitespace collapsing" in order to keep it focussed and precise.

**Comment by papandreou** [comment]
I just tried to upgrade from html-minifier 1.1.1 to 2.1.1, and the fix for this (8b19a64) seems to have caused a regression, according to `git bisect`.

It comes down to:

``` js
console.log(require('html-minifier').minify('<div><span></span> <!--# echo "foo" --> bar</div>', {
    collapseWhitespace: true,
    conservativeCollapse: true,
    ignoreCustomComments: [ /^#/ ]
}));
```

which used to output:

``` html
<div><span></span> <!--# echo "foo" --> bar</div>
```

but now comes out as:

``` html
<div><span></span><!--# echo "foo" --> bar</div>
```

It seems like `conservativeCollapse` is not being honored anymore in this particular case?

**Comment by papandreou** [comment]
Another weird thing that changed with that commit: With the same options as above,

``` html
<body>
<!--[if !IE]>-->Not IE<!--<![endif]-->
</body>
```

now minifies to

``` html
<body><!--[if !IE]>--> Not IE<!--<![endif]--> </body>
```

but it used to minify to:

``` html
<body> <!--[if !IE]>-->Not IE<!--<![endif]--> </body>
```

(notice that the whitespace moved)

**Comment by alexlamsl** [comment]
@papandreou please file a separate issue.

I won't be surprised to see `conservativeCollapse` having a few hiccups as I haven't been using it myself...

**Comment by papandreou** [comment]
@alexlamsl Okay, https://github.com/kangax/html-minifier/issues/652
