### ISSUE TITLE
LoDash Template minification

### ISSUE THREAD

**Issue by stramel** [kangax/html-minifier#217]
Trying to minify a HTML file that has LoDash templating causes it to hang indefinitely.

Seems similar/related to #177 & #83  
Would help fix [gulp-htmlmin](https://github.com/jonschlinkert/gulp-htmlmin/) [issue #12](https://github.com/jonschlinkert/gulp-htmlmin/issues/12)

**Comment by kangax** [comment]
What's the exact string?

**Comment by stramel** [comment]
``` html
<ol class="row">
  <% _.forEach(selectionSort, function(selectionId) { %>
    <li change-selection="selectionChanger"
        rules="scopeForPopular(scope.selectionSeparator, scope.selectionRules, <%- selectionId %>, 'rules', true)"
        selection="scopeForPopular(scope.selectionSeparator, scope.selectionRules, <%- selectionId %>, 'selectionRules', false)"
        selection-data="selectionData[<%- selectionId %>]"
        selection-id="<%- selectionId %>"
        selection-type="<%- selectionType %>"
        <%- selectionType %>>
    </li>
  <% }); %>
</ol>
```

**Comment by duncanbeevers** [comment]
This example has "invalid" html at `<%- selectionType %>`.
We offer the `customAttrSurround` option for dealing with this in handlebars templates.

``` html
<input type="checkbox" {{#if checked}}checked{{/if}}>
```

I think this situation can be dealt with using a customAttrSurround pair like `[/<%\-\s+/, /%>/]`, this preserving the LoDash delimiters and the `selectionType` attribute "name".

**Comment by icd2k3** [comment]
This doesn't work for me

for example
`<div <%= active ? 'class="active"' : 'class="inactive"' %>>`

with:

`customAttrSurround: [
    [/<%\=\s+/, /%>/],
    [/<%\-\s+/, /%>/]
]`

still hangs indefinitely. See https://github.com/kangax/html-minifier/issues/293

**Comment by duncanbeevers** [comment]
The "interior" of this attribute is not a valid html attribute.

```
active ? 'class="active"' : 'class="inactive"'
```

Perhaps you could use something like this?

``` html
<div class="<%= active ? 'active' : 'inactive' %>">
```

Using this format, no `customAttrSurround` is necessary.

**Comment by icd2k3** [comment]
Hey, thanks for the reply Duncan!

Yes things can definitely be rewritten this way, but there's a couple problems...

For one, this is a huge existing application so going through all the templates and rewriting all the places where inline/nested ejs tags are used would be a large task. I would also have to instruct my devs not to do this anymore even though it's allowed in ejs templates.

Also, there are times when using nested/inline ejs tags is beneficial. For example:
`<img <%= loadLater ? 'data-src="imgSRC"' : 'src="imgSRC"' %> />`
Rewriting it to work with htmlmin would make it longer
`<img data-src="<%= loadLater ? 'imgSRC' : '' %>" src="<%= loadLater ? '' : 'imgSRC' %>" />`

In the meantime I've been able to use [htmlcompressor](https://code.google.com/p/htmlcompressor/) without error, but htmlmin provides better compression.

**Comment by hwoarangzk** [comment]
I met the same problem using `art-template`, is it solved yet?
