### ISSUE TITLE
option for not turning quotes into &quot;?

### ISSUE THREAD

**Issue by Pomax** [kangax/html-minifier#218]
There is no good reason to convert quotes into HTML entities (only `<` and `>` cause parser problems in HTML), but it looks like the minify process does this anyway, and I cannot seem to find how to turn this behaviour off. Is there an option that I completely missed that turns off this conversion?

**Comment by Pomax** [comment]
actually, disregard, the &quot; comes from a different util earlier in the chain =_=

**Comment by ghost** [comment]
Ha ha, thanks. I just had the same problem. :)

**Comment by Pomax** [comment]
new year, same problems =D
