### ISSUE TITLE
Don't remove empty <script>'s with non-empty src (removeEmptyElements)

### ISSUE THREAD

**Issue by eush77** [kangax/html-minifier#219]
Empty `<script>`'s with non-empty `src` attribute should probably be preserved, just like `<textarea>`'s.

**Comment by kangax** [comment]
Hm, good point. Same for `<link>`'s.

**Comment by eush77** [comment]
Actually I can't see the problem neither with `<link>`'s, nor with other void elements (like `<img>` or `<meta>`). It seems that HTMLParser takes care of that.

**Comment by duncanbeevers** [comment]
I think this can be closed.

**Comment by kangax** [comment]
thanks @duncanbeevers
