### ISSUE TITLE
Parse error on /*><*/

### ISSUE THREAD

**Issue by kangax** [kangax/html-minifier#220]
https://news.ycombinator.com/item?id=8110056

**Comment by username1290** [comment]
Hi from HN, :+1:

**Comment by duncanbeevers** [comment]
Can you give a better description of the bug here? I wrote a simple test case that didn't fail as I expected it to, and thus wasn't very illuminating.

``` javascript
input = '<style type="text/css">/*><*/</style>';
equal(minify(input, { minifyCSS: true }), '<style type="text/css"></style>');
```

**Comment by kangax** [comment]
Hm, I see now that it fails in raw form — `/*>  < */` — without surrounding `<style>` tags. This is probably due to minifier attempting to parse `<*/` as a start tag.

@sogen is there a reason you have such markup outside of style element?

**Comment by username1290** [comment]
It was some "ascii banner text" to use as a bookmark in the CSS code, so I
pasted the pure CSS code (including that comment with the included > < )
into the minifier, to check the minification output

**Comment by kangax** [comment]
Since it works with style's surrounded and is not valid HTML otherwise, I think it's safe to close this.
