### ISSUE TITLE
Freeze when minify template

### ISSUE THREAD

**Issue by sopilkar** [kangax/html-minifier#222]
Example:

``` javascript
var input = '<input type="submit" name="accept" value="{{{ phrase "ACCEPT" }}}"/>';
var result = minify(input, {
    ignoreCustomComments: [
        [ /\{\{\{/, /\}\}\}/ ]
    ]
});
```

**Comment by duncanbeevers** [comment]
@sopilkar This is invalid HTML. You can't use double-quotes inside `value` attribute value.

Simply change the internal double-quotes to single-quotes.

``` javascript
var input = '<input type="submit" name="accept" value="{{{ phrase \'ACCEPT\' }}}"/>';
```

**Comment by sopilkar** [comment]
@duncanbeevers This is not invalid HTML. This is part of template that work successful. For this template engine needs use double-quotes only.
What's problem? I think if we use option 'ignoreCustomComments' html-minifier must ignore any characters inside this custom comment.
grunt-htmlcompressor can compress this html without problems but it very slow.

**Comment by kangax** [comment]
@sopilkar First of all, `ignoreCustomComments` is for ignoring comments; that means anything starting with `<!--` and ending with `-->` plus whatever regex you supply to match its contents. This is why it doesn't do anything for `{{{` and `}}}`. Second, parsing quotes within same quotes is a hassle and is not meant to work in the first place. I'm glad that htmlcompressor is able to "handle" them (and perhaps that's one of the reasons it's slow? :P), but I really don't think it's wise for us to "bend backwards" like that and try to support nonsensical (from HTML point of view) constructs. How would we know where the attribute value starts and where it ends, if matching quote no longer means the end of attribute value? The job of template engine you're using is easy — it's only looking for `{{{` and `}}}`; then it creates (sensible) HTML and passes it onto HTML parser/renderer. It's a multistep process. Trying to "understand" multi-step markup in our parser certainly sounds like a futile attempt. This is a path to ambiguous nightmare, a recipe for disaster, a can of worms waiting to be opened.

Having said that, I'm open to seeing possible solutions to this "issue", so long as they don't hinder performance of common use cases. If you have some ideas on how we could implement this — I'm all ears.

**Comment by sopilkar** [comment]
@kangax For example add a new option:

``` javascript
'ignoreTemplateBrackets': [
    ['{{{', '}}}'],
    ['{{#if}}', '{{/if}}']
    ....
]
```

Step one. If we use this option we need just mark these template blocks as 'ignored' (or escape it and unescape after finish parse).
Step two - run normal parsing process.

**Comment by alexlamsl** [comment]
With the current version you can do this already:

```
> minify('<input type="submit" name="accept" value="{{{ phrase "ACCEPT" }}}"/>', {ignoreCustomFragments:[/\{\{\{[\s\S]*?\}\}\}/]});
'<input type="submit" name="accept" value="{{{ phrase "ACCEPT" }}}">'
```

So I guess this is now considered fixed?

**Comment by skumaresan** [comment]
Hi,
We are using jquery template. I am getting html parse error for below line due to less than symbol.

`${( $data.isCategory = setdepth < 2 ),''}`

**Comment by alexlamsl** [comment]
@skumaresan I don't think what you said is related to this issue. Please file a new one?

**Comment by skumaresan** [comment]
@alexlamsl html parser consider  "< 2" as html tag. So its throw error.
