### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by stevenvachon** [kangax/html-minifier#225]
Not sure where the issue is, but I'd noticed that anything beyond this was not minified which led me to me thinking that it was all being treated as a comment. Running the start of the ignored part:

``` html
<!--[if IE 6]><style type="text/css"><!--
  #navbar.nav-sprite-v1 .nav-sprite {
    background-image: url(http://g-ecx.images-amazon.com/images/G/15/gno/sprites/global-sprite-v1._V339353380_.png);
  }
--> <![endif]-->
asdfasdf
```

resulted in a parse error

**Comment by kangax** [comment]
So basically this:

``` html
<!--[if IE 6]><!-- test --><![endif]-->
```

It probably chokes on the fact that it's a comment within a comment. I'll take a closer look when I get a chance.

**Comment by duncanbeevers** [comment]
What is the expected output here?

Preserve everything within the conditional comment?

``` javascript
var input = '<!--[if IE 6]><!-- test --><![endif]-->';
expect(minify(input, { removeComments: true }), input);
```

Remove the inner comment?

``` javascript
var input = '<!--[if IE 6]><!-- test --><![endif]-->';
expect(minify(input, { removeComments: true }), '<!--[if IE6]><![endif]-->');
```

Blow away all the comments?

``` javascript
var input = '<!--[if IE 6]><!-- test --><![endif]-->';
expect(minify(input, { removeComments: true }), '');
```

**Comment by kangax** [comment]
@duncanbeevers Good question. Looking at our tests — https://github.com/kangax/html-minifier/blob/gh-pages/tests/minifier.js#L168-L177 — we're treating IE conditional comments not like regular comments; they aren't affected by `removeComments`. And we also don't strip comments in attributes — https://github.com/kangax/html-minifier/blob/gh-pages/tests/minifier.js#L164-L165

So... we should do either 1 or 2. Stripping conditionals entirely would be wrong. I'm leaning towards stripping comments inside, leaving just conditionals (option 2).

Does this sound reasonable? /cc @stevenvachon

**Comment by duncanbeevers** [comment]
Whichever way we go, I'd like to have a more concrete use-case to target than this initial snippet.

I'm all for making the tool easy to use, and I want it to do the right thing out of the box. It's unclear to me what the right thing is, in this case.

**Comment by stevenvachon** [comment]
The contents of IE conditional comments should probably be parsed as HTML (by htmlparser).

**Comment by kangax** [comment]
I agree. Any way you put it, the fact that we can parse style + comments:

``` html
<style type="text/css"><!--
  #navbar.nav-sprite-v1 .nav-sprite {
    background-image: url(http://g-ecx.images-amazon.com/images/G/15/gno/sprites/global-sprite-v1._V339353380_.png);
  }
--></style>
```

..and conditionals + style:

``` html
<!--[if IE 6]><style type="text/css">
  #navbar.nav-sprite-v1 .nav-sprite {
    background-image: url(http://g-ecx.images-amazon.com/images/G/15/gno/sprites/global-sprite-v1._V339353380_.png);
  }
</style><![endif]-->
```

..but not both:

``` html
<!--[if IE 6]><style type="text/css"><!--
  #navbar.nav-sprite-v1 .nav-sprite {
    background-image: url(http://g-ecx.images-amazon.com/images/G/15/gno/sprites/global-sprite-v1._V339353380_.png);
  }
--></style><![endif]-->
```

is just not right.

**Comment by kangax** [comment]
Curiously, even @github's highlighting seems to choke on it :)

**Comment by alexlamsl** [comment]
Just tried:

```
<!--[if IE]><script><!--
alert(1)
--></script>abc<![endif]-->
```

and I couldn't find a web browser that wouldn't show `abc`.

So why are we expecting `minify()` to work in this case again? :sweat_smile:
