### ISSUE TITLE
customr attributes with line breaks spacing

### ISSUE THREAD

**Issue by webuniverseio** [kangax/html-minifier#226]
Hi, thank you very much for such a great tool, great job indeed!
I just wonder if it is possible to do anything with custom attributes when they have line breaks:

Will not be minified

```
<img data-class="
    test
    test2
" />
```

```
<img data-bind="attr: {
                    id: 'visualCartAddedItem' + ProductDetails.PID,
                    src: $root.UI.setDynamicImageWidthHeight(ProductDetails.ImageUrl, 91, 111, null, $data.isEGift),
                    alt: $root.Languages.isFrench() ? (ProductDetails.FrenchTitle || ProductDetails.Title) : ProductDetails.Title,
                    title: $root.Languages.isFrench() ? (ProductDetails.FrenchTitle || ProductDetails.Title) : ProductDetails.Title
">
```

Does it makes sense to remove line breaks and replace them with spaces?

**Comment by duncanbeevers** [comment]
Newlines in html attribute values are valid and recognized. I think the only way you're going to get what you're after here is with some kind of custom attribute processing. Currently `html-minifier` provides a handler to its html parser that deals with all of this. To handle this, we'd need to allow you to override/extend the built-in handler's attribute handling.

I played with this for just a moment, but didn't have a lot of incentive to go very deep. I'm reticent to suggest adding options to `html-minifier` that are really just proxying for features already provided, fully or partially, by the underlying html parser.

@szarouski Do you have any estimate of what kind of space savings you'd see in an optimal compression scenario?

My gut feeling is that this is too niche a use-case with too meager benefits to qualify for inclusion. I'm biased of course!

**Comment by duncanbeevers** [comment]
Looks like a duplicate of https://github.com/kangax/html-minifier/issues/98

**Comment by webuniverseio** [comment]
You're right, I agree with all the comments in #98, so I'll close that one. Thank you.
