### ISSUE TITLE
Uppercase Tags Handled Incorrectly

### ISSUE THREAD

**Issue by AlicanC** [kangax/html-minifier#229]
HTML:

``` html
<CUSTOM-TAG></CUSTOM-TAG><div>Hello :)</div>
```

Expected result:

``` html
<custom-tag></custom-tag><div>Hello :)</div>
```

The result which causes hours of debugging of a complex build system:

``` html
<custom-tag><div>Hello :)</div></custom-tag>
```

The same happens with standard tags too.

**Comment by kangax** [comment]
Gotta use case sensitive option, but tag nesting is incorrect indeed.

**Comment by AlicanC** [comment]
Should case sensitivity option affect how a file is parsed? Who would want the option to get his tags shagged?

**Comment by kangax** [comment]
> Should case sensitivity option affect how a file is parsed?

No, but it would keep your CUSTOM-TAG as is. Like I said, the parsing issue is a bug.

**Comment by AlicanC** [comment]
Oh, I understand. I never intended to keep their cases, but thanks for pointing it out.
