### ISSUE TITLE
Multiple files minify

### ISSUE THREAD

**Issue by CodeBendr** [kangax/html-minifier#230]
I can't seem to be able to minify multiple files like so

src: ['source/views/checkout/*.ejs'],
dest: 'build/views/checkout/'

Warning: Unable to write "build/views/checkout/" file (Error code: EISDIR). Use --force to continue.

**Comment by JGibel** [comment]
Are you putting them in a files property? You shouldn't need that last slash in dest as well.

files: [{
                expand: true,
                src: ['source/views/checkout/*.ejs'],
                dest: 'build/views/checkout'
            }]

**Comment by CodeBendr** [comment]
This is what i currently have. But still not working. It only works for single files. Can you send me the code for minifying multiple files? i know am doing something wrong. 

htmlmin: {
            options: {
                removeComments: true,
                collapseWhitespace: true
            },
            ejs_files: {
                src: 'source/views/*_/_.ejs',
                dest: 'build/views'
            }
          }
