### ISSUE TITLE
self closing tag after attribute not being handled correctly

### ISSUE THREAD

**Issue by AlistairB** [kangax/html-minifier#233]
In other words `<link rel="stylesheet" href="/bundles/links-c90492ab.css"/>` gets minified to `<link rel=stylesheet href=/bundles/links-c90492ab.css/>` which will make a request for `'/bundles/links-c90492ab.css/'` which will 404 due to the trailing slash.

Settings:

```
removeComments: true,
collapseWhitespace: true,
collapseBooleanAttributes: true,
removeAttributeQuotes: false,
keepClosingSlash: false,
removeRedundantAttributes: true,
useShortDoctype: true,
removeEmptyAttributes: true,
removeOptionalTags: true,
removeEmptyElements: false,
keepClosingSlash: true
```

Should remove closing slash before removing attribute quotes.

**Comment by duncanbeevers** [comment]
I think the most "efficient" solution in terms of number of output characters would be to generate quotes around the terminal attribute values in self-closed tags.

``` xml
<tag foo=bar baz="buzz"/>
<tag foo=bar baz=buzz><tagChild/></tag>
```
