### ISSUE TITLE
Error on big data

### ISSUE THREAD

**Issue by ghost** [kangax/html-minifier#234]
When "feeding" large amounts of HTML, the NPM package simply outputs to stdout.

**Comment by kangax** [comment]
Need some kind of reproducible example chunk/file

**Comment by ghost** [comment]
Any large chunk. I tried with 500k, for example.

**Comment by Klathmon** [comment]
I can confirm this is also happening to me on a 340kb input file. I can provide the source file to you (@kangax) if you want it.

**Comment by ghost** [comment]
Thanks for the confirmation @Klathmon

**Comment by alexlamsl** [comment]
Is this still an issue? `node benchmark` can now handle [a >3MB file](https://github.com/kangax/html-minifier/blob/gh-pages/benchmarks/es6.html) without blowing up...

**Comment by ghost** [comment]
I'll test and let you know.

**Comment by alexlamsl** [comment]
@conmarap while working on #494, I observed much performance improvements with larger files over the history of this repository.

Unless you have particular examples where the current version of `html-minifier` still chokes over, I think this issue have largely been resolved.

**Comment by ghost** [comment]
Ok, we can close this out and I'll simply re-open if I see such an example!
