### ISSUE TITLE
Sortable value stripped by collapseBooleanAttributes

### ISSUE THREAD

**Issue by pasine** [kangax/html-minifier#236]
I am using html-minifier with Angularjs and [ngTable](http://bazalt-cms.com/ng-table/).
The module use the syntax `sortable=" 'field-to-sort' "` to sort the tables ([Example](http://bazalt-cms.com/ng-table/example/3)).
I just realized that html-minifier is stripping the attribute value if `collapseBooleanAttributes`.
I went through issue #63 and got the reason.
I tried to find the specs of `sortable` attribute, but I wasn't able to find anything related.
I am not sure the attribute should accept parameters others than just `true/false`, so I don't know if this is an issue with html-minifier.
In case it isn't, I hope that sharing my issue could be useful to other people facing the same problem.

**Comment by duncanbeevers** [comment]
That attribute might just be acting as part of the ng-table directive, and isn't necessarily even included in the ultimate markup generated by the directive, so the sense of the meaning of the attribute is distinctly different in the context of angular.

According to the w3c spec, [`sortable` is a boolean attribute](http://www.w3.org/html/wg/drafts/html/master/tabular-data.html#attr-table-sortable).

[The spec for boolean attributes](http://www.w3.org/html/wg/drafts/html/master/infrastructure.html#boolean-attribute) is pretty unequivocal on how these attributes may be used.

> A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.
> 
> ...
> 
> The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

It's a little unfortunate that ngTable has overloaded the meaning of this attribute in a somewhat confusing way.

I don't think this qualifies as a bug in html-minifier. My feeling is that the best path forward would be to request a change in ngTable to use an alternative attribute such as `sortBy` to drive its sorting behavior. The old attribute could continue to be recognized, providing deprecation protection to existing consumers of the library.

CC @esvit

**Comment by pasine** [comment]
Never thought it was a bug in html-minifier. I was just not sure if the sortable attribute was boolean. Your link clarify the issue. Thanks.
