### ISSUE TITLE
Don't attempt to auto-close tags

### ISSUE THREAD

**Issue by goodpixels** [kangax/html-minifier#243]
...or make that a configurable option. I'm trying to minify a file, which is a partial view, hence it only includes the opening tag, and the closing tag is in another view. When I minify them, those tags are being closed, resulting in the `<body>` tag closed twice in the final output of my application.

**Comment by kangax** [comment]
Partial chunks of markup are not supported because we parse markup into a tree, modify it, then spit out markup again. We can't know that original markup was only half of the tree, because we did our best to try to parse it as a full tree.
