### ISSUE TITLE
<style> tag doesn't get compressed

### ISSUE THREAD

**Issue by genechan** [kangax/html-minifier#249]
I have a style tag holding bare minimum "page load" css for the page.
The comments (/**/,  ) don't get removed and the css does not get compress along with the reset of the html

**Comment by duncanbeevers** [comment]
Can you post an example style tag along with the minify options you're using?

**Comment by genechan** [comment]
Below is my grunt.js settings and style tag. I removed the comments for  manually already because it was breaking my code.

```
  //Minfiy html from my gruntfile.js
htmlmin:{
  default:{
    files:{
      "../htdocs/index.html":"../htdocs/index.html"
    }
  },
  release:{
    options:{
      removeComments: true,
      collapseWhitespace: true
    },
    files:[{
      expand: true,
        cwd: '../htdocs',
        src: ['*.html','**/*.html'],
        dest: '../htdocs'
    }]           
  }
}
    <style type="text/css">
        /* reset.css ############################################################# 
```

'||''|.                            .  
 ||   ||    ....   ....    ....  .||.  
 ||''|'   .|...|| ||. '  .|...||  ||  
 ||   |.  ||      . '|.. ||       ||  
.||.  '|'  '|...' |'..|'  '|...'  '|.' 

reset.css ############################################################# */

html {margin:0;padding:0;border:0;}
body, div, span, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, code, del, dfn, em, img, q, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, dialog, figure, footer, header, hgroup, nav, section {margin:0;padding:0;border:0;font-weight:inherit;font-style:inherit;font-size:100%;font-family:inherit;vertical-align:baseline;}
article, aside, dialog, figure, footer, header, hgroup, nav, section {display:block;}
body {line-height:1.5;background:white;}
table {border-collapse:separate;border-spacing:0;}
caption, th, td {text-align:left;font-weight:normal;float:none !important;}
table, th, td {vertical-align:middle;}
blockquote:before, blockquote:after, q:before, q:after {content:'';}
blockquote, q {quotes:"" "";}
a img {border:none;}
:focus {outline:0;}
.clearfix:after {content:"\0020";display:block;height:0;clear:both;visibility:hidden;overflow:hidden;}
.clearfix {display:block;}
.clear {clear:both;}
/\* END reset.css >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> _/
            .left{float: left;}
            .right{float: right;}
            header{
    width: 96%;
    float: right;
    max-height: 50px;
}
header nav{
    max-height: 50px;
}
nav .logo{
    max-height: 50px;
    background-color: black;
    width: 50%;
    display: inline-block;
    height: 50px;
}
nav .logo h1{
    display: inline-block;
    color:#669999;
    margin-left: 20px;
}
nav .logo ul{
    float: right;
}
nav .logo li{
    margin-right: 10px;
}
nav .logo ul,nav .logo li{
    display: inline;
}
nav .logo a,nav .logo a:visited{
    color: #666666;
    text-decoration: none;
}
nav .logo,nav .portal{
    float: left;
}
nav .portal{
    display: inline-block;
    width: 50%;
    background-color: #444444;
    height: 50px;
}
nav .portal div{
    display: inline-block;
}
nav .portal span,nav .portal a,nav .portal a:visited{
    color: #fff;
    text-decoration: none;
}
/_Style forms later*/
nav form{
    display: none;
}

```
    </style>    
```

**Comment by duncanbeevers** [comment]
@genechan Sorry, it looks like the markup got a little shredded here. Can you post your markup as a gist and provide a link to it?

**Comment by genechan** [comment]
https://gist.github.com/genechan/c5db7f8c3398fe6abd74

**Comment by duncanbeevers** [comment]
It looks like you simply need to specify the `minifyCSS` option in your minification configuration.

After adding `minifyCSS: true`, the markup you provided compresses to [this](https://gist.githubusercontent.com/duncanbeevers/792d37e7c48bb686c403/raw/703882251b41b63ca05340c04d40fb4581ba596d/gistfile1.html).

**Comment by genechan** [comment]
I can't believe I missed that.
Thank you so much!!

**Comment by duncanbeevers** [comment]
@genechan Would you mind closing this issue?
