### ISSUE TITLE
Angular-UI Bootstrap - Warning: Parse Error: < value ? '*' : ' ' }})</span>

### ISSUE THREAD

**Issue by ivanbreet** [kangax/html-minifier#254]
Hi,

I'm having a strange issue with the Angular-UI Bootstrap templates. I get the following error when I try to minify the `rating.html` file with `grunt-angular-templates`:
**Warning: Parse Error: < value ? '*' : ' ' }})</span>**

**The latest `rating.html`**

``` html
<span ng-mouseleave="reset()" ng-keydown="onKeydown($event)" tabindex="0" role="slider" aria-valuemin="0" aria-valuemax="{{range.length}}" aria-valuenow="{{value}}">
    <i ng-repeat="r in range track by $index" ng-mouseenter="enter($index + 1)" ng-click="rate($index + 1)" class="glyphicon" ng-class="$index < value && (r.stateOn || 'glyphicon-star') || (r.stateOff || 'glyphicon-star-empty')">
        <span class="sr-only">({{ $index < value ? '*' : ' ' }})</span>
    </i>
</span>
```

**htmlmin options**

``` javascript
htmlmin: {
            collapseWhitespace: true,
            collapseBooleanAttributes: true,
            removeAttributeQuotes: true,
            removeComments: true, // Only if you don't use comment directives!
            removeEmptyAttributes: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true,
            processScripts: ["text/ng-template"]
}
```

**Comment by duncanbeevers** [comment]
Hmm, this is a little tricky. I think technically in a text block like that, `<` should be html-encoded. I don't know how angular deals with that.

It certainly wouldn't look pretty writing `{{ $index &lt; value ? '*' : ' ' }}`.

I think this might be a situation that is simply out of reach of this tool. If being able to minify this is important, perhaps you could make a simple filter for emitting the output need based on the value of `$index`

**Comment by ivanbreet** [comment]
I totally agree. The filter is the best solution.

I'll raise it with the Angular-ui guys.

Thank you.
Ivan Breet
