### ISSUE TITLE
Minifying hangs in attributes surrounded by custom tags

### ISSUE THREAD

**Issue by improved-broccoli** [kangax/html-minifier#257]
``` html
<img src="img/shop.gif" {{#if sign_logo}} alt="{{ sign }}" data-echo="{{image sign_logo}}" {{/if}} width="80" height="60" />
```

The minifying hanged because there where a whitespace between the `"{{image sign_logo}}"``and`{{/if}}`.

My regex was  `[/\{\{#if\s+\w+\}\}/, /\{\{\/if\}\}/]`.

When I updated it to  `[/\{\{#if\s+\w+\}\}/, /\s\{\{\/if\}\}/]` (note the new `\s` at the start of the second regex), it didn't hang anymore. Though, it never hanged about the whitespace between `{{#if sign_logo}}` and `alt="{{ sign }}"`.
Maybe I'm splitting the hairs ...

**Comment by duncanbeevers** [comment]
Sorry I missed this issue. Is this still happening after wrapping individual attributes?

**Comment by improved-broccoli** [comment]
Unfortunately, it does.

**Comment by duncanbeevers** [comment]
So the idea with `customAttrSurround` is that the declared delimiters are immediately-adjacent to the beginning and end of any attr+value pair. What happens within the attribute, and specifically within the quote value portion of the attr+value pair is entirely driven by standard html parsing rules, according to which, whitespace within attribute values is perfectly valid.

You're not splitting hairs, as the parser definitely treats the two sections (attr-surround expressions and attr-value pairs) with distinct rules and no implicit crossover.

If you want to keep wrapping attrs with that extra whitespace, just go ahead and add it to each part of the regular expression, just as you did. I don't think there's any bug here, and the changes you suggested for the wiki documentation should be sufficient to help others diagnose this issue should they encounter it.

**Comment by improved-broccoli** [comment]
Ok, great, I agree. May I close ?
