### ISSUE TITLE
Handlebars tags broken when surrounding multiple attributes

### ISSUE THREAD

**Issue by improved-broccoli** [kangax/html-minifier#258]
``` html
<img src="img/shop.gif" {{#if sign_logo}}alt="{{sign}}" data-echo="{{image sign_logo}}"{{/if}} width="80" height="60" />
```

When I minify this markup, I get this:

``` html
<img src="img/shop.gif" if sign_logo alt="{{sign}}" data-echo="{{image sign_logo}}" if width="80" height="60">
```

You may noticed the opening and closing `if` tag is broken.

Here is my configuration (It is a Grunt task):

``` javascript
options: {
               removeComments: true,
               collapseWhitespace: true,
               removeCommentsFromCDATA: true,
               removeRedundantAttributes: true,
               customAttrSurround: [
                   [/\{\{#[^}]+\}\}/, /\{\{\/[^}]+\}\}/],
                ]
            }
```

I tried with `keepClosingSlash: true`, and it did not solved the issue.

**Comment by duncanbeevers** [comment]
The `customAttrSurround` option adds special per-attribute delimiters. It's not going to be able to recognize multiple attributes wrapped in a single handlebars block.

You'll have to duplicate the handlebars block for each attribute you wish recognized.

``` html
<img src="img/shop.gif" {{#if sign_logo}}alt="{{sign}}"{{/if}} {{#if sign_logo}}data-echo="{{image sign_logo}}"{{/if}} width="80" height="60" />
```

This does seem marginally useful, and just emitting broken markup without a warning certainly isn't ideal. On the other hand, it pushes more and more knowledge of the workings of templating systems into a general-purpose tool.

I hope the suggestion helps and the repetition in your markup doesn't grate.

**Comment by improved-broccoli** [comment]
It does. Thanks for answering. 

Could it be possible to add the caveats in this [wiki page](https://github.com/kangax/html-minifier/wiki/Minifying-Handlebars-templates)

**Comment by duncanbeevers** [comment]
@jbenoit2011 The wiki has been updated to call out individual attribute+value pair wrapping.

**Comment by improved-broccoli** [comment]
Great. Thanks. May I close the issue?
