### ISSUE TITLE
ignoreCustomTags optional attribute

### ISSUE THREAD

**Issue by robertTop10** [kangax/html-minifier#263]
When using mustache includes in a tag
`<a href="src" {{> attributes}}>Hello world</a>`

The HTML parser will now fail, I believed that ignoreCustomComments would achieve this outcome, but then realized it looks in between `<!-- -->`

Adding an option to exclude tags based on regexs (similar to customAttrSurround) would enable the minifier to be used in a greater range of scenarios.

**Comment by hwoarangzk** [comment]
Is this problem solved? I met the same

**Comment by fspafford** [comment]
I also need this feature so I can ignore some custom tags that are handled on the server side. Example:
<!-#System_GetValue ID=PageHeader>

**Comment by kangax** [comment]
You can use  for it
