### ISSUE TITLE
Closing tags of empty tags are lost 

### ISSUE THREAD

**Issue by igorbljahhin** [kangax/html-minifier#266]
Hi!

I got the issue with htmlmin (tried both htmlmin 0.1.3 and the latest 0.3.0): closing tag of empty element is lost after minifying. Too puty I can't attach the test project to the ticket, so you could reproduce this issue easily.

My source was src/main/webapp/index.html

<pre>
&lt;h1 class="headline1 breadcrumb" ui-view="breadcrumb" />
&lt;div class="block-l sr" ui-view="leftContent" />
&lt;div class="block-s" ui-view="faqLinks" />
</pre>

and it is minified into yo/dist/index.html

<pre>
&lt;h1 class="headline1 breadcrumb" ui-view="breadcrumb">
&lt;div class="block-l sr" ui-view="leftContent">
&lt;div class="block-s" ui-view="faqLinks">
</pre>

My directory structure is the following

<pre>
src/main/webapp/index.html
yo/dist
yo/Gruntfile.js
yo/package.json
</pre>

My Gruntfile is below:

<pre>
'use strict';

module.exports = function (grunt) {

    // Load grunt tasks automatically
    require('load-grunt-tasks')(grunt);

    // Time how long tasks take. Can help when optimizing build times
    require('time-grunt')(grunt);

    grunt.initConfig({
        yeoman: {
            app: '../src/main/webapp',
            dist: 'dist'
        },
        clean: {
            dist: {
                files: [
                    {
                        src: [
                            '<%= yeoman.dist %>/*'
                        ]
                    }
                ]
            }
        },
        copy: {
            dist: {
                files: [
                    {
                        expand: true,
                        dot: true,
                        cwd: '<%= yeoman.app %>',
                        dest: '<%= yeoman.dist %>',
                        src: [
                            '*.html'
                        ]
                    }
                ]
            }
        },      
        htmlmin: {
            dist: {
                options: {
                    removeEmptyElements: false
                },
                files: [
                    {
                        expand: true,
                        cwd: '<%= yeoman.dist %>',
                        src: ['*.html'],
                        dest: '<%= yeoman.dist %>'
                    }
                ]
            }
        }
    });

    grunt.registerTask('build', [
        'clean:dist', 
        'copy:dist',
        'htmlmin'
    ]);

    grunt.registerTask('default', [
        'build'
    ]);
};
</pre>

and package.json is

<pre>
{
  "name": "yo",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-contrib-clean": "~0.6.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-htmlmin": "~0.3.0",
    "load-grunt-tasks": "~0.6.0",
    "time-grunt": "~0.2.1",
    "install": "~0.1.7",
    "npm": "~1.4.11"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "test": "grunt test"
  }
}
</pre>

to reproduce just recreate directory structure with those three files from above and run

<pre>
cd yo
npm install
grunt
</pre>

**Comment by kangax** [comment]
The latest is 0.6.8 — https://github.com/kangax/html-minifier/releases

**Comment by igorbljahhin** [comment]
Forget about versions -- 0.1.3 and 0.3.0 are versions of grunt-contrib-htmlmin module.

I tested with htmlmin 0.6.8 and got the same issue:

<pre>
<b>C:\tmp\htmlmin-issue>cat src\main\webapp\index.html</b>
&lt;h1 class="headline1 breadcrumb" ui-view="breadcrumb" />
&lt;div class="block-l sr" ui-view="leftContent" />
&lt;div class="block-s" ui-view="faqLinks" /><br/>
<b>C:\tmp\htmlmin-issue>html-minifier -v</b>
html-minifier v0.6.8<br/>
<b>C:\tmp\htmlmin-issue>html-minifier src\main\webapp\index.html</b>
&lt;h1 class="headline1 breadcrumb" ui-view="breadcrumb">
&lt;div class="block-l sr" ui-view="leftContent">
&lt;div class="block-s" ui-view="faqLinks"><br/>
<b>C:\tmp\htmlmin-issue></b>
</pre>

**Comment by kangax** [comment]
Are you using keepClosingSlash option?

**Comment by kangax** [comment]
Also, are you sure you're serving document with XHTML mimetype where closing slashes really matter and not with HTML mimetype in which case browsers strip them during parsing anyway?

**Comment by igorbljahhin** [comment]
Thanks for pointing to the option "keepClosingSlash"!
