### ISSUE TITLE
Sort/normalize class tokens

### ISSUE THREAD

**Issue by samme** [kangax/html-minifier#267]
Like #4, this would help compression (and readability).

``` html
<a class="c a b"></a>
<a class="a b c"></a>
```

**Comment by duncanbeevers** [comment]
I'm concerned about this affecting class names containing templates such as this.

``` html
<a class="btn {{#if loading}}loading{{/if}}"></a>
```

The tokenization `btn`, `{{#if`, `loading}}loading{{/if}}` is clearly incorrect.

I'd also be interested in seeing the compression difference this makes. My suspicion is not much, but I'd be happy to be shown wrong.

**Comment by samme** [comment]
I was imagining an option (default: false) since it's not suitable for every case.

**Comment by alexlamsl** [comment]
I do wonder who write class names in random orders inside a HTML page to begin with.

OTOH, implementing this is probably simple enough, and gated by a flag makes it pretty safe as well.
