### ISSUE TITLE
Parse error on Map<Object, Object>

### ISSUE THREAD

**Issue by justinmusgrove** [kangax/html-minifier#272]
Newbie here, received the following error while trying to minify a page with the following snippet. Also confirmed using http://kangax.github.io/html-minifier/

`<p><code>Map<Object, Object></code></p>`

Is there a way to ignore within code tags?

**Comment by kangax** [comment]
Hm, an immediate fix (on your end) would be to just escape opening bracket:

``` html
<p><code>Map&lt;Object, Object></code></p>
```

I'm not sure right away if we should tolerate brackets in certain tags or not. Will think about it.

/cc @duncanbeevers

**Comment by justinmusgrove** [comment]
sounds good thanks!

**Comment by duncanbeevers** [comment]
This seems like plain old invalid HTML which the parser rightfully barfs on. The error message emitted indicates the problem pretty clearly.

Browsers don't seem to respect the markup in the way intended, so I don't think we should jump through any special hoops here.

![screen shot 2014-09-20 at 8 42 07 pm](https://cloud.githubusercontent.com/assets/7367/4347086/a6fa3162-4130-11e4-91b9-a3f712abe908.png)

**Comment by justinmusgrove** [comment]
Sounds good - an easy work around is to escape it
