### ISSUE TITLE
Add possibility to remove whitespace around certain inline tags

### ISSUE THREAD

**Issue by eush77** [kangax/html-minifier#273]
#43 made collapseWhitespace “smarter” about inline tags, so that e.g. the space in `<b>bold</b> <i>italic</i>` is preserved by the transformation.

However, one could want the “junk space” between two buttons or two images to be removed rather that preserved. He would get a cleaner DOM tree in the end and then set appropriate margins in CSS.

```
html-minifier --collapse-whitespace --some-other-introduced-option main.html
```

main.html:

``` html
<div>
    <button>Push me</button>
    <button>Push me</button>
</div>
```

Expected output:

``` html
<div><button>Push me</button><button>Push me</button></div>
```

Actual output:

``` html
<div><button>Push me</button> <button>Push me</button></div>
```

**Comment by duncanbeevers** [comment]
Is this something that makes sense to toggle all at once, or on a tag-by-tag basis?

**Comment by elliottsj** [comment]
> Is this something that makes sense to toggle all at once, or on a tag-by-tag basis?

Enabling `collapseInlineTagWhitespace` on a tag-by-tag basis is something I'd like to see. Continued in #691
