### ISSUE TITLE
STDIN buffer boundaries can split and corrupt multi-byte UTF-8 sequences

### ISSUE THREAD

**Issue by dfoxfranke** [kangax/html-minifier#275]
When `html-minifier` reads from STDIN, it does so in 4096-byte chunks. If the end of such a chunk falls in the middle of a multi-byte UTF-8 sequence, the character gets corrupted and turned into (U+FFFD REPLACEMENT CHARACTER).

**Comment by alexlamsl** [comment]
Is this still a problem on the current version? I'd think [this commit](https://github.com/kangax/html-minifier/commit/41c6cb002f3193d711464a7a39101cea93028e38) would have fixed that...

**Comment by alexlamsl** [comment]
We now read in all input as `Buffer` before converting to `String`, so this is no longer an issue.
