### ISSUE TITLE
How to preserve comments in minified JS?

### ISSUE THREAD

**Issue by cooljeffro** [kangax/html-minifier#277]
I'm trying to minify inline scripts in my HTML, but I'd like to leave the comments intact.  I'm having trouble getting this to work.  Comments are still being stripped out.

``` javascript
...
var htmlMinifier = require("html-minifier").minify;
var minifiedOutput = htmlMinifier(htmlString, {
    minifyJS: {
        output: {
            comments: true
        }
    }
});
```

Would this be the correct way of specifying to UglifyJS to preserve comments?

**Comment by XhmikosR** [comment]
See https://github.com/mishoo/UglifyJS2#keeping-comments-in-the-output

This isn't an issue with html-minifier per se BTW.

**Comment by alexlamsl** [comment]
I don't see how we can implement this in `html-minifier` further than what is done in `uglify-js` already.

**Comment by cooljeffro** [comment]
Sorry guys. It was a problem on my part with uglify-js
