### ISSUE TITLE
htmlmin:ignore

### ISSUE THREAD

**Issue by rexdf** [kangax/html-minifier#281]
will cause the following error

Running "htmlmin:dist" (htmlmin) task
Warning: public/index.html
TypeError: Cannot call method 'toLowerCase' of undefined Use --force to continue
.

Aborted due to warnings.

**Comment by kangax** [comment]
Works for me with latest version and we have tests for it too (which all pass)

**Comment by uglow** [comment]
I'm also seeing this issue when using grunt-contrib-htmlmin with the following options:
options: {
          collapseWhitespace: true,
          conservativeCollapse: true,
          collapseBooleanAttributes: false,   // Setting this to true will reduce the required="true" attribute to required, which breaks the app.
          removeAttributeQuotes: true,
          removeComments: true,
          removeCommentsFromCDATA: true,
          removeOptionalTags: true
        }

**Comment by rexdf** [comment]
My situation is qutoes `"` mismatching. ( In head/meta-summary including some automatically generated summaries)
