### ISSUE TITLE
Parse error with conditional operator

### ISSUE THREAD

**Issue by dwightkelly** [kangax/html-minifier#282]
I'm getting a parse error for the following code

```
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="cancelAJAXCall()">{{progressbar.value < progressbar.max ? "Cancel" : "OK"}}</button>
          </div>
```

here's the error message

```
Running "htmlmin:dist" (htmlmin) task
Minified dist/404.html 3.69 kB → 3.52 kB
Warning: dist/index.html
Parse Error: < progressbar.max ? "Cancel" : "OK"}}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
```

**Comment by kangax** [comment]
You'll need to escape `<` as `&lt;`. If we narrow it down, this is no different than `<button><</button>` which is invalid.

**Comment by dimylik** [comment]
just got same error with Angular expression:

`<span>{{someVar < 0 ? '-' : '+'}}</span>`

**Comment by Sollll** [comment]
Same here:
`{{orderForm.description.$viewValue.length<20....`
I think everything between {{}} should be ignored.

**Comment by ciarans** [comment]
+1 experiencing this with JS tags
