### ISSUE TITLE
Missing closing body and html tags

### ISSUE THREAD

**Issue by seriema** [kangax/html-minifier#284]
I didn't notice this until now, but my body and html tags aren't being closed. Using v0.3.0.

My original HTML file has `</body></html>` but in the minified version they're gone.

If it helps, the last thing before `</body>` is a script-element.

**Comment by kangax** [comment]
0.3.0? O_o https://github.com/kangax/html-minifier/releases

**Comment by seriema** [comment]
I'm using `grunt-contrib-htmlmin` (v0.3.0) and clicked the "report issue with HTML output" link and ended up here without noticing it was the issue-tracker for another project. Was confused for a sec.

**Comment by seriema** [comment]
The plot thickens... I went through your tests to see if I could help. Maybe add a test. When I noticed that stripping those closing tags are [on purpose](https://github.com/kangax/html-minifier/blob/gh-pages/tests/minifier.js#L745).

Checking W3C there seems to be [more tags](http://www.w3.org/TR/html5/syntax.html#optional-tags) that could be stripped out then.

But somehow I'd like an option flag for this. I don't think those few bytes matter so I'd rather have a XML-ish compliance (I'm old).

**Comment by kangax** [comment]
Understandable, and which is why it's under `removeOptionalTags` flag :) If you don't pass it, it shouldn't be removed. As for XML-ish compliance, it's always good to remember that all the `/>` and doctypes and other xml-isms are all largely disregarded by browsers when documents are served with html mime-type, rather than xhtml (as it happens in 99% of the cases).

**Comment by seriema** [comment]
Ah, it's a setting for `grunt-contrib-htmlmin` that's being passed on to `html-minifier` that's setting that flag (and others). Thanks for helping me understand what was going on. :) I'll close this for real now.
