### ISSUE TITLE
Change rules when inside an <svg> element

### ISSUE THREAD

**Issue by callumlocke** [kangax/html-minifier#285]
If I have inline `<svg>` elements in my page, I have to use `keepClosingSlash: true, caseSensitive: true` because otherwise HTMLMinifier will break the SVGs...

but I might not want to have those options enabled for my whole page.

it would be nice if HTMLMinifier could just force these options to `true` for anything inside an `<svg>` element.

**Comment by kangax** [comment]
Good point. I'll see what we can do.
