### ISSUE TITLE
There is no way to save unopened tags

### ISSUE THREAD

**Issue by anton-kotik** [kangax/html-minifier#286]
Input: 
<b>&lt;p&gt;test&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</b>

Output:
<b>&lt;p&gt;test&lt;/p&gt;</b>

Expected:
&lt;p&gt;test&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;

Option "Remove optional tags" is off.

**Comment by kangax** [comment]
I'm pretty sure closing tags are discarded by parser so we never even get our hands on them in minifier
