### ISSUE TITLE
Self-closing tags from html are not being preserved

### ISSUE THREAD

**Issue by dotnetwise** [kangax/html-minifier#287]
``` html
<div>
    This is projectsss

    <projectslist />

    <div>
        <div ui-view></div>
    </div>

</div>
```

When it is bundled it gets into :

``` html
<div>This is projectsss<projectslist><div><div ui-view></div></div></div>
```

Notice the missing of `/` in the `<projectslist>` tag

https://github.com/gruntjs/grunt-contrib-htmlmin/issues/90#issuecomment-60106299

https://github.com/ericclemmons/grunt-angular-templates/issues/109

**Comment by duncanbeevers** [comment]
Please see the documentation [in the README](https://github.com/kangax/html-minifier#options-quick-reference) regarding the `keepClosingSlash` minification option.

**Comment by Wolfium** [comment]
I just suffered from this.

keepClossingSlash did the trick, now the cached minized html from source is the same with same tags.

Only weird behavior is the defautt is to remove the closing slash

You can close this issue as it looks working properly and issue solved.

**Comment by crediblebytes** [comment]
Wow took an hour to find this one out. Why did we decide to make this propery default to false?
