### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by duncanbeevers** [kangax/html-minifier#289]
Angular 2 adds some new warts to its pseudo-HTML

``` html
<div [ng-repeat|todo]="todosOf('good')"></div>
```

``` html
<button (click)="deleteTodo(todo)">X</button>
```

**Comment by kangax** [comment]
Damn... what does this do, out of curiosity?

**Comment by duncanbeevers** [comment]
I'm not certain since Angular 2 is still very nebulous.
The `[ng-repeat|todo]` seems like an attribute-style directive which will iterate over the collection yielded by the attribute value `todosOf('good')` referencing the individual items as `todo`.

The `(click)` looks like some kind of event-binding.

In the [Angular design documents](https://drive.google.com/?pli=1#folders/0B7Ovm8bUYiUDR29iSkEyMk5pVUk) there is an `AngularJS Design Doc Templating` whose examples all use a more pedestrian-looking `on-click`, `bind-value`, and `ng-repeat` (and kin).

I've only seen this new syntax in blog posts [such as this one](http://www.infoq.com/news/2014/10/angular-2-atscript) concerning details revealed at ng-europe.

![angular2directive-1024x618](https://cloud.githubusercontent.com/assets/7367/4833188/96b3105e-5fa2-11e4-8d3d-52541138fc5c.jpg)

**Comment by andreialecu** [comment]
Bump. now with angular2 being in beta this is a big problem when using `webpack` + `html-loader`, when in minification mode. It will fail the build.

**Comment by doxavore** [comment]
I know of `customAttrSurround` which works for things like:

```
<button (click)="deleteTodo(todo)">X</button>
<input [(ngModel)]="todoTitle">
```

using this config:

```
htmlmin({
  collapseWhitespace: true,
  customAttrSurround: [
    [/\[/, /\]/],
    [/\(/, /\)/],
    [/\[\(/, /\)\]/]
  ]
})
```

However, I'm not sure how to handle the case of Angular 2's local variables and templates:

```
<video #videoLocalVar>
<li *nfFor="#item in list">
```

Are we able to allow prefixes without suffixes? I haven't had any progress after several attempts, such as adding `[ /\*/, new RegExp('') ]` to the `customAttrSurround`.

**Comment by andreialecu** [comment]
I didn't try this, but maybe `[ /\*/, /[^=]/ ]` might work?

Another idea might be `/[^a-zA-Z\-]/`

**Comment by alexlamsl** [comment]
Taking the examples from [here](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#property-binding)

```
> minify(`
... <template ngFor #hero [ngForOf]="heroes">
...   <hero-detail *ngIf="hero" [hero]="hero"></hero-detail>
... </template>
... <form (ngSubmit)="onSubmit(theForm)" #theForm="ngForm">
...   <div class="form-group">
...     <label for="name">Name</label>
...     <input class="form-control" required ngControl="firstName"
...       [(ngModel)]="currentHero.firstName">
...   </div>
...   <button type="submit" [disabled]="!theForm.form.valid">Submit</button>
... </form>
... `, { customAttrSurround: [ [/#/, /(?:)/], [/\*/, /(?:)/], [/\[?\(?/, /(?:)/] ], customAttrAssign: [ /\)?\]?=/ ] })

`<template ngfor #hero [ngforof]="heroes">
<hero-detail *ngif="hero" [hero]="hero"></hero-detail>
</template>
<form (ngsubmit)="onSubmit(theForm)" #theform="ngForm">
<div class="form-group">
<label for="name">Name</label>
<input class="form-control" required ngcontrol="firstName" [(ngmodel)]="currentHero.firstName">
</div>
<button type="submit" [disabled]="!theForm.form.valid">Submit</button>
</form>`
```

**Comment by alexlamsl** [comment]
@duncanbeevers do we still need to implement anything beyond the example above to make Angular 2 work?

**Comment by uglow** [comment]
I've [documented a configuration](https://github.com/angular/angular/issues/7295#issuecomment-189063411) that seems to work with Angular2.0.0-beta6

**Comment by alexlamsl** [comment]
@uglow looks the same as the one I gave in https://github.com/kangax/html-minifier/issues/289#issuecomment-180971821 ?

Unless they are planning on introducing new syntaxes, I think we have resolved this one.

**Comment by uglow** [comment]
@alexlamsl - yes, it is similar to your config but with 2 extra config flags: removeAttributeQuotes and caseSensitive. These flags are also necessary (at least when using `html-minifier` via `html-loader`). Just thought this note might help someone else.

**Comment by andreialecu** [comment]
@alexlamsl shouldn't html-minifier work with this syntax by default without custom workarounds? 

As far as I know those characters are legal in attributes: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

**Comment by alexlamsl** [comment]
@andreialecu wow, that's... crazy :see_no_evil:

**Comment by alexlamsl** [comment]
@kangax if I am reading what @andreialecu refers to correctly, things like `a?="b"` never needed `customAttrAssign` as `a?` is just a valid attribute name on its own...

**Comment by kangax** [comment]
Originally we followed HTML4 semantics, which is defined via SGML and lists specific attributes for specific tags. While HTML5 (seems to) specify attribute names more loosely, I still see that validator (https://validator.w3.org/nu/#textarea) complains with `foo?=bar`. It even complains with `data-foo?=bar`. 

I'm guessing if we were to follow HTML5 behavior strictly, we could tolerate things like that (assuming that browsers tolerate them too).

**Comment by code-tree** [comment]
So AFAIK, after this patch, the current requirement for Angular 2 is:

`removeAttributeQuotes: false, caseSensitive: true`

[This test](https://github.com/kangax/html-minifier/blob/31e784616dd5fedf25ab8eb81857b3f23d8f29a1/tests/minifier.js#L2703) probably then needs to be corrected? As [it doesn't look like](https://github.com/angular/angular/issues/7295#issuecomment-221638618) Angular supports `removeAttributeQuotes: true`.
