### ISSUE TITLE
Ignored tags inside a tag gives an error

### ISSUE THREAD

**Issue by torvalde** [kangax/html-minifier#290]
This code:

``` html
 <div <%if(node.uuid){%>data-uuid='uuid'<%}%>></div>
```

Gives an error, it does not seem code between the ignored tags are actually ignored.....

The fix for #261 improved the behaviour around ignor tags a bit, but not for the case above.

**Comment by icd2k3** [comment]
+1 similar issue here: https://github.com/kangax/html-minifier/issues/293

**Comment by kangax** [comment]
You can now use  around it
