### ISSUE TITLE
problem with html input type checkbox "checked"

### ISSUE THREAD

**Issue by oroboss** [kangax/html-minifier#292]
when using this in .php file:

```
&lt;input type=&quot;checkbox&quot;  &lt;?=isset($variable) ? 'checked' :'' ?&gt; &gt;
```

it freezes during htmlmin task !

have no problem with other input fields with php ternary conditions only checkbox "checked" cause it stop.

grunt config 

```
htmlmin: {
       dist: {
         options: {
           removeComments: true,
           collapseWhitespace: true
         },
         files: {
           'cpa.phtml': 'src/cpa.tpl.php',
         }
       }
    }
```

**Comment by mmobinvestor** [comment]
Have the same problem.
F.e.

```
<?php $checked = $cust_row['gender']==1 ? 'checked' : ''; ?>
<label class="radio-inline">
    <input type="radio" name="gender" value="2" <?php echo $checked;?> /> 
    Male 
</label>
```

or

```
<?php $checked = $cust_row['gender']==1 ? 'checked="checked"' : ''; ?>
<label class="radio-inline">
    <input type="radio" name="gender" value="2" <?php echo $checked; ?> /> 
    Male 
</label>
```

But, if we add " " (quotes)  it became good.

```
<?php $checked = $cust_row['gender']==1 ? 'checked' : ''; ?>
<label class="radio-inline">
    <input type="radio" name="gender" value="2" "<?php echo $checked;?>" /> 
    Male 
</label>
```

But this attribute must not have quotes. That's bug!
The same problem is attribute  ' selected ' in  tag < option > 

I tried to solve this problem with code, which I saw at [Issue 145](https://github.com/kangax/html-minifier/issues/145), but this code doesn't work. I saw **WARNING: TypeError: undefined is not a function Use --force to continue.**

file Gruntfile.js

```
htmlmin: {
        multiple: {
            options: {
                removeComments: true,
                collapseWhitespace: false,
                ignoreCustomComments: [
                    {
                        before: /<!--\s+ignores[^"-->"]+-->/,
                        after: /<!--\s+\/ignores\s+-->/
                    }
                ]
            },
            files: [{
                expand: true,
                cwd: '<%= dirs.test %>/user/template/',
                src: '*.tpl',
                dest: '<%= dirs.test %>/user/template/'
            }]
        }
    },
```

file *.tpl

```
<!-- igores -->
<input type="radio" name="gender"  value="2" <?php echo $checked2;?> > Male </label>
<!-- /ignores -->
```

**Comment by mmobinvestor** [comment]
Help Plz! Solve this problem.
Очень нужно, а не пашет :)

**Comment by kangax** [comment]
@duncanbeevers could you please take a look!

**Comment by roman-rr** [comment]
@kangax Подскажи пожалуйста как сделать пропуск минификации в выборочной части кода, после 
 КОД 
Вот этот вариант вызывает в других html файлах TypeError: Object #<Object> has no method 'test'

 ignoreCustomComments: [
                    {
                        before: /"]+-->/,
                        after: //
                    }

**Comment by mmobinvestor** [comment]
@kangax , Juriy, can you tell smth about this problem?
Any issue ? Plz..

**Comment by mmobinvestor** [comment]
@duncanbeevers , @kangax 
plz, help us with this bug

**Comment by kangax** [comment]
@mmobinvestor sorry, I'm swamped with work right now. Will try to get to it whenever I can but don't know when.

**Comment by alexlamsl** [comment]
Seems to work using `ignoreCustomFragments`:

```
var input = "<?php $checked = $cust_row['gender']==1 ? 'checked' : ''; ?>\n" +
            '<label class="radio-inline">\n' +
            '    <input type="radio" name="gender" value="2" <?php echo $checked;?> /> \n' +
            '    Male \n' +
            '</label>';
minify(input, {ignoreCustomFragments:[/<\?php\s.*?\?>/]});
```
