### ISSUE TITLE
customAttrSurround for ignoring inline (<div <%= "a" %>>) ejs template tags not working

### ISSUE THREAD

**Issue by icd2k3** [kangax/html-minifier#293]
Hey everyone,

I'm having a lot of trouble trying to get htmlmin to ignore ejs/underscore template tags as attributes, for example htmlmin will fail on the following:

`<div <%= "a" %>></div>`

but is fine with

`<div><%= "a" %></div>` or `<div class="<%= 'a' %>">`

I've tried using customAttrSurround:
`customAttrSurround: [
    [/<%\=\s+/, /%>/],
    [/<%\-\s+/, /%>/]
]`
and customAttrAssign:
`customAttrAssign: [/<%.*?%>/]`

Neither seem to be working as expected?

If I set removeIgnored to true the file compiles, but it also (obviously) removes any <%...%> which defeats the purpose... I just want html-minifier to completely ignore <%...%> tags wherever they are.

Any advice, tips, places to look would be much appreciated - our application has a LOT of ejs templates and if I can get them to parse through htmlmin it will save us a lot of file size.

At the very least I think you should be able to bypass parse errors by wrapping, but this fails too:
`<!-- htmlmin:ignore --><div <%= 'aa' %>></div><!-- htmlmin:ignore -->`

I'm using the latest version `0.6.9`

**Comment by icd2k3** [comment]
Sorry for all the title changes, wanted to be as descriptive as possible

**Comment by duncanbeevers** [comment]
In your first example:

``` html
<div <%= "a" %>></div>
```

The attribute is `"a"`, and the parts surrounding it are `<%=` and `%>`.

To recognize these via `customAttrSurround`, include a regular expression pair that captures the opening and closing parts.

``` javascript
customAttrSurround: [ [ /<%=\s+/, /\s+%>/ ] ]
```

**Comment by inetbug** [comment]
I have related issue.

When I try to minify

```
<li class="item {{item.type}}" {% if (logged) { %}data-order="{{item.order}}"{% } %}>
```

html-minifier throw parse error.

I try resolve this by using  `<!-- htmlmin:ignore -->`, but it doesn't work.

**Comment by duncanbeevers** [comment]
That sounds like a bug with `htmlmin:ignore`. Can you post a snippet of the failing markup, including the htmlmin comment?

**Comment by inetbug** [comment]
```
<ul class="items">
{% items.forEach(function (item) { %}
    <!-- htmlmin:ignore -->
    <li class="item {{item.type}}" {% if (logged) { %}data-order="{{item.order}}"{% } %}>
        {{item.content}}
    </li>
    <!-- htmlmin:ignore -->
{% }); %}
</ul>
```

```
/home/inetbug/project/node_modules/html-minifier/dist/htmlminifier.js:301
        throw 'Parse Error: ' + html;

Parse Error: <li class="item {{item.type}}" {% if (logged) { %}data-order="{{item.order}}"{% } %}>
        {{item.content}}
    </li>
    <!-- htmlmin:ignore -->
{% }); %}
</ul>
```

**Comment by drogobetski** [comment]
I'm having the issues and no luck!

**Comment by fed239** [comment]
Same bug with underscore templates. Here is my code:

```
<!-- htmlmin:ignore -->
<a href="#"
  <% if (x) { %>data-x="<%= x %>"<% } %>
>
<!-- htmlmin:ignore -->
```

**Comment by xuanfeng** [comment]
So who have the solutions?

**Comment by hwoarangzk** [comment]
met the same problem. Anyway to solve it?

**Comment by xuanfeng** [comment]
I have modify the htmlminifier.js by myself and the `<!-- htmlmin:ignore -->` can use.
See detail: https://github.com/kangax/html-minifier/issues/376

**Comment by hwoarangzk** [comment]
@xuanfeng 
Is there anyway to solve it without modifying the html?

**Comment by xuanfeng** [comment]
@hwoarangzk This is my solution with the issue . https://github.com/xuanfeng/fix-html-minifier-with-htmlmin-ignore

**Comment by kangax** [comment]
I just made it so that this works:

``` html
<!-- htmlmin:ignore -->
<a href="#"
  <% if (x) { %>data-x="<%= x %>"<% } %>
>
<!-- htmlmin:ignore -->
```

**Comment by kangax** [comment]
This works too (from the original description):

``` html
<!-- htmlmin:ignore --><div <%= 'aa' %>></div><!-- htmlmin:ignore -->
```

**Comment by shangcloud** [comment]
it appear error 'msg = [Error: Parse Error: <= 2 }}',how can i fix it?

my code is 
`
customAttrSurround: [
        [/\{\{.+/, /\}\}/]
 ]
`

`
{{ if:  ${a} <= 2 }} <div></div> {{ /if }}
`
