### ISSUE TITLE
Fails with browserify due 'require("./htmlparser")'

### ISSUE THREAD

**Issue by ibc** [kangax/html-minifier#294]
A simple example:

```
$ npm install html-minifier
```
- test.js:

```
var minifier = require("html-minifier");

module.exports = minifier.minify;
```
- Run browserify:

```
$ browserify test.js
Error: Cannot find module './htmlparser' from '/tmp/test/node_modules/html-minifier/dist'
```

This is because the "main" entry in package.json of `html-minifier` points to `./dist/htmlminifier.js` (really? this is not the NPM way at all). And such a file includes:

```
  if (global.HTMLParser) {
    HTMLParser = global.HTMLParser;
  }
  else if (typeof require === 'function') {
    HTMLParser = require('./htmlparser').HTMLParser;
  }
```

Since the call to `require()` uses a relative path it is "captured" by browserify() which attemps to load a file ("htmlparser.js") that does not exist at all. Shouldn't it be `require('htmlparser')`?

**Comment by jantimon** [comment]
Same here - any updates?

**Comment by jantimon** [comment]
Same as #84

**Comment by alexlamsl** [comment]
Fixed by https://github.com/kangax/html-minifier/commit/c4a6d6fd47af75200ef2e1e17c12c622387df0c5
