### ISSUE TITLE
customAttrCollapse not working

### ISSUE THREAD

**Issue by thany** [kangax/html-minifier#297]
I'm trying to use `customAttrCollapse` to do exactly what it's supposed to do, as far as I can tell from the readme. To collapse whitespace from a custom attribute. This is how I'm using it:

``` js
options: {
  collapseWhitespace: true,
  collapseBooleanAttributes: false
  removeComments: true,
  removeAttributeQuotes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  removeOptionalTags: true,
  customAttrCollapse: /ng\-class/
}
```

Example input:

``` html
<div ng-class="{ disabled: !charger_subgroup[features._name],
                recommended: charger_subgroup[features._name].recommenDation &gt; 0,
                notrecommended: !data.randomcars.count && data.recommendedTypecode != charger_subgroup[features._name].typeCode,
                active: data.selectedcharger.id === charger_subgroup[features._name].id }">
```

Output will be identical.
Please note: htmlmin is working fine apart from this function. The reason that this is identical, is simply because all other optimizations are not applicable, plus this is but a snippet from the rest of the file, which is minified perfectly.

I would expect the output to look like this:

``` html
<div ng-class="{ disabled: !charger_subgroup[features._name],recommended: charger_subgroup[features._name].recommenDation &gt; 0,notrecommended: !data.randomcars.count && data.recommendedTypecode != charger_subgroup[features._name].typeCode,active: data.selectedcharger.id === charger_subgroup[features._name].id }">
```

Kinda bulky, I know, but I assumed this is exactly what `customAttrCollapse` is for.

**Comment by duncanbeevers** [comment]
`customAttrCollapse`, as the documentation says, only strips newlines from attribute values.

I agree that your use-case makes sense. It looks like we could change the regular expression in use.
https://github.com/kangax/html-minifier/blob/f1754cd5607c75b1faa903a19f2b14d10b4ee9eb/src/htmlminifier.js#L253

from (remove newlines)

``` javascript
attrValue = attrValue.replace(/\n+/g, '');
```

to (remove newlines and instances of two-or-more whitespace characters)

``` javascript
attrValue = attrValue.replace(/\n+|\s{2,}/g, '');
```

**Comment by duncanbeevers** [comment]
Testing this change with your input produces your expected output.

``` html
<div ng-class="{ disabled: !charger_subgroup[features._name],recommended: charger_subgroup[features._name].recommenDation &gt; 0,notrecommended: !data.randomcars.count && data.recommendedTypecode != charger_subgroup[features._name].typeCode,active: data.selectedcharger.id === charger_subgroup[features._name].id }"></div>
```

**Comment by thany** [comment]
Yes, that would be a great little thing to have :)

A little side note though: in my case the newlines weren't removed either, even though that should've definitely worked, looking at the docs.

**Comment by askuzminov** [comment]
If html is CRLF, need to remove `\r`.

```
attrValue = attrValue.replace(/\n+|\r+|\s{2,}/g, '');
```

**Comment by duncanbeevers** [comment]
I poked around at this a little more and there are a lot of weird edge cases I'm concerned about messing up, like collapsing whitespace within quoted strings or any other weirdness people decide to put inside their attributes.

I think I'd rather see an API where the end-user provides both the attribute-selection and value-collapsing regular expressions.

``` javascript
customAttrCollapse: [ /ng\-class/, /\r+|\n+|\s{2,}/g ]
```

**Comment by bryanerayner** [comment]
This is an issue which especially affects Windows users. If the PR was only closed for lack of test cases being added, I'll gladly add some
