### ISSUE TITLE
benchmark.js not working on Windows?

### ISSUE THREAD

**Issue by XhmikosR** [kangax/html-minifier#300]
I'm getting this

```
C:\Users\xmr\Desktop\html-minifier>node -v && npm -v
v0.10.33
1.4.28

C:\Users\xmr\Desktop\html-minifier>node benchmark.js

Processing... html-minifier

C:\Users\xmr\Desktop\html-minifier\benchmark.js:80
            var minifiedSize = stats.size;
                                    ^
TypeError: Cannot read property 'size' of undefined
    at C:\Users\xmr\Desktop\html-minifier\benchmark.js:80:37
    at Object.oncomplete (fs.js:107:15)
```

Maybe it's due to gzip not available on Windows?
/CC @kangax

**Comment by kangax** [comment]
No idea actually. /cc @duncanbeevers

**Comment by XhmikosR** [comment]
Using https://github.com/kangax/html-minifier/compare/benchmark2, I'm getting:

```
C:\Users\xmr\Desktop\html-minifier>node -v && npm -v
v0.10.35
1.4.28

C:\Users\xmr\Desktop\html-minifier>node benchmark.js
Processing... html-minifier

C:\Users\xmr\Desktop\html-minifier\benchmark.js:89
              throw new Error('There was an error reading ' + minifiedFilePath
                    ^
Error: There was an error reading benchmarks\generated\html-minifier.min.html
    at C:\Users\xmr\Desktop\html-minifier\benchmark.js:89:21
    at Object.oncomplete (fs.js:108:15)
```

/CC @kangax @duncanbeevers: let me know if that works for you; if so we can merge it since it's the proper way to handle dirs cross-platform.

About this issue, I think it's due to `gzip`; Windows doesn't have it.

**Comment by duncanbeevers** [comment]
I haven't tried this out as I don't have a Windows rig handy.

I'm all-for cross-platform path handling, though I haven't really had to deal with it much myself.

@XhmikosR 
I see you've changed some lines to look like this:

``` javascript
path.join('benchmarks/generated/', fileName) + '.html.gz';
```

Is it somehow safe to use `/` within those sequences, but not to simply concatenate the path strings?

**Comment by XhmikosR** [comment]
I pushed that branch a better fix; now everything works on Windows too.

Please try it on a non Windows OS just to be safe.

@duncanbeevers: The plan was to add the whole string in `path.join`, but previously I had other issues so it didn't work. Now it should work fine.

```
Processing... html-minifier
filePath: benchmarks\html-minifier.html
minifiedFilePath: benchmarks\generated\html-minifier.min.html
gzFilePath: benchmarks\generated\html-minifier.html.gz
gzMinifiedFilePath: benchmarks\generated\html-minifier.min.html.gz
```

So, please try that branch and let me know so that I merge it.

**Comment by duncanbeevers** [comment]
The benchmarks run fine for me on OSX.

![screen shot 2014-12-24 at 7 02 32 am](https://cloud.githubusercontent.com/assets/7367/5548593/f0976412-8b3a-11e4-899e-86b45db19f2d.png)

**Comment by XhmikosR** [comment]
@duncanbeevers: I assume you used the latest benchmark2 branch?

Also, feel free to comment on the code changes in that PR. I went ahead with chalk since I find it better. But if we can achieve the same using cli-tables, I'm all for using that since it will be one less dev dependency.

**Comment by duncanbeevers** [comment]
Yeah, before running the benchmarks I reset my `benchmark2` branch to f0dcf0f37cc148eedea9765ce616bb3217e43ddc

I have no strong feelings about the benchmark reporter. It's not integrated into the build in any way; we're not using it to prevent performance regressions. It just seems like a nice-to-have, and makes for a good demo of what is achievable with the tool.

I know `chalk` is widely-used. I'm not as familiar with cli-tables, and simply hacked in the gzip reporting without looking deeply into the tool.
