### ISSUE TITLE
Improvement of collapseBooleanAttributes

### ISSUE THREAD

**Issue by mieszko4** [kangax/html-minifier#302]
`collapseBooleanAttributes` collapses attribute like `readonly`. The problem is that it does not check the value of the attribute which causes problem when using https://github.com/yeoman/generator-angular and `<rating></rating>` directive from http://angular-ui.github.io/bootstrap/.

A problem appears in this example:

```
<rating readonly="isReadOnly"></rating>
```

where `isReadOnly` is a scope variable.

It would be an improvement if `readonly` attribute would collapse only if its value is `true` or `readonly`.

**Comment by fregante** [comment]
Ideally it should have a whitelist of collapsable attributes vs. tags. Like in this case, just because the attribute is `readonly`, it doesn't mean that it should be collapsed (if that's what's happening)

**Comment by kangax** [comment]
Well, we're simply following the standards and having hard time keeping up with <del>abomina</del> modern HTML supersets like the one in Angular :)

According to spec, [readonly is a boolean attribute](https://html.spec.whatwg.org/multipage/forms.html#the-readonly-attribute), and a boolean attribute is [specified as](https://html.spec.whatwg.org/multipage/infrastructure.html#boolean-attribute):

> The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.
> 
> If the attribute is present, **its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name**, with no leading or trailing whitespace.

(emphasis mine)

So, according to HTML5, there's no reason to check boolean attribute value. If it's empty, we can remove it, if it has value (any value, although the value is supposed to conform to certain rules too, as described above), we leave it.

But of course we can try to be smarter about all this. I'll mark this as possible feature and we'll see if anyone else needs this.

**Comment by alexlamsl** [comment]
As mentioned in #426 and #493, `ignoreCustomFragment` can be utilised to avoid minification of specific boolean attributes in your project.

So is that good enough for the use case here, or do we want a more general flag that applies to all boolean attributes (since listing them all out in `ignoreCustomFragment` would be a bit of a chore :sweat_smile:)?

**Comment by mieszko4** [comment]
I think that `ignoreCustomFragment` is good enough.
