### ISSUE TITLE
Remove all white spaces between any tags

### ISSUE THREAD

**Issue by artuska** [kangax/html-minifier#304]
I have complete control over my HTML code and I really need to remove all spaces between all type of elements: block level and inline level — now white spaces collapses only between block level elements.

Is there a way to remove all spaces between all tags completely?

(I'm using [grunt-contrib-htmlmin](https://www.npmjs.org/package/grunt-contrib-htmlmin) v0.3.0 Grunt plugin which is a wrapper of HTML minifier)

I've found similar issues like #273, but I still got spaces between `<button>` or `<span>` tags.

**Comment by kangax** [comment]
Can you give a small example for reproduction?

**Comment by artuska** [comment]
Well, it is not a bug, there is nothing to reproduce, everything is working as expected.

I have `collapseWhitespace` option set to `true`.

If I have a bunch of any block level elements in my HTML: `div`, `p`, etc — they are collapsing leaving no spaces between them:

original:

```
<section>
    <header>Header</header>
    <div>Div</div>
    <p>Paragraph</p>
</section>
```

htmlmin:

```
<section><header>Header</header><div>Div</div><p>Paragraph</p></section>
```

If I have bunch of any inline level elements: `button`, `span`, `b`, `i`, etc. — they are collapsing with 1 space between them:

original:

```
<section>
    <button>Button</button>
    <em>Em</em>
    <span>Span</span>
</section>
```

htmlmin:

```
<section><button>Button</button> <em>Em</em> <span>Span</span></section>
```

So, I'm just asking for an option to collapse white spaces between all type of tags, not only block-level tags — option like `collapseWhitespace` but which is more aggressive:

original:

```
<section>
    <header>Header</header>
    <div>Div</div>
    <button>Button</button>
    <em>Em</em>
    <span>Span</span>
</section>
```

htmlmin:

```
<section><header>Header</header><div>Div</div><button>Button</button><em>Em</em><span>Span</span></section>
```

**Comment by kangax** [comment]
No, I understand. I just wanted to have an example handy for testing.

**Comment by kangax** [comment]
Marking as feature; we should definitely add this.

**Comment by artuska** [comment]
Thank you, that would be great! Should I close this issue?

**Comment by kangax** [comment]
Only after we fix it (I'll try to do it within the next month or so if no one beats me to it)

**Comment by AleksueiR** [comment]
:+1:

**Comment by Njke** [comment]
:+1: Any progress on that?

**Comment by Njke** [comment]
Btw, here is a quick fix, using `gulp-replace` (just add this after `.pipe(htmlmin(...))`):

``` js
.pipe(replace(/>\s+</g, '><'))
```

**Comment by sapics** [comment]
Following, white-spaces around inline tag might remove, isn't it? (need to add new options like `removeInlineTagWhitespace`)

``` diff
// https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L59
-      || (prevTag.substr(0, 1) === '/' && tags.indexOf(prevTag.substr(1)) === -1))) {
+      || (prevTag.substr(0, 1) === '/' && (options.removeInlineTagWhitespace || tags.indexOf(prevTag.substr(1)) === -1)))) {

// https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L64
-      || (nextTag.substr(0, 1) !== '/' && tags.indexOf(nextTag) === -1))) {
+      || (nextTag.substr(0, 1) !== '/' && (options.removeInlineTagWhitespace || tags.indexOf(nextTag) === -1)))) {
```
