### ISSUE TITLE
Is it possible to prevent `<link></link>` from becoming `<link>`?

### ISSUE THREAD

**Issue by benedfit** [kangax/html-minifier#305]
I'm using html-minifier on some XML and as expected it's changing `<link></link>` to `<link>` which unfortunately breaks the RSS feed that's being minified. I was wondering if there was a good way to tell the minifier not to do this?

Cheers

**Comment by XhmikosR** [comment]
Nope. And last time I brought it up, @kangax said this is intentional.

You can use https://github.com/dtrunk90/grunt-xmlmin for that.
