### ISSUE TITLE
Is it possible to use html-minifier with phtml files?

### ISSUE THREAD

**Issue by cortopy** [kangax/html-minifier#307]
I'm currently running html-minifier in gulp. However, it has problems understanding php tags inside html tags.

Running the task in a phtml file gives me the following error:

```
Error: Parse Error: <body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>
```

Something similar happens with other html minifiers, so I'm not sure whether phtml common syntax is included in libraries

**Comment by kangax** [comment]
You can wrap this chunk with  to at least completely ignore it
