### ISSUE TITLE
Source file "" not found.

### ISSUE THREAD

**Issue by honzahommer** [kangax/html-minifier#309]
He is example of my Gruntfile.js.

htmlmin: {
    dist: {
        options: {
            removeComments: true,
            collapseWhitespace: true,
            conservativeCollapse: true,
            minifyCSS: true
        },
        files: {
            'templates/index.html': 'index.html'
        }
    }
}

It returns me "Source file "" not found." error.

**Comment by kangax** [comment]
I'm not very familiar with Grunt, but you run HTMLMinifier as in [instructions](https://github.com/kangax/html-minifier#nodejs):

``` js
var minify = require('html-minifier').minify;
var result = minify('<p title="blah" id="moo">foo</p>', {
  removeAttributeQuotes: true
});
result; // '<p title=blah id=moo>foo</p>'
```

**Comment by honzahommer** [comment]
I need this run under Grunt :-(

On Tue, Dec 16, 2014 at 1:57 PM, Juriy Zaytsev notifications@github.com
wrote:

> I'm not very familiar with Grunt, but you run HTMLMinifier as in
> instructions https://github.com/kangax/html-minifier#nodejs:
> 
> var minify = require('html-minifier').minify;var result = minify('<p title="blah" id="moo">foo</p>', {
>   removeAttributeQuotes: true
> });
> result; // '<p title=blah id=moo>foo</p>'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kangax/html-minifier/issues/309#issuecomment-67155575
> .

## 

Best regards,
Honza Hommer

_Did you see my new website – www.honzahommer.cz
http://www.honzahommer.cz?_

**Comment by duncanbeevers** [comment]
@honzahommer Please refer the configuration example in the grunt-contrib-htmlmin readme. `files` is not a top-level option. You can always run grunt using the `--verbose` flag to see exactly which files are being targeted by a given task. Hopefully that output helps you zero-in the issue.
