### ISSUE TITLE
ProcessScripts + MinifyJS + Knockout breaks when using script blocks for template html

### ISSUE THREAD

**Issue by michaeldewayneharris** [kangax/html-minifier#311]
index.html 

```
<html>
<head>
</head>
<body>
<script type="text/html" id="template">
<!-- ko if: true -->
    <div></div>
<!-- /ko -->
</script>
</body>
</html>
```

app.js

```
var fs = require("fs");

var html = fs.readFileSync('index.html', 'utf8');

var htmlMinifier = require('html-minifier').minify;

var result = htmlMinifier(html, {
 collapseWhitespace: true,
    processScripts: ['text/html'],
    minifyJS: true
});

console.log(result);
```

With these options and html it will remove everything in the script block. 

If you set minifyJS to false then it will work however this option is probably useful for other users.

This also will work if you remove the knockout comment blocks, so i'm not sure what effect they are having on the minifier.

**Comment by duncanbeevers** [comment]
Yes, it sounds like the minifier should only attempt to forward `script` contents to uglify when the `type` attribute is unspecified, or `text/javascript`. Otherwise it should be treated as opaque.

**Comment by kangax** [comment]
@michaeldewayneharris let me know if it's good

**Comment by michaeldewayneharris** [comment]
Seems to be working properly now.
