### ISSUE TITLE
JavaScript comment line removing

### ISSUE THREAD

**Issue by efkan** [kangax/html-minifier#313]
Hello,

Please Ignore this issue befause of the wrong content. The following codes from an Express.js file. Minifier modules perhaps don't know Express codes. Anyway Express.js files are server side files and don't need minify process.

I apologize to everyone.

---

Can I use html-minifier to remove comments in a js file?

I've got the following results. I think `// CONFIGURE APP` may be a problem.
How can I remove comment lines that're start with `//` ? 

Inputted codes;

``` js
var app = express();

// CONFIGURE APP 
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
```

Output results;

``` js
var app = express(); // CONFIGURE APP app.set('view engine', 'ejs'); app.set('views', path.join(__dirname, 'views'));
```

**Comment by XhmikosR** [comment]
Seems to work fine [here](http://kangax.github.io/html-minifier/).

**Comment by efkan** [comment]
Thank you for your interest. I've tried. 

**Input codes;**

```
var app = express();
// CONFIGURE APP 
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
```

**Output codes**

```
var app = express(); // CONFIGURE APP app.set('view engine', 'ejs'); app.set('views', path.join(__dirname, 'views'));
```

//CONFIGURE APP still here :(

**Comment by silverwind** [comment]
You're probably looking for a [JS minifier](https://github.com/mishoo/UglifyJS2), your code minifies correctly when wrapped in a `<script>` tag.

**Comment by efkan** [comment]
@silverwind, thank you for your respond.

If there is possible a tool that is all-in-one I prefer that. I'm already using 'minifier' for JS files and I'm using html-minifier for html files. However my files (like EJS files) included HTML and Javascript codes as nested. For that reason I'm looking for a complete solution :)

**Comment by silverwind** [comment]
Well, your code isn't valid HTML, so html-minifier won't work on it. If you really have HTML strings inside your JS (which is bad practice), manually run the strings through html-minifier.

**Comment by efkan** [comment]
Thank you. If I can't find any solution properly I'll try..

**Comment by duncanbeevers** [comment]
@efkan Internally, html-minifier relies on uglifyjs, a very widely-used js-minifier. If you're sending pure javascript, you'll have to use uglify directly to minify that code. If you're serving templates that include inline javascript, you can use html-minifier's `minifyJS` option to minify that inline code the same way.

**Comment by efkan** [comment]
Hi @duncanbeevers, 

Thank you for your response. I remember I used to html-minifier with my project. But I can't remember "how could I do" :)  This reason maybe minifyJS. Thank you again. I'll try that :)
