### ISSUE TITLE
Is it possible to  compact groups of empty lines into one?

### ISSUE THREAD

**Issue by rexdf** [kangax/html-minifier#315]
My htmls have lots of empty line. Both `preserveLineBreaks: false` and `preserveLineBreaks: true` cannot compact it.

**Comment by kangax** [comment]
I think you're looking for `preserveLineBreaks=true` — https://github.com/kangax/html-minifier#options-quick-reference

**Comment by rexdf** [comment]
It seems not work at all!  @kangax  You cannnot find it in http://kangax.github.io/html-minifier/.

**Comment by kangax** [comment]
We didn't have a chance to add it to the site but the CLI and module have it of course.

**Comment by rexdf** [comment]
```
    dist: { // Target
            options: { // Target options
                //removeComments: true,
                minifyJS: true,
                minifyCSS: true,
                preserveLineBreaks: true,
                //collapseWhitespace: true
            },
            files: { // Dictionary of files
                'public2/index.html': 'public/index.html', // 'destination': 'source'
            }
        },
```

The above code cannot remove groups of empty lines.

**Comment by kangax** [comment]
collapseWhitespace should be true, afaik

**Comment by rexdf** [comment]
Yes, it remove all empty char. But some search engines seem not like it (I think so).

**Comment by rexdf** [comment]
Thanks for you and your project. I should set both collapseWhitespace and preserveLineBreaks to true.
It works now.
