### ISSUE TITLE
How disabled html parser

### ISSUE THREAD

**Issue by khmelevskii** [kangax/html-minifier#32]
I need to minify html-pattern like this:

``` html
<dl {{IF baz}}data-baz="1"{{END IF}}>
  <dt>foo</dt>
  <dd>bar</dd>
</dl>
```

but it can't be validated although it's absolutely correct.

**Comment by gregberge** [comment]
Hello, i met the same problem with hulkster, i solved this by a tricky replace https://github.com/neoziro/hulkster/commit/dc7e284245a5fcbf3b1006afe7562decf314fb47. It works but i am interested if you have a best solution.

**Comment by kangax** [comment]
It can't be parsed because it's not valid html5
