### ISSUE TITLE
Add recursive option to command line

### ISSUE THREAD

**Issue by mathpere** [kangax/html-minifier#323]
Hello,

Is there any plan to add recursive option to command line options + output dir option?
(in order to process multiple files inside subdirectories)

```
html-minifier src dest
```

This command would process all *.html files inside src directory and output would be written in dest directory.

**Comment by kangax** [comment]
Good idea. I'd love to have this so please feel free to send a PR.

**Comment by davidhund** [comment]
This would be awesome. At the moment I'm trying to `watch` `./src/*.html` and have something like: `html-minifier -o ./dist/* <STDIN>`

If html-minifier picks up STDOUT from some other process (such as `watch`) adding an output-**folder** would be enough, no?

Anyway: 'globs' would be awesome: `html-minifier ./src/**/*.html ./dest`

**Comment by simonewebdesign** [comment]
I'm writing an npm script and I tried doing something like:

```
html-minifier -o dist/* source/*.html
```

But it's not producing anything. Would be great indeed to have a _output-folder_ flag.

**Comment by vinyanalista** [comment]
+1 for that feature! [html-minifier](https://github.com/kangax/html-minifier) seems to be the best HTML compressor out there!

**Comment by kangax** [comment]
Damn right, it is! :)

**Comment by vinyanalista** [comment]
I know almost nothing about [Node.js](https://nodejs.org/), but I know a little about [Shell Script](https://en.wikipedia.org/wiki/Shell_script), so I made this script to minify HTML files from a folder and its subfolders:

``` bash
#!/bin/bash
# minify_html.sh
if test $# -ne 2
then
    echo "usage: sh minify_html.sh sourcedir destdir";
    exit 1;
fi

set -xv

for FOLDER in `find $1 -type d`
do
    mkdir -p "$2/${FOLDER#$1}";
done

for HTML_FILE in `find $1 -type f -name "*.html"`
do
    html-minifier --remove-comments -o "$2/${HTML_FILE#$1}" "$HTML_FILE";
done

for ASSET in `find $1 -type f ! -name "*.html"`
do
    cp "$ASSET" "$2/${ASSET#$1}";
done
```

How to use it:

```
sh minify_html.sh sourcedir destdir
```

What it does in those three `for` loops:
1. Replicate the folder structure
2. Minify all the HTML files found
3. Copy all the other files

But it does not seem to work... =/ I'm trying to minify [my personal website](https://github.com/vinyanalista/vinyanalista.github.io), and it seems like the [html-minifier](https://github.com/kangax/html-minifier#usage) command crashes for the second file found in the second `for` loop, which is [/blog/2012/index.html](https://github.com/vinyanalista/vinyanalista.github.io/blob/master/blog/2012/index.html). The first and the third `for` loops work as expected.

Am I doing something wrong? Did I forget something?

**Comment by vinyanalista** [comment]
`--remove-comments` is just an example. Do I need to tell `html-minifier` everything I want it to do? Or there is something like a default config? I realized that if I pass it only the input and the output files, it seems actually to just copy the file. What if I want it to perform exactly like the [online version](https://kangax.github.io/html-minifier/)?

**Comment by ramonck** [comment]
Created a pull request to fix this, was generating a pain for me, hope this helps others as well, the idea is to use a --file-ext html, so you only parse what you want.

https://github.com/kangax/html-minifier/pull/680

Best Regards,

**Comment by fulldecent** [comment]
"(libuv) kqueue(): Too many open files"

**Comment by Geczy** [comment]
I solved it by doing this. It will run for every html file in the directory you run it in

```bash
find . -name *.html -type f -exec html-minifier -o {} {} --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true --file-ext html \;
```
