### ISSUE TITLE
New npm release?

### ISSUE THREAD

**Issue by silverwind** [kangax/html-minifier#324]
Is anything particular hindering a new release?

I'm asking because I have a rather strange dependency issue on heroku (which would require a dirty hack to fix), and this issue could be remedied if this module would depend on `clean-css` 3.x.

**Comment by kangax** [comment]
> Is anything particular hindering a new release?

Only time needed to tag it, update changelog, push, publish, etc. If someone can do it, I'll gladly merge it in.

**Comment by silverwind** [comment]
If you're interested, I could add some release automation tasks to the Gruntfile, which could do the tag, push and publish tasks, leaving only the changelog to be written. It would require a few more devDeps thought.

See the `patch`, `minor`, `major` tasks in [one of my Gruntfiles](https://github.com/silverwind/tcpie/blob/master/Gruntfile.js).

**Comment by kangax** [comment]
Sure, that would be great!

**Comment by sindresorhus** [comment]
Another option is adding this to your .bashrc/.zshrc: https://gist.github.com/sindresorhus/8435329

**Comment by silverwind** [comment]
@sindresorhus Nice tip. Unfortunately not enough for this project because the version string needs to be replaced in 3 files in addition to package.json.

I've yet to find a suitable grunt module that handles everything I need here (bump, replace, git tag).

**Comment by sindresorhus** [comment]
> Unfortunately not enough for this project because the version string needs to be replaced in 3 files in addition to package.json.

Isn't that what the Gruntfile already does?

```
$ grunt && np
```

Anyways, you should separate the concerns between preparing for publish and actually publishing. My above tip concerns itself with the latter.

**Comment by silverwind** [comment]
There's an unhandled version tag in `index.html`, which is the issue.

**Comment by sindresorhus** [comment]
That can easily be handled by https://github.com/outaTiME/grunt-replace or a custom task simply using [`cheerio`](https://github.com/cheeriojs/cheerio).

**Comment by silverwind** [comment]
With `grunt-replace`, how would you obtain the replacement string (the new version, set by a previous task).

**Comment by sindresorhus** [comment]
Hmm, yeah, good point. `¯\(º_o)/¯`

**Comment by silverwind** [comment]
The furthest I got was to use [grunt-version](https://github.com/kswedberg/grunt-version) with custom regular expressions, which did the package.json tag and html replace fine, but that left me wondering how to obtain the version for an upcoming `git tag` task. Sometimes I really hate grunt.

**Comment by silverwind** [comment]
FYI, I found the cause for my heroku dependency mess: heroku defaults to npm 1.4.28 (the version packaged with node), which was wrongly resolving the clean-css dependency for this module to 3.x because my module itself depended on that version. After setting heroku to install npm 2.1.x, it correctly installed both 2.x and 3.x.

**Comment by silverwind** [comment]
I don't have an immediate need any more, so closing this. Regarding automation: It could be done in grunt but would likely require at least 2-3 extra devDeps, which I think would be module bloat for such a simple job.
