### ISSUE TITLE
"<" symbol in <pre> tag will cause warning.

### ISSUE THREAD

**Issue by everthis** [kangax/html-minifier#326]
![min](https://cloud.githubusercontent.com/assets/3142886/5660000/a40556e6-9755-11e4-967f-6a2c1b04f74b.JPG)

and all code in that .html file is:

``` html
<pre class="brush: js;">
    function getScriptParams(scriptFileName) {
       // Get all script tag
      var scripts = document.getElementsByTagName('script');
      var result = {};
      for(var i = 0; i < scripts.length; ++i) {
         // Check if the file name is the same as scriptFileName
        if(scripts[i].src.indexOf(scriptFileName) !== -1) {
          // Get the parameters string
          var urls = scripts[i].src.split('?');
          if(urls.length == 2) {
            var parameters = urls[1].split('&');
            for(var j=0; j < parameters.length; ++j) {
              var pair = parameters[j].split('=');
              result[pair[0]] = pair[1];
            }
          }
          break;
        }
      }
      return result;
    }
</pre>

<script src="scripts/test.js"></script>
```

**Comment by sroe** [comment]
Having the same problem with angular html expression `{{ 5 < 6 }}`.
:+1: for fixing or having a ignoreflag?

**Comment by sroe** [comment]
Okay best solution on this: #254 (using `&lt;` instead of < and so you could also use `&gt;` for >) for me that is enough :+1: if other solutions are hard to implement.

**Comment by v1vendi** [comment]
:+1: for the fix

**Comment by fregante** [comment]
It's because this is not valid HTML

> [HTMLMinifier can't work with invalid or partial chunks of markup](https://github.com/kangax/html-minifier#working-with-invalid-markup)

**Comment by kangax** [comment]
What @bfred-it said
