### ISSUE TITLE
Feature Request, possibility to include HTML files

### ISSUE THREAD

**Issue by LEDfan** [kangax/html-minifier#334]
Hi

I hope this isn't asked before, I searched in the issue tracker.

It would be awesome to create a include directive. So you can include other HTML files into one big HTML file.

Is this already possible?

Thanks!

**Comment by kangax** [comment]
Not sure why would html minifier be taking care of inclusions? Could you explain your use case?

**Comment by fregante** [comment]
This definitely shouldn't be part of a minifier.
@LEDfan use something like [ssi](https://github.com/67726e/node-ssi) on the HTML files before passing them to html-minifier
