### ISSUE TITLE
Prevent collapsing whitespace in PHP tags

### ISSUE THREAD

**Issue by remibreton** [kangax/html-minifier#336]
Using `grunt-contrib-htmlmin 0.4.0`, collapsing whitespace also affects PHP tags. This is a code-breaking issue when using single line comments in PHP.

``` html
<p>
    <?php
        // Test
        echo "Hello!";
    ?>
</p>
```

Get minified to:

``` html
<p><?php // Test echo "Hello!"; ?></p>
```

I know that `html-minifier` is meant for HTML only, but I think it's an incredible feature to PHP while I HTML and still benefit from the minifier. I just wish it would ignore `<?`, `<?php` & `?>` before collapsing whitespace.

Apologies if this issue was raised before!

**Comment by niksy** [comment]
+1 for this feature.

**Comment by kangax** [comment]
Current workaround would be to use  for this
