### ISSUE TITLE
include minimize in the performance comparison table

### ISSUE THREAD

**Issue by nschloe** [kangax/html-minifier#338]
I came across html-minifier when comparing its gulp-frontend [gulp-htmlmin](https://www.npmjs.com/package/gulp-htmlmin) with its more popular (by the number of downloads) equivalent [gulp-html-minify](https://www.npmjs.com/package/gulp-minify-html). The latter is based on [minimize](https://github.com/Moveo/minimize) so I think it'd be useful to include that into the performance comparison in the `README.md` as well.

**Comment by kangax** [comment]
Ah, interesting. I've never heard of it. But I do see this in credits:

> Minimize is influenced by the HTML minifier of kangax. This module parses the DOM as string as opposes to an object. However, retaining flow is more diffucult if the DOM is parsed sequentially. Minimize is not client-side ready. Kangax minifier also provides some additional options like linting. Minimize will retain strictly to the business of minifying. Minimize is already used in production by Nodejitsu.

It should be fairly easy to plug it in our benchmark. I don't have time right now, but if someone can do it and send PR, that would be great!
