### ISSUE TITLE
Quotes removal can lead to incorrect expressions

### ISSUE THREAD

**Issue by Javarome** [kangax/html-minifier#339]
When putting expressions in attributes, such as `<div ng-show="myList.length>0">`, removing the quotes lead to interpret `>` as a tag closing and so leads to output a `0>` because htmlmin generates `<div ng-show=myList.length> 0>`.

Of course a workaround is to disable the quotes removal, but this is losing an opportunity to remove a lot of quotes, whereas the parser could just avoid it if it detects a `>` in the attribute expression.

**Comment by alexlamsl** [comment]
Testing with the current `master`:

```
> minify('<div ng-show="myList.length>0">', {removeAttributeQuotes:true})
'<div ng-show="myList.length>0"></div>'
```

So I think this issue has been fixed a while ago?
