### ISSUE TITLE
Angular template's parse error

### ISSUE THREAD

**Issue by tamtakoe** [kangax/html-minifier#340]
Parse error for this:

<pre>&lt;span class="sr-only"&gt;({{ $index &lt; value ? \'*\' : \' \' }})&lt;/span&gt;</pre>

I try

<pre>customAttrAssign: ['{{.*}}'],
customAttrSurround: ['{{.*}}']</pre>

but it does not help

P.S. https://github.com/Moveo/minimize work good

**Comment by kangax** [comment]
It doesn't work because it's not part of an attribute. Marked as possible feature to see if we can do anything about this kind of markup.
