### ISSUE TITLE
customAttrSurround does not permit if...else

### ISSUE THREAD

**Issue by laurencedorman** [kangax/html-minifier#343]
``` hbs
<div>
    <input 
        {{#if type }}
            type="{{ type }}"
        {{else}}
            type="text"        
        {{/if}}
    >
</div>
```

If I try to use html-minifier's `customAttrSurround` option to minify the above template code (Handlebars), I get an error.

I could use the Handlebars helper `{{#unless}}` but I can't do this if I create a custom block helper that can return an else function using `options.inverse()`

**Comment by duncanbeevers** [comment]
Yeah, `customAttrSurround` is pretty simple and explicit in what it does. I'd suggest performing this `text || "text"` transformation prior to passing the data to the template, or moving the control structure outside of the tag so the minifier sees it as text.

**Comment by alexlamsl** [comment]
Or just use `ignoreCustomFragments:[/{{.*?}}/]`?

**Comment by alexlamsl** [comment]
@ld0rman actually `customAttrSurround` does work with your example. Here's a slightly more complicated one:

```
> minify(`
... <div>
...     <input
...         {{#if type = "a" }}
...             type="hello"
...         {{elseif type }}
...             type="{{ type }}"
...             placeholder="world"
...         {{else}}
...             type="text"
...         {{/if}}
...         value="{{value}}"
...     >
... </div>
... `, {
.....   customAttrSurround: [ [ /(?:(?:\{\{.*?)?\}\})?/, /(?:\{\{(?:.*?\}\})?)?/ ] ],
.....   collapseWhitespace: true,
.....   removeTagWhitespace: true,
.....   removeAttributeQuotes: true
..... });
'<div><input {{#if type = "a" }}type=hello {{elseif type }}type="{{ type }}"placeholder=world {{else}}type=text {{/if}}value={{value}}></div>'
```
