### ISSUE TITLE
remove comments and collapse whitespace (non-conservative)

### ISSUE THREAD

**Issue by WolfgangKluge** [kangax/html-minifier#346]
If I remove comments and collapse whitespace, I get

``` html
halloworld
```

from

``` html
hallo <!-- ... --> world
```

I think this is not the correct behaviour. One of the two whitespace characters should be preserved

**Comment by alexlamsl** [comment]
Hmm, regardless of `removeComments`, `collapseWhitespace` is misbehaving:

```
> minify('<div>hello <!-- cruel --> world</div>', {collapseWhitespace:true});
'<div>hello<!-- cruel -->world</div>'
```

Note the removed whitespaces. At the very least I would expect one of the two whitespaces to be kept.
