### ISSUE TITLE
Some newer options are not available via the CLI

### ISSUE THREAD

**Issue by tssajo** [kangax/html-minifier#347]
Some newer options are not available via the CLI such as `removeScriptTypeAttributes`, `removeStyleLinkTypeAttributes` and possibly more.

I might be able to fix this and submit a PR at some point...

**Comment by kangax** [comment]
That would be great! Thanks.

**Comment by tssajo** [comment]
@kangax : I created a PR but in the meantime cli.js got changed in your github repo (which is upstream repo to me)... Can you still merge my PR ?
If not, I can rebase my changes, just let me know.
Thanks!

**Comment by tssajo** [comment]
@kangax: Created new PR which can be merged as of now: https://github.com/kangax/html-minifier/pull/350

**Comment by tssajo** [comment]
Thanks for merging! Please don't forget to eventually bumb version to 0.7.2 to make `npm update -g html-minifier` work. Thanks!

**Comment by kangax** [comment]
Done

**Comment by tssajo** [comment]
Thanks! Perfect.
