### ISSUE TITLE
endless loop/freeze case

### ISSUE THREAD

**Issue by kelson42** [kangax/html-minifier#351]
This url
http://rest.wikimedia.org/eo.wikipedia.org/v1/page/html/Ciklada_kulturo/5636524

With this:
htmlMinifier.minify( html, {
                removeComments: true,
                conservativeCollapse: true,
        collapseBooleanAttributes: true,
                removeRedundantAttributes: true,
                removeEmptyAttributes: true,
        minifyCSS: true );

**Comment by tssajo** [comment]
This is possibly related to https://github.com/kangax/html-minifier/issues/213

**Comment by kangax** [comment]
Duplicate of #332
