### ISSUE TITLE
UnderscoreJS template <% ... %> not being ignored.

### ISSUE THREAD

**Issue by samkelleher** [kangax/html-minifier#353]
I understand that htmlmin is supposed to ignore <% ... %> tags out of the box without any extra configuration, but even on 0.7 it still throwing a parser error for the following string:

`<input type="checkbox" <%= (model.isChecked ? 'checked="checked"' : '') %> />`

Am I missing something, or can it not ignore the tags when used with attributes like this?

**Comment by fritx** [comment]
:+1: There is a flag named "removeIgnored", however, what we need seems to be "ignoreSomething"...

**Comment by fritx** [comment]
I am meeting the same problem, anyone could help?

**Comment by kangax** [comment]
You can surround it with  to completely ignore it
