### ISSUE TITLE
Option to not add missing or remove extraneous tags

### ISSUE THREAD

**Issue by wankdanker** [kangax/html-minifier#355]
Is it possible to not add in missing ending tags and not remove tags if there is no beginning tag?
### Example of tags being added

``` bash
echo "<html><body><div>" | html-minifier
```
#### Result

``` html
<html><body><div></div></body></html>
```
### Example of tags being removed

``` bash
echo "<p></p></div></body></html>" | html-minifier
```
#### Result

``` html
<p></p>
```
### Use case

I am trying to minify my templates so that the generated HTML will be minified as well. This works great except that in some cases one template may contain the beginning `<html>` tag and a different file contains the closing `</html>` tag.

It seems that the current implementation of html-minifier adds and removes tags as seen in the above examples thus mangling my minified templates. I could not find an option that would toggle this behavior. Is this something that could be toggled in some way?

**Comment by kangax** [comment]
Hey @wankdanker. Unfortunately it's not possible. I've answered this before in the other tickets here, but since this topic comes up once in a while, I've just added a short section in README on this — https://github.com/kangax/html-minifier#working-with-invalid-markup — check it out

**Comment by wankdanker** [comment]
Hi @kangax. Thank you for responding and making the change to the README. I was afraid this might be the case. Thank you for your work on this excellent module. :)
