### ISSUE TITLE
Problem to minify Django style template

### ISSUE THREAD

**Issue by benpptung** [kangax/html-minifier#356]
Hi I see the following problem

```
{% extends './basetpl/layout-base.swig' %}{% block header %}<style></style>{% endblock %}
```

It's Django style tempalte, would be translated as

```
{% extends './basetpl/layout-base.swig' %}{% block header %}<style></style>{:% endblock %}
```

I've tried all the options, do I miss any option to avoid the `colon` inserted.

**Comment by fregante** [comment]
Not sure of what the problem is, in my test the output is:

``` js
{% extends './basetpl/layout-base.swig' %}{% block header %}<style></style>{% endblock %}
```

no colons

**Comment by aburi** [comment]
I'm getting parse errors as well with my Django templates files on code like this:
`<img src="{% static "images/logo.png" %}">`

**Comment by kangax** [comment]
You can now use `ignoreCustomFragments` option
