### ISSUE TITLE
self closing div tag creating problems after turncation

### ISSUE THREAD

**Issue by ttelang** [kangax/html-minifier#357]
I am writing a web app for Chrome, I had the following html, 

``` html
<div class="bottom-area">
     <div class="left"  />
     <div class="right">
        <a class="click-button" href="" target="_blank" ng-click="addExtensionClickHandler()" ></a>
     </div>
</div>
```

Unminified code works fine in Chrome but after minification in the output the code is getting truncated after line 2 as something equivalent to the one below: 

``` html
<div class="bottom-area">
     <div class="left" />
</div>
```

the entire div with class=right is getting removed.

On modifying the code below as below it works fine.

``` html
<div class="bottom-area">
     <div class="left"  ></div>
     <div class="right">
          <a class="click-button" href="" target="_blank" ng-click="addExtensionClickHandler()" ></a>
     </div>
</div>
```

Best Regards,
Tarun

**Comment by fregante** [comment]
Self-closing tags are not part of HTML, but XHTML—which html-minifier doesn't seem to officially support.

**Comment by kangax** [comment]
What @bfred-it said :) I don't see a reason why you'd want to have something like `<div />` in your code.

**Comment by ttelang** [comment]
``` html
<div/> 
```

works in Chrome. By mistake I had this in my code and couldn't detect it because it was working perfectly in Chrome. 

But After minification this entire div was not appearing in the code. so it was very difficult for me to root cause the problem and had to waste lot of time debugging this problem.

It would be helpful for others if we warn / show error in case such code is encountered or atleast document this somewhere.

**Comment by fregante** [comment]
Browsers accept all kinds of invalid HTML (and XHTML); supporting all of it is an insane amount of work. The alternative would be using a headless browser to parse the HTML but that would slow things considerably and would lack other features.

You can use the module w3cjs to find those errors instead.
