### ISSUE TITLE
Added quotes around attributes containing domains?

### ISSUE THREAD

**Issue by Keenora** [kangax/html-minifier#358]
Hey! First of all, thank you very much for your work and the amount of effort you put into this. It is really worth it! :+1: 

Anyway; I think I've found a possible way to achieve a few more bytes. In my website I've replaced the quotes of all attribute-values with a specific regex. After checking it in the w3 validator there was no problem, so it worked pretty good. Then I've matched the result of my crunched markup with yours and have seen the canoncial href attribute. Mine was without quotes, which was right and valid, but yours added quotes, so 2 chars more. Here is an example:

```
<link rel=canonical href=http://www.keenora.de/>
```

And your minified version:

```
<link rel=canonical href="http://www.keenora.de/">
```

The same happened at some other points. For example, I've got a Facebook Like Button on my site and there is an attribute called "data-href" which contains the URL which you "like". The Minifier also added quotes around it. 

I am doing it in PHP but the RegEx could be used in JS as well:

```
'/(\s)([A-z\-]+)=\"([A-z_\d\,\.\-\:\/\+\#\?\@]+)\"/' replaced by '$1$2=$3'
```

Hope that helps! Keep it up! :3

Btw; You can use keenora.de as example. Pretty much crunched down (except the js, still need to work on that ^^)

**Comment by alexlamsl** [comment]
That is due to the trailing `/` in the `href` attribute value. This is now improved in the latest commit to `<link rel=canonical href=http://www.keenora.de/ >` (note the space before `>` to avoid confusion with self-closing tags)

**Comment by Keenora** [comment]
Works! :) Thank you very much :+1:
