### ISSUE TITLE
Django template one line if/then throwing a parse error using grunt build/htmlmin

### ISSUE THREAD

**Issue by rkpatel33** [kangax/html-minifier#360]
I narrowed down and issue with running htmlmin on a Django template to this line and can't figure out what is wrong with it. Breaking it into 5 lines works.

Throws parse error:

```
<form method="POST" class="form-horizontal" {% if selectedplan == 'trial' %}onsubmit="formOnSubmit()"{% endif %}>
```

This works:

```
  {% if selectedplan == 'trial' %}
    <form method="POST" class="form-horizontal" onsubmit="formOnSubmit()">
  {% else %}
    <form method="POST" class="form-horizontal">
  {% endif %}
```

**Comment by duncanbeevers** [comment]
Right, the first form isn't valid html, while the second is.

There's actually a `customAttrSurround` option to support intra-tag wrapped attributes of the form you're using.

**Comment by rkpatel33** [comment]
Thanks!
