### ISSUE TITLE
conservativeCollapse with removeOptionalTags behaves unexpectedly

### ISSUE THREAD

**Issue by dben** [kangax/html-minifier#361]
Using the conservativeCollapse flag with removeOptionalTags unexpectedly renders html options with an additional space (demonstrable on http://kangax.github.io/html-minifier/ )

``` html
<select>
  <option>abc</option>
  <option>def</option>
</select>
```

becomes

``` html
<select> <option>abc <option>def </select>
```

Expected:
closing </option> tags would not be removed if the result would change option text (with additional whitespace). 

``` html
<select> <option>abc</option> <option>def</option> </select>
```

**Comment by yuvalkarmi** [comment]
**I can confirm that this is an issue.**

Just spent hours trying to debug an AngularJS app that suddenly stopped working in production (ergo post-minification). After ruling out any javascript changes, I tracked it down to a partial that's used in almost every page of the app: html-minifier was removing the **closing tag for `option` elements that included text**.

@dben's description is reproducible, and this needs a fix.

Cheers!

**Comment by kangax** [comment]
Interesting anomaly. Marking as bug.

**Comment by davideanderson** [comment]
I have just discovered and verified that the same thing is happening to dictionary tags.

```
<dl>
    <dt>something</dt>
    <dd>anything</dd>
</dl>
```

becomes

`<dl> <dt>something <dd>anything </dl>`

**Comment by duncanbeevers** [comment]
@davideanderson This looks expected. `<dt>` and `<dd>` are only closed optionally.

http://www.w3.org/TR/html5/syntax.html#optional-tags

**Comment by davideanderson** [comment]
@duncanbeevers You are correct, but I shouldn't have simplified my example so much, it appears to ALWAYS remove the trailing tag for `<dd>`, but it isn't always optional, as pointed out in the spec you linked.

In my actual project, I was intermixing `<dd>` tags with `<accordion-group>` tags in an angular+foundation project.  All of the trailing `</dd>` tags were stripped, even if the following tag was not a dd or dt element, making the browser assume the following element was a child of the dd element.

**Comment by duncanbeevers** [comment]
@davideanderson Thanks for the explanation. According to the html spec, this is definitely not an appropriate collapse.
