### ISSUE TITLE
collapseWhitespace removes HTML5 source tags

### ISSUE THREAD

**Issue by Snugug** [kangax/html-minifier#362]
I've got a video tag with two source tags and a fallback to download the video:

``` html
<video library-class="media--video" controls loop>
  <source src="video.webm" type="video/webm">
  <source src="video.mp4" type="video/mp4">
  <div class="base--STYLED">
    <p><a href="video.mp4">Download <code>mp4</code> video <strong>My Video</strong></a></p>
  </div>
</video>
```

When `collapseWhitespace` is true, the first source gets removed from my HTML, and the closing source tag for the second one wraps my fallback. The first source tag should definitely not be removed, and the closing tag for the second shouldn't wrap the fallback. I'm using `v0.7.2`.

**Comment by Snugug** [comment]
Adding `conservativeCollapse` resolves this issue, but it shouldn't be needed for `<source>`

**Comment by kangax** [comment]
Hm, I just tried it on http://kangax.github.io/html-minifier/ and can't reproduce (with `collapseWhitespace` on but `conservativeCollapse` off)
