### ISSUE TITLE
Keep whitespace arround <math>

### ISSUE THREAD

**Issue by recmo** [kangax/html-minifier#368]
Input:

``` html
<p>where <math> <mi>R</mi> </math> is the Rici tensor.</p>
```

Expected output:

``` html
<p>where <math><mi>R</mi></math> is the Rici tensor.</p>
```

Should look like "where R is the Rici tensor."

Actual output:

``` html
<p>where<math><mi>R</mi></math>is the Rici tensor.</p>
```

Which will look like "whereRis the Rici tensor."

Please add `math` to the list on [line 46 in htmlminifier.js](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L46). I see `svg` is already there.

**Comment by kangax** [comment]
What about all the other [MathML tag names](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/math)? Technically we only support HTML now

**Comment by recmo** [comment]
I'm talking about the spaces around the `<math>` tag, what happens inside the `<math>` tag is irrelevant here.

The situation is analogous to `svg`. Both are valid HTML5. Both are commonly used inline in HTML. Both have significant white-space around them then. `svg` is currently included in the list. `math` is not.

Regarding white-space collapsing in MathML itself: After trying some formulas, it seems MathML works fine with all white-space collapsed. I have not investigated this specifically.

**Comment by kangax** [comment]
@Recmo oh, got it, makes sense. I'm really short on time now so please send PR (+ a minimal unit test) and I'll gladly merge. We can investigate other MathML tags later!
