### ISSUE TITLE
UTF not BOM

### ISSUE THREAD

**Issue by IRIDON** [kangax/html-minifier#372]
Encoding UTF all files without BOM - problems with Cyrillic

**Comment by kangax** [comment]
Can you give an example / failing test case?

**Comment by IRIDON** [comment]
example - encoding UTF8, failing - encoding UTF-8 without BOM.

**Comment by juking** [comment]
example: Chinese characters encoding by ANSI 
I want the original coding.

not UTF-8 without BOM

**Comment by alexlamsl** [comment]
I guess this is related to https://github.com/nodejs/node/issues/2835

**Comment by alexlamsl** [comment]
I guess we'll defer this to iconv...
