### ISSUE TITLE
Colons after quotes in inlined style when "minify CSS" is enabled

### ISSUE THREAD

**Issue by pmendelski** [kangax/html-minifier#373]
Hi,

I faced a problem with minimizing html content with inlined styles. html-minifier add colons after `&quot;`.

For following input:
(generated from style inlining tool)

``` html
<span style="font-family:&quot;Helvetica Neue&quot; , &quot;Helvetica&quot; , Helvetica , Arial , sans-serif">Spanned text</span>
```

Produced output:

``` html
<span style="font-family:&quot;:Helvetica Neue&quot;:,&quot;:Helvetica&quot;:,Helvetica,Arial,sans-serif">Spanned text</span>
```

It works fine in version 0.6.9. Problem appears in version 0.7.2.

**Comment by kangax** [comment]
I can reproduce and it seems to be a problem only when enabling "Minify CSS"

**Comment by silverwind** [comment]
This is definitely not valid CSS. You can't use HTML escapes in CSS. I see this:

``` js
> new (require("clean-css"))().minify("a{font-family:&quot;Helvetica Neue&quot; , &quot;Helvetica&quot; , Helvetica , Arial , sans-serif}").styles
'a{font-family:&quot}'
```

If anything, this should be brought up to clean-css, but I doubt the author wants to include hacks for this.

**Comment by kangax** [comment]
Thanks @silverwind

**Comment by pmendelski** [comment]
It's not so obvious when it comes to inlined css (http://stackoverflow.com/questions/5352947/how-to-escape-quotes-in-inline-styles). Thanks anyway. Great job with this repo and issue response time, thanks!
