### ISSUE TITLE
How to remove the js comments in the html?

### ISSUE THREAD

**Issue by hwoarangzk** [kangax/html-minifier#378]
Sometimes I have to write a little inline js code with comments in the html, and when I use `collapseWhitespace` to minify my html, the js comments doesn't get removed. But the result is that there is only one line code of my whole html string with the js comments in it and so it ruined the grammer and won't get compiled in some template engine:

<pre>
  <html>
  <%
    var a = 1; //this is the comment I want to move when minifying this html
    var b = 'ok';
  %>
  </html>
</pre>

After got minified, the html became:

<pre>
<html><%var a = 1; //this is the comment I want to move when minifying this html var b = 'ok';%></html>
</pre>

Is there anyway to solve this problem? Thanks :)

**Comment by Meligy** [comment]
Have you tried hte `preserveLineBreaks` option?

**Comment by kangax** [comment]
How would minifier know that `<%` starts a script? If it's inside a script element, you can use processScripts option, giving it stuff like "text/ng-template"
