### ISSUE TITLE
Supporting Polymer core-style tags as style (CSS) tag

### ISSUE THREAD

**Issue by Meligy** [kangax/html-minifier#380]
Hello,

First, thanks for the awesome library, and for supporting Polymer style attributes with `customAttrAssign:  /\?=/` option, which allows `<any hidden?="{{ blah }}">` to work just fine.

Now I need to go extra mile.

In Polymer (using 0.5), I have a lot of styles in `<core-style>` elements. This looks like:

```
<polymer-element name="blah">
  <template>
    <core-style ref="somethingGlobal" ></core-style>
    <core-style id="whatever">
        /* I should be removed!! */
        .something_in_shadow_DOM {
          background: green;
        }
    </core-style>
    <div class="something_in_shadow_DOM">
      To concatenate styles with no duplicates, use core-style tags instead of style tags
    </div>
  </template>
<polymer-element>
```

Note the `/* I should be removed!! */` line.

Is there any existing way to do it today? 

Otherwise, would it make sense to have a new option with array of tags to treat as CSS code, with `['style']` as a default value?
(then I can change it to `['style', 'core-style']` afterwards)

Thanks again.

**Comment by kangax** [comment]
Interesting. I'll mark it as possible feature for now and we'll see if anyone else needs this!

**Comment by akashkrishnan** [comment]
:+1:

**Comment by kangax** [comment]
@Meligy I would gladly add this if you can send a PR! :)

**Comment by Meligy** [comment]
Hi @kangax - sorry for not closing this earlier.

Actually, the team that needed this already moved to Polymer 1.0, which doesn't have `core-style` anymore. And even later my consulting gig with that team was finished.

By now most people using Polymer 0.5 should be using Polymer 1.0 anyway. So, I'll just close this one.

Thanks for following up.
