### ISSUE TITLE
Allow custom tag processors/minifiers

### ISSUE THREAD

**Issue by fregante** [kangax/html-minifier#382]
A bit of a stretch, but maybe it would make html-minifier easier to extend and less reliant on the maintainers, should other "plugins" come along (base64 minifier? jade templates? frameworktron-3000 awesomizer?)

This would allow me to just pop in a configuration like the following to add support for #381:

``` js
    {
        customMinifiers: [
            {
                regex: /<svg>.*<\/svg>/, // lazy regex
                parser: function (content) {
                    return svgo.optimize(content);
                }
            }
        ]
    }
```

**Comment by fregante** [comment]
Going through other issues, it looks like this could be a solution to:
- #378 + #353 + #385: `<%…%>` = UglifyJS.minify(content)
- #336: `<?php…?>` = content // don't minify at all

**Comment by kangax** [comment]
Hm, it's a thought... I'll mark as possible feature for now, thanks!

**Comment by StevenWeathers** [comment]
I second this, ESI tags are commonly used in large scale complex websites and would be lovely to not have to wrap each set of ESI tags in  manually, which also can leave big blocks of whitespace in the end run.

**Comment by futpib** [comment]
Awesome feature, I think it should not be regex/string driven though, I'd much prefer custom passes over DOM (or whatever structure is used to represent syntax trees in html-minifier). Also custom attribute minification would be useful (we have multi-line knockoutjs 'data-bind' attributes, I'm pretty sure minifyJS won't handle those properly).

**Comment by fregante** [comment]
hmmm can't find how to allow custom tags to be parsed. How would I use SVGO? (example in my first post)

**Comment by alexlamsl** [comment]
`svgo` seems to be using async-style API which isn't compatible with `html-minifier` atm.

I think in the general case `require('html-minifier/src/htmlparser')` is the way to go. The current custom processors are defined for `minifyCSS`, `minifyJS` and `minifyURLs`.

**Comment by fregante** [comment]
But that's not what I meant by custom with this issue, I meant custom tags, not custom processors :-/

Is my example in the second comment feasible?

**Comment by alexlamsl** [comment]
#378 not yet possible, everything else works.

Sorry for misreading this issue then - reopening...
