### ISSUE TITLE
django/liquid tag containing a partial html snippet

### ISSUE THREAD

**Issue by yuchant** [kangax/html-minifier#384]
This line is causing me issues.

`{% if article.content contains "<img" %}`

I'm trying rules like the following: am I on the right track?

```
                customAttrSurround: [
                    [ '\{\{.*', '.*\}\}'],
                    [ '\{\%.*', '.*\%\}'],
                ]
```

**Comment by fregante** [comment]
Can you show the code where this appears? I think `customAttrSurround` only works in attributes

**Comment by kangax** [comment]
You can use this:

```
<!-- htmlmin:ignore -->{% if article.content contains "<img" %}<!-- htmlmin:ignore -->
```
