### ISSUE TITLE
New Option: removeUnsafeOptionalTags

### ISSUE THREAD

**Issue by jesseray** [kangax/html-minifier#386]
In the discussion of [Issue #1](https://github.com/kangax/html-minifier/issues/1), it became clear that HTMLMinifier could not remove the optional `</p>` and `</li>` tags with consistent results because there were browser inconsistencies in a few edge cases. 

I have not verified that, but I am willing to assume that it's true. Even so, I think most devs would never encounter these edge cases in their own projects, so they should have some way to remove the optional `</p>` and `</li>` tags.

I do not mean that the `removeOptionalTags` directive should change. Rather, I want to see it remain the same but supplemented with another option, which could be called something like `removeUnsafeOptionalTags`.

**Comment by kangax** [comment]
That's a fair request. Marking as feature, thanks! (if you can send PR, that would be awesome of course :))

**Comment by ma11hew28** [comment]
Yes, let's do this! :+1:

[W3C HTML5 Specification - Optional Tags](http://www.w3.org/html/wg/drafts/html/master/syntax.html#optional-tags)

> An `li` element's end tag may be omitted if the `li` element is immediately followed by another `li` element or if there is no more content in the parent element.

...

> A `p` element's end tag may be omitted if the `p` element is immediately followed by an `address`, `article`, `aside`, `blockquote`, `details`, `div`, `dl`, `fieldset`, `figcaption`, `figure`, `footer`, `form`, `h1`, `h2`, `h3`, `h4`, `h5`, `h6`, `header`, `hgroup`, `hr`, `main`, `menu`, `nav`, `ol`, `p`, `pre`, `section`, `table`, or `ul` element, or if there is no more content in the parent element and the parent element is an HTML element that is not an `a`, `audio`, `del`, `ins`, `map`, `noscript`, or `video` element.

**Comment by alexlamsl** [comment]
Do we still want this, now that `removeOptionalTags` have incorporated HTML5 omission rules?

**Comment by kangax** [comment]
Hm, good question. Probably not then.

**Comment by alexlamsl** [comment]
@jesseray @mattdipasquale `removeOptionalTags` has been improved in #488 and now conforms to HTML5 tag omission rules.

If any of you thinks this feature is still necessary, please let me know and I'll reopen the issue.
