### ISSUE TITLE
Attribute "visible" should not be considered boolean

### ISSUE THREAD

**Issue by ebpierce** [kangax/html-minifier#389]
I cannot find any definition for the attribute "visible" in any version of HTML. The code at line 200 of htmlminifier.js, however, appears to treat it that way.  This might be a server-side only attribute in ASP.net and who knows where else, but it is not a client-side attribute as far as I can find.

This just happened to cause severe problems in an angular directive using a "visible" attribute.

**Comment by kangax** [comment]
Good point, not sure how it got there. Marking as bug.

**Comment by diegomesata** [comment]
I'm using yeoman angular. I have an angular control that have a visible attribute. ngtemplates uses htmlmin.

My app is: 

 `<wj-flex-grid-column ng-repeat="col in cols"  visible="{{col.visible}}"> </wj-flex-grid-column>`

But in the dist I got: 

`<wj-flex-grid-column ng-repeat="col in cols" header="{{col.header}}" visible> </wj-flex-grid-column>`

Do you have any idea? 

Thank you

**Comment by ebpierce** [comment]
I believe the issue you are having is the same as described. To fix this, for now, use a different attribute name (possibly "show" or "shown", instead of "visible".)
