### ISSUE TITLE
Source Maps

### ISSUE THREAD

**Issue by trisys3** [kangax/html-minifier#390]
Would this even be possible? At least, would it be possible without turning this module into html2js?

**Comment by kangax** [comment]
Not sure if possible, but it's an interesting idea!

**Comment by trisys3** [comment]
Thanks! I have no idea how to implement it, but from what I can tell you _might_ be able to get away with putting a comment at the bottom of the HTML file, perhaps before the ending `<html>` or `<body>` tag. If we put it after, it might work, but will probably cause issues in older browsers, though I don't know how old. I doubt any browsers support HTML source maps yet, but maybe if this module used it, they would start to.

Another probable issue would be JavaScript-based frameworks and linters that automatically scan HTML files for comments. It'll be hard to please every single one. I don't believe JavaScript source maps trip up any major linters or frameworks, but HTML comment-parsing is _much_ more prevalent.
