### ISSUE TITLE
[NFR] Option to Preserve Whitespace in Special Blocks (<%, %>, <?, ?>)

### ISSUE THREAD

**Issue by virgofx** [kangax/html-minifier#392]
For partials/templates where there are special language constructs mixed with HTML it would be nice if we could specify `collapseWhitespace: true` for all the HTML ; however, ensure that the PHP/JSP language does not get mangled with spaces which happens if `collapseWhitespace: true`

Perhaps a `preserveSpecialBlockWhitespace` with defaults to `false` for backwards compatibility.

If others have found a way to ensure that PHP partials can correctly minify/collapse whitespace in the HTML portion while still leaving the PHP intact, I would be grateful for any tips...

**Comment by kangax** [comment]
You can surround it with  which will leave them entirely untouched.
