### ISSUE TITLE
JS template minification problem

### ISSUE THREAD

**Issue by albv** [kangax/html-minifier#395]
Here is simplified version of my source file:

``` html
<script type='text/ng-template' id='template1'>
<html>
<head>
  <style></style>
</head>
<body></body>
</html>
</script>
<script type='text/ng-template' id='template2'>
  <div></div>
</script>
```

I am getting parse error when I am try to minificate it (all options disabled except processScripts: ['text/ng-template']). Without style block in first template it's all working fine.

**Comment by kangax** [comment]
Works for me

**Comment by kangax** [comment]
Duplicate of #382
