### ISSUE TITLE
Normalize order of attributes

### ISSUE THREAD

**Issue by kangax** [kangax/html-minifier#4]
This might result in better gzip compression.

**Comment by hsablonniere** [comment]
We need to group most used attributes of each elements together. Can it be computed, maybe...

**Comment by kangax** [comment]
Do you mean computing gzip savings? Which order results in better compression?

**Comment by duncanbeevers** [comment]
Once the gzip benchmark stuff lands, it'll be much easier to see whether efforts in this area yield size savings.

**Comment by duncanbeevers** [comment]
We can try simplistic approaches like alphabetizing attributes, or more sophisticated approaches like identifying which tag/attribute combos occur most-often. For example, determining that `div` tag's most-common attribute is `class` while `span` tag's most-common attribute it `id`, resulting in better encoding of `<div class=` and `<span id=` sequences.

**Comment by kangax** [comment]
> We can try simplistic approaches like alphabetizing attributes

Yeah, I imagine after gzip it's probably mostly insignificant, since afaik gzip already does some sort of optimal reordering?

> For example, determining that div tag's most-common attribute is class while span tag's most-common attribute it id, resulting in better encoding of <div class= and <span id= sequences.

Yep. Sounds reasonable.

**Comment by alexlamsl** [comment]
So if I understand correctly, we scan through a given tag name collecting statistics, then re-order the attributes by descending frequency?

Most of the time only shuffling the most frequently-used attribute to the front would suffice, but then if that attribute happens to have the same value across then we can form a longer chain if we perform reordering on the rest as well...

**Comment by kangax** [comment]
Sounds about right :)
