### ISSUE TITLE
Allow removeComments to take function returning boolean

### ISSUE THREAD

**Issue by dlmiles** [kangax/html-minifier#404]
``` JavaScript
options: {
 removeComments: function(s) {
   // s === "<!--foobar -->"
   // s === "<!--googleon: all -->"
  if((new RegExp('<!--\\s*google.*')).test(s)) {
   return false; // keep this one
  }
  return true;  // discard this one
 }
}
```

The problem with using "" is that even if htmlmin runs on the file, it does not remove the ! character only it needs.  But I'd prefer to have my markup without the workaround, and keep the htmlmin configuration where it should be inside its options.

**Comment by kangax** [comment]
Sorry, I'm not sure I understand the problem. Could you please rephrase it?

**Comment by dlmiles** [comment]
Allow removeComments to take function returning boolean

So that would mean each comment of passed into the function and the boolean return value dictates if that particular comment is removed or not.

The problem is even in production some comments are not intended to be removed, the mechanism that checks for "!" character is too limited and modifies the markup in a way that might break the intended output.

If you are going to have <!--! bypass, at least always remove that trailing ! character from the output markup.

**Comment by kangax** [comment]
Gotcha. Well, it's a reasonable request. Marking as possible feature.

**Comment by alexlamsl** [comment]
Wouldn't `<!-- htmlmin:ignore --><!--googleon: all--><!-- htmlmin:ignore -->` work in this case?

**Comment by dlmiles** [comment]
That would be a better solution to the magic sequence `<!--!`.

So long as the `<!-- htmlmin:ignore -->` are also removed from the output ?  For a htmlmin process I would expect they are.

Is there distinction made for which is considered inside ?  like ignore on and ignore off ?  
`<!-- htmlmin:ignore:on -->`

**Comment by alexlamsl** [comment]
AFAICT `<!-- htmlmin:ignore -->` does disappear after minification:

```
> minify(`
    <!--testing Google comments-->
    <p>This is a paragraph that will be indexed by Google.</p>
    <!-- htmlmin:ignore --><!--googleoff: index--><!-- htmlmin:ignore -->
    <p>This is a paragraph that will NOT be indexed by Google.</p>
    <!-- htmlmin:ignore --><!--googleon: index--><!-- htmlmin:ignore -->
  `, {
    collapseWhitespace: true,
    removeComments: true
  });

'<p>This is a paragraph that will be indexed by Google.</p><!--googleoff: index--><p>This is a paragraph that will NOT be indexed by Google.</p><!--googleon: index-->'
```

**Comment by alexlamsl** [comment]
I can foresee this interacting badly with `ignoreCustomFragments` if implemented as suggested.

@dlmiles I assume my suggestion above with `<!-- htmlmin:ignore -->` solves your problem. If not please hoiler and I'll reopen this issue.
