### ISSUE TITLE
It doesn't work when i put the config code into a file to apply .

### ISSUE THREAD

**Issue by ChanJoseph** [kangax/html-minifier#406]
everything is okay when I put the config code ( config/.htmlminrc ) into Gruntfile.js .
But when I put the config code into a file to apply , it doesn't work !!
here is the code. 

htmlmin: {
    options: {
        htmlminrc: 'config/.htmlminrc'
    },
    build: {
        expand: true,
        cwd: '<%= pkg.path.src.src %>',
        src: ['*.html'],
        dest: '<%= pkg.path.dest.dest %>'
    }
}

grunt.loadNpmTasks('grunt-contrib-htmlmin');
grunt.registerTask('default', ['jshint', 'uglify', 'csslint', 'autoprefixer', 'less', 'htmlmin', 'imagemin', 'watch']);

here is config/.htmlminrc content : 
{
    removeComments: true,
    removeCommentsFromCDATA: true,
    collapseWhitespace: true,
    collapseBooleanAttributes: true,
    removeAttributeQuotes: true,
    removeRedundantAttributes: true,
    useShortDoctype: true,
    removeEmptyAttributes: true,
    removeOptionalTags: true
}

can somebody give me a hand ?   thx .

**Comment by kangax** [comment]
This seems like something to ask in grunt plugin's issue tracker?

**Comment by ChanJoseph** [comment]
ew ..    I am not sure ,     I just try to find out the reason . 
I found that .  It work in some grunt plugin ( like uglify、jshint ) with that way which put the config code into a file to apply .

here is some Gruntfile.js codes
        jshint: {
            options: {
                jshintrc: 'config/.jshintrc'
            },
            build: [ 'Gruntfile.js', '<%= pkg.path.src.js %>*.js' ]
        },

It work .    but html-minifier plugin doesn't .  
I just don't get it . Do u know why ?

**Comment by kangax** [comment]
No idea, sorry.

**Comment by ChanJoseph** [comment]
Never mind , Thank you ~
