### ISSUE TITLE
Polymer 1.0 native element attributes Parse Error

### ISSUE THREAD

**Issue by qrzbrz** [kangax/html-minifier#408]
Polymer 1.0 uses [Binding to native element attributes](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#native-binding)

using minifier with Polymer gives a parse error:
    [31mERROR[0m: Minification error
    Parse Error: `<div id="topBar" class$="[[_computeBarClassName(justify)]]">`

In my opinion expressions like class$= in e.g. `<div class$="{{someclass}}" />`
are [valid html](http://www.whatwg.org/specs/web-apps/current-work/multipage/syntax.html#before-attribute-name-state), see:
http://www.whatwg.org/specs/web-apps/current-work/multipage/syntax.html#before-attribute-name-state

Especially for Polymer It would be great to use html-minifier , it would make things rocket fast.

**Comment by kangax** [comment]
Nope, it's not a valid HTML(4 or 5). But not to worry! Minifier got you covered, just take a look at "customAttrAssign" in options — https://github.com/kangax/html-minifier#options-quick-reference
