### ISSUE TITLE
The sequence of empty non-HTML-tags transformed wrong

### ISSUE THREAD

**Issue by evgeny-o** [kangax/html-minifier#41]
The sequence:
&lt;some-tag-1&gt;&lt;/some-tag-1&gt;
&lt;some-tag-2&gt;&lt;/some-tag-2&gt;
transformed to:
&lt;some-tag-1&gt;&lt;some-tag-2&gt;&lt;/some-tag-2&gt;&lt;/some-tag-1&gt;. The minifying should keep original sequence. As workaround I should wrap each group by &lt;div&gt;-tags.

**Comment by kangax** [comment]
This is now fixed
