### ISSUE TITLE
Quotes and self-closing elements

### ISSUE THREAD

**Issue by tigt** [kangax/html-minifier#414]
When using the minifier for inline SVG, and keeping the trailing slash (because `<rect />` is shorter than `<rect></rect>`), it will collapse the space between the slash and the final attribute value, while keeping the attribute value surrounded in quotes:

``` html
<rect x=10 y=27 fill="#333"/>
```

One character per element could be saved if the final space was kept, and the quotes removed:

``` html
<rect x=10 y=27 fill=#333 />
```

Not a huge deal, but I figured it was worth bringing up as a possibility.

**Comment by kangax** [comment]
Cool, we'll see what we can do!

**Comment by alexlamsl** [comment]
@kangax this is also implemented now.
