### ISSUE TITLE
<el attr='..."...'> becomes <el attr="...&quot;...">

### ISSUE THREAD

**Issue by 5lava** [kangax/html-minifier#415]
For instance, following valid HTML (both 4 and 5):

```
<a title='foo "bar" banana'></a>
```

is ~~minified~~ maxified to:

```
<a title="foo &quot;bar&quot; banana"></a>
```

which is 2*5=10 bytes more than the original.

**Comment by kangax** [comment]
Yep, we should probably be smarter about this. Notice that this doesn't happen with:

```
<a title="foo 'bar' banana"></a>
```

..because we always normalize to double quotes for attribute values.

**Comment by kangax** [comment]
Btw, this shouldn't happen if you set `quoteCharacter: "'"` option

**Comment by kangax** [comment]
This is now implemented!
