### ISSUE TITLE
Minifying <noscript> contents

### ISSUE THREAD

**Issue by 5lava** [kangax/html-minifier#416]
Turns out the minifier completely ignores contents of `<noscript>` tag. Is that a bug or something that's done for a reason?

**Comment by kangax** [comment]
No reason, it's just a very rarely used "feature" so that's probably why no one brought it up yet.

**Comment by kangax** [comment]
Duplicate of #288

**Comment by 5lava** [comment]
I will use Search before asking. I will use Search before asking. I will use Search before asking.
I will use Search before asking. I will use Search before asking. I will use Search before asking.
I will use Search before asking. I will use Search before asking. I will use Search before asking.

**Comment by kangax** [comment]
@5lava apparently the problem was in our 3rd party (but heavily modifed) parser — it was ignoring everything within noscript. Fairly easy fix and done — https://github.com/kangax/html-minifier/commit/854d87e4fb54684428ffc6cde80820b5665bb53b

**Comment by 5lava** [comment]
Yay, well done! Thanks Juriy.
