### ISSUE TITLE
Inconsistent behaviour of removing attribute quotes

### ISSUE THREAD

**Issue by 5lava** [kangax/html-minifier#417]
HTML 4 spec (http://www.w3.org/TR/html401/intro/sgmltut.html#h-3.2.2) re unquoted attributes:

> The attribute value may only contain letters (a-z and A-Z), digits (0-9), hyphens (ASCII decimal 45), periods (ASCII decimal 46), underscores (ASCII decimal 95), and colons (ASCII decimal 58).

HTML 5 spec (http://www.w3.org/TR/html5/syntax.html#attributes-0) re unquoted attributes:

> ...must not contain any literal space characters, any U+0022 QUOTATION MARK characters ("), U+0027 APOSTROPHE characters ('), "=" (U+003D) characters, "<" (U+003C) characters, ">" (U+003E) characters, or U+0060 GRAVE ACCENT characters (`)...

Currently the minifier stands somewhere in between of those two specs: it neither strictly follows HTML 4 specs (which I'm personally okay with) nor it takes an advantage of HTML 5 allowances:
1. `<img src="/logo.jpg">` => `<img src=/logo.jpg>`
2. `<img src="/logo.jpg" />` => `<img src="/logo.jpg">` (compare with previous one)
3. `<img src="/logo/">` => no changes (which is safe from HTML 4 point of view, since the trailing slash could become a part of self-closing tag syntax)
4. `<img src="/logo/" id=foo>` => still no changes

**Comment by kangax** [comment]
Yep, for the 3 and 4, we might be able to be smarter and only leave quotes when it's the last attribute. Right now it's a dumb check for trailing slash of an attribute value — https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L111-L112

I'll look into 1 and 2 tomorrow.

**Comment by mathiasbynens** [comment]
Even when the last attribute value ends with `/`, e.g. `/logo/`, we don’t need the quotes. No browser would parse `<img src=/logo/>` as if it was `<img src="/logo" />`.

Note that `/>` has no meaning in HTML. It is only relevant in XML documents.

**Comment by kangax** [comment]
@mathiasbynens hm, i just looked through older issues and actually the problem was that we were losing traling slash in url's (which results in extra redirect as far as I understand) — https://github.com/kangax/html-minifier/issues/91

So we could only remove quotes from url-containing attributes, although that's probably more difficult to determine than just if we're on the last attribute.

**Comment by 5lava** [comment]
> No browser would parse `<img src=/logo/>` as if it was `<img src="/logo" />"`

@mathiasbynens, turns out you're 99.996293% right :)
I added following line to my website:
`<img src=/fooooo/>`
and some time later found 701391 requests to `/fooooo/` and 26 requests to `/fooooo`.

List of user-agents that requested `/fooooo` (without trailing slash):

```
Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) OPiOS/11.0.0.96155 Mobile/12H143 Safari/9537.53
Mozilla/5.0 (iPad; CPU OS 9_0_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) OPiOS/11.0.0.96155 Mobile/13A404 Safari/9537.53
Mozilla/5.0 (iPad; CPU OS 9_0_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) OPiOS/11.0.0.96155 Mobile/13A452 Safari/9537.53
Mozilla/5.0 (iPhone; CPU iPhone OS 9_0_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) OPiOS/11.0.0.96155 Mobile/13A452 Safari/9537.53
Mozilla/5.0 (Linux; Android 4.1.2; SPH-D710 Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; Android 4.2.2; AX610 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96244
Mozilla/5.0 (Linux; Android 4.4.2; BLU ADVANCE 4.0 L Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.107 Mobile Safari/537.36 OPR/29.0.1809.91837
Mozilla/5.0 (Linux; Android 4.4.2; SM-G7102 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; Android 5.0.1; SAMSUNG-SGH-I337 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; Android 5.0.1; VS985 4G Build/LRX21Y) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; Android 5.0.2; Blade S6 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; Android 5.0.2; STUDIO X PLUS Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; Android 5.0; BLU ENERGY X PLUS Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; Android 5.0; SM-G900F Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; Android 5.1.1; Build/LVY48F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; Android 5.1.1; Nexus 6 Build/LVY48F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Mobile Safari/537.36 OPR/32.0.1953.96473
Mozilla/5.0 (Linux; U; Android 4.4.2; zh-cn; GT-I9500 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.0 QQ-Manager Mobile Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:28.0) Gecko/20100101 Firefox/28.0 (FlipboardProxy/1.6; +http://flipboard.com/browserproxy)
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.42 Safari/537.36 OPR/33.0.1990.11 (Edition beta)
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.78 Safari/537.36 OPR/32.0.1953.96473
```

Mostly Opera.

**Comment by kangax** [comment]
@5lava may I ask which site you're using this on that you have 701391 requests? :)

**Comment by 5lava** [comment]
That one was smash.com, but please don't associate me the crap you're going to see — I DID NOT write that code. The new version of the website is coming soon :)
