### ISSUE TITLE
Cannot assign to read only property 'canCollapseWhitespace' of true

### ISSUE THREAD

**Issue by mizzle-mo** [kangax/html-minifier#419]
Downloaded it with a React starter kit this morning and the build worked.  As of 20 minutes ago with the message "Cannot assign to read only property 'canCollapseWhitespace' of true".

Still investigating.

**Comment by chicoxyzzy** [comment]
same issue on node 4.2 and html-webpack-plugin 1.6.0

**Comment by kangax** [comment]
Can someone make a small reproducible test case? Could it be related to whichever build tool is wrapping minifier?

**Comment by chicoxyzzy** [comment]
I've found what causes this issue https://github.com/ampedandwired/html-webpack-plugin/commit/909b811d70d0065a81fa36e173e99097b96f6c37

@MizzleMo you should pass options not `true` to minify value of html-webpack-plugin
