### ISSUE TITLE
maximum limit is 120 files

### ISSUE THREAD

**Issue by ovarunendra** [kangax/html-minifier#420]
I have more than 120 files in my folder, after 120 files its getting hanged.

**Comment by kangax** [comment]
How are you running it? (exact configuration)

**Comment by ovarunendra** [comment]
grunt configuration:

``` javascript
 grunt.initConfig({
   htmlmin: {                                     
            dist: {                                      
                options: {                                 
                    removeComments: true,
                    collapseWhitespace: true
                },
                files: [ {
                    expand: true,
                    cwd: 'src/',
                    src: ['**/*.html'],
                    dest: 'src/'
                }]
            }
        }
})

grunt.loadNpmTasks('grunt-contrib-htmlmin');
```

Inside src i have two folder each have more than 100 html files. when I run grunt htmlmin it compress first 120 files after that it got hanged.

**Comment by kangax** [comment]
Well, you should find what's causing the hang. Nothing we can do otherwise. When you find it, feel free to open an issue if it doesn't exist already.
