### ISSUE TITLE
Parse Errors on Ternary PHP Statements in HTML

### ISSUE THREAD

**Issue by grimmdude** [kangax/html-minifier#421]
Seems like there's a problem with parsing ternary php statements within HTML elements.  For example:

``` html
<a href="/legal.htm"<?php echo e(Request::path() == '/' ? ' rel="nofollow"':''); ?>>Legal Notices</a>
```

Thanks,

-Garrett

**Comment by aburi** [comment]
Similarly with:
`<img src="{% static "images/logo.png" %}">`

**Comment by kangax** [comment]
@aburi there's nested double quotes inside double quotes so how can we parse this? (not knowing that `{%` starts special context)

**Comment by aburi** [comment]
@kangax, would you be able to provide a short example of how to use `ignoreCustomFragments` to ignore `{{`, for example? I'm not sure where to place it in my Gruntfile.js. Thanks.

**Comment by kangax** [comment]
See here — https://github.com/kangax/html-minifier/commit/99823dfd1983502c84dfd2b0be0cde85a7cf17e6#diff-6041927ff3475da14e6a01e7dfdad8a9R874

**Comment by kangax** [comment]
For grunt you'll probably need to wait for grunt plugin to update

**Comment by aburi** [comment]
Thanks @kangax.

**Comment by grimmdude** [comment]
Thanks for that fix.  Will this be in a release soon?
