### ISSUE TITLE
angular2 bindings/attributes 

### ISSUE THREAD

**Issue by fxck** [kangax/html-minifier#422]
There's alot of stuff like this `<a [router-link]="['/Index']">Index</a>` or even `([some-thing])="asdf"` in angular2, and the minifier doesn't seem be to able to handle those..

![image](https://cloud.githubusercontent.com/assets/1303561/10636820/7411fa78-7802-11e5-9b60-244cdeb34c38.png)

.. and yes, it is valid html.

**Comment by kangax** [comment]
You can use `customAttrSurround` for this — https://github.com/kangax/html-minifier/blob/gh-pages/tests/minifier.js#L521-L537

**Comment by fxck** [comment]
Amazing thanks, but still, these are all valid attributes, it could by "on" by default.

**Comment by david-gang** [comment]
Update: I missed #289 

Hi @kangax 

I agree with @fxck 
Angular 2 will be a very popular framework.
Additionally according to http://stackoverflow.com/a/30863873/2343743 these attributes are valid.

**Comment by andreialecu** [comment]
Bump. I think this should be supported by default, and is a big problem when using `webpack` +`html-loader` with angular2.
