### ISSUE TITLE
customAttrSurround no working for {%....}

### ISSUE THREAD

**Issue by aburi** [kangax/html-minifier#424]
I spent the last couple hours trying to get **customAttrSurround** working to ignore DjangoCMS placeholders. 

_htmlminifier_ is choking on:
`<img src="{% static "images/logo.png" %}">`

... and produces this error:

```
➜  spiresystems git:(develop) ✗ grunt htmlmin
Running "htmlmin:dist" (htmlmin) task
Warning: src/templates/500.html
Parse Error: <img src="{% static "images/logo.png" %}">
```

_htmlmin_ options in Gruntfile.js look like:

```
options: {
    removeComments: true,
    collapseWhitespace: true,
    minifyJS: true,
    minifyCSS: true,
    customAttrSurround: [ [ /{%\s+/, /\s+%}/ ] ]
},
```

And the expressions for opening and closing check out on http://www.regexr.com/

Anyone able to help me here? Would be much appreciated.

**Comment by duncanbeevers** [comment]
`customAttrSurround` is used for markup surrounding attribute name-value pairs. In this case, the custom markup is entirely within the attribute value.

Your issue can be mitigated by using single-quotes rather than double-quotes for the `"images/logo.png"` portion of the attribute value.

Essentially, the parser is seeing this as a malformed chunk of markup, like `<img src="{% static "` without a closing bracket.

**Comment by aburi** [comment]
Thanks - that worked! So I don't even need to use the **customAttrSurround** option.

On a side note, I'm trying to target every html file in a certain directory:

```
files: {
    'dist/*.html' : 'src/*.html'
}
```

But it doesn't work properly, and instead creates a `*.html` file in the destination folder. 

Do you know how to fix this?

**Comment by duncanbeevers** [comment]
Sorry, build-system issues are a little out of my purview. You can probably programmatically generate that config to pair destination files with source files.

**Comment by aburi** [comment]
Understood. Thanks @duncanbeevers 

I'm getting parse errors again, and I assume I should be using **customAttrSurround** this time?

```
<p{% if form.name.errors %} class='error'{% endif %}>
      {{ form.name.label_tag }}
      {{ form.name }}
      {% if form.name.errors %}
      {% for error in form.name.errors %}
      <span class='error_msg' style='color:#ff0000'>{{ error }}</span>
      {% endfor %}
      {% endif %}
</p>
```

**Comment by duncanbeevers** [comment]
You need whitespace between the `<p` and `{%`.

**Comment by aburi** [comment]
@duncanbeevers, I tried adding a space prior to posting that, but I received the same parse error. I think it has something to do with having `{{` nested inside `{%`. I'm not sure how to deal what that, but I'll look into it. Thanks for the help!
