### ISSUE TITLE
HTMLLint not exposed for npm imports

### ISSUE THREAD

**Issue by nikgraf** [kangax/html-minifier#425]
I noticed in package.json you have this line:

```
  "main": "src/htmlminifier.js",
```

Unfortunately you don't expose HTMLLint there. Maybe I'm doing something wrong, but right now the only way to import the Linter is like this:

```
var HTMLLint = require('./node_modules/html-minifier/dist/htmlminifier.min.js').HTMLLint;
var lint = new HTMLLint();
```

What do you think about exporting the Linter as well there?

**Comment by kangax** [comment]
I think we can close this as duplicate of #80
