### ISSUE TITLE
enabled custom attribute is being collapsed

### ISSUE THREAD

**Issue by dciccale** [kangax/html-minifier#426]
i'm minifying a custom angular element which has a custom attribute `enabled` that is being collapsed by the minifier.

`<my-element enabled="someValue"></my-element>`

is being minified to

`<my-element enabled></my-element>`

and I actually need `someValue` to use it inside the directive.

correct me if i'm wrong but is the attribute `enabled` in the specs?

if it is not, then shouldn't be collapsed.

naming the attribute to `is-enabled` works

**Comment by kangax** [comment]
Yep, it's part of AudioTrackList — http://www.w3.org/TR/html51/single-page.html#audiotracklist — although we're not checking tag name. This is how it got in in the first place — https://github.com/kangax/html-minifier/issues/63#issuecomment-37763316

**Comment by dciccale** [comment]
ok, then i will just use a custom `is-enabled` attr. however a more powerful solution would be knowing the scope of the attribute to actually apply the minifying rule or not. this could mean a major change of course.

or i should stick to html conventions and check for the attribute presence instead of its value.

what are your thoughts?

**Comment by kangax** [comment]
Yes, we can be more strict, although we encourage valid markup so you'd need to write data-enabled. I'll keep this open as a potential feature and we'll see if anyone else runs into this or has any ideas.

**Comment by alexlamsl** [comment]
So as stated in https://github.com/kangax/html-minifier/issues/493#issuecomment-183624538, you can ~~ab~~use `ignoreCustomFragment` to ignore these attributes in your case.

**Comment by alexlamsl** [comment]
So I think we already support this through `ignoreCustomFragments`:

```
> minify('<my-element enabled="someValue"></my-element>', {
...   collapseBooleanAttributes:true
... });
'<my-element enabled></my-element>'

> minify('<my-element enabled="someValue"></my-element>', {
...   collapseBooleanAttributes:true,
...   ignoreCustomFragments: [/enabled=".*?"/]
... });
'<my-element enabled="someValue"></my-element>'
```
