### ISSUE TITLE
Wrong result with Processing Instructions

### ISSUE THREAD

**Issue by asabosch** [kangax/html-minifier#437]
We are using a template system based on processing instructions, because this works with most tools.
But html-minifier does some wrong parsing.

This template:

``` html
<div class="row">
  <?if $projects->count()!=0 ?>
  <p>
    <?if $instances->count()!=0 ?>
    <p>
    <!--show something-->
    </p>
    <?end ?>
  </p>
  <?end ?>
</div>
```

renders to:

``` html
<div class="row"><?if $projects->count()!=0 ?><p><?if $instances->count()!=0 ?></p><p><!--show something--></p><?end ?><?end ?></div>
```

with just --collapse-whitespace option. There is one closing /p tag moved to a wrong location.

**Comment by kangax** [comment]
Since this is not HTML (and minifier only works with HTML), you need to ignore `<?if`, etc. with conveniently-provided `ignoreCustomFragments` — https://github.com/kangax/html-minifier#options-quick-reference
