### ISSUE TITLE
&quot; problem when using minifyjs: true

### ISSUE THREAD

**Issue by julkue** [kangax/html-minifier#438]
An attribute like:

``` html
onclick="window.open('src/resources/pdfs/RC300_OM.pdf', '_blank')"
```

Will become:

``` html
onclick="window.open(&quot;resources/pdfs/RC300_OM.pdf&quot;,&quot;_blank&quot;)"
```

when using `minifyjs: true`.
It's very important for me to fix it since Browsers aren't able to handle such things. How can this be solved?

**Comment by julkue** [comment]
@kangax

**Comment by stevenvachon** [comment]
This happens with `minifycss:true` and `style="font-family: &quot;fontname&quot;"` as well

**Comment by alexlamsl** [comment]
Interim workaround may be `minifyjs:{quote_style:1}`

**Comment by julkue** [comment]
@alexlamsl Can you please explain what this does?

**Comment by alexlamsl** [comment]
As specified [here](https://github.com/mishoo/UglifyJS2/blob/master/README.md#beautifier-options), it tells `minifyjs` to use `'` for strings thus avoiding this `&quot;` issue.

**Comment by julkue** [comment]
ok thx so far

**Comment by alexlamsl** [comment]
The other workaround would be to set `preventAttributesEscaping` to `true`

**Comment by kangax** [comment]
This is now implemented!

**Comment by stevenvachon** [comment]
`style` attributes containing `&quot;` still don't work.
