### ISSUE TITLE
Odd results when using ignoreCustomFragments and <!-- htmlmin:ignore -->

### ISSUE THREAD

**Issue by nejsimon** [kangax/html-minifier#442]
Hello

I'm trying to minify a wordpress theme when deploying it to a server. I've added regex to ignore any `<?php ?>` blocks. Some tags open in one file and closes in another, such as the `<body>` tag in header.php and `</body>` in footer.php so I'm wrapping them in `<!-- htmlmin:ignore -->`. However this causes problems when a `<?php ?>` block is within the tag wrapped in `<!-- htmlmin:ignore -->`.

Input `<!-- htmlmin:ignore --><body <?php body_class(); ?>><!-- htmlmin:ignore -->`

Expected result `<body <?php body_class(); ?>>`.

Actual result `<body  htmlmin29190600104629993 >`

Testcase:

```
var minify = require('html-minifier').minify;
var result = minify('<!-- htmlmin:ignore --><body <?php body_class(); ?>><!-- htmlmin:ignore -->', {
    ignoreCustomFragments: [
        /<\?php((.|\r|\n)+?)\?>/gi,
    ],
});
console.log( result );
```

**Comment by kangax** [comment]
Looks like a bug; in the meantime you can use `ignoreCustomFragments`
