### ISSUE TITLE
improperly strips foreign element "/" closing characters by default 

### ISSUE THREAD

**Issue by bkimmel** [kangax/html-minifier#444]
For foreign elements like SVG, (especially &lt;stop&gt;, &lt;polygon&gt;, etc.) "/" characters are required to close the element (see: http://www.w3.org/TR/html5/syntax.html#start-tags #6). gulp-htmlmin strips them out by default, which results in invalid SVG that is not readable by the User Agent. Can be worked around by setting keepClosingSlash: true in options, but the default behavior does the "wrong thing" for embedded SVG (and I would assume other foreign elements like MathML as well.)

**Comment by kangax** [comment]
Well... minifier originally started as purely HTML-only, hence this (by default falsy) option. If this can be customized easily, is this really a problem? Or just a matter of principal? :)

**Comment by bkimmel** [comment]
In my experience as a user and fan of html-minifier it is both a "practical problem" (because embedded SVG is part of HTML in practice - and having it quietly butchered in a way that makes it not work is surprising) and a "matter of principle" (re: HTML5 spec).  I have used html-minifier (thank you for your hard work) a lot and given nothing back - so I'll volunteer to look at it and see if I can submit a PR to address the issue if that would be generally helpful...

Thanks.
