### ISSUE TITLE
customAttrAssign issues on Polymer

### ISSUE THREAD

**Issue by cpboyd** [kangax/html-minifier#447]
I've tried the following

``` javascript
  var optsHtml = {
    caseSensitive: true,
    customAttrAssign: [/\?=/],
    customAttrSurround: [
        [ /\{\{#if\s+\w+\}\}/, /\{\{\/if\}\}/ ],
        [ /\{\{#unless\s+\w+\}\}/, /\{\{\/unless\}\}/ ]
      ],
    collapseWhitespace: true,
    preserveLineBreaks: true,
    minifyCSS: true,
    // minifyJS: true,
    removeComments: true
  };
```

However, the `customAttrAssign` and `customAttrSurround` seem to be causing issues.

I copied the values directly from the minifier.js test code.  Any advice on what I may have done wrong?

This is the error that I'm getting:

``` javascript
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: <div id="checkbox" class$="[[_computeCheckboxClass(checked, invalid)]]">
        <div id="checkmark" class$="[[_computeCheckmarkClass(checked)]]"></div>
      </div>
    </div>
```

**Comment by cpboyd** [comment]
I added `/\$=/` to the customAttrAssign, but the resulting file from html-minifier ends up having the style$ value stripped.

e.g.
`<div id="drawer" style$="[[_computeDrawerStyle(drawerWidth)]]">` becomes:
`<div id="drawer" style$="">`

**Comment by KnowRe** [comment]
I have pretty much the same problem, and it seems like because `minifyCSS` option drops the content in `style` attribute.

Will there be any way to avoid template chunk (such as `{{foo}}` or `[[foo]]`) to be minified with `style` attribute?

**Comment by fgirardey** [comment]
I have the exact same error with Polymer Annotated attribute binding.

See : https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#attribute-binding

**Comment by alexlamsl** [comment]
@fgirardey taking the example from your link:

```
> minify(`
... <template>
...
...   <!-- Attribute binding -->
...   <my-element selected$="{{value}}"></my-element>
...   <!-- results in <my-element>.setAttribute('selected', this.value); -->
...
...   <!-- Property binding -->
...   <my-element selected="{{value}}"></my-element>
...   <!-- results in <my-element>.selected = this.value; -->
...
... </template>
... `, { customAttrAssign: [/\$=/], collapseWhitespace: true, removeAttributeQuotes: true, removeComments: true })

'<template><my-element selected$={{value}}></my-element><my-element selected={{value}}></my-element></template>'
```

Is that how you'd expect it to work?

**Comment by cpboyd** [comment]
@alexlamsl That's how I would expect it to work.  However, the issue seemed more to be with collapsing style attributes.

**Comment by alexlamsl** [comment]
@cpboyd `minifyCSS` uses `clean-css`, so I can't see an easy way to work around this rather than `minifyCSS:false`

They don't have any `data-style` or other alternative attribute names in Polymer for avoid name collision?

**Comment by cpboyd** [comment]
@alexlamsl Ah.  I see.

Thanks for the advice.

**Comment by cpboyd** [comment]
@alexlamsl As an aside: gulp-minify-inline allows a cssSelector.
Specifying `style[is!="custom-style"]` allows it to ignore the Polymer-specific CSS and apply to the rest.
