### ISSUE TITLE
Do not strip boolean attributes

### ISSUE THREAD

**Issue by matthieusieben** [kangax/html-minifier#448]
[kangax/html-minifier](kangax/html-minifier) has a lot of dependents. One of which is [grunt-angular-templates](https://www.npmjs.com/package/grunt-angular-templates). In angular, you can define directives which allow you to use HTML attributes whose value must be eval'd.

I recently used the `open` attribute in an angular directive which, as it turns out, is an HTML5 boolean attribute. Of course, when the html got minified, `isBooleanAttribute()` returned true and the instruction disappeared.

Wouldn't it be better to either:
- check that the value of boolean attributes is either empty or the same as the attribute before stripping the attribute value
- or check that the boolean attribute is used on the right element (in this case `<detail>`) before trying to modify the attribute value ?

**Comment by kangax** [comment]
Probably related to https://github.com/kangax/html-minifier/issues/426

**Comment by matthieusieben** [comment]
Indeed. This issue can be closed unless you want to keep track of the propositions I made.
