### ISSUE TITLE
Fails to close self-closing div tag

### ISSUE THREAD

**Issue by DukeyToo** [kangax/html-minifier#449]
While `div` is not strictly supposed to be a self-closing tag, it is common in my angularjs to have a div like this:

```
<div ng-include="mytemplate.html" />
```

When expanded with the template, it will be a fully formed `div` tag, but at compile-time the closing tag is ignored by htmlmin and it becomes

```
<div ng-include="mytemplate.html">
```

...which breaks the structure of the html.

**Comment by kangax** [comment]
> While div is not strictly supposed to be a self-closing tag

div is never supposed to be a self-closing tag — https://html.spec.whatwg.org/#the-div-element
