### ISSUE TITLE
Parse error when a template code is inside a tag

### ISSUE THREAD

**Issue by manuel-di-iorio** [kangax/html-minifier#450]
This html code will give `Parse error`, even with the setting `removeIgnored` set to `true`:

```
<option name="en" <? mycode ?> >Option</option>
```

Is there a way to fix?

**Comment by kangax** [comment]
I don't think we have `removeIgnored` option. Use https://github.com/kangax/html-minifier/blob/gh-pages/tests/minifier.js#L859 instead

**Comment by manuel-di-iorio** [comment]
`I don't think we have removeIgnored option`
:rabbit: Joking? It's in your readme reference and in the code

Btw `ignoreCustomFragments` works great, thanks. You should update the readme :)

**Comment by kangax** [comment]
Oh, `removeIgnored` is deprecated. It's not in the tests and not in the code. I'll remove it from docs.
