### ISSUE TITLE
Vulnerability in dependency uglify-js

### ISSUE THREAD

**Issue by absolute-quantum** [kangax/html-minifier#451]
I ran a NSP check on my project while using html-minifier as a dep in my package.json, and was confronted with the following results:

![2015-12-24_16-35-19](https://cloud.githubusercontent.com/assets/1427870/11996066/70f95980-aa5c-11e5-9917-72b162a13aa8.png)

Link to the nodesecurity post: https://nodesecurity.io/advisories/48

Could you please update uglify-js to at least version 2.6.0?

**Comment by kangax** [comment]
cc @XhmikosR

**Comment by XhmikosR** [comment]
It's already the latest since it's using `2.6.x` but I will update everything else.

**Comment by XhmikosR** [comment]
Note @kangax you will need to make a new release for this to be picked up.

**Comment by XhmikosR** [comment]
https://github.com/kangax/html-minifier/commit/ebb0b3df3ae675d2d881ec0775a14c8cd03aa455

**Comment by kangax** [comment]
Thanks! Published.
