### ISSUE TITLE
Error when reading from STDIN

### ISSUE THREAD

**Issue by menelaos** [kangax/html-minifier#458]
As of `1.1.1`, there seems to be a problem reading from `STDIN`:

```
cat file.html | html-minifier
```

yields

```
ERROR: Cannot write to output
```

Works fine in `1.0.0`.

**Comment by liamcurry** [comment]
I'm getting the same error from a fresh NPM install. Installing `1.0.0` fixed it for me.

**Comment by jawj** [comment]
Same here.

**Comment by alexlamsl** [comment]
This is same as #459, which is now [fixed](https://github.com/kangax/html-minifier/commit/1c670d761051949cb87b7b1d8dd6cce3fa914fad)
