### ISSUE TITLE
Hyphenated tag names producing incorrect output

### ISSUE THREAD

**Issue by stephenplusplus** [kangax/html-minifier#46]
From: https://github.com/yeoman/yeoman/issues/1010

It seems using a custom hyphenated tag name will return strange markup.

I ran a test:

```
Actual value:
<custom -directive="">Testing 1, 2, 3.</custom>
Expected value:
<custom-directive>Testing 1, 2, 3.</custom-directive>
```

**Comment by kangax** [comment]
This is invalid HTML so [parser](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlparser.js) doesn't know how to handle it. Need to add support for custom directives to make this work. Perhaps API of some sort to register tag name. Feel free to experiment.

**Comment by stephenplusplus** [comment]
Ah, I see. I wasn't sure if custom markup was intended to be supported. And it added to my confusion when running the test in the browser, the output was fine, but from Node, it failed. With Angular gaining momentum, and web components coming, there are an increasing number of devs who would stand to gain from html-minifier supporting these custom elements. I'll see if I have some time this weekend to play around!

**Comment by grEvenX** [comment]
Fix proposed in https://github.com/kangax/html-minifier/pull/50

**Comment by kangax** [comment]
This is now fixed
