### ISSUE TITLE
Incorrect meta viewport optimization

### ISSUE THREAD

**Issue by iver56** [kangax/html-minifier#463]
``` html
<meta name="viewport" content="initial-scale=1.0001, minimum-scale=1.0001, maximum-scale=1.0001, user-scalable=no"/>
```

becomes

``` html
<meta name="viewport" content="initial-scale=1001,minimum-scale=1001,maximum-scale=1001,user-scalable=no">
```

which is incorrect. The output should have `1.0001`, not `1001`

https://github.com/kangax/html-minifier/commit/3c9389a805199280756dd82bbc1e6f460f71062e is probably the culprit

**Comment by kangax** [comment]
Ah, we need to replace it with something like /^1.0*$/
