### ISSUE TITLE
Parse error on <!DOCTYPE ... 

### ISSUE THREAD

**Issue by tarraq** [kangax/html-minifier#465]
I'm experiencing parsing errors on the doctype definition of a HTML email (but the minification is done before the HTML knows it will end up an email).

Tag is:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
```

The Exception given in the catch(e) is:

```
Parse Error: 
< htmlmin6571564904823772 
! htmlmin6571564904823772 
D htmlmin6571564904823772 
O htmlmin6571564904823772 
C htmlmin6571564904823772 
T htmlmin6571564904823772 
Y htmlmin6571564904823772 
P htmlmin6571564904823772 
E htmlmin6571564904823772 
  htmlmin6571564904823772 
h htmlmin6571564904823772 
t htmlmin6571564904823772 
m htmlmin6571564904823772 
l htmlmin6571564904823772 
  htmlmin6571564904823772 
P htmlmin6571564904823772 
U htmlmin6571564904823772 
B htmlmin6571564904823772 
L htmlmin6571564904823772 
...
```

The error continues for all of the characters in the tag.

Is there a way to ignore doctypes entirely? 

Memory constraints on the platform means that I have to run the minification on a line by like basis. While I realise this isn't as effective as all in one go, that is a necessity at the moment. 
Does the parser require a full tree to parse, and then that can be the issue?

**Comment by kangax** [comment]
Yeah, parser requires full tree — https://github.com/kangax/html-minifier#working-with-invalid-markup — so unfortunately line by line won't work.
