### ISSUE TITLE
Processing directories stops after the first file is minified in CLI

### ISSUE THREAD

**Issue by scriptype** [kangax/html-minifier#469]
Hello, it seems this change (moving [this line](https://github.com/kangax/html-minifier/blob/gh-pages/cli.js#L192) around) just broke the recursive processing.

I'm using html-minifier in this way:

```
html-minifier --input-dir src/pages --output-dir dist
```

It just stops after succesfully minifying the first file encountered in `src/pages`.

I made a little debugging and found that doing `cli.exit(status)` in `runMinify` function causes the early exit. `runMinify` is being called from a forEach loop in `processDirectory` where it's looping through the list of files in the given directory.

**Comment by Nogbit** [comment]
I'm having the same problem, just spent way too much time thinking I was doing something wrong.  Not doing that again.  I will always assume it's someone elses fault first.  ;-)

Also, it's really [this line](https://github.com/kangax/html-minifier/blob/gh-pages/cli.js#L225) which then fires the [cli.exit](https://github.com/kangax/html-minifier/blob/gh-pages/cli.js#L194).  (as @scriptype  already mentioned)

**Comment by kawazoe** [comment]
I am still experiencing a similar issue with the latest 1.2.0 release. But instead of stopping after the first file, it stops after the first folder. For instance, the following structure will only generate the two files in the deepest 'Bar' folder.
- Root/
  - a.html
  - Foo/
    - b.html
    - Bar/
      - c.html
      - d.html

**Comment by alexlamsl** [comment]
@kawazoe can you open a separate issue for this?

**Comment by kawazoe** [comment]
I have just created #532 to cover this issue
