### ISSUE TITLE
something wrong with span?

### ISSUE THREAD

**Issue by davidagraf** [kangax/html-minifier#47]
When minifying

```
<span class="something"><div>test</div></span>
```

I get the result

```
<span class=something></span><div>test</div>
```

I tested it today with http://kangax.github.io/html-minifier/

**Comment by kangax** [comment]
This is invalid html. Span can not have block element like div in it.

**Comment by davidagraf** [comment]
Christ, I do not seem to know html! Sorry for bothering you!

**Comment by kangax** [comment]
No problem. Just watch out because browsers will do the same thing — automatically close span when encountering div inside. I ran into these issues in the past in some of the client code. Always hard to track and causes subtle but nasty issues.
