### ISSUE TITLE
&quot; problem when using minifycss: true

### ISSUE THREAD

**Issue by stevenvachon** [kangax/html-minifier#472]
Similar to #438

``` html
<tag style="font-family: &quot;fontname&quot;; width:100%">
```

becomes

``` html
<tag style="font-family:&quot;width:100%">
```

**Comment by alexlamsl** [comment]
I think the general solution to this and #373 would be to unescape these HTML entity characters before feeding them to minify{css,js}?

**Comment by stevenvachon** [comment]
Perhaps [postcss](https://npmjs.com/postcss)'s powerful parser can handle it, and accurately. If so, we could switch from cleancss to [cssnano](https://npmjs.com/cssnano).

**Comment by gheoan** [comment]
+1 for `cssnano`

**Comment by kangax** [comment]
I love PostCSS too (had great success with it) so I'm all for it.
