### ISSUE TITLE
Inline-CSS, background-style not minified

### ISSUE THREAD

**Issue by Keenora** [kangax/html-minifier#475]
I pushed my site through the minifier again and found out, that background styles within an inline css is not minified. For example:

`background:#222 url(css/images/resp-back-1440.jpg) fixed no-repeat`

Can be minified right after the URL of the image and the fixed to:

`background:#222 url(css/images/resp-back-1440.jpg)fixed no-repeat`

**Comment by alexlamsl** [comment]
I think you should report this to [clean-css](https://github.com/jakubpawlowicz/clean-css), which actually performs the minification of CSS here.

**Comment by alexlamsl** [comment]
In fact, they already seem to have this implemented/disabled:
https://github.com/jakubpawlowicz/clean-css/issues/497
https://github.com/jakubpawlowicz/clean-css/issues/555

So you should probably follow up there.

**Comment by Keenora** [comment]
Oh, I got it. Well, they want to stay as compatible as possible. Totally get that :) Thanks!
