### ISSUE TITLE
Issue with Vue.js / `@` attributes

### ISSUE THREAD

**Issue by SteveEdson** [kangax/html-minifier#479]
[Vue.js](http://vuejs.org/) features event shorthand properties like so:

```
<!-- same as above -->
<input v-on:keyup.enter="submit">

<!-- also works for shorthand -->
<input @keyup.enter="submit">
```

The `@` part of this currently raises a `Parse Error`.

Is it possible to allow exceptions / ignore invalid HTML? 

Thanks.

**Comment by alexlamsl** [comment]
You can handle this with `customAttrSurround`:

```
> minify('<input @keyup.enter="submit"/>', {customAttrSurround:[[/@/,/(?:)/]])
'input @keyup.enter=submit>'
```

**Comment by SteveEdson** [comment]
Thanks, works great.
