### ISSUE TITLE
Error when piping from STDIN

### ISSUE THREAD

**Issue by peterbraden** [kangax/html-minifier#483]
```
echo foo | ./node_modules/html-minifier/cli.js
undefined
ERROR: Cannot write to output
```

Works when specifying an input file. Doesn't work with a specified -o output. This worked until recently.

Thanks!

**Comment by alexlamsl** [comment]
Seems to work on latest Node.js on Windows:

```
html-minifier>echo foo | node cli
foo
```

Which OS & Node.js are you running?

**Comment by alexlamsl** [comment]
This is the same with #459, which is now [fixed](https://github.com/kangax/html-minifier/commit/1c670d761051949cb87b7b1d8dd6cce3fa914fad)

**Comment by kangax** [comment]
@alexlamsl I added you as a repo collaborator so feel free to close issues that you definitely know are fixed!

**Comment by alexlamsl** [comment]
@kangax :ok_hand:

**Comment by peterbraden** [comment]
Thanks!
