### ISSUE TITLE
strip whitespace between elements within <head>

### ISSUE THREAD

**Issue by stevenvachon** [kangax/html-minifier#486]
https://github.com/kangax/html-minifier/blob/v1.1.1/tests/minifier.js#L1137-L1148

`<head>` is not rendered, so the above test has inefficient output when `preserveLineBreaks` is `false`.

**Comment by alexlamsl** [comment]
According to https://github.com/kangax/html-minifier/pull/246#issue-41099287, `preserveLineBreaks` was added to aid readability of minified source code.

So I can't see why `<head>` should be treated differently.

**Comment by stevenvachon** [comment]
The issue is present with `preserveLineBreaks=false` and `conservativeCollapse=true`.

**Comment by alexlamsl** [comment]
I see - your quoted test case was for `preserveLineBreaks`, so that confused me.

**Comment by stevenvachon** [comment]
Yeah, I hadn't noticed that and had to recheck my findings. Unfortunately, they remained.

**Comment by alexlamsl** [comment]
So thinking about it some more, I think `conservativeCollapse` should stay as it is, since there are people who do [weird things](https://mathiasbynens.be/demo/css-hidden-elements).

It's not like the normal `collapseWhitespace` is keeping any spaces within `<head>` anyway.

**Comment by stevenvachon** [comment]
I'm pretty sure that link doesn't exist for practical reasons.

**Comment by alexlamsl** [comment]
`conservativeCollapse` serves as the safety switch when `collapseWhitespace` gets too aggressive.

So we should strive to improve `collapseWhitespace` instead, which a few recent PRs did, and leave `conservativeCollapse` for special use cases.
