### ISSUE TITLE
ignoreCustomFragments: <%tag%>

### ISSUE THREAD

**Issue by nosovk** [kangax/html-minifier#489]
Hello!
I use your template for building SendGrid templates.
There is <% text %> wrapper for their special tags (like <%asm_group_unsubscribe_url%> )
But somehow gulp build fails in that tag. I know that it's invalid, that's why I try to add ignore regexp to html parser.

[projects/gulpCommonTasks/tasks/inliner.js](https://github.com/dudeonthehorse/Email/blob/dev/gulpCommonTasks/tasks/inliner.js)
.pipe(htmlmin({collapseWhitespace: true, minifyCSS: true, ignoreCustomFragments:"/<\%[\sa-z_]+\%>/ig"}))

but htmlmin still try to minify that tag and fails.
Any ideas how to fix that?

**Comment by alexlamsl** [comment]
`minify()` handles `<% %>` natively, so no need to use `ignoreCustomFragments`:

```
> minify('<div> blah <%asm_group_unsubscribe_url%> </div>', { collapseWhitespace: true });
'<div>blah<%asm_group_unsubscribe_url%></div>'
```

Works as expected for me - what particular HTML code are you trying which is failing for you?

**Comment by alexlamsl** [comment]
With `master` rather than `1.1.1` on `npm` this gives:

```
> minify('<div> blah <%asm_group_unsubscribe_url%> </div>', { collapseWhitespace: true });
'<div>blah <%asm_group_unsubscribe_url%></div>'
```

(Note the extra whitespace after `blah`.) Is this the desirable behaviour you are looking for?

**Comment by alexlamsl** [comment]
@nosovk can you provide a more concrete example for the failure?

**Comment by alexlamsl** [comment]
@nosovk I believe the issue is resolved, but do re-open this issue if that is not the case.
