### ISSUE TITLE
<template> type tags and contents aren't minified

### ISSUE THREAD

**Issue by ArktekniK** [kangax/html-minifier#490]
I had a look through closed and open issues but couldn't see this problem.

I'm using include directives (http://www.html5rocks.com/en/tutorials/webcomponents/imports/) and HTML template tag (https://developer.mozilla.org/en/docs/Web/HTML/Element/template) and as such, I have many files with bare templates in them, within something like 

```
<template id="my-settings-template">
  <div>
    etc etc
  </div>
</template>
<script>
  // Script to register the template with the browser as a custom element
</script>
```

It appears that only the js is getting minified! Everything within template tags is ignored

**Comment by alexlamsl** [comment]
Looks pretty minified to me:

```
> minify(`
... <template id="my-settings-template">
...   <div class="form-group">
...     <label for="name">Name</label>
...     <input class="form-control" required/>
...   </div>
...   <button type="submit">Submit</button>
... </template>
... <script>
...   // Script to register the template with the browser as a custom element
...   alert(1 + 3);
... </script>
... `, { collapseWhitespace: true, removeAttributeQuotes: true, minifyJS: true });
'<template id=my-settings-template><div class=form-group><label for=name>Name</label><input class=form-control required></div><button type=submit>Submit</button></template><script>alert(4)</script>'
```

Did you have a specific example and output you are expected to see?

**Comment by alexlamsl** [comment]
@ArktekniK can you provide a more concrete example for your issue?

**Comment by ArktekniK** [comment]
Hey sorry it looks like I had a syntax error that was caused by a custom formatter. Passing the template works as expected. 

Sorry my mistake

**Comment by alexlamsl** [comment]
No worries - glad it's settled :wink:
