### ISSUE TITLE
json/ld in <script>

### ISSUE THREAD

**Issue by JamesJosephFinn** [kangax/html-minifier#492]
Hello! Thanks for the great tool. This is a feature request.

Like lots of folks, I have json/ld seo microdata inside a `<script>` tag. The `minifyJS` switch is turned on, but no go. This is because uglifyJS does not minify json. Should I file the request with them, or do you think you could integrate a json minifier?

Thanks!

**Comment by alexlamsl** [comment]
https://github.com/kangax/html-minifier relies fully on https://github.com/mishoo/UglifyJS2 for that part of minification. So it may be more fruitful requesting support for your format in question over there?

**Comment by JamesJosephFinn** [comment]
Understood. Thanks.
