### ISSUE TITLE
Suggestion: style tag/attribute selector for Polymer

### ISSUE THREAD

**Issue by cpboyd** [kangax/html-minifier#493]
As mentioned in https://github.com/kangax/html-minifier/issues/447#issuecomment-183512009, gulp-minify-inline allows a cssSelector.

clean-css breaks Polymer's CSS, so an easy work-around is to simply ignore any style tags that are marked `is="custom-style"`.

This allows you to still clean non-Polymer style tags.

**Comment by cpboyd** [comment]
Actually...

I just removed the cssSelector and css options from gulp-minify-inline and it somehow results in working CSS when the result from html-minifier doesn't look the same as with minifyCss disabled.

So the issue for polymer is more that the minifyCSS modifies the style attributes.  Style tags seem to be ok.

**Comment by alexlamsl** [comment]
Yes, both `style=...` as well as `<style>...</style>` are minified.

This is similar to #302 and #426, where others are using standard HTML tags with non-standard attribute values. So one workaround is to avoid the attribute name collision by `data-style` if supported, for instance.

**Comment by alexlamsl** [comment]
One way to achieve what you want is to utilise `ignoreCustomFragments`

```
> minify(`
...   <div id="drawer" style$="[[_computeDrawerStyle(drawerWidth)]]">
...     <span style="font: 12px bold">content</span>
...   </div>
... `, {
.....   customAttrAssign: [/\$=/],
.....   ignoreCustomFragments: [/style\$?="\[\[.*?\]\]"/],
.....   minifyCSS: true,
.....   collapseWhitespace: true
..... });

'<div id="drawer" style$="[[_computeDrawerStyle(drawerWidth)]]"><span style="font:12px 700">content</span></div>'
```

**Comment by alexlamsl** [comment]
So the above is for `style="..."` - for `<style>...</style>` you can simply use `<!-- htmlmin:ignore -->` to achieve what you described with `gulp-minify-inline`

Is there any other cases that I haven't covered yet?

**Comment by cpboyd** [comment]
That works, thanks.
