### ISSUE TITLE
merge <%...%> and <?...?> features into ignoreCustomFragments

### ISSUE THREAD

**Issue by alexlamsl** [kangax/html-minifier#495]
At the moment `<% %>` and `<? ?>` are handled by `htmlparser` as special cases.

But if we were to update the defaults of `ignoreCustomFragments`, we can remove this extraneous logic from the parser, with the added benefit of reducing associated corner cases in `handler.char()`, not to mention potential improvement in performance.

@kangax do you think it's worthwhile?

**Comment by kangax** [comment]
Definitely a good idea!
