### ISSUE TITLE
<noscript><p></noscript> is unclosed

### ISSUE THREAD

**Issue by KenSharp** [kangax/html-minifier#497]
The W3C validator complains that `<noscript>` tags are unclosed if the last "optional" `</p>` tags are dropped before the closing `</noscript>`. It doesn't complain in a `<div>`, however, so I'm not sure if this is actually a problem with the validator, or the final `</p>` should not be dropped.

Happy:
`<!DOCTYPE html><title>Blah</title><body>`
`<div><p>This is some text in a div</p></div>`
`<div><p>This is some more text in a div</div>`
`</body>`

Unhappy:
`<!DOCTYPE html><title>Blah</title><body>`
`<noscript><p>This some text in a noscript</p></noscript>`
`<noscript><p>This some more text in a noscript</noscript>¬
`</body>`

**Comment by KenSharp** [comment]
Actually:

> A p element's end tag may be omitted if the p element is immediately followed by an address, article, aside, blockquote, div, dl, fieldset, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, nav, ol, p, pre, section, table, or ul, element, or if there is no more content in the parent element and the parent element is not an a element.
> https://www.w3.org/TR/html5/syntax.html#optional-tags

I think that the minifier is correct, and the validator is incorrect. I'll open an issue with them.

I'll leave this open for now just so someone more experienced can confirm.

**Comment by alexlamsl** [comment]
Yeah, I guess the acid test is whether any real world browsers will blow up, probably in the form of whitespace damages.

Just to confirm, you tested with this repository rather than `1.1.1` from `npm`?

**Comment by alexlamsl** [comment]
Actually, looks like you are using the version from `npm` - here's what the latest `removeOptionalTags` would do:

```
> minify(`
... <!DOCTYPE html>
... <html>
...   <head>
...     <title>Blah</title>
...   </head>
...   <body>
...     <div><p>This is some text in a div</p></div>
...     <div><p>This is some more text in a div</p></div>
...   </body>
... </html>
... `, {
.....   collapseWhitespace: true,
.....   removeOptionalTags: true
..... });
'<!DOCTYPE html><title>Blah</title><div><p>This is some text in a div</div><div><p>This is some more text in a div</div>'

> minify(`
... <!DOCTYPE html>
... <html>
...   <head>
...     <title>Blah</title>
...   </head>
...   <body>
...     <noscript><p>This is some text in a noscript</p></noscript>
...     <noscript><p>This is some more text in a noscript</p></noscript>
...   </body>
... </html>
... `, {
.....   collapseWhitespace: true,
.....   removeOptionalTags: true
..... });
'<!DOCTYPE html><title>Blah</title><noscript><p>This is some text in a noscript</noscript><noscript><p>This is some more text in a noscript</noscript>'
```

But I guess W3C validator would probably choke on it all the same...

**Comment by alexlamsl** [comment]
Nasty... W3C Validator also chokes with the fact that `<body>` got omitted when `<noscript>` is used:

> A body element's start tag may be omitted if the element is empty, or if the first thing inside the body element is not a space character or a comment, except if the first thing inside the body element is a **meta**, **link**, **script**, **style**, or **template** element.

No mention of `<noscript>` either in the specification, though in reality `<noscript>` is [allowed](https://www.w3.org/TR/html5/scripting-1.html#the-noscript-element) to be inside `<head>` so logically I can't see how we can omit `<body>` safely here.

IOW, the tag omission rules seem to have forgotten all about `<noscript>`'s existence... :cold_sweat:

**Comment by alexlamsl** [comment]
Okay, so in the [Living Standard](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags) at least `</p>` got clarified:

> A p element's end tag may be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, section, table, or ul element, or if there is no more content in the parent element and the parent element is an HTML element that is not an a, audio, del, ins, map, **noscript**, or video element.

**Comment by KenSharp** [comment]
You worked it out without me. :-)

For reference I was using https://kangax.github.io/html-minifier/ . I think it's time I moved to the command line. Much easier.

**Comment by alexlamsl** [comment]
@KenSharp ah okay, I keep forgetting about the online page

The pending fix is at https://alexlamsl.github.io/html-minifier/ if you want to test/break it :wink:

**Comment by KenSharp** [comment]
All looks good here. Sorry for the slow response.

**Comment by alexlamsl** [comment]
Thanks for the testing!
