### ISSUE TITLE
IE Conditional Comments

### ISSUE THREAD

**Issue by alexlamsl** [kangax/html-minifier#499]
So far I have encountered these forms:

```
<!--[if cond]>content<![endif]-->
<![if cond]>content<![endif]>
<!--[if cond]>-->content<!--<![endif]-->
<!--[if cond]><!-->content<!--<![endif]-->
```

where `content` can contain incomplete HTML markups.

Looking at #157, #225 & #274 - I propose the following behaviour:
- consume `content` as part of the comment for all forms of conditional comments, not just the first
- attempt to minify `content` just as we do with `processScripts`, fallback if error

**Comment by alexlamsl** [comment]
Thinking about it some more, [Downlevel-revealed conditional comments](https://en.wikipedia.org/wiki/Conditional_comment#Downlevel-revealed_conditional_comment) are supposed to form part of the document without causing any parsing errors.

So my proposal is reduced to:
- minify `content` just as we do with `processScripts`, fallback if error
- fix `htmlparser` to allow for `content` to contain comments

**Comment by kangax** [comment]
I don't remember entire context of downlevel-revealed comments but I think what you're saying sounds reasonable.
