### ISSUE TITLE
Minifying html with empty body and removeOptionalTags crashes

### ISSUE THREAD

**Issue by Conduitry** [kangax/html-minifier#500]
Attempting to minify a document with an empty body, and with the removeOptionalTags flag set to true, crashes:

```
> require('html-minifier').minify('<body></body>', { removeOptionalTags: true })
RangeError: Invalid array length
    at removeEndTag ([...]/htmlminifier.js:792:21)
    at Object.minify ([...]/htmlminifier.js:1051:9)
[...]
```

The problem seems to be that `removeEndTag()` is called while `buffer` is an empty array. `index` gets set to -1, the loop gets bypassed, but then we try to set `buffer.length` to -1.

I noticed this issue appear in 1.2.0; it did not happen in 1.1.1.

**Comment by alexlamsl** [comment]
Thanks for reporting this - I have submitted a fix in #501
