### ISSUE TITLE
Removal of closing </p> tag breaks HTML

### ISSUE THREAD

**Issue by remcohaszing** [kangax/html-minifier#503]
I have the following snippet of HTML:

``` html
<md-list-item ui-sref=".app-config">
  <md-icon md-font-icon="mdi-settings"></md-icon>
  <p translate>Configure</p>
</md-list-item>
```

After minification using `html-minifier@1.2.0`, this changes into:

``` html
<md-list-item ui-sref=.app-config>
  <md-icon md-font-icon=mdi-settings></md-icon>
  <p translate>Configure
</md-list-item>
```

This behaves seamingly random in the browsers I've tested (Chrome and Firefox). Most definitely the minified version doesn't behave as its unminified counterpart.

When using `html-minifier@1.1.1` everything still worked just fine.

I did a quick research and I think 0574066 is the culprit. Apparently it isn't safe to remove the closing tag `</p>` here.

**Comment by alexlamsl** [comment]
AFAICT, `<md-list-item>` isn't part of HTML?

Anyway, you can switch off `removeOptionalTags` to avoid this issue when minifying general XML documents.

**Comment by remcohaszing** [comment]
It's an AngularJS directive (https://material.angularjs.org/latest/api/directive/mdListItem).

I think custom elements are part of HTML. Otherwise several popular frameworks, such as AngularJS wouldn't be HTML compatible.

I do wish to remove optional tags, such as `<head>` and `<body>`.

**Comment by alexlamsl** [comment]
From https://html.spec.whatwg.org/multipage/syntax.html#optional-tags

> A p element's end tag may be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, section, table, or ul element, or if there is no more content in the parent element and the parent element is an HTML element that is not an a, audio, del, ins, map, noscript, or video element.

So it certainly allows for removal of `</p>` if it's immediately followed by `</md-list-item>`. I have just tested by inspecting the DOM tree under IE11 and it adds `</p>` back as expected - what are those browsers you have mentioned behaved in this case?

**Comment by alexlamsl** [comment]
(I assumed you've also applied at least `collapseWhitespace:true` since `</p>` won't be removed otherwise)

**Comment by remcohaszing** [comment]
The `ui-sref` directive does add an `<a>` tag at runtime. I'd say this looks like a bug in AngularJS' HTML parser instead.

I'll investigate this further later today.

I have no clue how `collapseWhitespace` is related, but yes, I'm using it.

**Comment by alexlamsl** [comment]
Without `collapseWhitespace` in your example above, `</p>` would be immediately followed by whitespace instead of `</md-list-item>`, which prevents it from being removed.

Interesting that AngularJS parse the HTML directly instead of relying on the browser built-in functionalities. Thanks for looking into this!

**Comment by alexlamsl** [comment]
I have submitted a fix to make `removeOptionalTags` more conservative around non-HTML tags.

Please try the [online version](https://alexlamsl.github.io/html-minifier/) to see if this is working as expected. :wink:

**Comment by remcohaszing** [comment]
Thanks! That online version seems to work as expected.

I've created a simple example showing that browsers seem the cause for this issue, not AngularJS. I validated this by opening a file with the following contents and inspecting it using Firefox and Chrome.

``` html
<!doctype html>
<html ng-app="myApp">
  <body>
    <h2>Regular</h2>
    <div ng-include="'template.html'"></div>
    <h2>Minified</h2>
    <div ng-include="'minified.html'"></div>
    <h2>No closing tag</h2>
    <div ng-include="'minified-no-closing-p.html'"></div>
    <h2>Browser generated</h2>
    <div id="browser-generated"></div>
    <script type="text/ng-template" id="template.html">
      <custom>
        <p>Regular 1</p>
      </custom>
      <custom>
        <p>Regular 2</p>
      </custom>
      <custom>
        <p>Regular 3</p>
      </custom>
    </script>
    <script type="text/ng-template" id="minified.html">
      <custom><p>Minified 1</p></custom><custom><p>Minified 2</p></custom><custom><p>Minified 3</p></custom>
    </script>
    <script type="text/ng-template" id="minified-no-closing-p.html">
      <custom><p>Minified no closing p 1</custom><custom><p>Minified no closing p 2</custom><custom><p>Minified no closing p 3</custom>
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js"></script>
    <script>
      angular.module('myApp', []);
      document.getElementById('browser-generated').innerHTML = '<custom><p>Minified no closing p 1</custom><custom><p>Minified no closing p 2</custom><custom><p>Minified no closing p 3</custom>';
    </script>
  </body>
</html>
```

When all `custom` tags are replaced with `div`s, it seems to render fine. Thanks for fixing this so fast! :smile_cat:
