### ISSUE TITLE
Behaviour changed between 1.1.1 -> 1.2.0

### ISSUE THREAD

**Issue by stuht** [kangax/html-minifier#504]
Hi,

we had breaking builds due to implicit upgrade from 1.1.1 to 1.2.0 using the gulp-htmlmin plugin.

The following test case in _minifier.js_ works in 1.1.1 but fails due to an additional space in 1.2.0:

```
test('ignoring comments', function() {
    ...
    input = '<p>d</p>&nbsp;<!-- comment -->\n<span>s</span>';
    output = '<p>d</p>&nbsp;<span>s</span>';
    equal(minify(input, { removeComments: true, collapseWhitespace: true }), output);
}
```

Result in 1.2.0:

```
'<p>d</p>&nbsp; <span>s</span>'
```

I am not sure, which is the intended behaviour.

**Comment by alexlamsl** [comment]
If you swap `&nbsp;` for say `text`, then you should see why the whitespace needs to be preserved. The old behaviour would have caused rendering differences.

What I am not sure about is whether we should treat `&nbsp;` specially when dealing with text contents.

**Comment by alexlamsl** [comment]
Btw, I couldn't find your quoted test case in https://github.com/kangax/html-minifier/blob/gh-pages/tests/minifier.js - is there another file by the same name in your project?

**Comment by stuht** [comment]
Thanks for the clarification.

I only added the test case locally to verify the changed behaviour.
