### ISSUE TITLE
Minifier creates empty space after php tag

### ISSUE THREAD

**Issue by repdien** [kangax/html-minifier#505]
In case you use something like this-> class="post-<?php echo $post->id ?>", Minifier will create an empty space between - and php opening tag. As a result the styles are broken

**Comment by repdien** [comment]
ok I just saw it's fixed submitted in #501

**Comment by alexlamsl** [comment]
You can try the [online version](https://alexlamsl.github.io/html-minifier/) to see if your use case works as expected.
