### ISSUE TITLE
Inserting unnecessary space before <time> tag

### ISSUE THREAD

**Issue by faitno** [kangax/html-minifier#516]
I have issue with 

```
<div> <time datetime="2014-06-03 20:57:35"><time><div>
```

tag - it insert unnecessary space before it, but if I replace **time** to **span**, space before is disappears:

```
<div><span datetime="2014-06-03 20:57:35"><span><div>
```

**Comment by alexlamsl** [comment]
I just tried it [online](https://kangax.github.io/html-minifier/):

```
<div> <time datetime="2014-06-03 20:57:35"><time><div>
```

gives:

```
<div><time datetime="2014-06-03 20:57:35"><time><div></div></time></time></div>
```

i.e. no whitespace. What options did you use in your case?

**Comment by alexlamsl** [comment]
Trying with closing tags instead of all opening tags as with your example:

```
<div> <time datetime="2014-06-03 20:57:35"></time></div>
```

gives:

```
<div><time datetime="2014-06-03 20:57:35"></time></div>
```

as expected.

**Comment by alexlamsl** [comment]
@soulcreate please provide a test case which demonstrate the issue if this is still a problem for you.
