### ISSUE TITLE
Having a < in angular expression {{}} Crashes the plugin

### ISSUE THREAD

**Issue by trumbun** [kangax/html-minifier#529]
Hi, 
When having a < inside a angular express {{a.length < 3 ? ' Less than 3' : 'More than 2'}} inside the html the puling crashes. If that express is inside an attribute it works.

Changing the < to > in the expression works

**Comment by alexlamsl** [comment]
`<` instead normal text content is not standard HTML - use `&lt;` instead.

Alternatively, you can use `ignoreCustomFragments` on `{{...}}`.

**Comment by chrisnicola** [comment]
Oddly I'm getting this on something like this:

`<div>&lt;{{ email }}&gt;</div>`

In this case the angle brackets are outside and HTML encoded.

**Comment by trumbun** [comment]
Thanks I added the following command ignoreCustomFragments: [/{{.*?}}/]
