### ISSUE TITLE
Processing a tree of directories will only output files for the deepest one

### ISSUE THREAD

**Issue by kawazoe** [kangax/html-minifier#532]
When using the `--intput-dir` and `--output-dir` parameters to minify a complex folder structure, it stops processing after the deepest folder. For instance, the following structure will only generate the two files in the 'Bar' folder.
- Root/
  - a.html
  - Foo/
    - b.html
    - Bar/
      - c.html
      - d.html

**Comment by alexlamsl** [comment]
Thanks - I'll get a PR ready...
