### ISSUE TITLE
The AMP <html ⚡> syntax throws a parse error

### ISSUE THREAD

**Issue by daniellmb** [kangax/html-minifier#534]
Using the alternate `amp` ([Accelerated Mobile Pages](https://www.ampproject.org/docs/get_started/about-amp.html)) attribute works ok:

``` html
<html amp>
```

However, the lightning bolt syntax:

``` html
<html ⚡>
```

Throws a parsing error:

![screen shot 2016-03-03 at 4 58 41 pm](https://cloud.githubusercontent.com/assets/108018/13514845/42befa8e-e161-11e5-8459-728d4abcb2f4.png)

**Comment by alexlamsl** [comment]
That's because we only support basic characters as tag names and attributes - see #248 and #289
