### ISSUE TITLE
Minify CSS URLs

### ISSUE THREAD

**Issue by surrim** [kangax/html-minifier#535]
`minifyURLs` doesn't pay attention to the following snippet:

``` html
<style>
    html {
        background-image: url("http://example.com/images/background-1.jpg");
    }
</style>
```

That's because html-minifier calls clean-css for inline CSS and clean-css doesn't use relateurl.
A possible solution for that would be to replace the `url(...)`-parts with html-minifier directly.

**Comment by alexlamsl** [comment]
`clean-css` has its [own mechanisms](https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-api) for URL rewrites, namely `rebase`, `relativeTo` and `root`.

**Comment by alexlamsl** [comment]
In theory we can populate those fields I mentioned within `minifyCSS` when they are not specified by the user, and `minifyURLs.site` is defined.

@kangax @XhmikosR how do you feel about this?

**Comment by surrim** [comment]
Thanks for the cute patch, works fine here.

**Comment by alexlamsl** [comment]
Thanks for testing. :+1:
