### ISSUE TITLE
removeEmptyElements removes iframes

### ISSUE THREAD

**Issue by KenSharp** [kangax/html-minifier#536]
It would appear that when removeEmptyElements is set to true, "empty" iframes are removed.

```
<iframe src='bacon.html'></iframe>
```

I know that it technically appears empty, but it really isn't. The attributes maketh the iframe.

This isn't true of frames:

```
<frame src='bacon.html'></frame>
```

...becomes:

```
<frame src=bacon.html>
```

Making the iframe "non-empty" stops it from being stripped:

```
 <iframe src='bacon.html'>iframe therefore I am</iframe>
```

Poor iframes.

**Comment by alexlamsl** [comment]
On the bright side, I bet we've removed a lot of ads :smiling_imp:

**Comment by KenSharp** [comment]
I wondered why embedded YouTube videos kept going missing....

I'm new to Github, I didn't realise every little thing I do would be logged against this ticket. 😳 I need to RTFM.

**Comment by alexlamsl** [comment]
No harm for that - and thanks for taking care of it :+1:
