### ISSUE TITLE
wrong HTML element nesting after minification

### ISSUE THREAD

**Issue by mbarchein** [kangax/html-minifier#54]
Found a bug when minifying HTML with `<button>` inside a `<span>`

Input:

``` html
<span>
     <button>
         Hit me
     </button>
</span>
```

Output produced by html-minifier:

``` html
<span></span><button>Hit me</button>
```

Should be:

``` html
<span><button>Hit me</button></span>
```

Thanks.

**Comment by munsellj** [comment]
+1.  
Another Example:

```
<a>
  <p>Link</p>
</a>
```

Becomes:

```
<a></a><p>Link</p>
```

Instead of:

```
<a><p>Link</p></a>
```

I was assuming this was due to collapseWhitespace, but the same issue also occurs when only running removeComments.

**Comment by serrynaimo** [comment]
+1

**Comment by a-ursino** [comment]
+1

**Comment by josteing** [comment]
+1

**Comment by chrisdhanaraj** [comment]
+1, @Taritsyn fix works.
