### ISSUE TITLE
php tags space issue

### ISSUE THREAD

**Issue by sameh0** [kangax/html-minifier#545]
html-minifier injects a space i don't know why in the links of style 
this the original code 
`<div class="img" style='background: url("ww/ss/<?php echo $a?>-sml.jpg")no-repeat left  
`
and this is the minified one 
`<div class="img" style='background:url("ww/ss/ <?php echo $a?> -sml.jpg") no-repeat left`
as you see it injects space between`/ss/ and <?php` , this comes with the option `collapseWhitespace:true` don't know why ...

**Comment by alexlamsl** [comment]
Fixed in #509 - you can use the [online version](http://kangax.github.io/html-minifier/) to confirm.

**Comment by sameh0** [comment]
how to update the npm one ? 
i am using it with Gulp

**Comment by alexlamsl** [comment]
The fixed version is not published on `npm` yet - should be `1.3.0` by the time we do.

**Comment by sameh0** [comment]
can i install it from git and get it running with Gulp ?

**Comment by alexlamsl** [comment]
I'm not an expert with this sort of thing. Sorry. :sweat:
