### ISSUE TITLE
Rediculously slow on certain invalid input

### ISSUE THREAD

**Issue by futpib** [kangax/html-minifier#546]
Example:

``` sh
time node -e "require('html-minifier').minify('<foo bar=\"bazbazbazbazbazbazbaz\"')"
```

```
/node_modules/html-minifier/src/htmlparser.js:272
        throw 'Parse Error: ' + html;
        ^
Parse Error: <foo bar="bazbazbazbazbazbazbaz"

real    0m2.713s
user    0m2.662s
sys     0m0.015s
```

Adding just one more "baz" brings it down to 20 seconds before error on my system.

`node --trace ...` output suggests that execution of the following regular expression is what takes so long `^<([\w:-]+)((?:\s*[\w:\.-]+(?:\s*(?:(?:=))\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>`
Which leads us to [src/htmlparser.js#L108](https://github.com/kangax/html-minifier/blob/v1.2.0/src/htmlparser.js#L108)

**Comment by alexlamsl** [comment]
Fixed by #510 - you can verify it using the [online version](http://kangax.github.io/html-minifier/).
