### ISSUE TITLE
Changelog for 1.3.0

### ISSUE THREAD

**Issue by alexlamsl** [kangax/html-minifier#547]
Rather than spamming gitter, I guess I'll just update it here as we wait...
### Bug fixes
- messages cli.js (#498)
- extraneous whitespace inserted by `ignoreCustomFragments` (#502, #505, #506, #509, #513, #545, #552)
- `removeOptionalTags` on empty element crashes (#500, #508)
- `HTMLParser` halts on malformed markups (#177, #332, #507, #510, #512, #542)
- `removeComments` would give incorrect result if comment matches `ignoreCustomFragments` (#511, #515)
- `removeOptionalTags` too aggressive around non-HTML tags (#503, #514)
- incorrect `collapseWhitespace` within inline tags (#519)
- `removeTagWhitespace` does not work on the web (#528)
- `cli` cannot handle nested directories (#532, #533)
- `removeEmptyElements` always remove `<iframe>`, `<audo>` & `<video>` (#536, #538, #539)
- incorrect auto-closing of tags which permits phrasing content only (#541)
- extraneous whitespace inserted in attributes around custom fragments (#551, #553)
- `minifyJS` does not work the same way on the web (#531)
### Improvements
- minification of contents within conditional comments (#524)
- `collapseWhitespace` around comments and `removeEmptyElements` (#525)
- clean up `<script type="...">` (#521)
- support parsing of non-conventional attributes (#289, #534, #542)
- general performance (#520, #522)
- don't inject tags generated by HTML parser (#540)
- support parsing of non-standard tag names (#248, #543)
- migrate from `jscs` & `jshint` to `eslint` (#554)
- `grunt test` to cover browser tests (#537)

**Comment by kangax** [comment]
@alexlamsl this is suuuuper helpful! You're amazing, thanks :heart: I'll tag and push the release with this list once we finalize all the existing PR's

**Comment by alexlamsl** [comment]
IMHO we are good for `1.3.0` without #544:
- `benchmark.js` gives identical results before & after
- `clean-css` doesn't seem too enthusiastic about it

**Comment by kangax** [comment]
Perfect, I'll tag and release as soon as I can! Thanks for all your help again.

**Comment by alexlamsl** [comment]
Yay!

**Comment by kangax** [comment]
So what's on the menu for 1.4.0? :)

**Comment by alexlamsl** [comment]
About that... :smiling_imp:

**Comment by alexlamsl** [comment]
On a more serious note -  if you are planning on integrating `svgo` then at some point we'll need to change over to `minify(html, callback)`...

**Comment by kangax** [comment]
Yeah, perhaps... How about reordering of attributes for better gzip compression? That's one of the more interesting optimizations I can think of.

**Comment by alexlamsl** [comment]
Sounds like fun... let me sleep on that...

**Comment by yshterev** [comment]
Good job guys .. keep on the good work :smile:
