### ISSUE TITLE
Support for ie conditional operators

### ISSUE THREAD

**Issue by iamallyniam** [kangax/html-minifier#550]
An error occurs when using IE conditional operators such as '|'. The following code should validate as it states in this stackoverflow post http://stackoverflow.com/questions/16461970/ie-conditional-operator-or-if-is-greater-than-ie9-or-not-ie

```
<!--[if gte IE 9 | !IE ]><!-->
        <div class="hide">
            <svg>...</svg>
        </div>   
 <![endif]-->
```

Instead getting a parse error

`Parse Error: <![endif]-->`

**Comment by alexlamsl** [comment]
See [Wikipedia](https://en.wikipedia.org/wiki/Conditional_comment#Downlevel-revealed_conditional_comment), I believe you need `<!--<![endif]-->` to make this specific hack to work.

**Comment by iamallyniam** [comment]
Thank you, that worked perfectly.
