### ISSUE TITLE
White space added before opentag

### ISSUE THREAD

**Issue by quentinsup** [kangax/html-minifier#551]
I've upgraded the version of html-minifier from 1.0.0 to 1.2.0, and there is a new issue between this two version when using _collapseWhitespace_, and using jsp tag into attributes : 
`<div class="titi.<%=tsItem_[0]%>">` is now "minified" to `<div class="titi. <%=tsItem_[0]%> ">`(since 1.2.0), with whitespace added before _<%_ and after _%>_, which modify the interpretation of the class attribute in the IHM !

I tried the options _collapseInlineTagWhitespace_ and _removeTagWhitespace_, but always the same...

Please help !

**Comment by alexlamsl** [comment]
Confirmed - when `collapseWhitespace` is applied on attributes containing `ignoreCustomFragments` this would happen.
