### ISSUE TITLE
Closing </p> will be removed

### ISSUE THREAD

**Issue by julkue** [kangax/html-minifier#555]
Given input:

``` html
<p>Test</p>
```

**Expected:**

``` html
<p>Test</p>
```

**Actual:**

``` html
<p>Test
```

Caused by enabled option _Remove optional tags_

**Comment by alexlamsl** [comment]
Erm... [That is a Feature](https://github.com/kangax/html-minifier/blob/gh-pages/tests/minifier.js#L1039-L1042):tm:

**Comment by julkue** [comment]
@alexlamsl If so, why isn't it added here?
![info](https://cloud.githubusercontent.com/assets/8310677/13786900/04c90b7a-eada-11e5-9e4f-4fb1ce4801bf.png)

**Comment by alexlamsl** [comment]
Because the feature was enhanced but the docs didn't get updated.

Feel free to send in a PR for that :wink:

**Comment by alexlamsl** [comment]
Actually, where did you get that text from? The [link to the blog post](http://perfectionkills.com/experimenting-with-html-minifier/#remove_optional_tags) doesn't seem to contain the text in your image...

**Comment by julkue** [comment]
@alexlamsl from the [website](http://kangax.github.io/html-minifier/).
