### ISSUE TITLE
With the new release custom html code gets broken after minification

### ISSUE THREAD

**Issue by trombitas** [kangax/html-minifier#559]
I use html-minifier through [grunt-contrib-htmlmin](https://github.com/gruntjs/grunt-contrib-htmlmin) in a large project. Recently I observed that some existing code is breaking after minification:

```
<q r-center>
     <rf> ... </rf>
</q>
```

This is a html for my AngularJS application. The result of the minification is something like this:

```
<q r-center/>
<rf>..</rf>
```

Which is equivalent to this:

```
<q r-center></q>
<rf>..</rf>
```

Wich means the <rf> tag is pushed out from the Q tag. These tags are custom ones, there is no info regarding their type: block, inline, but the project does not need one. There are just tags.

Maybe this is an intended/normal behavior with this new version, and if so, I will need to get back to an earlier one or change the whole plugin.

**Comment by alexlamsl** [comment]
Assuming that `<rf>` isn't a standard HTML5 tag, you may be looking at #557 & #558?

**Comment by trombitas** [comment]
Yes, I used `<rf>` as an example for a non-standard HTML5 tag, but it could be any tag.

**Comment by alexlamsl** [comment]
In that case, please follow #557 and I shall close this duplicated issue.
