### ISSUE TITLE
Premature Closing Tag

### ISSUE THREAD

**Issue by willpracht** [kangax/html-minifier#560]
An issue we've run into recently with an upgrade from `v1.2.0` to `v1.3.0`:

This template:

``` html
<span><my-angular-directive></my-angular-directive></span>
```

...becomes...

``` html
<span></span><my-angular-directive></my-angular-directive></span>
```

I'm wondering if this has something to do with the regex changes between `v1.2.0` and `v1.3.0`.

**Comment by alexlamsl** [comment]
Duplicate of #557 - please follow that issue.

**Comment by willpracht** [comment]
Ah, my bad :). Thanks!
