### ISSUE TITLE
html code broken with version 1.3.0

### ISSUE THREAD

**Issue by jgermade** [kangax/html-minifier#565]
since I've update to 1.3.0, my code is broken

finally I realized that it's happening at least with label tags

if you try this code in http://kangax.github.com/html-minifier/

``` html
<label class="input-wrapper">
    <div class="text-label"></div>
</label>
```

you will get this code:

``` html
<label class=input-wrapper></label><div class=text-label></div>
```

instead of:

``` html
<label class=input-wrapper><div class=text-label></div></label>
```

**Comment by alexlamsl** [comment]
~~If you put your example code into IE11/Chrome and inspect the DOM, you'll see it inserts `</label>` exactly as we do here. It would help a lot if you can show me some examples where browsers don't do that so we narrow the conditions down.~~ Looks like `<div>` is special even if it's [not listed](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) as phrasing content, at least on IE11.

@kangax so I've got this narrowed down to the following events:
- `html5:false` has always been closing inline tags since https://github.com/kangax/html-minifier/commit/30510e0147f015f747513ec79d29713e655f580f
- `html5:true` is now doing something similar due to phrasing content #541
- as `html5` defaults to `true`, we have almost never hit that first code path before :disappointed:

**Comment by alexlamsl** [comment]
http://stackoverflow.com/questions/18609554/is-div-inside-label-block-correct

https://datatables.net/forums/discussion/26944/invalid-html-div-inside-label-causes-css-rendering-problems

https://bugzilla.mozilla.org/show_bug.cgi?id=431074

**Comment by dciccale** [comment]
My minification is also broken

original html

``` html
<span class="btn btn-zen-default btn-file" ng-class="{'disabled': isUploading}">
  <i class="zmdi zmdi-download"></i>
  <ng-transclude></ng-transclude>
  <input type="file" file-change="upload()" ng-model="file" name="file">
</span>
```

after minification with options

``` js
var htmlminOpts = {
  removeComments: true,
  collapseWhitespace: true,
  removeEmptyAttributes: false,
  collapseBooleanAttributes: true,
  removeRedundantAttributes: true
};
```

``` html
<span class="btn btn-zen-default btn-file" ng-class="{\'disabled\': isUploading}"><i class="zmdi zmdi-download"></i></span>
<ng-transclude></ng-transclude><input type="file" file-change="upload()" ng-model="file" name="file">
```

the `<ng-transclude>` tag renders outside the span along with the `<input>` tag and should be inside.

aren't both elements inline?

**Comment by sumitkm** [comment]
@dciccale I think you can't have stuff inside `span` but we have the same problem. I am trying the following setting, works for me, but I have very conservative minification, ymmv!

```
opts =
{
 ...
 includeAutoGeneratedTags: false
}
```

**Comment by dciccale** [comment]
the previous version was working (just to have in mind), I don't know what exactly changed now.

thanks @sumitkm will try it out.. and come back

**Comment by dciccale** [comment]
amazing @sumitkm it works! thanks so much

**Comment by sumitkm** [comment]
@dciccale glad it works, but please treat this as a workaround and proceed with caution. If the minifier was helping you close missing end tags, that fallback I believe is now gone. The sample you quoted, all tags are appropriately closed, that's the key assumption for this workaround.

**Comment by alexlamsl** [comment]
@dciccale your example is actually #557, which the fix is merged and can be tested [online](http://kangax.github.io/html-minifier/)

@sumitkm thanks for suggesting the workaround :wink:

**Comment by dciccale** [comment]
@alexlamsl merged doesn't mean published in this case right? :D

**Comment by alexlamsl** [comment]
@dciccale the online version will always have the latest version from the repository. The `npm` version would not be updated until the next `npm publish`, so if you rely on that then stay tuned :wink:

**Comment by sumitkm** [comment]
@alexlamsl the 'bugs' have been a 'blessing in disguise'. We had to 'fix' non-compliant html in a hurry :D. looking forward to the next npm publish.

**Comment by luxalpa** [comment]
"includeAutoGeneratedTags: false" doesn't work for me, it just removes the closing tags, making the result even weirder :(

**Comment by azamat-sharapov** [comment]
@SmaugTheGreat try latest `gh-pages` branch, it should work. I'm doing so, until next release.
