### ISSUE TITLE
Document that `removeTagWhitespace` will result in invalid HTML

### ISSUE THREAD

**Issue by XhmikosR** [kangax/html-minifier#570]
``` html
<span class="fa fa-file-text fa-fw"aria-hidden=true></span>
```

while it should be 

``` html
<span class="fa fa-file-text fa-fw" aria-hidden=true></span>
```

Using 1.3.0.

**Comment by XhmikosR** [comment]
`data-foo` is affected too.

**Comment by alexlamsl** [comment]
I've just tried the minified version under DOM Explorer (IE11) and it turns out okay. Is there a specific browser which is causing a problem?

**Comment by XhmikosR** [comment]
It's not valid HTML. But seriously, don't use IE as a development browser...

**Comment by alexlamsl** [comment]
Tried it on Chrome 49 and it works just as fine. (I've confined the other browsers on OSX, whilst I'm primarily a Windows user...)

Whilst I'd agree it's not strictly valid HTML, but this is implementing #2 and I did test that it doesn't cause any DOM mutations back then...

**Comment by XhmikosR** [comment]
I too am a Windows user, but it's self-destructive to use a browser that doesn't follow the specs most of the time :P

Anyway, back to this issue. If you view the page source with Firefox, you should see it complains about missing space between attributes. Or just use https://validator.w3.org/ and see for yourself :)

**Comment by XhmikosR** [comment]
One more

``` html
<html lang=en class=no-js prefix="og: http://ogp.me/ns#"itemscope itemtype=http://schema.org/WebPage>
```

**Comment by XhmikosR** [comment]
Oh, yet another one, `alt`

``` html
<img src=https://assets.mpc-hc.org/assets/img/cloudvps_small.a29313ea.png width=100 height=70 title="CloudVPS - Private Cloud, Clusters &amp; VPS"alt="CloudVPS logo">
```

**Comment by XhmikosR** [comment]
All right, so after discussing it with @alexlamsl it seems it's intended. But we should document that turning this on **will** result in invalid HTML.
