### ISSUE TITLE
v0.5.1 breaks grunt-contrib-htlmmin

### ISSUE THREAD

**Issue by kvervo** [kangax/html-minifier#58]
The new update breaks grunt-contrib-htmlmin. When trying to use grunt, it will crash with the following error:   

> Loading "htmlmin.js" tasks...ERROR
> Error: Cannot find module 'html-minifier'

The problem is package.json for the npm package. Line `"main": "./dist/all.js"` reference a path that does not exist in node_module html-minifier v0.5.1. Removing this line of code does fix the issue.

**Comment by clakech** [comment]
:+1: :scream:

**Comment by glassesmouse** [comment]
+1 Having the same issue with htmlmin task in grunt.

**Comment by kangax** [comment]
Should be fixed in 0.5.2
