### ISSUE TITLE
<a> with <code>

### ISSUE THREAD

**Issue by igoradamenko** [kangax/html-minifier#581]
Hello!

When I minify piece of code like this:

`<p><a href="#"><code>Code word</code></a> and other words</p>`

I am getting this:

`<p><a href="#"><code>Code word</code></a>and other words</p>`

Is it possible to keep space after closing anchor tag? 

I use Gulp plugin, v.1.3.0, settings:

`{
    removeComments: true,
    collapseWhitespace: true
}`

**Comment by igoradamenko** [comment]
Oops. Sorry about that. It seems like error in Gulp plugin (it depends on v.1.0.0 of html-minifier). I've tried to test this case in html-minifier directly and it works fine.

**Comment by alexlamsl** [comment]
@igoradamenko thanks for the confirmation :+1:

**Comment by igoradamenko** [comment]
No, guys, error exactly in `html-minifier`. Sorry about the confusion.

Let's define `inline element` as A, `block element` as B and `text with space in the start` as C. So if A contains B and C follows A then space in C is removed. I think it's wrong, you can see the example in OP of this issue.

I've created the PR with fix and tests for this. Please check this out: #583
