### ISSUE TITLE
version 1.3.0 change dom structure

### ISSUE THREAD

**Issue by zyf0330** [kangax/html-minifier#582]
I use version 1.3.0, and found this problem.

```
var minify = require('html-minifier').minify;
var result = minify('<label>'+
    '<input name="comment_school" type="radio" :value="true" v-model="is_good"/>'+
    '<div class="cg_btn">'+
    '<div class="cg_icon">'+
    '<div class="cg_pic" style="background-image: url(../images/jiaxiao1.png);"></div>'+
    '</div>'+
    '<div class="cg_text">'+
    '<span class="cg_word">aaa</span>'+
    '</div>'+
    '</div>'+
    '</label>', {
    removeAttributeQuotes: true
});
console.log(result);
```

This is result
`<label><input name=comment_school type=radio :value=true v-model=is_good></label><div class=cg_btn><div class=cg_icon><div class=cg_pic style="background-image: url(../images/jiaxiao1.png)"></div></div><div class=cg_text><span class=cg_word>aaa</span></div></div>`.
This doesn't occur at version 1.3.1, so the new version fixed it?

**Comment by zyf0330** [comment]
So if it is ,  you should add some text to tell people this.

**Comment by alexlamsl** [comment]
Read #576, or basically any number of issues that has been closed here.

**Comment by zyf0330** [comment]
I just didn't see something in "Releases".

**Comment by alexlamsl** [comment]
When you think you find a bug, it helps to:
- look if somebody else already reported it under [Issues](https://github.com/kangax/html-minifier/issues)
- test against latest version
