### ISSUE TITLE
Attribute value is removed using AngularJS OR condition syntax

### ISSUE THREAD

**Issue by huyph** [kangax/html-minifier#584]
I have this attribute: (where `||` is or condition in AngularJS)
`<element loading="vm.loadingData1 || vm.loadingData2 || vm.loadingData3"></element>'`

Running `htmlmin` turn that into `<element loading></element>`

Is this expected?. If it is, I guess I am using a bad standard here to combine multiple boolean condition.

Thanks

**Comment by alexlamsl** [comment]
What options did you use? I just tried it [online](http://kangax.github.io/html-minifier/) and it doesn't remove the attribute value...

**Comment by huyph** [comment]
Uhm. Perhaps 'collapseBooleanAttributes' is the cause here?

``` javascript
        options: {
          collapseWhitespace: true,
          conservativeCollapse: true,
          collapseBooleanAttributes: true,
          removeCommentsFromCDATA: true,
          removeOptionalTags: true
        },
```

**Comment by huyph** [comment]
i also found that it also strip in this case:
`loading="vm.loadingData1"` 

And i am using grunt-contrib-htmlmin v1.1.0

**Comment by alexlamsl** [comment]
Using `html-minifier` from npm (1.3.1):

```
> var minify = require("html-minifier").minify;
> minify('<element loading="vm.loadingData1 || vm.loadingData2 || vm.loadingData3"></element>', {
  collapseWhitespace: true,
  conservativeCollapse: true,
  collapseBooleanAttributes: true,
  removeCommentsFromCDATA: true,
  removeOptionalTags: true
});

'<element loading="vm.loadingData1 || vm.loadingData2 || vm.loadingData3"></element>'
```

So may be you need to check the version of `html-minifier` you have installed? I think `npm ls` would show that.

**Comment by alexlamsl** [comment]
`loading` is certainly not classified as boolean attribute over here, so `collapseBooleanAttributes` will not do anything to it.

I'll close this for now, but if you can demonstrate a test case using `html-minifier` where this is broken, feel free to reopen.

**Comment by huyph** [comment]
Actually the exact string is
`<element indeterminate="analyticsSearchersVm.topIPsIndeterminate || analyticsSearchersVm.topCountriesIndeterminate || analyticsSearchersVm.initialLoadAllDataForMapIndeterminate"/>`

This does replicate the issue in the online HTML minifier (http://kangax.github.io/html-minifier/)

**Comment by alexlamsl** [comment]
`indeterminate` is a standard HTML boolean attribute for use with `<input type="checkbox">`

So the solution is to either rename your custom attribute (`ng-indeterminate`?) or don't use `collapseBooleanAttributes`.

**Comment by huyph** [comment]
I see. 

So any reason why HTML mininifier does not do a check on whether the element is of type `<input type="checkbox">` ?

**Comment by alexlamsl** [comment]
Most likely due to simplicity of implementation.

You are more than welcome to improve :wink:

**Comment by huyph** [comment]
fair enough...will do once I get a chance :wink: 

Thanks for your time! Much appreciate !
