### ISSUE TITLE
whitespace not stripped around handlebars helpers

### ISSUE THREAD

**Issue by dwelle** [kangax/html-minifier#589]
HBS:

```
{{#if}}
{{/if}}
{{#if shareStatus}}
    <div></div>
{{/if}}
{{value}}
```

config:

```
collapseWhitespace         : true,
collapseInlineTagWhitespace: true,
```

output:

```
{{#if}} {{/if}} {{#if shareStatus}}<div></div>{{/if}} {{value}}
        \_______\                                   /
                 \_________ should strip __________/
```

**EDIT:**  if implemented, care should be taken not to collapse whitespace around HBS helpers inside tags, e.g. `<div class="{{#if a}}a{{/if}} {{#if b}}b{{/if}}"></div>`

version `1.3.1`

**Comment by dwelle** [comment]
Meanwhile, if I'm not missing some case, one can run this on the output:

```
html.replace( /<[\s\S]+?>|(\}\} \{\{)/g, (m, g1) => {
    return g1 ? "}}{{" : m;
});
```

**Comment by alexlamsl** [comment]
What you think are directives it's actually just plain-text to a HTML parser. Which means those whitespaces are significant.

If you want to have the most optimal minified output, try applying `html-minifier` after any server-side directive processing.

**Comment by dwelle** [comment]
It's not about optimization -- if those whitespaces remain, they break CSS (for `inline`/`inline-block` elements). I also can't run `html-minifier` on output, because we don't render on server-side. We minify the templates, precompile, send those templates to client, and render there.

And since `html-minifer` already supports options such as `customAttrAssign`/`customAttrSurround` to allow the plugin to recognize e.g. HBS syntax, I thought it's in the plugin's scope to [allow to] strip whitespace for block helpers.

**Comment by alexlamsl** [comment]
Question - does the document work client-side without passing through `html-minifier`?

I fail to see how line breaks would not break CSS whilst a space character would.

**Comment by dwelle** [comment]
Line breaks sure would as well. After minification, which turns the above into:

```
{{#if}} {{/if}} {{#if shareStatus}}<div></div>{{/if}} {{value}}
```

...we pipe it to `handlebars` to precompile, which parses the string into executable function. Problem is, it retains the HTML whitespace (outside of HBS helpers and other HBS syntax), and that's the problem.

There's been a lot of discussion about whitespace control over at [wycats/handlebars.js](https://github.com/wycats/handlebars.js), but the bottom line there is that handlebars doesn't deal with HTML semantics, thus it won't try to strip whitespace on its own.

So I thought the most likely candidate to tackle this is `html-minifier` since it already touches on non-HTML syntax.

**Comment by alexlamsl** [comment]
So if the original input works but the minified output breaks, I'd consider this a bug in `html-minifier`.

In this case, I believe there's not much we can do. After all, features like `ignoreCustomFragments` are here to workaround otherwise invalid HTML inputs, rather than just throwing parser errors. Best to leave `handlebars` etc. to handle their own expectations.

**Comment by dwelle** [comment]
Both the input _and_ the output breaks the CSS, that's why we're using `html-minifier` in the first place (because it removes at least some of the spaces).

`ignoreCustomFragments` won't help, because this introduces even more whitespace issues.

IMO (and in handlebars maintainers' opinion), the stripping of whitespace in HTML (even if there's HBS sprinkled among it), is best left for something that actually understands HTML (e.g. `html-minifier`).
