### ISSUE TITLE
please update uglify-js!

### ISSUE THREAD

**Issue by bonesoul** [kangax/html-minifier#598]
Check it using retire.js yourself!

```
↳ html-minifier 0.6.9
 ↳ uglify-js 2.4.24
uglify-js 2.4.24 has known vulnerabilities:  https://nodesecurity.io/advisories/48
```

**Comment by alexlamsl** [comment]
Check the version of [html-minifier](https://www.npmjs.com/package/html-minifier) yourself!

**Comment by bonesoul** [comment]
sorry express-beautifier uses and older version of this package, so i notified them now :) https://github.com/lackneets/express-beautify/issues/1

**Comment by alexlamsl** [comment]
This one seems to be more up-to-date: https://www.npmjs.com/package/express-minify-html

**Comment by bonesoul** [comment]
thanks :+1:
