### ISSUE TITLE
Use unquoted attribute values where possible

### ISSUE THREAD

**Issue by mathiasbynens** [kangax/html-minifier#60]
See http://mothereff.in/unquoted-attributes for a quick testing tool, or http://mathiasbynens.be/notes/unquoted-attribute-values for all the details + spec links.

The following code could be useful: https://github.com/mathiasbynens/mothereff.in/blob/59b0a78022549360f3d42f7ceb85999e94070887/unquoted-attributes/eff.js#L4-L6

**Comment by kangax** [comment]
Thanks @mathiasbynens. I have no time to tinker with this right now; will do when I get a chance. Pull request would be awesome, of course! :)

**Comment by mathiasbynens** [comment]
See #61 :) Easier than I had thought.
