### ISSUE TITLE
preventAttributesEscaping may output malformed HTML

### ISSUE THREAD

**Issue by FLamparski** [kangax/html-minifier#603]
I found this while dealing with a build process involving Polymer's Vulcanize and HTML Minifier. In short, given the following HTML:

```
<tag boolean-attribute path="/blah" />
```

Vulcanize may in some cases turn it into

```
<tag boolean-attribute="" path="/blah" />
```

And then after running this through the HTML Minifier, the following may be emitted if the `preventAttributesEscaping` flag is turned on:

```
<tag boolean-attribute= path="/blah">
```

Note the `boolean-attribute=` - this is malformed HTML, and for instance Chrome interprets it as something like `boolean-attribute="path='/blah'"`. Part of the blame is on Vulcanize outputting attributes with empty values for inputs with boolean attributes, but that's a separate bug.

**Comment by alexlamsl** [comment]
Thanks for the report - a fix is pending at #605
