### ISSUE TITLE
Improve benchmark

### ISSUE THREAD

**Issue by XhmikosR** [kangax/html-minifier#612]
I think we should retrieve the pages when running the benchmark so that we are up to date. If something fails when getting the page, we can just use the old one.

/CC @alexlamsl, just opened this so that we don't forget it :)

**Comment by alexlamsl** [comment]
Also it would be nice to update `README.md` so as to reduce some manual work.

**Comment by kangax** [comment]
I would also like to include Facebook in the results (I'll see if I can get a test user)

**Comment by alexlamsl** [comment]
@kangax they do have public-facing pages like https://www.facebook.com/DonaldTrump/

Anyway, my thinking is that I'll have `benchmark.js` scans through `benchmarks/index.json` to download the files, then proceed as it was from there.

**Comment by XhmikosR** [comment]
BTW @alexlamsl the links in index.json might not be up to date. I updated them in README.md some time ago and forgot about this.

**Comment by alexlamsl** [comment]
@XhmikosR I see - is `README.md` the most up to date information, or would you mind listing them all out in this issue?

**Comment by XhmikosR** [comment]
I think I updated all of them in README.md. Only http://kangax.github.io/compat-table/es6/ and https://github.com/kangax/html-minifier are left.

**Comment by alexlamsl** [comment]
Ouchies - MSN gives me this:

``` html
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE HTML PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.2//EN" "http://www.openmobilealliance.org/tech/DTD/xhtml-mobile12.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-HK" dir="ltr">
...
```

I've almost forgotten all about XHTML's existence :cold_sweat:

**Comment by XhmikosR** [comment]
We could remove that, and add something else. Maybe CNN BBC or something?

**Comment by alexlamsl** [comment]
`ignoreCustomFragments` by default should handle this, except I've overwritten it when running the benchmarks, so that's easily fixable.

This prompts me to think if `useShortDoctype` should get rid of that XML declaration...

**Comment by alexlamsl** [comment]
@XhmikosR I'll take up your offer and switch from MSN to CNN/BBC:

``` html
<div class="headlinebar">
 <p font-size:14px;"="" font-size:16px;"="" style="background:#009C15;color:white;padding-bottom:12px;margin-bottom:-12px;padding-top:10px;padding-left:16px;margin-top:-11px;margin-right:-16px;margin-left:-16px;">...</p>
</div>
```

**Comment by XhmikosR** [comment]
Cool, feel free to add those and normalize the URLs while at it :)
