### ISSUE TITLE
Whitespace shifting between inline tags

### ISSUE THREAD

**Issue by alexlamsl** [kangax/html-minifier#618]
Currently with `collapseWhitespace`

``` html
<a href="foo">
  <img src="bar">
</a>
<a href="baz">
  <img src="moo">
</a>
```

becomes

``` html
<a href="foo"><img src="bar"> </a><a href="baz"><img src="moo"> </a>
```

This is caused by an optimisation which observes

``` html
<a href=#a>
  a
</a>
<a href=#b>
  b
</a>
c
<a href=#d>
  d
</a>
```

to be rendered as `[u]a b [/u]c [u]d[/u]` which is consistent with

``` html
<a href="#a">a </a><a href="#b">b </a>c <a href="#d">d </a>
```

/cc @XhmikosR

**Comment by XhmikosR** [comment]
1.3.0
![1 3 0](https://cloud.githubusercontent.com/assets/349621/14404282/7dc09ef4-fe7a-11e5-8991-e3953651b044.png)

1.4.0
![1 4 0](https://cloud.githubusercontent.com/assets/349621/14404285/843f4ea6-fe7a-11e5-89ac-aac449388481.png)

No other change in code, just the space behavior change in html-minifier.

**Comment by XhmikosR** [comment]
So apparently, the behavior now is what it was before, in the original files.

**Comment by alexlamsl** [comment]
This commit changes/fixes the behaviour:
https://github.com/kangax/html-minifier/commit/b0dc2cb335ca4726f62b85ee53028d7b03e96252
