### ISSUE TITLE
Remove classes

### ISSUE THREAD

**Issue by ilovebeatles** [kangax/html-minifier#619]
Hello, you doing a great job with that task. Is there a way to delete all css classes from minify html?

**Comment by alexlamsl** [comment]
Can you elaborate on what you mean?

**Comment by ilovebeatles** [comment]
Sure. Something like this:
<div class="foo">bar</div> => <div>bar</div>

**Comment by ilovebeatles** [comment]
Sure. Something like this:

`<div class="foo">bar</div> => minify => <div>bar</div>`

**Comment by alexlamsl** [comment]
In that case it's a duplicate of #322 then. Please follow that issue.
