### ISSUE TITLE
Add support for parsing <?php ?>, <%= %>, etc. directives

### ISSUE THREAD

**Issue by ivanbreet** [kangax/html-minifier#62]
We are tying this into build processes for Drupal themes. Unfortunately we need the `<?php echo $user; ?>` etc for the templates.

Any way we can get this compatability?

**Comment by jonathan-fielding** [comment]
I second this, would be awesome if we had this feature

**Comment by johannesjo** [comment]
Yeah me too. Shouldn't be too hard to implement.

**Comment by pzi** [comment]
+1

**Comment by Shuky** [comment]
+1

**Comment by nancoder** [comment]
+1

**Comment by mhulse** [comment]
FYI, I'm trying to fix this. I have a discussion going in issue #10 if anyone want's to provide feedback.

**Comment by hutber** [comment]
Awesome :+1: Looking forward to when this is working :) Turning off for now.

**Comment by kangax** [comment]
This is now [fixed](https://github.com/kangax/html-minifier/commit/7f4f709da1b4a7747e9d1fe2a55035401cc24f79). Thanks @mhulse
