### ISSUE TITLE
How to use HTML Linting option?

### ISSUE THREAD

**Issue by karensg** [kangax/html-minifier#620]
The documentation is unclear about this. I assume I have to pass HTMLLint object, how do that for grunt?

**Comment by alexlamsl** [comment]
This is how you would do it via `minify()` directly (lint errors output to console):

```
var minify = require('html-minifier').minify;
var HTMLLint = require('html-minifier/src/htmllint').HTMLLint;
var lint = new HTMLLint();
var input = "...";
var output = minify(input, { lint: lint });
lint.populate();
```

Presumably you replace `minify()` with your call to the grunt plug-in.

You can also refer to https://github.com/kangax/html-minifier/blob/gh-pages/tests/lint.js#L32-L36

**Comment by karensg** [comment]
It did not integrate with my setup after all. So I switched to `grunt-html`. Thanks for your quick reply anyway.
