### ISSUE TITLE
Unclosed <p> tag causes no output at all

### ISSUE THREAD

**Issue by kornelski** [kangax/html-minifier#627]
``` html
<p>foo
```

gives 0 byte output if "Include auto-generated tags" option is off.

**Comment by alexlamsl** [comment]
This works:

```
> minify('<p>foo')
'<p>foo</p>'
> minify('<p>foo',{includeAutoGeneratedTags:false})
'<p>foo'
```

Can you give a more concrete example of this bug?

**Comment by kornelski** [comment]
I guess you've found it. For the record, I've reproduced these using default settings on https://kangax.github.io/html-minifier/

**Comment by alexlamsl** [comment]
@pornel yeah after a bit of digging - thanks for the report 😉
