### ISSUE TITLE
Feature Request: Support ignoring Mako templates.

### ISSUE THREAD

**Issue by sethmlarson** [kangax/html-minifier#637]
[Mako](http://www.makotemplates.org/)-styled templates are used by many different services and at the current time they produce an error.  Could there be an option to specify that the HTML being inserted may contain Mako tags and to have the minifier simply skip over them as opposed to having to surround every instance of a Mako tag with a minifer:ignore tag?

**Comment by alexlamsl** [comment]
Have you tried [ignoreCustomFragments](https://github.com/kangax/html-minifier/blob/gh-pages/README.md#options-quick-reference)?

Judging from the example on the front page, that should suffice.

**Comment by alexlamsl** [comment]
Closing. If you have a usecase not covered by existing options please reopen.
