### ISSUE TITLE
Future: Collapsing white-space

### ISSUE THREAD

**Issue by dalgard** [kangax/html-minifier#64]
Collapsing white-space is one of the most useful features of this library, in my opinion, since it actually makes my document smaller (mainly by removing indentation). I really like the considerations in the blog post about how to improve it, so I'm opening this issue to track how things are going.
## 

Replacing stretches of white-space with a single space character, like the browser does, is definitely a good idea, and I'd very much like to see it implemented.

Currently, my biggest issue, as one might imagine, is around phrasing (i.e. inline) content, so I also like the idea of being able to white-list certain elements, the contents of which won't be touched; in my case it would primarily be `<p>`.

Another option (a bit more advanced, but nice) would be specifying elements _around_ which white-space won't be removed - such as `<strong>` and `<em>`.
## 

I hope the development of this feature hasn't been forgotten - thanks for the great work so far! :)

**Comment by kangax** [comment]
We already have this. See https://github.com/kangax/html-minifier/pull/67 for example
