### ISSUE TITLE
Whitespace jumps around htmlmin:ignore 

### ISSUE THREAD

**Issue by kornelski** [kangax/html-minifier#641]
When using default settings on http://kangax.github.io/html-minifier/:

``` html
<p>Hello <!-- htmlmin:ignore --><a>
</a><!-- htmlmin:ignore -->.</p>
```

is converted to:

``` html
<p>Hello<a>
</a> .
```

without the space between `Hello` and `<a>`. This happens even when "Conservative collapse" option is on.

And a space appears after `</a>`, before `.`.

**Comment by alexlamsl** [comment]
That is because the ignored section is being treated as comment and optimised accordingly.

We don't guarantee any whitespace preservations around `htmlmin:ignore` anyway - if you need a space put one inside the ignored section.

**Comment by kornelski** [comment]
That is difficult for me, because in my case the `<!-- htmlmin:ignore -->` section is [generated by a macro in a template](https://github.com/ImageOptim/website/blob/7fee010f4ff2efa2b5f350b4ddf1e57ec91431f1/pages/_layout.html#L52-L61).

Additionally shifting of whitespace from before the macro to after the macro [looks bad](https://github.com/ImageOptim/website/blob/7fee010f4ff2efa2b5f350b4ddf1e57ec91431f1/pages/_layout.html#L129), as it puts a space before a full stop.

**Comment by alexlamsl** [comment]
Okay so you don't have control over the ignored section placement, things can indeed get complicated.

Just to clarify, the whitespace displacement is an artifact of `collapseWhitespace` optimisation around HTML comments. In this case it is breaking things, so it'll need to be fixed.

I have an idea on improving this situation (& fix your particular example), will get to it once I'm done with the meetings today.

Thanks for the report! :wink:

**Comment by kornelski** [comment]
Works great. Thank you for the fix!
