### ISSUE TITLE
How to keep particular html comments when removing them

### ISSUE THREAD

**Issue by johannesjo** [kangax/html-minifier#642]
I've a copyright header which I need to include for all html files. Is there a way to keep those intact when removing html comments? There is CDATA but this not a good option...

**Comment by alexlamsl** [comment]
[ignoreCustomComments](https://github.com/kangax/html-minifier#options-quick-reference) or `<!--! comment -->`

**Comment by johannesjo** [comment]
Oh. Sorry, didn't see that. Thank you very much!
