### ISSUE TITLE
Error thrown on option tag

### ISSUE THREAD

**Issue by mrbinr** [kangax/html-minifier#643]
Hi,

As mentionned in https://github.com/jonschlinkert/gulp-htmlmin/issues/51#issuecomment-201358276 there is errors related to parsing on option tag :

When i use gulp-htmlmin on template containing twig element like `<option {% if value=='1' %}selected="selected"{% endif %}>My Value</option>` an error is thrown.
It's really strange, because if i remove it, and rerun gulp with other twig element in page everything works.

Any idea ?

Thanks for you help

Best Regards,

Pascall

**Comment by alexlamsl** [comment]
Please use [ignoreCustomFragments](https://github.com/kangax/html-minifier#options-quick-reference):

```
> minify(
  '<option {% if value==\'1\' %}selected="selected"{% endif %}>My Value</option>',
  { ignoreCustomFragments:[/\{%[\s\S]*?%\}/] }
);

'<option {% if value==\'1\' %}selected="selected"{% endif %}>My Value</option>'
```
