### ISSUE TITLE
HTML parser error

### ISSUE THREAD

**Issue by hit0907** [kangax/html-minifier#650]
HTML parser error when attribute haven't quotation: &lt;p data-params={"multiple":true}&gt; Test &lt;/p&gt;

**Comment by alexlamsl** [comment]
`<p class=test>` works for me [here](http://kangax.github.io/html-minifier/)

Which options did you use?

**Comment by hit0907** [comment]
Yes, it working. Error when set attribute value is JSON string data-params={"multiple":true}

**Comment by alexlamsl** [comment]
That's because it's invalid HTML. You cannot omit quotation marks when the value contains `'`, `"`, `=` or whitespaces.

**Comment by hit0907** [comment]
My current page html have attributes value contains  ' ,  " and it working ( data={"multiple":true} ). I added ' (data='{"multiple":true}' ) and it working. Thanks for tool.
