### ISSUE TITLE
convervativeCollapse not honored after 8b19a64a

### ISSUE THREAD

**Issue by papandreou** [kangax/html-minifier#652]
(originally reported on #215)

I just tried to upgrade from html-minifier 1.1.1 to 2.1.1, and the fix for this (8b19a64) seems to have caused a regression, according to `git bisect`.

It comes down to:

``` js
console.log(require('html-minifier').minify('<div><span></span> <!--# echo "foo" --> bar</div>', {
    collapseWhitespace: true,
    conservativeCollapse: true,
    ignoreCustomComments: [ /^#/ ]
}));
```

which used to output:

``` html
<div><span></span> <!--# echo "foo" --> bar</div>
```

but now comes out as:

``` html
<div><span></span><!--# echo "foo" --> bar</div>
```

It seems like `conservativeCollapse` is not being honored anymore in this particular case?

Another weird thing that changed with that commit: With the same options as above,

``` html
<body>
<!--[if !IE]>-->Not IE<!--<![endif]-->
</body>
```

now minifies to

``` html
<body><!--[if !IE]>--> Not IE<!--<![endif]--> </body>
```

but it used to minify to:

``` html
<body> <!--[if !IE]>-->Not IE<!--<![endif]--> </body>
```

(notice that the whitespace moved)

**Comment by alexlamsl** [comment]
@papandreou thanks for the report. I've filed #655 to fix these cases plus a few more.
