### ISSUE TITLE
error in cli.js on line 33;  statement: "require('.')";  OS: Ubuntu (multiple versions)

### ISSUE THREAD

**Issue by patrickneugebauer** [kangax/html-minifier#653]
I tried to run html-minifier (CLI) on Ubuntu (14.04 + 15.10) and I keep getting an error:
`Error: Cannot find module '.'`

It appears to be coming from cli.js on line 33 from the statement:
`var minify = require('.').minify;`

The following statement does not appear to work on Ubuntu:
`require('.')`

I had to hard code the require path to get it working on Ubuntu.  I just replaced line 33 with:
`var minify = require('./src/htmlminifier.js').minify;`

**Comment by alexlamsl** [comment]
Rather than the OS, which version of Node.js are you running?

**Comment by patrickneugebauer** [comment]
I was running v0.10.25.  
I did a fresh command line Install on Ubuntu, the repository is a little bit old.  [https://nodejs.org/en/download/releases/](https://nodejs.org/en/download/releases/)  

I just downloaded the LTS version (v4.4.3) and the original code works correctly.  Thank you for humoring me.

**Comment by alexlamsl** [comment]
Interesting `require()` behaviour then. According to [the docs](https://nodejs.org/dist/latest-v0.10.x/docs/api/modules.html#modules_all_together), it should read `main` field in `package.json` and resolve accordingly (which it obviously does in Node.js 4 and 6).
