### ISSUE TITLE
Trailing whitespace in an inline element causes space between elements to be removed

### ISSUE THREAD

**Issue by OverZealous** [kangax/html-minifier#656]
This looks to be related to #618

I'm still seeing this behavior, using `2.1.2`.  My most minimal case is this:

``` html
<a>hi </a> <a>there</a>
```

which gets converted to

``` html
<a>hi </a><a>there</a>
```

This is wrong, because the space needs to still exist _between_ the elements, rather than inside.  Otherwise, the two elements have no space between them.  I would be OK with either not changing the output, or having only the space between the elements preserved.

If the first element doesn't have a space after the text content (`<a>hi</a> <a>there</a>`), then the output is as expected.  So this appears to be some sort of special handling causing the issue.

**Comment by OverZealous** [comment]
Note: I can use `conservativeCollapse` to work around this for now, but obviously that makes a difference in how much compression we get.

And thanks for all the hard work!

**Comment by alexlamsl** [comment]
As stated in #618, this is the correct whitespace transformation - if you run a quick test and note the blue underline of `<a>` link as you move the whitespace around you'll see why.

**Comment by OverZealous** [comment]
OK, this is interesting.  I put together [an example of this](https://jsfiddle.net/OverZealous/L8urpy76/).  Unexpectedly, it looks like for straight inline elements, this is right.  However, if the element has it's display mode changed to `inline-block` (for example, for rendering links as a button with padding, etc), then the compressed styling is rendered differently.

I guess the only correct thing to do in this situation is to use `conservativeCollapse`, because then I can use an element either way without worrying about alignment.

Thanks.

**Comment by alexlamsl** [comment]
Sorry if I wasn't clear - when you have cases like CSS modifications of layout styles, then `conservativeCollapse` is indeed the correct option to use.

Before the fix, `html-minifier` was causing input and output HTML layouts to differ.
