### ISSUE TITLE
--quote-character value in command line

### ISSUE THREAD

**Issue by inad9300** [kangax/html-minifier#658]
I'm trying to use html-minifier via an npm script (so, through the command line), and I don't manage to properly pass a value to the `--quote-character` option. This is how my attempt looks like: `"optimize:html": "html-minifier --quote-character \" index.html"`.

Could you please help me in this one?

Thanks!

**Comment by alexlamsl** [comment]
Didn't try it, but have you forgotten to escape the `"` for the command line? Your `\"` will just come out as `"`, whereas `\\"` might work.

**Comment by inad9300** [comment]
You were right in your intuition. With `\"` I was escaping the `"` for JSON, but not for the terminal. However, with `\\"` you escape the `\` for JSON, thus you get an invalid JSON, since you end up with a string attempting to content a _free_ `"`. Therefore the final solution is to use `\\\"`, so that you escape both the `\` and the `"` for JSON, ending up with a escaped double quote (`\"`) in the terminal.

Perhaps it's worth mentioning it somewhere on the docs.

Thanks!

**Comment by alexlamsl** [comment]
Glad you got it sorted - if you have any ideas on improving the docs, PRs are always welcome.
