### ISSUE TITLE
running dist/htmlminifier.js with node fails

### ISSUE THREAD

**Issue by nha** [kangax/html-minifier#659]
By reading the README I was under the impression that this minifier would run under node.js:

But cloning the repository and running it with node (v4.2.4) I get:

```
$ node dist/htmlminifier.js

html-minifier/dist/htmlminifier.js:17430
 var xhr = new global.XMLHttpRequest()
```

Note: I do care about this error since I get the same in Nashorn, as I would like to make a wrapper for the JVM.

**Comment by alexlamsl** [comment]
[npm installs](https://github.com/kangax/html-minifier#installation-instructions) the script which is why you can run `htmlminifier <options>` on the command line.

Otherwise use `node cli.js <options>`.

**Comment by nha** [comment]
I tried I tried the following:

```
npm install -g html-minifier // version 2.1.3
html-minifier --minify-js true sample.js -o sample.min.js // same output as the input (while it differs with uglify.js 2.6.2)
html-minifier --minify-js sample.js -o sample.min.js      // hangs on forever (well at least a few minutes - then I killed it)
html-minifier --input-dir source/ --output-dir expected/  // writes to stdout, creates one empty file on expected/ (there were several .js files on the source/ folder)
```

I did not have more success using the cli.js bash script.

Using html-minifier 2.1.3, node 4.2.4 and OSX 10.11
How should I use this module ?
