### ISSUE TITLE
minifier inserts whitespace

### ISSUE THREAD

**Issue by partap** [kangax/html-minifier#66]
I'm using [AngularJS](https://github.com/angular/angular.js), so some tags use dashes... (e.g. ng-repeat)
When I ran html-minifier on my source, I would end up with spaces inserted into some of my tags (e.g. ng -repeat)

Honestly, I haven't checked using the latest version (I was using [grunt-contrib-htmlmin](https://github.com/gruntjs/grunt-contrib-htmlmin)) but I figured I'd mention it here, just in case...

**Comment by partap** [comment]
Just rechecked... `<ng-repeat>` was a bad example...I'm not using it as a tag (only as an attribute)
...but I did reproduce the behavior with `<ng-include>`
If I have this in my source:

``` html
<ng-include src="template"></ng-include>
```

it turns into:

``` html
<ng -include="" src="template"></ng>
```

Heh, looks like GitHub's syntax highlighter doesn't like dashes in the tag name, either...

**Comment by partap** [comment]
one more update:  Angular allows an alternative XMLish syntax: `<ng:include>`, but minifier has the same problem...
this:

``` html
<ng:include src="template"></ng:include>
```

minfies into:

``` html
<ng :include="" src="template"></ng>
```

**Comment by kangax** [comment]
It should work in latest version
