### ISSUE TITLE
Handlebars attribute assignments without quotes

### ISSUE THREAD

**Issue by topaxi** [kangax/html-minifier#660]
Is it possible to make this work?

``` hbs
<input type="checkbox" checked={{get 'someBoolean'}}>
```

While I could use quotes in this example, there are cases where, in Ember, the quotes do a string conversion and are undesired in a case where an attribute assignment shouldn't be a string.
If I use quotes, I get either `checked="false"` or `"checked="true"` which both result in a checked checkbox.

**Comment by alexlamsl** [comment]
You have a whitespace in the attribute value, so by standard HTML you need quotes.

If you are injecting custom stuff consider `ignoreCustomFragments`.

**Comment by topaxi** [comment]
Awesome this works! :)

For anyone else, this is the config I'm now using:

``` javascript
{
  customAttrSurround: [
    [ /\{\{#[^}]+\}\}/, /\{\{\/[^}]+\}\}/ ]
  ],
  ignoreCustomFragments: [
    /\{\{[^\}]+\}\}/g
  ]
}
```
