### ISSUE TITLE
Not properly minifying if : is used for custom tags

### ISSUE THREAD

**Issue by harshadbankar** [kangax/html-minifier#662]
In my project i have custom tag like
`<div><page:login:new:user></page:login:new:user></div>`

And when I do minify, it is getting converted as 
`<div><page:login :new:user=""></page:login></div>`

Any idea on how to solve this?

*i already know I can use - instead of : 
But i want to know for above case

**Comment by alexlamsl** [comment]
IIRC, you can only use one `:` (as namespace) in XML, i.e. colons have special meanings and cannot be used as part of your tag name casually.
