### ISSUE TITLE
[feature req] minifier fails if input folder contains anything else than html files

### ISSUE THREAD

**Issue by revelt** [kangax/html-minifier#665]
Hi!

If there are images in the input directory, `html-minifier` breaks. For example, I use npm script task:

`html-minifier --input-dir ./test1 --output-dir ./test2 --html-5 --collapse-whitespace`

There is only 1 html file and 1 png image in the folder `test1/`.

I get the following error:

```
Minification error on test1/test-icon.png
Parse Error: <����O��... (and goes on)...
```

I'd like to use `html-minifier` to minify my static website's _output_ folder — it contains everything that normal website would contain, including images.

If there is a temporary solution to feed only .html files from the folder into `html-minifier`, please advise as well, I'm keen to minify all my .html files.

Thank you.

**Comment by alexlamsl** [comment]
It is not a bug per se, just a missing feature.

PR is welcome.

**Comment by revelt** [comment]
Updated the title. I'll see what I can do :smiley:

**Comment by revelt** [comment]
This is awesome, it does work now:

`html-minifier --input-dir ./test1 --output-dir ./test2 --collapse-whitespace --file-ext html`

Thanks guys!

**Comment by revelt** [comment]
I noticed the subfolders are still not read. This might be out of scope of this library, so I'm wondering is it possible to combine two libraries on npm script.

I asked a [question](http://stackoverflow.com/questions/38262757/passing-the-glob-result-into-another-script) on SE, is it possibly to combine `glob`-style libraries with others (such as `html-minifier`).

If anybody has an idea that would make minification on folders much easier. Actually, `.html` only could be globb'ed straight into this library, bypassing this closed issue!

**Comment by alexlamsl** [comment]
Actually, that commit broke the recursive functionality, i.e. if `--file-ext` is specified, then subdirectory would mostly be skipped.

I am curious though - what is the expectation when skipping over non-HTML files. Do we just store minified files in the output directory, or are we expected to copy over image files etc.?

**Comment by revelt** [comment]
> I am curious though - what is the expectation when skipping over non-HTML files. Do we just store minified files in the output directory, or are we expected to copy over image files etc.?

I have a Hugo-diven static website and I want to run the minifier on the whole `/public/` folder — everything that is generated by Hugo. It's necessary because HTML partials often have spaces everywhere, what adds up when rendered and looks clearly computer-generated with ten spaces, opening `<div>`, twenty spaces and fifteen line breaks, then some text...

Thanks again for sorting folder recursion + filtering by extension in v3.0.1, I really appreciate that!
