### ISSUE TITLE
Spaces are removed around <wbr> elements

### ISSUE THREAD

**Issue by mrcsmcln** [kangax/html-minifier#666]
I think it's safe to say `<wbr>` elements will be used in inline contexts, but the minifier removes spaces around them.

**Comment by alexlamsl** [comment]
Use `conservativeCollapse` if you want to override default HTML layout rules.

**Comment by mrcsmcln** [comment]
I'm aware of that option, but I think you might be missing my point. I guess I'm asking why `<wbr>` isn't included in [this list](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L64), since it is in fact an element that would be used inline and should have spaces around it, just like `<span>`, `<strong>`, `<sub>`, etc.

**Comment by alexlamsl** [comment]
Ah, I see what you mean after reading the meaning of that tag :sweat_smile: 

You may want `inlineTags` instead of `inlineTextTags` if you want to maintain the whitespace around the tag. Although I wonder if we can optimise `a <wbr> b` as `a<wbr> b`...

PR is welcome :wink:

**Comment by alexlamsl** [comment]
fixed by #673
