### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by stefanwalther** [kangax/html-minifier#668]
Hi,

if I have the following code in my Html file, I get a parser error:

```
 if(RecNo() >=65 and RecNo() <= 90,RecNo()-64) as Num,
```

It's actually part of a code block, a code example ... just to give you some background information ...

Any ideas?
Regards
Stefan

**Comment by alexlamsl** [comment]
`>` and `<` need to be escaped, i.e. as `&gt;` and `&lt;` respectively.
