### ISSUE TITLE
Whitespaces in Media-Query Attributes

### ISSUE THREAD

**Issue by Keenora** [kangax/html-minifier#669]
My trainee found a little saving inside of my page, which was totally valid and could be minified as well:

`<link rel=stylesheet href=css/style-mobile.css media="(max-width: 737px)">`

an the whitespace inside the media, can be saved (The quotes also):

`<link rel=stylesheet href=css/style-mobile.css media=(max-width:737px)>`

**Comment by alexlamsl** [comment]
Interesting - PR is welcome :wink:
