### ISSUE TITLE
Conditional comments bug

### ISSUE THREAD

**Issue by dudeonthehorse** [kangax/html-minifier#670]
Hello! Found a bug with using `https://github.com/jonschlinkert/gulp-htmlmin`

"processConditionalComments: true" works fine for 

`<!--[if (gte mso 9)|(IE)]><table width="100%" align="center"><tr><td width="250"><![endif]-->`

and for 

``

but in this construction

``

I'm loosing all code between conditional comments.

Catched this bug in my email development framework https://github.com/dudeonthehorse/kilogram

**Comment by Chariyski** [comment]
I have the same bug with:

```
<!--[if gte IE 11]><!-->
  <h3 hidden>Some text</h3>
<![endif]-->
```

**Comment by alexlamsl** [comment]
@Chariyski https://en.wikipedia.org/wiki/Conditional_comment#Downlevel-revealed_conditional_comment

``` html
<!--[if gte IE 11]><!-->
  <h3 hidden>Some text</h3>
<!--[endif]-->
```

**Comment by alexlamsl** [comment]
@dudeonthehorse not sure what you are trying to achieve here - can you give a more complete example than the code snippet to illustrate?

The current behaviour doesn't actually depend on whether you have conditional comments for the cases you've mentioned, btw.

**Comment by Chariyski** [comment]
@addaleax I do not understand why you have copied that link, but my case is identical to:

```
<!--[if gt IE 6]><!-->
This code displays on non-IE browsers and on IE 7 or higher.
<!--<![endif]-->
```

Without that comment the minifier is working correctly.

**Comment by addaleax** [comment]
@Chariyski It’s been over 2 years since I’ve had anything to do with this project, is there a chance you wanted to ping somebody else? Otherwise I’m not sure how I’m able to help here. :D

**Comment by Chariyski** [comment]
@addaleax  I'm sorry. I made a mistake with @alexlamsl nick.
Have a nice day.

**Comment by alexlamsl** [comment]
@Chariyski in your original example, `<![endif]-->` is causing the HTML parser to report an error, whereas `<!--[endif]-->` works as expected.

**Comment by Chariyski** [comment]
@alexlamsl Yes that way is working correct.
Thank you :)

**Comment by alexlamsl** [comment]
Closing as the behaviour described is not specific to conditional comments.

Feel free to provide more in-depth examples and reopen this issue.
