### ISSUE TITLE
Not closing table caption (invalid HTML)

### ISSUE THREAD

**Issue by tomasz1986** [kangax/html-minifier#674]
```
<!doctype html>
<title>test</title>
<table>
<caption>
</caption>
</table>
```

is minified to

```
<!DOCTYPE html><title>test</title><table><caption></table>
```

whis is invalid HTML.

> Error: table closed but caption was still open.

Source: https://validator.w3.org

**Comment by alexlamsl** [comment]
This is a feature following the rules of [optional tags](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags)

```
A caption element's end tag may be omitted if the caption element is not immediately followed by a space character or a comment.
```

**Comment by tomasz1986** [comment]
Are you saying that this is a bug in the Validator then?

**Comment by alexlamsl** [comment]
I'd say we have different goals. `html-minifier` aims to find the minimum representation of a given input. HTML validators aim to promote best practices for authoring HTML pages.

If there is visual rendering differences between the input and minified output on a web browser, feel free to (re)open an issue. :wink:

**Comment by ghost** [comment]
Can You make BlackList Tags ? Everyone who want, can add caption to blacklist.
I now there is no visual rendering differences between the input and minified output, but every validator say "missing caption", and this is bad. I must disable removeOptionalTags and I am very sad becouse it is great feature.
