### ISSUE TITLE
Lag when processing large (> 500KB) files

### ISSUE THREAD

**Issue by tomasz1986** [kangax/html-minifier#675]
The minifier website freezes when processing large HTML files. It happens both in Firefox and Chromium but especially the latter gets completely frozen and has to be restarted to fix the issue. Firefox is usually responsive again after a few seconds.

Especially after processing one code, if I copy and paste a new code over the existing one and press "check" then the process gets stuck completely.

Is there anything that could be done about this?

**Comment by alexlamsl** [comment]
Minification is synchronous and runs on the main (UI) thread at the moment.

PRs to migrate to Web Workers (without losing browser compatibility) or general performance improvements are welcome.

**Comment by ghost** [comment]
@alexlamsl  I will be glad to implement, any guidance you could provide? regarding the development environment setup?

I am new to github community.

**Comment by alexlamsl** [comment]
@imvetri would this help?

https://guides.github.com/activities/forking/

**Comment by ghost** [comment]
@alexlamsl Thanks.. very helpful.

**Comment by ghost** [comment]
Hi @tomasz1986 ,  I am setting up development environment to try out idea suggested by Alex. (making minification asynchronous on browser side).

Would you mind sharing info how to use html-minifier on browser side? or any references to boilerplate projects will help me much. 

Thanks :)

UPDATE 1: I figured it.. :)
