### ISSUE TITLE
PHP tag inside a pair of quotes in script tag under enabling minifyJS

### ISSUE THREAD

**Issue by kylehon** [kangax/html-minifier#679]
I found a bug when putting PHP tag `<?php ?>` inside a pair of single/double quotes in script tag `<script>`

Before compressed:

``` html
<script>
$('#element').myPlugin({
    key: '<?php ?>'
});
</script>
```

``` html
<script>
$('#element').myPlugin({
    key: "<?php ?>"
});
</script>
```

Actual (after compressed):

``` html
<script>$("#element").myPlugin({key:"\t\t"})</script>
```

``` html
<script>$("#element").myPlugin({key:"\t\t"})</script>
```

Expected: 

``` html
<script>$("#element").myPlugin({key:""})</script>
```

``` html
<script>$("#element").myPlugin({key:""})</script>
```

I tried adding some regex in `ignoreCustomFragments` but it doesn't help.

I guess these lines may be related to my issue: https://github.com/kangax/html-minifier/commit/0960482ab9d691fd5c32f9885936ce39c8258f6c

Or would there be any may that by-pass/escape this issue?

Thank you!

**Comment by outaTiME** [comment]
Same here bro, im using:

```
  const htmlminOptions = {
    collapseWhitespace: true,
    // custom
    removeComments: true,
    minifyJS: true,
    ignoreCustomFragments: [ /<(WC@[\s\S]*?)>(.*?)<\/\1>/ ]
  };
```

on **windows** platform im getting:

```
<script type="text/javascript">var device_id="\t<WC@GPSID></WC@GPSID>\t"</script>
```

but if i remove the `minifyJS` flag:

```
<script type="text/javascript">var device_id = '<WC@GPSID></WC@GPSID>';</script>
```

**Comment by outaTiME** [comment]
The problem comes with minifyJS flag on **windows** platform, how to solve this ?

**Comment by LeoLei** [comment]
It's the same to me!

node express with ejs, before compressed

```
<script>
    var isLogin = "<%= is_login  %>";
</script>
```

result in:
`<script>var isLogin="\t<%= is_login  %>\t";</script>`

This will make logic error. And also, if i remove **/<%[\s\S]*?%>/** from **ignoreCustomFragments**  list, it leads to an error, thrown by HTMLParser in **src/htmlparser.js** :

```
232       parseEndTag('</' + stackedTag + '>', stackedTag);
233     }
234
235     if (html === last) {
236       throw new Error('Parse Error: ' + html);
237     }
```

I found the code in the file of **src/htmlminifier.js**

```
 793   var customFragments = (options.ignoreCustomFragments || [
 794     /<%[\s\S]*?%>/,
 795     /<\?[\s\S]*?\?>/
 796   ]).map(function(re) {
 797     return re.source;
 798   });
 799   if (customFragments.length) {
 800     var reCustomIgnore = new RegExp('\\s*(?:' + customFragments.join('|') + ')+\\s*', 'g');
 801     // temporarily replace custom ignored fragments with unique attributes
 802     value = value.replace(reCustomIgnore, function(match) {
 803       if (!uidAttr) {
 804         uidAttr = uniqueId(value);
 805       }
 806       var token = uidAttr + ignoredCustomMarkupChunks.length;
 807       ignoredCustomMarkupChunks.push(match);
 808       return '\t' + token + '\t';
 809     });
 810   }
```

In the line of 808, the two '\t's are added. Removing them both,  the compression is going correctly! I'm not sure what's them adding for.

**Comment by outaTiME** [comment]
But it happens only in _windows_ platform ... in mac it works fine ...
