### ISSUE TITLE
Support for Node.js 0.10

### ISSUE THREAD

**Issue by alexlamsl** [kangax/html-minifier#682]
@kangax @XhmikosR with latest version of `grunt-eslint` they have modified the code to explicitly fail to run on Node.js 0.10 - I have upgraded this dependency without thinking and broke Travis build. 😢 

So the question is - do we also drop `0.10` from Travis, or just revert back to a previous version of `grunt-eslint`?

**Comment by kangax** [comment]
I would drop 0.10 IIRC quite few popular projects are dropping it recently.

**Comment by XhmikosR** [comment]
Well, for one, that is why you wait for the CI builds to finish.

But anyway. ESLint is a devDependency. Everything else will still work. So I'd say revert the change for now.

And when it's really the time to drop 0.10, it should be accompanied by a major version bump.

**Comment by alexlamsl** [comment]
@XhmikosR lesson learnt 😓 

Okay, I'll revert the `grunt-eslint` version change on master, and leave a PR open for dropping `0.10` when we move on to `3.0` then.
