### ISSUE TITLE
--decode-entities is broken for strings like &amp;x;

### ISSUE THREAD

**Issue by jacksonp** [kangax/html-minifier#685]
`$ html-minifier --decode-entities <(echo "&amp;x;")`
`&ampx;`

Expected output:
`&x;`

Tested the above with versions 2.1.7 and 3.0.0.

**Comment by alexlamsl** [comment]
According to [this](https://mothereff.in/ampersands) your expected output would contain ambiguous ampersand, whereas the current minified output doesn't.

The feature is implemented according to https://mathiasbynens.be/notes/ambiguous-ampersands

**Comment by jacksonp** [comment]
Thanks, I now see that what I put for the expected output is not correct, and that `&amp` without the trailing `;` is in the HTML spec (that was a surprise).

I was in the process of checking my pages were valid HTML after using html-minifier. As your link notes, the current output, `&ampx;` is invalid markup. Maybe that's worth a note in the documentation for the `--decode-entities` option?

From my perspective, I'd like to use `--decode-entities`, but would also like to end up with valid markup. Possible?

**Comment by alexlamsl** [comment]
Validity is a relative measure - removing optional tags can be seen as invalid markup by some HTML validators, for instance.

What I am aiming for here is to have identical rendering of original input and minified output on all (commonly used) web browsers - so please report any observed corner cases and I will try and fix them 😉

**Comment by jacksonp** [comment]
Fair enough, thanks for that. I'll just leave a couple points for your consideration.
If a validator flags missing optional tags as invalid markup, that sounds like a bug in the validator. I'm not convinced validity is really that relative.
It would be nice to be able to use html-minifier as part of a build process that checks for valid HTML (for what it's worth, I'm using https://github.com/validator/validator/).
