### ISSUE TITLE
cli does not process subdirectories when --file-ext is specified

### ISSUE THREAD

**Issue by alexlamsl** [kangax/html-minifier#686]
https://github.com/kangax/html-minifier/issues/665#issuecomment-231395509

**Comment by alexlamsl** [comment]
@revelt please give `html-minifier 3.0.1` a go and see if it works for you.

**Comment by revelt** [comment]
@alexlamsl thank you so much, at last, first time I can minify my whole static website using `html-minifier`! 👍
