### ISSUE TITLE
minify thymeleaf

### ISSUE THREAD

**Issue by luiz04nl** [kangax/html-minifier#689]
okay? I would like minify html in combination with thymeleaf and spring, but generates the following error:

org.xml.sax.SAXParseException: The type of link element "must be terminated by the matching end tag" </ link> ".

I not found an option or other solution, any suggestions?

**Comment by alexlamsl** [comment]
Please provide actual examples of HTML input and minified output to demonstrate the issue.

**Comment by luiz04nl** [comment]
I needed some more options:

--minify-js true --minify-css true --minify-ur-ls true --keep-closing-slash --remove-comments  --collapse-whitespace  --collapse-inline-tag-whitespace --case-sensitive --conservative-collapse 

thank you
