### ISSUE TITLE
Removes end of revealed IE conditional comments

### ISSUE THREAD

**Issue by dalgard** [kangax/html-minifier#69]
The html minifier _quite impressively_ abstains from removing IE conditional comments -- with one exception: The end of (valid) revealed comments. Meaning this exact string:

`<!--<![endif]-->`

The beginning of the conditional comment stays, but the end is removed. This messes up my file quite a bit... :)

**Comment by dalgard** [comment]
The thing is easily remedied by changing the regex on `line 44` in `htmlminifier.js` to this:

`/(?:<!)?\[(?:if[^\]]+|endif)\]/`

**Comment by kangax** [comment]
Do you mean the regex on [line 66](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L66)?

I tried your regex:

```
function isConditionalComment(text) {
  return ((/\[if[^\]]+\]/).test(text) || (/(?:<!)?\[(?:if[^\]]+|endif)\]/).test(text));
}
```

but it still fails. Didn't have a change to look more into it yet.

**Comment by dalgard** [comment]
It seems I didn't have the newest version - I have asked grunt-contrib-htmlmin to update. Sorry for the trouble, please don't change anything.

(I can see some problems with the code above; mixing my approach with the one in 0.5.2 would need a few changes, but that is a moot point :))
