### ISSUE TITLE
Self closing input tag adds a whitespace between elements.

### ISSUE THREAD

**Issue by rodriguezmilton** [kangax/html-minifier#692]
Try with the following structure:

```
<input value="value 1" />
<input value="value 2" />
```

And you will get:

```
<input value="value 1"> <input value="value 2">
```

You may want to use [minifier page](https://kangax.github.io/html-minifier/) to test it.

**Comment by alexlamsl** [comment]
`<input>` is an inline-text element, so surrounding whitespace (`\n` in this case`) is significant and needs to be preserved.
