### ISSUE TITLE
Scripts of type "application/javascript" are sometimes deleted if processed

### ISSUE THREAD

**Issue by JoeUX** [kangax/html-minifier#694]
Test file is the page source here: https://www.engadget.com/2016/07/24/ben-heck-s-nintendo-playstation-prototype-teardown-part-1/

Most of its scripts are `text/javascript`. There is also one `application/javascript` type. It wraps its function in HTML comment syntax.

If `appplication/javascript` is added to the list of scripts to process, the entire script is deleted.

If `application/javascript` is not added to types to process, it processes the script anyway, but does not delete it. A couple of unexpected things are still happening:
- The type attribute is deleted. Only type `text/javascript` is supposed to be deleted according to the docs.
- It actually processes and minifies the script – it's stripping whitespace and HTML comment syntax. It shouldn't be processing this type unless we tell it to. Since it's a script, it probably shouldn't do anything to HTML comment syntax – it should only look for JS comments, if even that.

Here's the original script:

``` Javascript
<script type='application/javascript'><!--
function runOmni(){
s_265.pfxID="weg";
s_265.pageName=s_265.pfxID+' : '+"Ben Heck's\u00a0Nintendo PlayStation prototype teardown, part 1";
s_265.server=location.protocol+'//'+location.host;
s_265.channel="us.engadget";
s_265.linkInternalFilters="javascript:,engadget.com,joystiq.com,massively.com,tuaw.com,switched.com,techcrunch.com";
s_265.mmxgo=true;
s_265.prop12=document.location;
s_265.prop1="article";
s_265.prop2="gaming";
s_265.prop8="bss:21";
s_265.prop45="aws";
s_265.prop54="blogsmith";
s_265.prop62="video_5min_entrybody";
s_265.prop9="bsd:21433957";
s_265.prop18="gaming|sony|nintendo|gear|av|diy";
s_265.prop19="av|benheck|benheckshow|diy|do it yourself|doityourself|element14|gaming|gear|nintendo|partner|sfx-100|sony|syndicated|teardown|thebenheckshow|video|@av|@badge-video|@company-nintendo|@company-sony|@DIY|@element14|@features|@gaming|@gear|@livefyre|@swipe-featuredvideo|@uk";
s_265.prop22="element14";
s_265.prop23="07-24-2016";
s_265.prop65="original_content";
s_265.t();
}
var s_account="aolwbengadget,aolsvc";

var bN_cfg={h:location.hostname,p:{"dL_ch":"us.engadget","dL_dpt":document.title,"dL_sDpt":document.title,"cms_src":"AMP","dL_siteID":"bss:21","dL_cmsID":"bsd:21433957","dL_categories":"gaming|sony|nintendo|gear|av|diy","dL_tags":"av|benheck|benheckshow|diy|do it yourself|doityourself|element14|gaming|gear|nintendo|partner|sfx-100|sony|syndicated|teardown|thebenheckshow|video|@av|@badge-video|@company-nintendo|@company-sony|@DIY|@element14|@features|@gaming|@gear|@livefyre|@swipe-featuredvideo|@uk","dL_author":"element14","dL_published":"07-24-2016","dL_source":"original_content","dL_vid":"video_5min_entrybody"}};
(function(d){var s=d.createElement('script'),h=d.getElementsByTagName('head')[0];s.src='//s.aolcdn.com/os_merge/?file=/aol/omniture.min.js&file=/aol/beacon.min.js';h.appendChild(s);})(document);//--></script>
```

Here's the HTML Minifier output when `application/javascript` is _not_ added to script types to process:

``` Javascript
<script>function runOmni(){s_265.pfxID="weg",s_265.pageName=s_265.pfxID+" : Ben Heck's Nintendo PlayStation prototype teardown, part 1",s_265.server=location.protocol+"//"+location.host,s_265.channel="us.engadget",s_265.linkInternalFilters="javascript:,engadget.com,joystiq.com,massively.com,tuaw.com,switched.com,techcrunch.com",s_265.mmxgo=!0,s_265.prop12=document.location,s_265.prop1="article",s_265.prop2="gaming",s_265.prop8="bss:21",s_265.prop45="aws",s_265.prop54="blogsmith",s_265.prop62="video_5min_entrybody",s_265.prop9="bsd:21433957",s_265.prop18="gaming|sony|nintendo|gear|av|diy",s_265.prop19="av|benheck|benheckshow|diy|do it yourself|doityourself|element14|gaming|gear|nintendo|partner|sfx-100|sony|syndicated|teardown|thebenheckshow|video|@av|@badge-video|@company-nintendo|@company-sony|@DIY|@element14|@features|@gaming|@gear|@livefyre|@swipe-featuredvideo|@uk",s_265.prop22="element14",s_265.prop23="07-24-2016",s_265.prop65="original_content",s_265.t()}var s_account="aolwbengadget,aolsvc",bN_cfg={h:location.hostname,p:{dL_ch:"us.engadget",dL_dpt:document.title,dL_sDpt:document.title,cms_src:"AMP",dL_siteID:"bss:21",dL_cmsID:"bsd:21433957",dL_categories:"gaming|sony|nintendo|gear|av|diy",dL_tags:"av|benheck|benheckshow|diy|do it yourself|doityourself|element14|gaming|gear|nintendo|partner|sfx-100|sony|syndicated|teardown|thebenheckshow|video|@av|@badge-video|@company-nintendo|@company-sony|@DIY|@element14|@features|@gaming|@gear|@livefyre|@swipe-featuredvideo|@uk",dL_author:"element14",dL_published:"07-24-2016",dL_source:"original_content",dL_vid:"video_5min_entrybody"}};!function(e){var o=e.createElement("script"),n=e.getElementsByTagName("head")[0];o.src="//s.aolcdn.com/os_merge/?file=/aol/omniture.min.js&file=/aol/beacon.min.js",n.appendChild(o)}(document)</script>
```

And if you add `application/javascript` to types to process, it just deletes the whole thing.

For some reason this script has HTML comment syntax around the function (e.g. `<!--`). This is key. The comment stripping functionality seems to be deleting the script, but it probably shouldn't delete it since this is a script, not HTML. (The comment syntax doesn't enfold the entire script, so why is the whole script, including the type attribute gone? Probably because it becomes an empty element.)

And if we _don't_ tell it to process these scripts, it's actually processing them anyway, but not deleting it based on the comment syntax anymore, which is inconsistent.

Expected behavior:
1. Ignore HTML comments in scripts.
2. Don't process scripts other than `text/javascript` unless we add the script type to the processing option.

**Comment by alexlamsl** [comment]
Assuming you meant `processScripts` - it is used for HTML templates, not JavaScript snippets.

**Comment by alexlamsl** [comment]
We delete whatever default value is for `<script type=...>`, so that includes [application/javascript](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L156)

**Comment by alexlamsl** [comment]
So given the above, I think this is a case of misunderstanding the meaning of `processScripts` and that we process JavaScript blocks as long as it is specified with one of the supported `type` attribute values.

What use case does this actually break?

**Comment by alexlamsl** [comment]
Closing as working as expected. Please reopen if this is not the case.

**Comment by JoeUX** [comment]
I'm puzzled by these comments, since they contradict the docs. Do you want people to file bugs? This is a bug.
1.  On removing script type attributes, the doc says: "Remove type="text/javascript" from script tags. Other type attribute values are left intact."
   
   That's quite clear. Other type values are to be left intact.
   
   On the processScripts feature, the doc says: "Array of strings corresponding to types of script    elements to process through minifier (e.g. text/ng-template, text/x-handlebars-template, etc.)"
2. It says script elements. The examples are text elements, specifically templating languages, but since the description says script elements, it should process scripts.
   
   And in fact, it does process scripts. It also processes JSON-LD, which is popping up a lot more lately. I used it to process JSON-LD on that same source file (the formal type is "application/ld+json").
   
   It doesn't just process templating languages, and the doc doesn't say that it only processes templates. If someone's intention is that it only process templates, then the app would have to be changed and hopefully the doc would be updated.

I don't know what the "default value" for `<script type=...>` means. There's nothing in the doc or the web app about setting a default value a script type. I never set a default anywhere. The doc implies there's just one hardcoded default (text/javascript), and the source test file had several different types.

**Comment by alexlamsl** [comment]
You are welcome to improve the docs by submitting PRs.

**Comment by alexlamsl** [comment]
You are welcome to improve the docs by submitting PRs.

**Comment by alexlamsl** [comment]
You are welcome to improve the docs by submitting PRs.

**Comment by alexlamsl** [comment]
You are welcome to improve the docs by submitting PRs.

**Comment by alexlamsl** [comment]
You are welcome to improve the docs by submitting PRs.

**Comment by alexlamsl** [comment]
You are welcome to improve the docs by submitting PRs.
