### ISSUE TITLE
Strange behavior during minification

### ISSUE THREAD

**Issue by joeskeen** [kangax/html-minifier#695]
I had an HTML file that contained some markup that looked like this:

``` html
<table>
  <tr>
    <td>
      <textarea />
    </td>
  </tr>
  <tr>
    <td>
      <label>foo</label>
    </td>
    <td>
      <input />
    </td>
    <td>
      <label>bar</label>
    </td>
  </tr>
</table>
```

I expected it to minify to something like this:

``` html
<table><tr><td><textarea /></td></tr><tr><td><label>foo</label></td><td><input></td><td><label>bar</label></td></tr></table>
```

But instead I got this:

``` html
<table><tr><td><textarea>
    </td>
  </tr>
  <tr>
    <td>
      <label>foo</label>
    </td>
    <td>
      <input>
    </td>
    <td>
      <label>bar</label></td></tr></table>
```

(I tested out all of this in your online version here: http://kangax.github.io/html-minifier/)

After a lot of scratching my head, I realized that the `textarea` tag shouldn't be self-closing, so I changed it to `<textarea></textarea>` and it minified fine.  The curious thing is that although it stops working when it gets to the textarea, it seems to decide everything is OK later on and minifies the rest of the document.

When inspecting the console logs, I couldn't find any errors or warnings that would indicate why this was happening.

**Comment by ghost** [comment]
I couldn't understand clearly after "the curious thing is". Could you provide an example? I'll try to reproduce issue from my side.

**Comment by joeskeen** [comment]
Sure.  By that I meant that instead of just stopping minifying the rest of the file, it starts minifying again later on (see the last line of the output: `<label>bar</label></td></tr></table>`.  So whatever prevents it from minifying the middle of the document seems to no longer be an issue later on.

Another thing that confuses me is it's not just the self-closing `textarea` that is causing this behavior.  In fact, this minifies properly:

``` html
<table>
  <tr>
    <td>
      <textarea />
    </td>
  </tr>
</table>
```

Outputs:

``` html
<table><tr><td><textarea></td></tr></table>
```

**Comment by alexlamsl** [comment]
`<textarea>` needs a closing tag according to the [specification](https://developer.mozilla.org/en/docs/Web/HTML/Element/textarea), so I don't think you can get away with a self-closing tag.

**Comment by joeskeen** [comment]
@alexlamsl I do agree that the `textarea` should require a closing tag.  But instead of silently failing to minify a chunk of code following the `textarea` then having minification mysteriously start to work again, it would be great if there was an error or a warning or something that would indicate that the code is invalid, rather than silently failing to minify.  When we first started using html-minifier, we had a few errors due to invalid markup.  Once we resolved those issues, I assumed that we would get errors whenever the markup is invalid.  But without errors or warnings, it is difficult to identify that there is a problem.
Is there any way to enable more verbose or diagnostic logging?  Perhaps this would help.

**Comment by alexlamsl** [comment]
I don't see that as failing as much as it treats the rest being the content of `<textarea>` - but either way, if you have specific usecase(s) in mind which complies with the HTML specification, PR is always welcome :wink:

**Comment by joeskeen** [comment]
OK, so I get that your tool isn't designed to work with malformed HTML.  In fact, it seems that you recently removed linting completely (https://github.com/kangax/html-minifier/commit/22d134003df20d02c479edfb42fd931c6a21d608).  I have referenced this from a feature request on HTMLHint to emit a warning if a self-closing tag isn't valid (https://github.com/yaniswang/HTMLHint/issues/142#issuecomment-235347685).  I am not asking if your tool can please support invalid markup.

What I would like to see is a way to enable more verbose logging for cases like these where your tool is aware that there are problems with the markup when parsing it into the tree (i.e. can't find a closing `<textarea>` tag).  If there were any output, we could look at our build output for an explanation as to why things didn't turn out the way that we expected them to.  I know that my example was small, but this was amongst thousands of lines of HTML in our code base, and was some old code written long before we started to add minification into our build pipeline.

**Comment by alexlamsl** [comment]
If you want [html-minifier-lint](https://github.com/kangax/html-lint) to report on this corner case, please submit a Pull Request to that project. As you've noticed those features have been migrated off to a separate module.
