### ISSUE TITLE
removeComments removes server-side include commands

### ISSUE THREAD

**Issue by salim523** [kangax/html-minifier#697]
Hi I am using server-side include (SSI) for my private site and when I have removeComments: true it remove the `<!--#include virtual="/path/to/file" -->`
Is there exception you can add for SSI? Right now I am using as removeComments: false but it will be nice to remove other comments but not remove SSI.

**Comment by alexlamsl** [comment]
Try `ignoreCustomComments`.

**Comment by alexlamsl** [comment]
Please reopen if issue persists.
