### ISSUE TITLE
File Encoding

### ISSUE THREAD

**Issue by delayedone** [kangax/html-minifier#698]
Hey,

i'm using the gulp plugin and i need to set the encoding of the input and output files but i can't find the option for this.
I want to minify angular templates, which are encoded with iso-8859-1.
But the output results are always utf-8.
The problem is: i need correctly parsed iso-8859-1, but i get a lot of errors in the output file.

**Comment by alexlamsl** [comment]
You'll need to find another module to transform character encodings - `html-minifier` always treats input and output as UTF-8

**Comment by delayedone** [comment]
Well ok, thanks for the quick response :)
