### ISSUE TITLE
Collapse whitespace in comments and attributes

### ISSUE THREAD

**Issue by mblandfo** [kangax/html-minifier#703]
Example: Go to http://kangax.github.io/html-minifier/ and uncheck remove comments, and the following barely gets minified at all

```
                        <!-- ko include: {
                                name: 'templates/widgets/formControls/submit',
                                data: {
                                    label: okKey,
                                    isLoading: isSaving,
                                    disabled: okDisabled
                                }
                            } -->
                        <!-- /ko -->
            <div class="dialogBody" data-bind="include: {
                        name: dialogTemplate,
                        data: $data
                    }">
            </div>
```

**Comment by alexlamsl** [comment]
Looks like you are trying to optimise some code rather than text where HTML comments are designed for.

If you have a specific new feature in mind, PR is always welcome :wink:

**Comment by mblandfo** [comment]
Alright. I'm thinking of adding "Collapse comment whitespace" and "Collapse attribute whitespace" - I guess this will apply to all attributes since I can't think of a reason to limit it to certain attributes right now. 

These will both use the Conservative collapse method regardless of whether that option is true/false.

**Comment by alexlamsl** [comment]
If the code in question is JavaScript(-like), then you can use `customEventAttributes` to apply minification to the attribute values.

As for the HTML comments with code, which framework does that? If it is a server-side directive you can feed the rendered result to `html-minifier` to obtain the better minification. Otherwise a new feature is needed :wink:

**Comment by mblandfo** [comment]
Oh, yeah, customEventAttributes should work for the data-bind attributes. I guess that's not in the online demo page.

I'm using knockout.js, so it's not server side.

**Comment by alexlamsl** [comment]
Indeed not - I always thought of the online page as a quick demo, but then I've been getting reports of people using it as if the real thing :sweat_smile: 

May be it's time to take a look at #675 etc. to improve the tool in that case...

**Comment by stoodder** [comment]
Would second this one, running in to the same issue. For me, It's also when dealing with multi-line attributes.
