### ISSUE TITLE
Feature request: variable name shortening based on frequency of occurence (Information Theory)

### ISSUE THREAD

**Issue by benelot** [kangax/html-minifier#704]
Hello,

I only came by this project but had an idea that could greatly reduce the length of scripts and other things that uses names. Maybe it would be possible to make a list of names and their frequencies of occurrence within their scope (could be the entire script or more specific to their validity scope) and then the variable names could be replaced with short names, with shorter names for those names that occur more often (Encoding based on frequency).

For example (let us say our alphabet has only two letters A and B):

| name: | frequency in scope: |
| --- | --- |
| variable foo | 3 |
| variable bar | 5 |
| variable goo | 1 |

This would now lead to replacing variable foo with ABA, variable bar with AA, and variable goo with ABB (where the variable names are created using Huffmann encoding: https://www.siggraph.org/education/materials/HyperGraph/video/mpeg/mpegfaq/huffman_tutorial.html)

For the actual alphabet, we can of course encode many more things with short names, but the using huffmann encoding will reduce the amount transferred significantly as soon as you have more variables than the number of letters in the alphabet (you will just get an n-ary tree https://en.wikipedia.org/wiki/Huffman_coding#n-ary_Huffman_coding). 

Tell me what you think!

**Comment by ghost** [comment]
@benelot , good suggestion. 

Can you provide some clarification on this:- html-minifier only deals with html. Your suggestion is more towards javascript if i'm not wrong.

**Comment by benelot** [comment]
Oh, I thought it also does other things like scripts inlining as well. I must have misinterpreted this. Thanks for clarification.

**Comment by alexlamsl** [comment]
JavaScript optimisation is performed by [`uglify-js`](https://github.com/mishoo/UglifyJS2) and I think they take character frequency into account when mangling names already. In any case you can file an issue with them if you want to share your ideas with them.

As for `html-minifier`, we aid compression via features like `sortAttributes` and `sortClassName`.

**Comment by benelot** [comment]
Thanks for the information, I will propose the idea to unglify-js then. Here is is:
https://github.com/mishoo/UglifyJS2/issues/1253
