### ISSUE TITLE
Optimisation suggestion: group <NOSCRIPT> in HEAD

### ISSUE THREAD

**Issue by tinovyatkin** [kangax/html-minifier#707]
As many tracking codes use <NOSCRIPT> in the HEAD and load order don't make any sense in this case I assume they can be safely grouped together saving 18 bytes on each occasion.

**Comment by alexlamsl** [comment]
I can think of loading style sheets via `<link>` which would be load-order dependent.

And just out of curiosity, what do people normally use `<head><noscript>...</noscript></head>` for?

**Comment by tinovyatkin** [comment]
I use to load stylesheets when scrips are not available (when they are, I do link rel=preload and loadCSS), and for tracking alternatives for Google Analytics and Facebook pixel. I think a lot of people do the same

**Comment by tinovyatkin** [comment]
Anyway, you can merge in document appearance order, so, it will not broke stylesheet load ordering (if somebody are relying on that).

**Comment by alexlamsl** [comment]
What I meant is you can't merge the following, for instance:

```
<noscript><link rel=stylesheet href=1.css></noscript>
<link rel=stylesheet href=2.css>
<noscript><link rel=stylesheet href=3.css></noscript>
```

Either case, feel free to send a PR and I'll be happy to review it :wink:
