### ISSUE TITLE
hear is my html content,what can i do?

### ISSUE THREAD

**Issue by jiezhiyong** [kangax/html-minifier#708]
<div class="swiper-container" id="banner_wrap">
                <div class="swiper-wrapper" id="banner">
                    <div class="load"></div>

```
            </div>
            <div class="swiper-pagination"></div>
        </div>
        <!--banner template-->
        <script type="text/html" id="banner_list">
            {for ban in banners}
            <div class="swiper-slide">
                <a href="{if ban.href==""}javascript:;{else}${ban.href}{/if}"><img src="${ban.pic}" alt="${ban.title}"></a>
            </div>
            {/for}
        </script>
```

**Comment by alexlamsl** [comment]
Please refer to https://github.com/kangax/html-minifier/blob/gh-pages/README.md on how to use this package?

Closing for now. Please elaborate if there is a specific issue.
