### ISSUE TITLE
Parse error when valid HTML contains "<"

### ISSUE THREAD

**Issue by RoxKilly** [kangax/html-minifier#712]
Unable to parse valid HTML documents if their text contains `<`. For example:

```
<div> < back </div>
```

My gulp task:

```
gulp.task('build-html',function(){
    return gulp.src(appDev+'test.html')
        .pipe(htmlmin({collapseWhitespace: true}))
        .pipe(gulp.dest(appProd));
});
```

Generates error:

```
Error: Parse Error: < back </div>
    at new HTMLParser (html-minifier\src\htmlparser.js:236:13)
```

I can't possibly be the first one here to have come across this, so perhaps I missed something obvious?

**Comment by alexlamsl** [comment]
That is not valid HTML - use `&lt;` instead of `<`.

**Comment by extensionsapp** [comment]
@alexlamsl Tell me how can I track or ignore this error? The site page gives 502 an error. This is very bad. In this case, I would like to get the original line `<div> < back </div>` at the output instead of the error.
