### ISSUE TITLE
only the first attribute in <wbr> has whitespace

### ISSUE THREAD

**Issue by ken1987** [kangax/html-minifier#713]
``` html
<!-- non-compressed -->
<wbr        data-a="a"       data-b="b">

<!-- compressed by v2.1.3 -->
<wbrdata-a="a"data-b="b">

<!-- compressed  by v3.0.2 -->
<wbr data-a="a"data-b="b">

<!-- i hope -->
<wbr data-a="a" data-b="b">
```

**Comment by alexlamsl** [comment]
I just tried it [here](https://kangax.github.io/html-minifier/) and I've got `<wbr data-a=a data-b=b>` - what is your combination of options?

**Comment by ken1987** [comment]
Don't remove quotes around attributes when possible

**Comment by alexlamsl** [comment]
Between `removeAttributeQuotes` and `removeTagWhitespace`, pick the right combination to get your desired output.

**Comment by ken1987** [comment]
Sorry @alexlamsl . The result of the previous example is correct.
The result of the following example is wrong,when only  `Collapse whitespace`  is true.

``` html
<!DOCTYPE html>
<html>
<body>
    <wbr             data-a="a"                  data-b="b" />
</body>
</html>
```

compressed  by v3.0.2

```
<!DOCTYPE html><html><body><wbr data-a="a"data-b="b"></body></html>
```

**Comment by alexlamsl** [comment]
Indeed - adding anything around `<wbr>` seems to upset the minifier.

I will take a look when I get some free cycles.
