### ISSUE TITLE
html-minifier hangs with --minify-js

### ISSUE THREAD

**Issue by bjoe2k4** [kangax/html-minifier#717]
Command never returns and an empty file is created. No problems without `--minify-js`

Create empty file. (also happens with real html file)
`touch test.html`

`html-minifier -o test.min.html --remove-comments --collapse-whitespace test.html`
works.

`html-minifier -o test.min.html --remove-comments --collapse-whitespace --minify-js test.html`
never returns.

Any help appreciated.

Turns out also `--minify-css` is broken for me.

```
├─┬ html-minifier@3.0.3
│ ├─┬ change-case@3.0.0
│ │ ├── camel-case@3.0.0
│ │ ├── constant-case@2.0.0
│ │ ├── dot-case@2.1.0
│ │ ├── header-case@1.0.0
│ │ ├── is-lower-case@1.1.3
│ │ ├── is-upper-case@1.1.2
│ │ ├── lower-case@1.1.3
│ │ ├── lower-case-first@1.0.2
│ │ ├── no-case@2.3.0
│ │ ├── param-case@2.1.0
│ │ ├── pascal-case@2.0.0
│ │ ├── path-case@2.1.0
│ │ ├── sentence-case@2.1.0
│ │ ├── snake-case@2.1.0
│ │ ├── swap-case@1.1.2
│ │ ├── title-case@2.1.0
│ │ ├── upper-case@1.1.3
│ │ └── upper-case-first@1.1.2
│ ├─┬ clean-css@3.4.19
│ │ ├── commander@2.8.1
│ │ └─┬ source-map@0.4.4
│ │   └── amdefine@1.0.0
│ ├─┬ commander@2.9.0
│ │ └── graceful-readlink@1.0.1
│ ├── he@1.1.0
│ ├─┬ ncname@1.0.0
│ │ └── xml-char-classes@1.0.0
│ ├── relateurl@0.2.7
│ └─┬ uglify-js@2.7.3
│   ├── async@0.2.10
│   ├── source-map@0.5.6
│   ├── uglify-to-browserify@1.0.2
│   └─┬ yargs@3.10.0
│     ├── camelcase@1.2.1
│     ├─┬ cliui@2.1.0
│     │ ├─┬ center-align@0.1.3
│     │ │ ├─┬ align-text@0.1.4
│     │ │ │ ├─┬ kind-of@3.0.4
│     │ │ │ │ └── is-buffer@1.1.4
│     │ │ │ ├── longest@1.0.1
│     │ │ │ └── repeat-string@1.5.4
│     │ │ └── lazy-cache@1.0.4
│     │ ├── right-align@0.1.3
│     │ └── wordwrap@0.0.2
│     ├── decamelize@1.2.0
│     └── window-size@0.1.0
```

**Comment by alexlamsl** [comment]
Refer to `--help`, both `--minify-css [value]` and `--minify-js [value]` requires specifying a value.

**Comment by bjoe2k4** [comment]
Okay, thanks, works now.
Some warning would have been nice, since this worked without value quite nice in earlier versions.

**Comment by alexlamsl** [comment]
That is true - those options are extended to allow for more fine-grained control at some point. Sorry about the confusion :sweat_smile:

**Comment by ubershmekel** [comment]
It isn't explained clearly what that `value` should be, and it is unfortunate that html-minifier just hangs instead of errors :(

**Comment by humaknlght** [comment]
Where can I find a complete list of the values I can use?
