### ISSUE TITLE
Parse Error with textarea

### ISSUE THREAD

**Issue by CodaCodr** [kangax/html-minifier#718]
HTMLMinifier tries to parse the content of a `textarea` and bombs out with "Minification error: Parse Error ..." when encountering: 

`<textarea>stuff that might look like html but should be treated as text</textarea>`

**Note**: The file verifies at w3c.

As a test case (not tested myself) try: `<textarea><div> </span></textarea>`

**Comment by alexlamsl** [comment]
https://validator.w3.org/ doesn't like your last example when I tried just now.

**Comment by CodaCodr** [comment]
Don't know what you did, but...

![issue-718](https://cloud.githubusercontent.com/assets/436812/18683110/81005eac-7f34-11e6-9969-2d7e19e526ca.JPG)

**Comment by CodaCodr** [comment]
So now we've proved my untested example works by testing it... is there a likelihood this parsing error will be fixed soon?  Just asking.

**Comment by alexlamsl** [comment]
I've got this from the page

![error](https://cloud.githubusercontent.com/assets/1898413/18683424/d3229146-7fa2-11e6-99f1-b22a724fec0f.png)

**Comment by CodaCodr** [comment]
Well, you saw my paste. Content of textarea is text. HTMLMinifier should parallel how a browser treats it, not try to treat like... I don't know... an iframe?

I don't know how you're getting that result (is it the same source? might be worth sending them an issue report).

**Comment by CodaCodr** [comment]
Oh... line 1 ??? Is that a valid document?

**Comment by alexlamsl** [comment]
You can submit a PR to fix what you think the issue is, then we can discuss further from there.

**Comment by CodaCodr** [comment]
I can't do the PR, sorry.

And there's no more to discuss, viz:

_For elements in HTML, the constraints of the Text content model also depends on the kind of element. For instance, an "<" inside a textarea element does not need to be escaped in HTML because textarea is an escapable raw text element._ (http://w3c.github.io/html/single-page.html#text)

**Comment by alexlamsl** [comment]
That looks like HTML5 specification, which isn't the only one the parser is designed to handle. In fact I believe this parser was written before HTML5 came out. There have been a few other corner cases where web browsers would fall back gracefully while `html-minifier` would complain.

Either case, if this is a major/urgent concern of yours I'd suggest submitting a fix.

**Comment by CodaCodr** [comment]
Misdirections aside, textarea content is not a corner case. I'm done here.

**Comment by alexlamsl** [comment]
Thanks for the talk.
