### ISSUE TITLE
Question: How to easily enable all minification options?

### ISSUE THREAD

**Issue by callumlocke** [kangax/html-minifier#721]
I might be missing something, but it seems like I have to manually enable a LOT of options to get standard minification.

Is there a shortcut to enable a standard set of uncontroversial minification options at once? By 'uncontroversial' I mean anything that reduces the output size without introducing any HTML5 validation errors, and without changing how the document renders in most cases.

**Comment by alexlamsl** [comment]
There is no shortcut option per se, but if you are using the command-line tool you can specify a JSON config file as input via `-c <file>`

**Comment by alexlamsl** [comment]
Closing as answered. Will re-open if you think otherwise or have further questions.

**Comment by code-tree** [comment]
I agree with @callumlocke. It would be nice to have a list of recommended options. Ones that have been tested well, and are guaranteed not to negatively affect all modern browsers (and most old ones).

This could be enabled via a `--standard` arg or something like that.

**Comment by code-tree** [comment]
If not, at least a list of recommended options in the README?

**Comment by code-tree** [comment]
After looking through them all, it seems like a safe basic config is?

``` json
removeComments: true,
collapseWhitespace: true,
conservativeCollapse: true,
```

**Comment by alexlamsl** [comment]
Personally I don't use this for absolute conformance, as I tune `options` for my specific use cases.

PR to augment documentation if you believe this is useful would be welcome 👍
