### ISSUE TITLE
Another ignoreCustomFragments space problem from #436

### ISSUE THREAD

**Issue by adamchal** [kangax/html-minifier#722]
On http://kangax.github.io/html-minifier/, if you use:

``` php
<?php echo 'There should NOT be a whitespace after closing PHP tag if'; ?>
<span>collapseInlineTagWhitespace is used</span>
```

Result:

``` php
<?php echo 'There should NOT be a whitespace after closing PHP tag if'; ?> <span>collapseInlineTagWhitespace is used</span>
```

Expected:

``` php
<?php echo 'There should NOT be a whitespace after closing PHP tag if'; ?><span>collapseInlineTagWhitespace is used</span>
```

If `collapseInlineTagWhitespace` is `true`, then whitespace around blocks ignored by `ignoreCustomFragments` should be collapsed.

I believe this arose while fixing #436.

**Comment by alexlamsl** [comment]
I think this is a choice between correctness & optimal minification. #436 was fixed by being always conservative with whitespaces around custom fragments.

You are welcome to refine this with a PR, of course.
