### ISSUE TITLE
minifyCSS option

### ISSUE THREAD

**Issue by jay8t6** [kangax/html-minifier#724]
For some reason, it only minifies the first `<style>` tag it finds in the HTML, can it minify all the `<style>` tags found in the html?

**Comment by alexlamsl** [comment]
Just tested this and seems to work:

```
<style>
  a {
    background-color: blue
  }
</style>
<a href="/foo">bar</a>
<style>
  a {
    background-color: red
  }
</style>
```

gives:

```
<style>a{background-color:#00f}</style><a href=/foo>bar</a><style>a{background-color:red}</style>
```

Can you give a more specific example illustrating your issue?

**Comment by jay8t6** [comment]
@alexlamsl Thanks for following up on this quickly. I will see if I can create a small HTML that reproduces the issue. Note that the HTML I am trying to minify is a polymer element that contains CSS within <don-module> tag. Would that make a difference?

**Comment by jay8t6** [comment]
@alexlamsl I meant to say within dom-module tag.

**Comment by alexlamsl** [comment]
@jay8t6 I am unfamiliar with the framework which you've mentioned, so it would be more helpful for me to see a more concrete example before I comment on the issue further.

**Comment by jay8t6** [comment]
@alexlamsl Checkout the HTML content in this fiddle, it contains style tag within some-module:

https://jsfiddle.net/kaycebasques/2q3fqehz/

Also, this page talks a little bit about the page:
https://www.polymer-project.org/1.0/docs/devguide/styling

**Comment by alexlamsl** [comment]
@jay8t6 that example only has one `<style>` section AFAICT, and it seems to minify properly.

**Comment by alexlamsl** [comment]
Closing for now. Will reopen once a concrete example of failure is provided.

**Comment by jay8t6** [comment]
@alexlamsl I figured it out. It was an external css file that was being imported into the html after the minify task runs, all I had to do was minify the external css using gulp-clean-css before the import happens, it was a mistake on my side. your minifier works great! this is not an issue, thanks for working with me.

**Comment by alexlamsl** [comment]
@jay8t6 glad that you've got it worked out.
