### ISSUE TITLE
--minify-js doesn't work on command line.

### ISSUE THREAD

**Issue by cchan** [kangax/html-minifier#726]
I can't get the JS between <script></script> tags to minify. :/

**Comment by alexlamsl** [comment]
Please provide a concrete example as to the issue you have encountered?

**Comment by cchan** [comment]
Here's an example @alexlamsl, sorry I didn't provide one earlier.

```
<script>$('window').click(() => {
  console.log('hello');
});</script>
```

I suspect it has something to do with the ES6? It works fine using a `function(){}` instead.

**Comment by alexlamsl** [comment]
It's not working because [`uglify-js`](https://github.com/mishoo/UglifyJS2) does not support ES6 (yet?)

**Comment by cchan** [comment]
Ah, okay. Darn.

**Comment by cchan** [comment]
Ah, true. Looks like it's on the way, though: mishoo/UglifyJS2#1290

**Comment by towerpark** [comment]
Instead of failing silently, some warning would be appreciated  :)
