### ISSUE TITLE
import failing on webpack-built script

### ISSUE THREAD

**Issue by TintypeMolly** [kangax/html-minifier#727]
## Situation

I am building a boilerplate for universal react app.

I wanted to minimize my html output on the server side.

So I just did `npm install --save html-minifier` and `import {minify} from "html-minifier";`.

Then this error popped up when I built and started the server.

```
Error: ENOENT: no such file or directory, lstat 'C:\Users\tintypemolly\workspace\react-boilerplate\lib'
    at Error (native)
    at Object.fs.lstatSync (fs.js:982:18)
    at Object.realpathSync (fs.js:1647:19)
    at C:\Users\tintypemolly\workspace\react-boilerplate\build\~\html-minifier\~\uglify-js\tools\node.js:23:1
    at Array.map (native)
    at Object.<anonymous> (C:\Users\tintypemolly\workspace\react-boilerplate\build\~\html-minifier\~\uglify-js\tools\node.js:22:1)
    at __webpack_require__ (C:\Users\tintypemolly\workspace\react-boilerplate\build\webpack:\webpack\bootstrap fb83bf644d298bef2a7c:19:1)
    at Object.<anonymous> (C:\Users\tintypemolly\workspace\react-boilerplate\build\~\html-minifier\src\htmlminifier.js:8:1)
    at __webpack_require__ (C:\Users\tintypemolly\workspace\react-boilerplate\build\webpack:\webpack\bootstrap fb83bf644d298bef2a7c:19:1)
    at Object.<anonymous> (C:\Users\tintypemolly\workspace\react-boilerplate\build\webpack:\server.js:7:1)
```

I am running this on both Windows 10 and macOS Sierra.
node's version is 6.6.0, npm's version is 3.10.8 on both machines.
This occurs on both machines.

Where the error occurs is this line.
https://github.com/TintypeMolly/react-boilerplate/blob/fail/html-minifier/src/server.js#L7
`import {minify} from "html-minifier";`
## How to reproduce

```
git clone https://github.com/TintypeMolly/react-boilerplate.git
git reset --hard origin/fail/html-minifier
cd react-boilerplate
npm install
npm start
```

you can replace `npm start` with `npm run build` and then `node build/server.js`

The former is for development mode, and the latter is for production mode.

On both cases the same error occurs.
## Why do this occurs?

I found that `uglify-js`, which this repo depends on, is doing something like below.

```
var FILES = exports.FILES = [
    "../lib/utils.js",
    "../lib/ast.js",
    "../lib/parse.js",
    "../lib/transform.js",
    "../lib/scope.js",
    "../lib/output.js",
    "../lib/compress.js",
    "../lib/sourcemap.js",
    "../lib/mozilla-ast.js",
    "../lib/propmangle.js",
    "./exports.js",
].map(function(file){
    return fs.realpathSync(path.join(path.dirname(__filename), file));
});
```

I think this code is packed in to the `server.js` output file when I build my project with `webpack`.

When I build my project with `webpack`, the output is a single file.

For `uglify-js`, `path.dirname(__filename)` means the `uglify-js` source directory.

But once when it is packed into `/path/to/project/build/server.js` of my project, it doesn't mean that anymore.

It's just build output directory of my project, so ends up `Error: ENOENT: no such file or directory`

---

Is this something that `html-minifier` can resolve or should I create a issue on `uglify-js` or `webpack`?

**Comment by alexlamsl** [comment]
Thank you for the detailed description of the issue.

So if I understand correctly, you are trying to use `webpack` on `html-minifier` and its dependencies in order to use the latter within a browser as opposed to running in native Node.js environment? If so, both `html-minifier` and `uglify-js` use `browserify` for this use-case, and you can grab the artifacts from [here](https://github.com/kangax/html-minifier/tree/v3.1.0/dist).

**Comment by alexlamsl** [comment]
And just to summarise, if you want your particular use case to work as-is, then IMHO you'll need to file an issue with `webpack` and let them sort this out for you.

**Comment by TintypeMolly** [comment]
> So if I understand correctly, you are trying to use webpack on html-minifier and its dependencies in order to use the latter within a browser as opposed to running in native Node.js environment?

No, I want to use `html-minifier` on the server-side(`node`) to minimize my http response to users' http request. I don't use this on the client side.

I think I need to look into how `browserify` deal with this kind of problem and hopefully `webpack` has something like it.

Thx.

**Comment by acusti** [comment]
@TintypeMolly Did you ever figure out a solution for this issue?

**Comment by TintypeMolly** [comment]
@acusti not really. used different minify library.

**Comment by zmagyar** [comment]
I have ran into the same issue. I think much more projects are using webpack than browserify nowadays. It's a shame this minifier can not be used.

Actually the issue is not with webpack but with minifier/uglify. It does require the fs package for convenience only. I.e. the operation of uglify does not require fs, it is only used to create 'elegant' code. As the minifier uses a fork by @alexlamsl I think this is the right project to file the issue. 
I think it would be a really useful change to change that part as it is more important to allow the usage of the module than having an elegant code which saves a few lines.

**Comment by NandoSangenetto** [comment]
I have the same issue. 

I used webpack to build my react app for SSR, and I'm trying to minify my HTML on the fly using node with no success.

**Comment by TheoryOfNekomata** [comment]
I solved this issue by using `null-loader` on the path where the `main` file of `uglify-js` is loaded.

I added:

```
rules: [
  // ... some rules
  {
    test: path.resolve(__dirname, 'node_modules/uglify-js/tools/node.js'),
    loader: 'null-loader',
  },
  // ...some more rules
]
```

into my Webpack config.

I agree it is not something in `html-minifier` itself, but I think this is a solution nonetheless. Maybe this is an issue of the `main` files not being in the topmost directory of its `require()` s.
