### ISSUE TITLE
attribute draggable should be treated as enum

### ISSUE THREAD

**Issue by JeffGreat** [kangax/html-minifier#731]
'draggable="true"' is minified as 'draggable'. It shouldnt since it is not a boolean value but an enum. Browser like Chrome do not work if true value is not set clearly.
fyi: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

However some previous pull requests have already treated this problem. Dont know why it is still there.

**Comment by alexlamsl** [comment]
Just tested online, `<div draggable="true"></div>` gives `<div draggable=true></div>`. There is even [a test for it](https://github.com/kangax/html-minifier/blob/gh-pages/tests/minifier.js#L1358).

Please provide an example which demonstrates your issue?

**Comment by alexlamsl** [comment]
Closing as not reproducible.
