### ISSUE TITLE
Minifying removes some closing tags from the HTML

### ISSUE THREAD

**Issue by gespinha** [kangax/html-minifier#732]
Hi there,

I'm minifying a VisualForce component file, which is basically an HTML file, when parsed and for this to work, I'm minifying a file which needs to contain unusual stuff like closing `</meta>` tags and closing `</img>` tags, but attempting to minify these files, removes these closing tags.

I assume its because they are not parsed when following the HTML spec. Or is this a bug? If not, how can I solve this and prevent these closing tags from being removed?

Cheers,

**Comment by alexlamsl** [comment]
You can play around with various options [online](http://kangax.github.io/html-minifier/) to see which resolves your issue at hand.

A concrete example illustrating your problem would also be helpful.

**Comment by gespinha** [comment]
Thanks for the suggestion. I decided to go with a different grunt package instead. Thank you :)
