### ISSUE TITLE
Regular Expression backreference issue in ignoreCustomFragments

### ISSUE THREAD

**Issue by outaTiME** [kangax/html-minifier#733]
Hi Juriy, 

The regexp backreferences usage in `ignoreCustomFragments` was affected from 3.0.3 version, here my case:

```
{
  ignoreCustomFragments: [ /<(WC@[\s\S]*?)>(.*?)<\/\1>/ ]
}
```

The grouping update of regexp expression in the code below (`htmlminifier.js`) was the problem because the `\1` backreference points to first group and not to `ignoreCustomFragments` group expression (so logically my regexp stop working):

in v3.0.3:
https://github.com/kangax/html-minifier/blob/89c29688d84b97de949b47dda66e72201760048a/src/htmlminifier.js#L865

> new RegExp('\s_(?:' + customFragments.join('|') + ')+\s_', 'g')

in v3.1.0:
https://github.com/kangax/html-minifier/blob/969d21a0a86696d0bb148e3c6bd572bddd9049c5/src/htmlminifier.js#L872

> new RegExp('(\s_)(?:' + customFragments.join('|') + ')+(\s_)', 'g');

any plans of update ? 
Thks !!!

**Comment by alexlamsl** [comment]
I think the fix would be to manually extract the surrounding whitespaces instead of using the same regex. I will take a look when I get some spare cycles, but pull requests are always welcome :wink:
