### ISSUE TITLE
New line after <code> tag

### ISSUE THREAD

**Issue by kfuzaylov** [kangax/html-minifier#734]
I have html code with "code" tag
And it looks like this https://www.dropbox.com/s/nbkbsqu0kilkuad/origin.png?dl=0
After minification I got new line after "code" tag
And code now looks like that
https://www.dropbox.com/s/tvh08ocudro8gep/new-line.png?dl=0
So there is a space on code top.

I think would be nice to add some option to prevent this by tag name.

Thanks.

**Comment by alexlamsl** [comment]
Thank you for the images - but may I get the actual HTML markup so it's easier to see the issue at hand?

**Comment by alexlamsl** [comment]
Closing due to lack of response - please provide a test case so this can be investigated further.
