### ISSUE TITLE
html-manifier is chocking on esprima/doc/index.html

### ISSUE THREAD

**Issue by ampgcat** [kangax/html-minifier#74]
Warning: index.html
Parse Error: < 1) ? "baby" :
    (age < 5) ? "toddler" :
    (age < 18) ? "child": "adult";
....

I'm running html-minifier through grunt / grunt-contrib-htmlmin.

Please let me know if you need more info

**Comment by kangax** [comment]
Definitely need more info — an exact chunk of html that can't be parsed.

**Comment by ampgcat** [comment]
It seems to be choking around line 116 where it says

var str = (age < 1) ? "baby" :
    (age < 5) ? "toddler" :
    (age < 18) ? "child": "adult";

The following is the error message I get from grunt.

C:\test>grunt
Running "htmlmin:dist" (htmlmin) task
Warning: index.html
Parse Error: < 1) ? "baby" :
    (age < 5) ? "toddler" :
    (age < 18) ? "child": "adult";
</pre>

<p>which will yield the following report:</p>

...
I'm using removeComments: true, collapseWhitespace: true

I can send you the whole index.html etc. if you need..

**Comment by kangax** [comment]
index.html should do it

**Comment by ampgcat** [comment]
OK. Just sent it to your gmail account.

**Comment by kangax** [comment]
works for me when i paste it to http://kangax.github.io/html-minifier/

**Comment by ampgcat** [comment]
Mm. I just copy&paste'd the whole html using chrome and IE and pressing 'Minify' didn't return anything in the lower box for me.
If I copy&paste a simple html, i.e.
<!DOCTYPE html>
<html lang="en">
</html>
it does return someting in the lower box.
This makes me think it IS failing.
Do you mean you are getting something in the lower box?

**Comment by kangax** [comment]
@ampgcat Is this still happening? I'm closing this for now; will reopen if still an issue
