### ISSUE TITLE
IE Conditionals still failing.

### ISSUE THREAD

**Issue by BrokenEyesCode** [kangax/html-minifier#740]
Hi have the following in our html
```
<!--[if lte IE 8]>
    <!--#include virtual="includes/ie8-error.html"-->
<![endif]-->

```
When I try to minify this I get

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> Error: Parse Error: <![endif]-->

I thought this was solved in 1.3.0, but I'm still getting this error on 3.0.3.

**Comment by alexlamsl** [comment]
There's a HTML comment inside your example, so the parsing failed due to nested comment. PR to improve on this corner case is welcomed.

**Comment by alexlamsl** [comment]
Actually, just tested on IE11 and the example you've provided cannot be parsed by IE either.

![nested conditional](https://cloud.githubusercontent.com/assets/1898413/20089663/72ed79d4-a5c3-11e6-94c0-25f9297920f9.PNG)

So if this is some template syntax for server-side rendering, use `ignoreCustomFragments` to workaround this syntax problem.

**Comment by BrokenEyesCode** [comment]
It is indeed, its an apache server side include, works fine on IE9 (IE8 Document mode), its not supposed to be parsed for later browsers.  Thanks, I'll test your suggestion.
