### ISSUE TITLE
HTML code broken with a partial view of code (v3.1.1)

### ISSUE THREAD

**Issue by Odepia** [kangax/html-minifier#743]
Let's say I have a partial HTML file, like a footer include like so (footer.html):

```
      <form>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
        </div>
        <div class="form-group">
          <label for="exampleInputFile">File input</label>
          <input type="file" id="exampleInputFile">
          <p class="help-block">Example block-level help text here.</p>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </body>
</html>
```

Even with `includeAutoGeneratedTags: false`, the minified code is the following:

```
<form><div class=form-group><label for=exampleInputEmail1>Email address</label><input id=exampleInputEmail1 type=email class=form-control placeholder=Email></div><div class=form-group><label for=exampleInputFile>File input</label><input id=exampleInputFile type=file><p class=help-block>Example block-level help text here.</div><button class="btn btn-default"type=submit>Submit</button></form>
```

The tags `</body></html>` have been removed.

Any idea?

**Comment by alexlamsl** [comment]
By specifying the version, do you mean this is a regression, i.e. it works before in a previous version of `html-minifier`?

If I understand correctly, the parser would simply drop dangling end tags regardless of minifier options.

**Comment by Odepia** [comment]
I have that issue since version 3.0.0 which was the first version of html-minifier I used for my projects. I am not able to confirm if it is a regression or not, sorry :(

> If I understand correctly, the parser would simply drop dangling end tags regardless of minifier options.

Yes, correct.

**Comment by alexlamsl** [comment]
In that case it's probably a "feature" since the very beginning.

Pull request to improve on this situation is welcome, of course.

**Comment by Odepia** [comment]
Thank you for the (very) quick reply!

I hope a next release of html-minifier will fix that issue :)

**Comment by alexlamsl** [comment]
After playing around with this a bit, the major problem with supporting dangling close tags is that we've lost the context which the fragment is in, so options like `removeOptionalTags` won't work properly.
