### ISSUE TITLE
NPM package is broken

### ISSUE THREAD

**Issue by heatmonkey** [kangax/html-minifier#746]
ERR! fetch failed https://registry.npmjs.org/html-minifier/-/html-minifier-3.2.0.tgz
WARN retry will retry, error on last attempt fetch failed with status code 404

**Comment by heatmonkey** [comment]
This is a NPM issue, nevermind.

**Comment by alexlamsl** [comment]
See #745 - I have removed the latest release for now and wait for `npm` to settle down first.
