### ISSUE TITLE
Version mismatch on npm

### ISSUE THREAD

**Issue by ryexley** [kangax/html-minifier#750]
Looks like v3.2.0 was "released" sometime earlier today. Running `npm ls html-minifier` shows v`3.2.0` as the latest available version. However, looking at the package information on [the npm web site](https://www.npmjs.com/package/html-minifier) shows v`3.1.1` as the latest available of 48 releases. We're getting failures trying to install packages that depend on this that are attempting to install v`3.2.0` and it's unable to find it. Did something get unpublished from npm or something?

**Comment by alexlamsl** [comment]
See #745 and https://github.com/npm/registry/issues/85

Also http://status.npmjs.org/incidents/wx7mld1cj0vz

**Comment by ryexley** [comment]
Thanks for the update...sorry, I should've looked through previously closed issues before opening this one.

**Comment by alexlamsl** [comment]
3.2.2 is now published
