### ISSUE TITLE
IE warning HTML1410

### ISSUE THREAD

**Issue by soubok** [kangax/html-minifier#757]
I noticed the following warning message in the IE console (Edge):
`HTML1410 "Invalid unquoted attribute value. Unquoted attribute values should not contain ("), ('), (<), (=), or (`)."`

with the following HTML code:
`<link href=http://foo/?ln=fr rel=alternate hreflang=fr>`

**Comment by alexlamsl** [comment]
I tried `<link href="http://foo/?ln=fr" rel=alternate hreflang=fr>` and `html-minifier` does not remove the quotes. Please provide the input HTML which cause the output you've claimed.

**Comment by soubok** [comment]
sorry, it's my fault, my href attribute content is provide by `<?php ... ?>`, then you have no way to know 	
that my php script outputs `http://foo/?ln=fr`

eg. 
`<link href="<?php echo 'http://foo/?ln=fr' ?>" rel="alternate" hreflang="fr">`

however, I wondering if `ignoreCustomFragments` treats this case ?

**Comment by alexlamsl** [comment]
It would have already been captured by `ignoreCustomFragments`, and should not remove attribute quotes in that case.

I will have a look at what went wrong when I am in front of a computer. Thanks for the report!

**Comment by alexlamsl** [comment]
Should be fixed in `3.2.3`

**Comment by soubok** [comment]
thanks
