### ISSUE TITLE
Cannot find module 'internal/fs' 

### ISSUE THREAD

**Issue by dongyingzi** [kangax/html-minifier#758]
Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-contrib-htmlmin" "--save-dev"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by alexlamsl** [comment]
That's either `npm` or `grunt-contrib-htmlmin` - nothing I can help you with here.
