### ISSUE TITLE
Closing CDATA comment gets removed when minifyJS option is used

### ISSUE THREAD

**Issue by philippsimon** [kangax/html-minifier#763]
When minifying `XHTML` with `CDATA` comments inside the scripts always the ending `CDATA` comment gets deleted because of the following issue of uglifyjs: https://github.com/mishoo/UglifyJS2/issues/88

For our gulp minify task I used the following function to fix it.
Maybe it helps somebody:
```javascript
function fixScriptCDataComments() {
  return through.obj((file, enc, callback) => {
    file.contents = new Buffer(
      String(file.contents).replace(/(<script[^>]*>)\s*([\s\S]*?)\s*(<\/script>)/g,
        (match, openTag, tagContent, closeTag) => {
          if (tagContent.match(/^\/\*\s*<!\[CDATA\[\s*\*\//) && !tagContent.match(/\/\*\s*]]>\s*\*\/$/)) {
            return openTag + tagContent + '/*]]>*/' + closeTag;
          } else {
            return match;
          }
        })
    );
    return callback(null, file);
  });
}
```

**Comment by alexlamsl** [comment]
You may specify a `function()` to `minifyJS` to work around it. But based on the issue you quoted it's ultimately a bug/feature of `uglify-js`.

Closing, but thanks for the workaround which others might find useful :wink:
