### ISSUE TITLE
Parse Error - Square Brackets

### ISSUE THREAD

**Issue by CarbonFactory** [kangax/html-minifier#764]
name: 'Error',
  message: 'Parse Error: `<li if-authenticated=["Customer","Customer-Inventory-Invoice","Super-Admin","System-Admin"]>`

It fails to understand the square brackets.  The code was working with version 2 of gulp-htmlmin

Using `gulp-htmlmin` and `angular-validator` latest versions
Nodejs 5.1

**Comment by alexlamsl** [comment]
This isn't valid HTML to begin with, so I don't see why `html-minifier` would handle it in the first place.

Also, please specify the version of `html-minifier` which you believe to have worked.

**Comment by CarbonFactory** [comment]
Please close this. I refactored the attributes to valid HTML.
It was working with `NodeJS `4 and `html-minifier` version 2

**Comment by alexlamsl** [comment]
Tested on `html-minifier` with your example for `2.0.0` and `2.1.5` - `Parse Error` is thrown in both cases.

Glad to hear you have found a workaround for your issue. :+1:
