### ISSUE TITLE
files hosted on `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [kangax/html-minifier#766]
Hi, I'm from [cdnjs](https://github.com/cdnjs/cdnjs). Recently we want to add your lib to https://cdnjs.com, I want to confirm what files should be hosted on cdnjs. (shortly, we host files for browser use)
Do we only need to host the files under `dist`? Or we also need other files under `assets` or `src`?
Thank you very much!

https://github.com/cdnjs/cdnjs/issues/9834

**Comment by alexlamsl** [comment]
[`/dist/htmlminifier.min.js`](https://github.com/kangax/html-minifier/blob/gh-pages/dist/htmlminifier.min.js) should be the only file you need to use `html-minifier` within a web browser.

Everything else is just UI and Web Worker logic.

**Comment by alexlamsl** [comment]
Oh and of course if you want to use a specific version, use the tagged file, e.g. [for `3.2.3`](https://github.com/kangax/html-minifier/blob/v3.2.3/dist/htmlminifier.min.js)

**Comment by alexlamsl** [comment]
If you encounter any issues beyond the suggestion above, please reopen.

**Comment by maruilian11** [comment]
@alexlamsl thank you!

**Comment by zebapy** [comment]
@alexlamsl What function is exposed to window to even use minifier like this?
