### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'html5' in true

### ISSUE THREAD

**Issue by ForsakenHarmony** [kangax/html-minifier#768]
I'm not sure if you are using it the right way
[htmlminifier.js](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L613)

[in Operator (MDN)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in)

you may want to use [includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)?

and yes, I know I passed true instead of an object

**Comment by alexlamsl** [comment]
The code works as is. Please specify a test case which you expect to work but doesn't.
