### ISSUE TITLE
Feature Request: collapseBooleanAttributes Custom Regex

### ISSUE THREAD

**Issue by trisys3** [kangax/html-minifier#771]
We are using Angular in our project, which allows special JavaScript expressions in the HTML. This causes problems with some options, like `collapseBooleanAttributes`. For example, I added some elements that are supposed to be draggable depending on some condition, e.g.:

    <div draggable="{{ scopeCondition }}"></div>

When I minify this HTML with `collapseBooleanAttributes`, the `draggable` attribute collapses to an empty string:

    <div draggable></div>

depending on other minifier options. This means `draggable` is never `true`, no matter the value of `scopeCondition`, meaning the `<div>` can never be draggable.

As I said, I am using Angular, but I would think users of other libraries like Ember/Backbone would be similarly affected.

The simplest thing I can think of would be to add another option allowing for custom attribute values that will not be collapsed. This could be called, for example, `customBooleanAttributeCollapseRegex`, and would take a custom regular expression for attribute values that should not get minified, e.g. perhaps `/^\{\{\.*\}\}$/`.

One way to avoid this, at least in Angular, is to use the `ng-attr` syntax. For example,

    <div ng-attr-draggable="{{ scopeCondition }}"></div>

This `<div>` is now draggable, as long as `scopeCondition` is truthy in the current scope, whether before minification or after (I tried it, it works). I'm not sure if there are similar quick-fixes for other frameworks, like Ember.

**Comment by alexlamsl** [comment]
Even without `html-minifier`, use of template strings as boolean attribute values is [not recommended](https://docs.angularjs.org/guide/interpolation) ( see "Binding to boolean attributes")

**Comment by trisys3** [comment]
I was not talking about that kind of "boolean" attribute, whose presence means `true` and whose absence means `false`. I was talking about attributes like `autocomplete` or `draggable`, which can take actual values like `true` or `false`. These attributes do not have any special Angular helpers (well, except `ng-attr-`, which is more general-purpose). `html-minifier` still collapses these attributes if they have any value outside an `enum`. For example, for `draggable`, if the value is anything but `true` or `false`, it gets collapsed to the empty string.
