### ISSUE TITLE
Consider separating CLI.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [kangax/html-minifier#773]
And create something like `html-minifier-cli`.  `clean-css` actually did [something like this](https://github.com/jakubpawlowicz/clean-css/commit/2b5e3f3d5244c8f20409d88d747d4c35bc292507) a couple of days ago.

**Comment by timreichen** [comment]
This tool should include the cli interface, not have a separate package for it. Look at [crisper](https://github.com/PolymerLabs/crisper) or [browserify](https://www.npmjs.com/package/browserify) for example.
The structure of a package should be something linke this:
![structure](https://cloud.githubusercontent.com/assets/14932257/25696053/fff7dbb2-30b5-11e7-96e5-f70bf3634283.png)
