### ISSUE TITLE
Major clean-css version bump caused a weird issue

### ISSUE THREAD

**Issue by web-padawan** [kangax/html-minifier#774]
Today I faced a bug brought up by `clean-css` 4.
All `@apply` rules are collapsed and some selectors broken.

Se pretty-printed version of an example below:

Before:
```
:host .icon-search {
  width: 15px;
  height: 15px;
  margin-right: 4px;
  fill: var(--filter-input-icon-color)
}
:host .filter-input {
  @apply(--filter-input)
}
```

After:
```
:host .icon-search {
  width: 15px;
  height: 15px;
  margin-right: 4px;
  fill: var(--filter-input-icon-color) @apply(--filter-input)
}
```
I use `gulp-htmlmin` which version is pinned, but it has resolved to `html-minifier` 3.3.0
Consider making a major version bump when upgrading dependencies to their major versions.

**Comment by alexlamsl** [comment]
I see you have reported the issue to `clean-css` already. Closing.
