### ISSUE TITLE
minifyJS not removing comments

### ISSUE THREAD

**Issue by Somebi** [kangax/html-minifier#776]
How to pass options for uglify js?

**Comment by alexlamsl** [comment]
I just tried the following example with `minifyJS:true`
```html
<script>
// comment
console.log();
</script>
```
And it correctly gives:
```html
<script>console.log()</script>
```
Can you give an example of your problem?

**Comment by Somebi** [comment]
Strange indeed. Now it's gone for me too... Sorry then, close this issue. I'll open and post examples if I'll spot that issue again.
