### ISSUE TITLE
non-breaking spaces are being rewritten to spaces

### ISSUE THREAD

**Issue by bradvogel** [kangax/html-minifier#777]
When using `collapseWhitespace:true` and `conservativeCollapse:true` options, I'm seeing that non-breaking spaces (character code `160`, represented as `\u00A0` below) are being incorrectly converted to regular spaces (character code `32`). This isn't expected and can alter the presentation of the html - especially when the html is sent in an email. Some email clients such as gmail will collapse paragraphs with regular spaces.

```
$ node
> require('html-minifier').minify('<p>\u00A0</p>').charCodeAt(3)
160 // This is correct - a non-breaking space.
> require('html-minifier').minify('<p>\u00A0</p>',{collapseWhitespace:true, conservativeCollapse: true}).charCodeAt(3)
32 // This should be 160, a non-breaking space. Instead it's a regular space.
```

**Comment by alexlamsl** [comment]
Thanks for the report - fixing via #780.

**Comment by bradvogel** [comment]
Thanks! Mind rereleasing on npm?

**Comment by alexlamsl** [comment]
Working on it 😉

**Comment by alexlamsl** [comment]
`3.3.1` is released - please test and ensure it works for you 😉

**Comment by jacksonp** [comment]
I think this is still an issue:

```
$ html-minifier -V
3.3.1
$ cat -v nbsp_test.html
<p> M-BM-  M-BM-  test
$ html-minifier --collapse-whitespace --conservative-collapse nbsp_test.html | cat -v
<p>M-BM- test </p>
```
(`cat -v` shows non-breaking spaces as `M-BM- `.)

**Comment by alexlamsl** [comment]
Do the original input and minified output render differently on a web browser?

**Comment by jacksonp** [comment]
Yes.

Can't attach .html files here, but nbsp_test.html renders the same as `<p> &nbsp; &nbsp; test` and the html-minifier output renders the same as `<p>&nbsp;test`.

**Comment by alexlamsl** [comment]
@jacksonp you can paste the contents here using ` ```html\n<content\n>\n``` `

I have had a quick look and see an issue, but will need to know all the possible outputs so I can come up with a proper fix. But let's reopen this for now.

**Comment by jacksonp** [comment]
3.3.2 fixes it. Nice one, thanks.
