### ISSUE TITLE
Handlebar regex from command line?

### ISSUE THREAD

**Issue by benguild** [kangax/html-minifier#778]
I have a template that I'm trying to minify in a build script. However, it has curly brace elements `<html>{{ something }}<a{{ if }} href="test"{{ end }}>test</a></html>"`, etc. and whenever I use the instructions **[here](https://github.com/kangax/html-minifier/wiki/Minifying-Handlebars-templates)** to avoid these from the command-line, I get:

```
Cannot read property 'source' of undefined
```

...I'm assuming this is user error. Here's the command I'm attempting:

```
html-minifier --file-ext html --custom-attr-surround '[[/\{\{#[^}]+\}\}/, /\{\{\/[^}]+\}\}/]]' --input-dir tmpl/ --output-dir tmpl-min/
```

Wasn't sure if broken or if this is something I've done incorrectly here. I'm happy to update the wiki with cli instructions if you're able to assist. Thanks in advance.

**Comment by alexlamsl** [comment]
Try [`ignoreCustomFragments`](https://github.com/kangax/html-minifier#options-quick-reference) with `[/{{[\s\S]*?}}/]`?

**Comment by benguild** [comment]
@alexlamsl Getting "Parse Error:" with that after " --ignore-custom-fragments" ... outputs the entire body of the file. For other files, it's just generating empty HTML files.

**Comment by alexlamsl** [comment]
I tried your example above and haven't got any errors:
```
$ echo '<html>{{ something }}<a{{ if }} href="test"{{ end }}>test</a></html>' | html-minifier --ignore-custom-fragments ["{{[\s\S]*?}}"]
<html>{{ something }}<a {{ if }} href="test" {{ end }}>test</a></html>
```

**Comment by benguild** [comment]
Ah, I see. That does work. However, with quotes in it... it chokes:

```bash
echo '<h4{{ if "1" }}>' | html-minifier --ignore-custom-fragments ["{{[\s\S]*?}}"]
```

I'm wondering about other edge-cases, as well.

**Comment by alexlamsl** [comment]
That's because your command line isn't escaping the string correctly. I'm on Windows, and my version of the command looks like this:
```
html-minifier --ignore-custom-fragments "[""{{[\\s\\S]*?}}""]"
```

**Comment by alexlamsl** [comment]
I use the API myself most of the time, and not so well-versed with character escaping rules on difference OSes command line interfaces. But essentially `html-minifier --ignore-custom-fragments` wants a JSON representation of an array of strings which corresponds to the regex's.

Alternatively, you can supply a JSON configuration file via `html-minifier -c <.conf>` - see https://github.com/kangax/html-minifier/blob/gh-pages/sample-cli-config-file.conf for such an example.

**Comment by alexlamsl** [comment]
Closing as resolved - please reopen if otherwise.

**Comment by benguild** [comment]
That works well. Thanks

**Comment by jfoclpf** [comment]
FYI I've been using this and so far it's working fine:

`--ignore-custom-fragments "/{{[{]?(.*?)[}]?}}/"`
