### ISSUE TITLE
Extra whitespace before `doctype` when `Conservative collapse` is true

### ISSUE THREAD

**Issue by sparanoid** [kangax/html-minifier#779]
Tested [here](http://kangax.github.io/html-minifier/):

Input (with `Conservative collapse` enabled):

```html
 <!doctype html>
<p>Auto generated HTML</p>
```

Output:

```html
 <!DOCTYPE html> <p>Auto generated HTML
```

Expected:

```html
<!DOCTYPE html> <p>Auto generated HTML
```

**Comment by alexlamsl** [comment]
I've performed the same test with either default options or just `collapseWhitespace` and both gave me the correct results, i.e. no initial whitespace.

Outputs are `<!DOCTYPE html><p>Auto generated HTML` and `<!doctype html><p>Auto generated HTML</p>` respectively. Note there isn't even a whitespace between `<!DOCTYPE html>` and `<p>` - are you sure you have enabled `collapseWhitespace` and that those are actually `"\x20"`?

**Comment by sparanoid** [comment]
hi @alexlamsl sorry it's my mistake, the actual option is `Conservative collapse`, when this option is enabled, you can reproduce the above issue.

**Comment by alexlamsl** [comment]
This is working as expected then - `conservativeCollapse` [will always leave one space behind.](https://github.com/kangax/html-minifier#options-quick-reference)

**Comment by sparanoid** [comment]
@adamchal yeah after enabling `conservativeCollapse` it is working, but I think the additional space before `<!doctype` should be removed, it is not represented as anything (ie text node) in document tree.

**Comment by alexlamsl** [comment]
`conservativeCollapse` is for the conservative case, since people might be feeding `minify()` with fragments of the document. Either case, it's only one byte (or two if you have another one at the end), so I don't think it's worth the extra logic.

(I'm assuming you are addressing me in the comment above.)
