### ISSUE TITLE
can't import within create-react-app 

### ISSUE THREAD

**Issue by zebapy** [kangax/html-minifier#781]
While using [create react app](https://github.com/facebookincubator/create-react-app) I'm trying to do `import { minify } from 'html-minifier';` but am getting an error:

```
Warning in ./~/clean-css/lib/optimizer/level-2/properties/override-properties.js
Critical dependencies:
14:28-35 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/clean-css/lib/optimizer/level-2/properties/override-properties.js 14:28-35
```

Also tried `var minify = require('html-minifier').minify;`

Browser console says `Uncaught SyntaxError: Unexpected token !           override-properties.js:14 `

Also, I can `import CleanCSS from 'clean-css';` just fine.

**Comment by alexlamsl** [comment]
(Presumably you are asking the same question as https://github.com/kangax/html-minifier/issues/766#issuecomment-278663295 )

Are you trying to use `html-minifier` in the web browser? If so, please pick up a copy from [here](https://github.com/kangax/html-minifier/tree/gh-pages/dist).

**Comment by zebapy** [comment]
Not necessarily. If the import worked, I should be able to use the `minify` function. 

As for including the script in the browser via a `<script src="">` tag, what global function is exposed and intended to be used? I'm trying to look at the example in `assets` but it's using `require` in the browser?

**Comment by alexlamsl** [comment]
The [online version](http://kangax.github.io/html-minifier/) uses the file I mentioned above to function. Refer to https://github.com/kangax/html-minifier/blob/gh-pages/assets/master.js for a good example on how it is used.

**Comment by GendelfLugansk** [comment]
@zebapy Did you find a workaround? I also have issues importing `html-minifier` but I'm using ember-cli

**Comment by GendelfLugansk** [comment]
UPD: replacing `require` with `requireMinify` in [htmlminifier.js](https://github.com/kangax/html-minifier/blob/gh-pages/dist/htmlminifier.js) and then importing it like `const htmlMinifier = window.requireMinifier('html-minifier');` seems to work for me. But when replacing one should be careful about words `required` and `requires`.
