### ISSUE TITLE
Parse Error - Not fully sure where making mistake

### ISSUE THREAD

**Issue by SSAT** [kangax/html-minifier#787]
Here is error from console when run the gulp. Any help will be appreciated.

```
\Projects\Git-Source\gsapp\node_modules\map-stream\index.js:103
        throw err
        ^
Error: Parse Error: <
<p id="index17"><strong>slok mÚ 5 ]</strong>Drix suvMnI KV rqn jVwvI hir pRym purKu min vuTw ]<br>
sBy kwj suhylVy QIey guru nwnku siqguru quTw ]1]</p>
```

**Comment by alexlamsl** [comment]
`<` is not valid HTML - use `&lt;`

**Comment by SSAT** [comment]
Thanks @alexlamsl , but I'm not seeing where is the extra "<" is to replace with &lt;. I'm using just the html tag. Can you please elaborate on the solution. I will appreciate it.

**Comment by alexlamsl** [comment]
That first character right after `Parse Error:` in the error message?
