### ISSUE TITLE
Is html-minifier have reserved name list ?

### ISSUE THREAD

**Issue by ausir0726** [kangax/html-minifier#794]
When I use compress html 
```
<div class="add">test</div>
```
it will have an error
```
TypeError: b[c].push is not a function
```
I found that because class name `add` is reserved name .
I guess that will trigger some add function.
I know that is not a good class name design ,
but I got template from other guy , so I need fix it ,
just want ask is html-minifier have reserved name list .
and is this error need a clear error message ? ( because my template is not simple like my example )

thanks .

**Comment by alexlamsl** [comment]
From what you described this looks like a bug with `html-minifier`. I shall investigate and work on a patch.

Thanks for the report.
