### ISSUE TITLE
Despite minifyCss set to false, inlined styles gets modified

### ISSUE THREAD

**Issue by PEM--** [kangax/html-minifier#798]
When minifying this with `minifyCss: false`:
```
<p style="background-color:blue;color:red;">Test</p>
```
The output is changed and the last `;` in the inline style gets removed leading to reconciliation errors in React. While removing the last `;` is a neat feature, when the `minifyCss` is `false`, the inline style should not be altered.

Referenced errors:

* https://github.com/facebook/react/issues/9353
* https://github.com/ssrwpo/ssr/issues/45

**Comment by alexlamsl** [comment]
Sounds reasonable - PR is welcomed.

**Comment by petermikitsh** [comment]
This creates integration issues with react server-sider rendering. Right now, I'm only observing those issues in Firefox. The markup is reusable in Chrome + Safari.

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ="background:#0C8DCE;" data-reactid="5">
 (server) ="background:#0C8DCE" data-reactid="5"><
```

I guess those trailing semicolons do matter.

**Comment by buildbreakdo** [comment]
@petermikitsh Have this issue in Chrome as well. Unclear how to configure html-minifier to leave trailing semicolon alone in the style attribute, @alexlamsl is the referenced issue a proposed fix?

**Comment by DChristiany** [comment]
I have created a fork (found here: https://github.com/DChristiany/html-minifier), that offers a configuration option, that does not remove trailing semicolons.
Should I just create a Pull Request (sorry, i'm new to working on open source projects).
