### ISSUE TITLE
Support IE "Downlevel-revealed Conditional Comments"

### ISSUE THREAD

**Issue by kangax** [kangax/html-minifier#8]

**Comment by willfarrell** [comment]
Is this related to https://github.com/kangax/html-minifier/pull/38?

**Comment by willfarrell** [comment]
Sorry, commented too soon. Does anyone even use these?

http://en.wikipedia.org/wiki/Conditional_comment#Downlevel-revealed_conditional_comment

**Comment by dben** [comment]
Yes, they are pretty frequently used to shim old versions of ie so they work correctly with html5 features/ JSON support

**Comment by cloudgifts** [comment]
Is there a solution here?

**Comment by kangax** [comment]
Haven't had a chance to look into this yet. Patch is, as always, welcome.
