### ISSUE TITLE
htmllint.js deserves its own module

### ISSUE THREAD

**Issue by eerne** [kangax/html-minifier#80]
It would be nice to separate htmllint.js form html-minifier returning results as json object. That way it could be useable with mocha and friends.

**Comment by nikgraf** [comment]
@kangax need some help here? Exposing it as separate npm module would be nice & then you could add it as dependency for the minifier.

**Comment by kangax** [comment]
@nikgraf Sure, I would _love_ some help with this!

**Comment by nikgraf** [comment]
What about you create a repo or an organization with a repo and I will do some pull requests?

**Comment by kangax** [comment]
@nikgraf I created html-lint repo and just imported html-minifier in there (to have some kind of foundation and already existing lint files/test) — https://github.com/kangax/html-lint

Please feel free to delete all the unnecessary stuff.

**Comment by alexlamsl** [comment]
@kangax I'm guessing we need a resync or recreate that repo?

Current plan of action:
- clone `html-minifier` as `html-lint`
- refactor `html-lint` to depend on `html-minifier`
- strip `HTMLLint` from `html-minifier`

**Comment by kangax** [comment]
Sounds good to me!

**Comment by alexlamsl** [comment]
May I get write permission to html-lint?

**Comment by kangax** [comment]
Added

**Comment by alexlamsl** [comment]
`html-minifer-lint` now done and online https://github.com/kangax/html-lint/pull/1

Next up - removing `HTMLLint` from here...
