### ISSUE TITLE
es6 template literals in html markup

### ISSUE THREAD

**Issue by orneryd** [kangax/html-minifier#801]
I have a case where I am using es6 template literals within markup to perform runtime interpolation on templates

in certain cases this is fine
```html
<div attr="${this.value}">${this.text}</div>
```
 I had to add a minifyCSS override to get it to not strip out partial style blocks
```javascript 
minifyCSS: function(css){
  return css;
}
```
which made this possible:
```html
<div style="color: ${this.textColor}">${this.text}</div>
```
Now I am having trouble getting this to work
```html
<input type="checkbox" class="input-${this.type}" name="${this.type}" id="${this.id}"
       value="${this.value}" ${this.addAttr ? 'attr="val"' : ''}/>
```
the attribute values are fine, it's the ternary syntax at the end it is having trouble with because this works fine:
```html
<input type="checkbox" class="input-${this.type}" name="${this.type}" id="${this.id}"
       value="${this.value}" ${this.addAttr}/>
```
I added a customAttrSurround regex to attempt to handle the syntax
```javascript
let minifyOptions   = {
  customAttrSurround: [/\$\{(.*?)}/g],
  processConditionalComments: true,
  collapseWhitespace: true,
  removeComments: true,
  minifyCSS: function(css){
    return css;
  }
};
```
but it fails here:
```bash
Error: Parse Error: <input type="checkbox" class="input-${this.type}" name="${this.type}" id="${this.id}"
       value="${this.value}" ${this.addAttr ? 'attr="val"' : ''}/>
at new HTMLParser (/usr/local/lib/node_modules/gmst/node_modules/html-minifier/src/htmlparser.js:235:13)
    at minify (/usr/local/lib/node_modules/gmst/node_modules/html-minifier/src/htmlminifier.js:954:3)
    at Object.exports.minify (/usr/local/lib/node_modules/gmst/node_modules/html-minifier/src/htmlminifier.js:1307:10)
...
```

The documentation around how to create custom regex could probably use a little updating. Any assistance would be greatly appreciated

**Comment by alexlamsl** [comment]
`${this.addAttr ? 'attr="val"' : ''}` within a tag is definitely not compliant with any HTML specifications. Read up on `ignoreCustomFragments`.

Any pull request to improve documentations are always welcome.

**Comment by orneryd** [comment]
So i am trying to figure out what kind of regex is needed. where does it start looking? do i need to include the entire tag or can it be a part of the tag?
```
ignoreCustomFragments	Array of regex'es that allow to ignore certain fragments, when matched (e.g. <?php ... ?>, {{ ... }}, etc.)	[ /<%[\s\S]*?%>/, /<\?[\s\S]*?\?>/ ]
```
do I need a different regex? because this doesn't work
```javascript
    ignoreCustomFragments: [/\$\{.*?}/],
```

Edit: I realize that it's not html compliant. The templates are getting wrapped up into template literal strings, put into javascript and then processed before being inserted into the dom. I'm doing this in favor of pulling in a templating framework.

**Comment by orneryd** [comment]
I also tried this:
```
    ignoreCustomFragments: [/<.*\$\{.*?}.*>/],
```
no dice, I also tried making certain parts lazy, no dice.

**Comment by sumbad** [comment]
Try to use this:
`ignoreCustomFragments: [ /<%[\s\S]*?%>/, /<\?[\s\S]*?\?>/, /\$\{[\s\S]*?\}/ ]`
It allows you to use es6 template literals in html markup.

**Comment by jrussellsmyth** [comment]
@sumbad your regex fails on nested es6 literals
