### ISSUE TITLE
xml-safe rules for sitemap.xml?

### ISSUE THREAD

**Issue by ralyodio** [kangax/html-minifier#802]
Is it possible to get XML-safe minification for a sitemap.xml file I'm generating?

I would need the XML doctype and quotes intact. Pretty much just whitespace trimming.

**Comment by alexlamsl** [comment]
Without any example input, expected/actual output I wouldn't know what you are referring to.

In any case, `collapseWhitespace` alone would seem to fit your description.

Closing as this isn't an issue per se with `html-minifier`.
