### ISSUE TITLE
htmlmin auto remove Closed label, E.g /

### ISSUE THREAD

**Issue by andy-huaan** [kangax/html-minifier#803]
Automatically deleting the end tag results in an error E.g / in thymeleaf project
**1.Before compression**
```
<!DOCTYPE html>
<html lang="zh" xmlns:th="http://www.thymeleaf.org/">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
    <input />
</body>
</html>
```
**2.After compression**
`<!DOCTYPE html><html lang="zh" xmlns:th="http://www.thymeleaf.org/"><meta name="viewport" content="width=device-width,initial-scale=1"><input>`
Since there is no end tag /，thymeleaf project,wechat project can not run

**Comment by alexlamsl** [comment]
It is valid HTML to omit `/` in self-closing elements - the parser you are using with the minified output is not compliant and needs to be fixed.

Alternatively, read https://github.com/kangax/html-minifier#options-quick-reference which provides an option named `keepClosingSlash`.

**Comment by andy-huaan** [comment]
Solved, Thank you!

**Comment by goumang2010** [comment]
<img width="1431" alt="2018-06-29 9 27 48" src="https://user-images.githubusercontent.com/12218607/42094747-51b19438-7be3-11e8-8f9f-e5b622da41cd.png">


Why keepClosingSlash not work? @alexlamsl

**Comment by HadiChen** [comment]
> <img alt="2018-06-29 9 27 48" width="1431" src="https://user-images.githubusercontent.com/12218607/42094747-51b19438-7be3-11e8-8f9f-e5b622da41cd.png">
> 
> 为什么keepClosingSlash不起作用？@alexlamsl

I also encountered this problem, how can I solve it?
