### ISSUE TITLE
Strips some complete style rules

### ISSUE THREAD

**Issue by jpodwys** [kangax/html-minifier#804]
#### Issue

When I run `iron-list` through `html-minifier` with the `minifiCSS` flag enabled, it removes [this entire style rule](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L260-L266). (I understand that I may need to submit this issue to `clean-css`, but I want to start here.)

#### Steps to Reproduce

1. Copy the raw `iron-list` markup [from here](https://raw.githubusercontent.com/PolymerElements/iron-list/master/iron-list.html) to your clipboard
2. Go to [https://kangax.github.io/html-minifier/](https://kangax.github.io/html-minifier/)
3. Paste the `iron-list` markup
4. Click "Minify"
5. Notice that the output is missing [this entire style rule](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L260-L266)

#### Expected Outcome

The style rule should not have been removed. I've confirmed that leaving the `minifyCSS` config `false` fixes the issue, but it also comes with the side effect of no longer minifying any CSS. Is there a way that I can both enable CSS minification and not have that style block removed?

Thanks for your help!

**Comment by alexlamsl** [comment]
`html-minifier` relies on `clean-css` to perform `minifyCSS` - can you verify this is reproduced on `clean-css` and if so, file an issue with them instead?

**Comment by jpodwys** [comment]
Looks like it was actually due to [a bug](https://github.com/PolymerElements/iron-list/issues/387) in the version of `iron-list` I was using. It's been addressed. now.
