### ISSUE TITLE
Quote matching issue in ignoreCustomFragments

### ISSUE THREAD

**Issue by silverwind** [kangax/html-minifier#805]
Given this Handlebars template as input:

````html
<span class="{{classes}}"></span>
````

When `removeAttributeQuotes: true` is set, the quotes will (presumably rightfully) be removed giving this result:

````html
<span class={{classes}}></span>
````

To keep the quotes (because the variable can resolve to a value containing spaces) I added `ignoreCustomFragments: [/"\{\{.*?\}\}"/]`, which results in double double-quotes like in the result:

````html
<span class=""{{classes}}""></span>
````

Is that expected? It seems the value of `removeAttributeQuotes` has no effect on these quotes.

**Comment by alexlamsl** [comment]
You've included the quotes within `ignoreCustomFragments`, so yeah `html-minifier` won't see the existing quotes anymore and will add a new pair like so.

Does `ignoreCustomFragments: [/\{\{.*?\}\}/]` (without the quotes in the RegExp) not work for you somehow?

**Comment by silverwind** [comment]
Unfortunately not, with your regex, I get a weird space introduced:

````html
<span class="sprite sprite-{{sprite}}"></span>
````

turns into

````html
<span class="sprite sprite- {{sprite}}"></span>
````

**Comment by alexlamsl** [comment]
I see - that would be the issue as that extra whitespace shouldn't be there.

Let me see if I can fix that.

**Comment by alexlamsl** [comment]
I started investigating this but failed to reproduce the whitespace as you described:
```js
$ node
> var minify = require('.').minify
> minify(`
  <span class="sprite sprite-{{sprite}}"></span>
  <span class="{{sprite}}"></span>
`,{
  ignoreCustomFragments: [/{{.*}}/],
  collapseWhitespace: true,
  removeAttributeQuotes: true
})
'<span class="sprite sprite-{{sprite}}"></span><span class="{{sprite}}"></span>'
```

Can you specify the options which produce the extraneous whitespace in your example?

**Comment by silverwind** [comment]
Here are the minimal options with which I can reproduce:

````js
const minify = require('.').minify;

const opts = {
  collapseWhitespace: true,
  ignoreCustomFragments: [/{{.*?}}/],
  sortClassName: true,
};

console.log(minify(`
  <span class="sprite sprite-{{sprite}}"></span>
  <span class="{{sprite}}"></span>
`, opts));
````
Which logs:
````html
<span class="sprite sprite- {{sprite}}"></span> <span class="{{sprite}}"></span>
````

**Comment by alexlamsl** [comment]
@silverwind thanks for the information and sorry for the delay.

I would be grateful if you can verify whether #807 addresses your particular use case.
