### ISSUE TITLE
Removing logs, debuggers, alerts.

### ISSUE THREAD

**Issue by rajeshwar-fissionlabs** [kangax/html-minifier#806]
I would like to remove console logs from the build folder, which will be used for production environment. I would like to remove `console.log`, `window.console.log`, `debugger`, `alerts` using a set of configuration properties.

May be for a few environments, i may need, alerts but not console logs. So if there is a configuration setup, it would help to customise these things.

**Comment by alexlamsl** [comment]
`html-minifier` uses `uglify-js` to compress JavaScript snippets within the HTML input, so any customisation can be configured through `minifyJS` which will get passed through.

And if you can't find what you want from there, file an issue with https://github.com/mishoo/UglifyJS2/issues instead.
