### ISSUE TITLE
Remove tab and newline in attribue

### ISSUE THREAD

**Issue by vanduc1102** [kangax/html-minifier#810]
Hi all, 

I have code like this:

```javascript
var minify = require('html-minifier').minify;
var html = '\r\n<div class=\"ele-tag\r\n\r\n\t\t\tcustomClass\"\r\n\t\t\t\t\t><a class=\"ele-tag_wrapper\" href=\"#\"\r\n\t\t>\r\n\t\t\t\r\n\t<\/div>';
var result = minify( html, {
    collapseWhitespace: true,
    removeAttributeQuotes: true,
    removeEmptyAttributes: true,
    removeComments: true,
    sortAttributes: true,
    sortClassName: true,
    collapseInlineTagWhitespace: true
});
console.log("result : ",result);
```

with version *3.4.3* 
output: `result :  <div class="customClass ele-tag"><a class=ele-tag_wrapper href=#></a></div>
`

version *3.4.4* or *3.5.0*:
output: `result :  <div class="ele-tag                   customClass"><a class=ele-tag_wrapper href=#></a></div>
`

It causes of errors in my *nodejs-tap* testcase.
Could you please check?

**Comment by alexlamsl** [comment]
This is a side effect of fixing #805.

AFAICT the new output is still correct, so I think you can safely adjust your test case to this new behaviour.

**Comment by alexlamsl** [comment]
Please let me know if my analysis is amiss to re-open this issue.

**Comment by vanduc1102** [comment]
the issue is on 3.5.0 which release 13 hours ago, but #805 was closed 10 days ago, I think you should reopen the issue

**Comment by alexlamsl** [comment]
As you said, `3.4.4` was also affected, which released a while back. That is the release which carries the fix for #805.

**Comment by vanduc1102** [comment]
both `3.4.4` and `3.5.0` do not work, you can test with my code in the description

**Comment by alexlamsl** [comment]
What do you mean by "not work"? It produces valid HTML AFAICT.

Different, but valid.

**Comment by alexlamsl** [comment]
Because `\t` are used to pad around custom fragments during transformation, `sortClassName` would give sub-optimal results after the fix for #805. But as long as it is still valid HTML and renders identically, it is an acceptable outcome.

Unless you are claiming your example output actually isn't valid HTML or gives a different rendering in a web browser, please update your own test case to adjust to this new behaviour.

**Comment by vanduc1102** [comment]
ok, I was thinking `3.4.3` and `3.4.4` or `3.5.0` should procedure the same result. because in my testcase I generated the `html` code from `jade` and `html.twig` and compare strings of result by string equals ,some tabs was added to make code easy to read, so with version `3.5.0` my testcase doesn't work anymore.

**Comment by alexlamsl** [comment]
The trade-off was made to fix a correctness issue, which is more important than optimal output.

I do understand why your test case failed, and sorry for the inconvenience it caused. I believe updating your test case is the correct solution in this scenario.
