### ISSUE TITLE
Strip CSS Comments from Style Tags

### ISSUE THREAD

**Issue by jogibear9988** [kangax/html-minifier#815]
Is it possible to remove Comments from inline Styles?

In my document created from polymer build, this seems not to work...

**Comment by alexlamsl** [comment]
`minifyCSS` is the option - please post a reproducible case if you believe it is not working for you.

**Comment by jogibear9988** [comment]
look at this html:

        <!DOCTYPE html><html><head><meta charset="utf-8"><title>MCC</title><style>/*! blabla */html{line-height:1.15;}</style><body>test 1234</body></html>

the comment blabla is not removed, used commandline:

        html-minifier --collapse-whitespace --collapse-inline-tag-whitespace --remove-comments --minify-js true --minify-css true

**Comment by alexlamsl** [comment]
IIRC `/*!` is special and is retained by `clean-css` by default.

Consult https://github.com/jakubpawlowicz/clean-css for the option to pass to `minifyCSS` to remove all comments.

**Comment by jogibear9988** [comment]
i've found it! but how can i add a paremter to html-minifier commandline?

doing like this:

     --minify-css {"level":{"1":{"specialComments":0}}}

does not work

**Comment by jogibear9988** [comment]
solved:

this works:

      --minify-css {\"level\":{\"1\":{\"specialComments\":0}}}

**Comment by jogibear9988** [comment]
One more Question, my Javascript inside the html seems not to be minimized (code is intended). How can I setup this correctly?

     --minify-js {\"output\":{\"beautify\":false,\"indent_level\":0}}

seems not to work... ;-(

**Comment by alexlamsl** [comment]
Try `--minify-js` alone, i.e. with default options?

Otherwise, please post the example which you believe isn't working.

**Comment by alexlamsl** [comment]
Closing as it doesn't look like an issue with `html-minifier`.

Do continue with any questions on how to use various options.

**Comment by jogibear9988** [comment]
I've tried minimize js alone, but the js in my html file still has comments and spaces... i'll post a example

**Comment by jogibear9988** [comment]
Can I post my HTML File anywhere? Some of the js in the file is minizied, some not.... But it's 6MB (or 600 kb 7zipped)

**Comment by alexlamsl** [comment]
Even if you upload it, I won't be able to read such a huge file.

Can you reduce that down to a minimal test case which illustrates the issue?

**Comment by jogibear9988** [comment]
I can not reproduce i a small file.

I've uploaded it, maybe you see something that is wrong in my file?

[index-compiled.new.zip](https://github.com/kangax/html-minifier/files/1031011/index-compiled.new.zip)
