### ISSUE TITLE
trimCustomFragments and content in quotes

### ISSUE THREAD

**Issue by silverwind** [kangax/html-minifier#820]
I wonder if it's somehow possible to tell `trimCustomFragments` to not trim inside quotes. Example:

````js
"use strict";

console.log(require('.').minify(`
  <div id="list {{name}}-list">
    {{name}}
  </div>
`, {
  ignoreCustomFragments: [/{{.*?}}/],
  collapseWhitespace: true,
  trimCustomFragments: true,
}));
````

This results in a broken class attribute:

````html
<div class="list{{name}}-list">{{name}}</div>
````

With `trimCustomFragments` set to `false`, the class is correct, but there's whitespace (which leads to unwanted text nodes being created) on the tag content:

````html
<div class="list {{name}}-list"> {{name}} </div>
````

I also attempted to set `ignoreCustomFragments` to include quotes through `[/".*?{{.*?}}.*?"/]`, but that leads to a double quoting issue (while trimming correctly):

````html
<div class=""list {{name}}-list"">{{name}}</div>
````

**Comment by silverwind** [comment]
I'm working around this now by using this replacement after `.minify`:

````js
> " {{a}} <a> {{b}} </a> {{c}} ".replace(/(>|^|}}) ({{|<|$)/g, "$1$2")
'{{a}}<a>{{b}}</a>{{c}}'
````

**Comment by alexlamsl** [comment]
`trimCustomFragments` is applied without any semantic knowledge, i.e. whether it's within an attribute value or a text node, so at least extending that would involve some heavylifting.

Having said that, with your example above I can get it to work with `ignoreCustomFragments` set to `[/[^"']*?{{.*?}}[^"']*(?=["'])/]`

**Comment by alexlamsl** [comment]
May need to employ `[^<>"']` for fun and profit in the general case.

**Comment by silverwind** [comment]
> trimCustomFragments is applied without any semantic knowledge, i.e. whether it's within an attribute value or a text node, so at least extending that would involve some heavylifting.

Adding this knowledge to `trimCustomFragments` sounds like a proper solution. I think `collapseWhitespace` already works like that (e.g. it knows if trimmable whitespace is in a attribute value or not).

**Comment by alexlamsl** [comment]
Anything to do with custom fragments is orthogonal to any valid HTML - think of it as a pre-processor that generates valid HTML for the rest of optimisations to proceed, then restore the broken pieces at the very end.

**Comment by silverwind** [comment]
By the way: Your regex seems to have a few unintended matches 😉 

https://regex101.com/r/COQsIr/1

**Comment by alexlamsl** [comment]
> Your regex seems to have a few unintended matches.

Not surprised - it was a hack to demonstrate a potential solution :ghost: 

But my comment above just reminds me of something - your input isn't invalid HTML to begin with, so why use custom fragments at all?
```js
require('.').minify(`
  <div id="list {{name}}-list">
    {{name}}
  </div>
`, {
  collapseWhitespace: true
});
```
gives:
```html
<div id="list {{name}}-list">{{name}}</div>
```

**Comment by silverwind** [comment]
Indeed it's not neccesary in that example, but I have it there to guard against issues like [this one](https://github.com/kangax/html-minifier/wiki/Minifying-Handlebars-templates#intra-attribute-values), which is a possibilty (thought, avoidable by using single quotes).

**Comment by silverwind** [comment]
Feel free to close the issue if you think this is too hard to fix. I'm quite happy with my workaround :)

**Comment by alexlamsl** [comment]
In that case, how about:
```js
require('.').minify(`
  <div id="list {{name}}-list {{#is type "music"}}music{{else}}film{{/is}}">
    {{name}}
  </div>
`, {
  ignoreCustomFragments: [/{{.*?["'].*?}}/],
  collapseWhitespace: true
})
```
which gives:
```html
<div id="list {{name}}-list {{#is type "music"}}music{{else}}film{{/is}}">{{name}}</div>
```

**Comment by silverwind** [comment]
Looking good, I'll test that further.

One tweak: `{{2,}.*?["'].*?}{2,}` so it also matches ` {{{triple}}}` and more curly pairs.

**Comment by alexlamsl** [comment]
I agree that there isn't a trivial solution for the specific requirements you are aiming for here, OTOH it's a bit of a corner case (ignoring custom fragments while retaining context).

So if my proposed solution can resolve your issue, I'll proceed to close this - will keep this at the back of my mind in the next round of overhaul for custom fragments :wink:

**Comment by silverwind** [comment]
Did one more tweak so it also matches multi-line fragments: `/{{2,}[\s\S]*?["'][\s\S]*?}{2,}/`:

````
{{ some
    fragment }}
````

Now I've got to manually trim whitespace inside these fragments, but that's expected :)

**Comment by alexlamsl** [comment]
Thanks for letting me know of your use cases. Always good to keep tap especially around features which I don't get to use myself.
