### ISSUE TITLE
Add aria-* attributes to collapseBooleanAttributes

### ISSUE THREAD

**Issue by silverwind** [kangax/html-minifier#821]
I noticed that [`aria-*`](https://www.w3.org/TR/wai-aria/states_and_properties#state_prop_def_header) are missing from the list of collapsible attributes. Many of them are booleans and could potentially be added.

I haven't researched yet if there are any compatibility issues when leaving out the values. The spec is also rather explicit about them having true/false as values.

**Comment by alexlamsl** [comment]
Never used them before - is there some examples that can be tested within a normal web browser?

That way at least we can experiment with the code snippets to see if it is optimisable across major platforms.

**Comment by alexlamsl** [comment]
Actually, looking at https://developer.mozilla.org/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets
```html
<!-- Now *these* are Tabs! -->
<!-- We've added role attributes to describe the tab list and each tab. -->
<ol role="tablist">
  <li id="ch1Tab" role="tab">
    <a href="#ch1Panel">Chapter 1</a>
  </li>
  <li id="ch2Tab" role="tab">
    <a href="#ch2Panel">Chapter 2</a>
  </li>
  <li id="quizTab" role="tab">
    <a href="#quizPanel">Quiz</a>
  </li>
</ol>

<div>
  <!-- Notice the role and aria-labelledby attributes we've added to describe these panels. -->
  <div id="ch1Panel" role="tabpanel" aria-labelledby="ch1Tab">Chapter 1 content goes here</div>
  <div id="ch2Panel" role="tabpanel" aria-labelledby="ch2Tab">Chapter 2 content goes here</div>
  <div id="quizPanel" role="tabpanel" aria-labelledby="quizTab">Quiz content goes here</div>
</div>
```
Those `aria-labelledby` don't look very boolean to me?

**Comment by silverwind** [comment]
I don't have much experience with them either, but I noticed it though a stray `aria-hidden=true` I had in my code. Other booleans include aria-busy, aria-checked, aria-disabled just to name a few (scan for true/false in the spec).

As for testing them, it might be possible to run a audit with [this Chrome extension](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb).

**Comment by silverwind** [comment]
Probably not a good idea after all. While the HTML5 spec includes the feature of minimized boolean attributes, WAI-ARIA does not have such a definition and strongly requires true/false values, so I'd expect parsers (mostly screen readers) to probably not honour this HTML5 feature.

**Comment by alexlamsl** [comment]
Yeah, HTML5 or not, I think we should at least wait for these features to mature a bit more before fiddling with them.

So let's wait until we have ubiquitous access to `aria` on major browser platforms before revisiting this again :wink:
