### ISSUE TITLE
No Longer Works

### ISSUE THREAD

**Issue by ghost** [kangax/html-minifier#824]
I updated to from 0.6.9 to 3.5.2 and the plugin no longer works. I'm getting the following error: 
minify is not defined.

minify(HTMLCode, {
   removeAttributeQuotes: false,
   collapseWhitespace: true,
   removeComments: true
});

I made sure the plugin is loading; and it is. So I'm guessing the issue is the plugin itself.

**Comment by alexlamsl** [comment]
Works fine AFAICT:

```html
$ npm install html-minifier
$ npm ls
`-- html-minifier@3.5.2
  +-- camel-case@3.0.0
  | +-- no-case@2.3.1
  | | `-- lower-case@1.1.4
  | `-- upper-case@1.1.3
  +-- clean-css@4.1.3
  | `-- source-map@0.5.6
  +-- commander@2.9.0
  | `-- graceful-readlink@1.0.1
  +-- he@1.1.1
  +-- ncname@1.0.0
  | `-- xml-char-classes@1.0.0
  +-- param-case@2.1.1
  | `-- no-case@2.3.1 deduped
  +-- relateurl@0.2.7
  `-- uglify-js@3.0.15
    +-- commander@2.9.0 deduped
    `-- source-map@0.5.6 deduped


$ node
> require('html-minifier').minify(`
  <html>
    <body>
      Hello World!
    </body>
  </html>
  `, {
    removeAttributeQuotes: false,
    collapseWhitespace: true,
    removeComments: true
  });
'<html><body>Hello World!</body></html>'
```

Please provide a proper example which demonstrate the failure.

**Comment by ghost** [comment]
Page is offline and there isn't much to show. I think i'll downgrade back to 0.6.9 since it was working fine before I replaced the file with 3.5.2. Was there a major change that requires different implementation?

**Comment by alexlamsl** [comment]
I've already provided proof that things are working as they should. I've yet to see anything from you which shows otherwise.

Nobody can provide assistance with the current level of information you have provided. So if that's the best you can do, then I'm afraid you'll be on your own.
