### ISSUE TITLE
uglify js fails randomly

### ISSUE THREAD

**Issue by simllll** [kangax/html-minifier#825]
see also https://github.com/mishoo/UglifyJS2/issues/2077

I ran into the issue that my worker processes failed to minfiy inline javascript after a while. UglifyJS failed with "bug S.input.push_directives_stack is not a function #2077". 

I checked the parameters, and found that html-minifier does never "reset" the options of uglifyjs.. somehow this "options" get modified inside uglifyjs.
see options after a while (in related bug), I can see for example something like this in there: "toplevel:
AST_Node {
end: [Object],
start: [Object],
body: [Object],
cname: undefined,"

I assumed this is the root cause of my failed compressions, but... 
Well, just while filling out this bug report, the error came back... it fails for simple things like "ga_send_event({ c: 'job-page', a: 'app-downloaden', l: 'ios-bottom', e: event})"
minifyjs options { parse: { bare_returns: true } }
uglify js error TypeError: S.input.push_directives_stack is not a function

Any ideas?

thanks
simon

**Comment by alexlamsl** [comment]
@simllll hi, it's me again :sunglasses: 

I assume you've got to the bottom of this in https://github.com/mishoo/UglifyJS2/issues/2077#issuecomment-307410397, so I'm closing this.
