### ISSUE TITLE
AMD compatible

### ISSUE THREAD

**Issue by rogerdielrton** [kangax/html-minifier#826]
Hello.
Can be released a client side (web browser) version of "dist/htmlminifier.min.js"
that it will be AMD-compatible (http://requirejs.org/docs/whyamd.html)?
In any case, someone knows how to generate it?
THanks in advance.

**Comment by alexlamsl** [comment]
I haven't done anything with that before, though what is your use case which `dist/htmlminifier.min.js` currently cannot cover?

<sup>I was worried you are asking for Ryzen support for a second there.</sup>

**Comment by rogerdielrton** [comment]
Without knowing AMD/RequireJS is a bit diffcult to understand the following, but I go with it:
If I put
<script src="https://kangax.github.io/html-minifier/dist/htmlminifier.min.js"></script>
in my page, then it defines a "require" global object that enters in clonflict (replaces or is replaced by) with
<script data-main="scripts/main" src="http://requirejs.org/docs/release/2.3.3/minified/require.js"></script>
So, my initial RequireJS configuration call, "require.config({", fails because "config" does not exists in the "require" object.

My request is: extend Grunt generator to generate an specific version of html-minifier that will be AMD-compatible.
I think that here, http://requirejs.org/docs/node.html, there is more information about it.
Sorry if I don't reply to you, but now I am going to be out during some hours.

**Comment by alexlamsl** [comment]
I think I understand your requirements, though I'm afraid this is out of my depth.

Pull request on this is welcome - and if you need help understanding this codebase in order to make those changes, ask away :wink:

**Comment by rogerdielrton** [comment]
I have implemented the solution given here [http://requirejs.org/docs/commonjs.html#manualconversion] for converting the CommonJS module htmlminifier-3.5.2.min.js into a AMD module, but it does not works. I believe that htmlminifier-3.5.2.min.js is not CommonJS because its first line of code is "require=function e(t,n,r){...", when the "require" would need be provided and not defined.
Is that no one has need to use "html-minifier" with RequireJS?
Please, reply to this issue.

**Comment by alexlamsl** [comment]
Those `/dist` files are used by the [online minifier](http://kangax.github.io/html-minifier/) so far and that's about it, so chances are you are correct that nobody is using it for the purpose you've described.

Feel free to make changes as long as the online minifier remains operational afterwards :wink:

**Comment by rogerdielrton** [comment]
Sorry, alexlamsl, but I have not more time to spend in this question. Finally, I have done a server side service that receives the input HTML and returns the minimized HTML.

**Comment by alexlamsl** [comment]
@rogerdielrton no problem - whatever works for you.
