### ISSUE TITLE
Documentation surrounding conservativeCollapse is unclear

### ISSUE THREAD

**Issue by EthanNYT** [kangax/html-minifier#827]
Github description for this option:

>Always collapse to 1 space (never remove it entirely). Must be used in conjunction with collapseWhitespace=true

[Official (?) documentation](http://perfectionkills.com/experimenting-with-html-minifier/#collapse_whitespace):

>Second option is to never fully remove white space characters, and instead always collapse them to one white space character...This second option—collapsing to one white space—has not yet been added to minifier.

Seems that is no longer true? Is there somewhere else we should be looking for updated documentation on the options (blog post is from 7 years ago)?

**Comment by alexlamsl** [comment]
The documentation on https://github.com/kangax/html-minifier/blob/gh-pages/README.md would be the latest.

If you think something needs to be improved, please file a Pull Request.
