### ISSUE TITLE
Minify script tag without type attribute

### ISSUE THREAD

**Issue by saeidzebardast** [kangax/html-minifier#830]
`html-minifier` doesn't minify script tags without `type` attribute. I have to set `type` attribute on the script tag and `processScripts = ['text/javascript']`.
**Note:** _`type` attribute is optional for HTML5._

**Input**
```html
<script>
function () {
   console.log('Not Minified!');
}
</script>

<script type="text/javascript">
function () {
   console.log('Minified Successfully!');
}
</script>
```

**Output**
```html
<script>function () {
   console.log('Not Minified!');
}</script><script>function () { console.log('Minified Successfully!'); }</script>
```

Should I add the `type` attribute to all script tags?

**Comment by alexlamsl** [comment]
`processScripts` is for processing HTML templates, not JavaScript - I think you are looking at `minifyJS`

As for why the code between `<script>` is not being minified, they aren't valid JavaScript:
```js
$ type test.js
function () {
   console.log('Not Minified!');
}

$ type test.js | node
[stdin]:1
function () {
         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:74:10)
```
