### ISSUE TITLE
Handlebars-like syntax outputs empty files

### ISSUE THREAD

**Issue by cbdabner** [kangax/html-minifier#831]
I'm sure I can use `ignoreCustomFragments` for this, but I can't get it working.
I'm running the following on a Windows machine:
```
html-minifier --ignore-custom-fragments "[""{{[\\s\\S]*?}}""]" --input-dir . --file-ext hbs --output-dir publish
```

Here's an example file:
```html
{{!< default}}

<header>
    {{#if tag.image}}
    <div class="cover" style="background-image: url({{tag.image}})"></div>
    {{/if}}
</header>
```

The `{{!< default}}` is a template extension on Handlebars used by Ghost. It is causing a parse error despite matching the regex. I would like to try and resolve this as I need it, but removing this line, I get no errors, and a file created, but the file is empty.

**Comment by alexlamsl** [comment]
`ignoreCustomFragments` works just fine:

```js
$ node
> require('.').minify(`
{{!< default}}

<header>
    {{#if tag.image}}
    <div class="cover" style="background-image: url({{tag.image}})"></div>
    {{/if}}
</header>
`, { ignoreCustomFragments: [ /{{[\s\S]*?}}/ ] });

'\n{{!< default}}\n\n<header>\n    {{#if tag.image}}\n    <div class="cover" style="background-image: url({{tag.image}})"></div>\n    {{/if}}\n</header>\n'
```

**Comment by alexlamsl** [comment]
You'll have to figure out how shell in Windows works, or alternatively use `--config-file` and use JSON instead.

**Comment by cbdabner** [comment]
@alexlamsl Thanks for having a look. I had tried the JSON config file, which also failed. That's why I posted, but now that I look at that, it was a poorly formatted file 😞

I have no idea how the shell in windows wants it, but the config file makes it easy.
