### ISSUE TITLE
Removing custom attributes by part of the name

### ISSUE THREAD

**Issue by NeverwinterMoon** [kangax/html-minifier#832]
In our code, we use custom attributes, for example, `data-test-something` or `data-test-selected-value="bla"` to make E2E matches independent of class names. So we used our own utility to strip all the attributes that start with the specific prefix (`data-test-`) when making the production bundle. Is there any way to have similar effect using html-minifier or is it in some plans/totally out of scope?

**Comment by alexlamsl** [comment]
While this is out of scope for `require("html-minifier").minify()`, you may roll your own processor by utilising `require("html-minifier/src/htmlparser")`

See https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L946 for example usage.
