### ISSUE TITLE
Suggestion for PHP-excluding with `ignoreCustomFragments`

### ISSUE THREAD

**Issue by wottpal** [kangax/html-minifier#833]
Wouldn't it be better to use something like `/<\?[^(\?>)]*(\?>)?/` for the default exclusion pattern (`ignoreCustomFragments`). This also matches sequences starting with `<?php` but **not** closing (no `?>`) until EOF. This is quite common in the PHP-world and has caused me a lot of headache before.

Dennis

**Comment by alexlamsl** [comment]
`html-minifier` targets complete HTML fragments as default, and you can tweak options to fit your specific use cases.

**Comment by wottpal** [comment]
I totally see your point. 
But IMHO there is only additional value in this and no obvious drawback at all, right? I bet the majority of users with php-files will just skip minification in their build process because of these shortcomings instead of spending time either getting comfortable with regular-expressions like I did _or_ crazily filter their gulp-pipes into entire-php files / html-mixed php files. This is definitely not what we want for a faster web, right?

**Comment by alexlamsl** [comment]
Think false positives for non-PHP users when they need to use `<?` as part of normal text, for instance.
