### ISSUE TITLE
collapseWhitespace doesn't fully collapses whitespace between two inputs

### ISSUE THREAD

**Issue by EvgenyOrekhov** [kangax/html-minifier#834]
```js
minify("<input>    <input>", {collapseWhitespace: true});
```

Expected: `<input><input>`
Actual: `<input> <input>`

HTMLMinifier version: 3.5.2
Node.js version: 8.1.4

**Comment by alexlamsl** [comment]
That's working as expected - you may view the result in a web browser to see why that single whitespace is preserved.

**Comment by scipper** [comment]
And why is it preserved? I have the same expectation like @EvgenyOrekhov

**Comment by EvgenyOrekhov** [comment]
@scipper See https://jsbin.com/tajiwugahe/edit?html Whitespace between `<input>` tags have the same effect on rendering as whitespace between words.

**Comment by scipper** [comment]
does this only apply to `<input>`? what's the rule behind this behaviour? It still not obvious to me.

**Comment by EvgenyOrekhov** [comment]
@scipper A quick googling revealed that this applies to all `inline` (such as `<input>`) and `inline-block` elements.

**Comment by scipper** [comment]
Thanks for the explanation! (I wonder what you googled? This information can't be found in the [docs](https://www.npmjs.com/package/html-minifier) or on [perfectionkills.com](http://perfectionkills.com/experimenting-with-html-minifier/)

**Comment by EvgenyOrekhov** [comment]
@scipper Based on alexlamsl's comment above, I assumed that the `collapseWhitespace` option is not intended to alter the behavior of the code, so I googled for the rules of HTML rendering, not for the rules of html-minifier. Something like "html whitespace between elements".
