### ISSUE TITLE
Allow specifying the protocol the document will be served over, so it can be stripped in sources

### ISSUE THREAD

**Issue by chris-morgan** [kangax/html-minifier#835]
Take this:

    <script src=https://example.com/example.js></script>

html-minifier can’t take this any further at present, but if it could be told “the scheme of the resulting page will always be `https:`” (colloquially, “the page will always be served over HTTPS”), you could omit any matching schemes from URLs in the document, like so:

    <script src=//example.com/example.js></script>

Naturally this will be an opt-in feature.

**Comment by alexlamsl** [comment]
Setting `minifyURLs` to `https://abc.com/` will minify stated input to stated output from above.

**Comment by chris-morgan** [comment]
Thanks. I didn’t notice that option.

**Comment by chris-morgan** [comment]
Actually I’ve decided I’m not happy with this approach: it will necessarily break some relative links if you’re putting in a dummy value (that is, if you can’t declare with certainty the URL of the resource, but can declare its protocol).

`minifyURLs` | URL | Mangled to
-------------|-----|-----------
`https://everything.is.tls/` | `/foo` | `foo`
`https://everything.is.tls/dummy/` | `../foo` | `/foo`
`https://everything.is.tls/a/b/c/d/e/f/g/` | `../../../../foo` | `/a/b/c/foo`

Basically, the only way to be sure with this is to choose ridiculously improbable, long and deep paths. Something like this ought to do it, for example:

```javascript
minifyURLs: 'https://' + ('\0'.repeat(100) + '/').repeat(100)
```

… but I can’t imagine this will be particularly good for performance.

I request, then, that this be reopened: `minifyURLs` is not appropriate for cases where the scheme is known, or even the entire origin, but not the full URL. The package used, relateurl, doesn’t seem to have any convenient way of handling this case. (I know `minifyURLs` can be a function, but that misses the point.)

**Comment by alexlamsl** [comment]
If you haven't noticed by now, `minifyURLs` is handled by `relateurl` - so if you want its capability extended, go file an issue there.
