### ISSUE TITLE
Potential issue minifying a HTML file used as part of a partial where there is an opening tag but no closing tag

### ISSUE THREAD

**Issue by tomalexhughes** [kangax/html-minifier#837]
I'm developing a WordPress theme and using gulp-htmlmin to minify the HTML inside my PHP file.

Because I'm using WordPress I had a wrapping <div> element in my header file that was then closed in my footer file. Therefore the opening <div> tag did not have a respective closing tag in the same file.

When using gulp-htmlmin the closing <div> tag was automatically inserted at the end of the file, causing the wrapping div to close earlier in my code than expected.

Is there a setting to disable this behaviour or is it a bug?

**Comment by alexlamsl** [comment]
Try setting `includeAutoGeneratedTags` to `false`.

**Comment by jhpratt** [comment]
@alexlamsl I have the opposite problem — I'm attempting to parse strings separately (in a JS template literal), and may _only_ have the close tag. Currently this is removed. Is there any way around this?
