### ISSUE TITLE
processConditionalComments removes closed tags

### ISSUE THREAD

**Issue by maksim-shabanski** [kangax/html-minifier#838]
I have problem with 'processConditionalComments'.
If I set up the 'processConditionalComments: true', my code break.
He removes all closed tags: it was like that `<!--[if (gte mso 9)]></td></tr></table><![endif]-->` and became like this `<!--[if (gte mso 9)]><![endif]-->`

Before:
```
<!--[if (gte mso 9)]><table><tr><td><![endif]-->
<p>Example</p>
<!--[if (gte mso 9)]></td></tr></table><![endif]-->
```

After:
`<!--[if (gte mso 9)]><table><tr><td><![endif]--><p>Example</p><!--[if (gte mso 9)]><![endif]-->`

How can prevent this?

**Comment by alexlamsl** [comment]
`processConditionalComments` only supports proper HTML fragments, which would not apply in your case.

**Comment by luigimannoni** [comment]
For people coming from google and finding the same issue on, for example, minifying MSO/VML conditionals [here's how I have solved it.](https://github.com/Slicejack/bojler/pull/120)

Simply set the processConditionalComments to false and put a basic regexp on ignoreCustomComments to match the if/endif comments.
```
    processConditionalComments: false,
    ignoreCustomComments: [ /\[if.*|\[endif/ ]
```
