### ISSUE TITLE
minified URLs do not support <base>

### ISSUE THREAD

**Issue by stevenvachon** [kangax/html-minifier#839]
The base URL needs to be resolved with the value of `<base>` before any URLs can be minified.

**Comment by alexlamsl** [comment]
URL can be supplied through `minifyURLs`.

Pull Request is welcomed if you want to parse `<base>` as value for `minifyURLs`.

**Comment by stevenvachon** [comment]
Per the HTML specification, the first instance of `<base>` overrides the page's URL.

Page URL: `http://host/page.html`
`<base>` URL: `/path/page2.html`
Resolved URL: `http://host/path/page2.html`

Any relative URL on the page will be relative to the resolved URL.

**Comment by stevenvachon** [comment]
Was this fixed, or is it being ignored?
