### ISSUE TITLE
A random (?) space.

### ISSUE THREAD

**Issue by concatime** [kangax/html-minifier#840]
Hi. I have this snippet `<a href='/'>Home</a>` which is compiled to `<a href=/ >Home</a>`
My settings are:
```
collapseInlineTagWhitespace: true,
removeAttributeQuotes: true,
collapseWhitespace: true,
removeComments: true
```
On GTmetrix, I have 99% since their version does not contain the space between slash and closing tag. On validator.w3.org, `<a href=/>` is valid.
Maybe I'm just missing an option.

**Comment by alexlamsl** [comment]
It will be interpreted as `<a href="" />`, which is valid format but invalid attribute value.

**Comment by concatime** [comment]
Oh, sorry for wasting you time. So it seems that GTmetrix is using an invalid minifier.

**Comment by alexlamsl** [comment]
Please don't worry about it - I tried to save that space at one point and discovered the painful truth :wink:

**Comment by concatime** [comment]
Hahaha, we're on the same boat ;)

**Comment by concatime** [comment]
I will try to report it to GTmetrix.
