### ISSUE TITLE
htmlmin:ignore not working version 3.2.3

### ISSUE THREAD

**Issue by calgary007** [kangax/html-minifier#842]
I am trying to put an include directive inside the htmlmin:ignore tag but it is not working.

  
    
    

I put the following in online npm minifier as well and it just removes everything.

I am running it with following options
--case-sensitive --collapse-boolean-attributes --collapse-whitespace --remove-attribute-quotes --remove-comments --remove-script-type-attributes --remove-style-link-type-attributes --sort-attributes --sort-class-name --input-dir=www --output-dir=www --file-ext=html

**Comment by alexlamsl** [comment]
Tested with the online version:
```html
<!-- htmlmin:ignore -->
<!--#include virtual="https://www.someWebsite.com/static/login/onlinelogin.html" -->
<!-- htmlmin:ignore -->
```
