### ISSUE TITLE
It seems like html-minifier does not support es6?

### ISSUE THREAD

**Issue by drmrbrewer** [kangax/html-minifier#843]
Probably because html-minifier uses [uglify-js](https://www.npmjs.com/package/uglify-js), and uglify-js doesn't support es6... but [uglify-es](https://www.npmjs.com/package/uglify-es) *does*... see [here](https://github.com/mishoo/UglifyJS2/issues/659).

Can we switch to using uglify-es in html-minifier too?  How?

**Comment by drmrbrewer** [comment]
Anyone?

**Comment by alexlamsl** [comment]
Use `minifyJS: function(text, inline) { ... }` to swap in any external JavaScript optimiser as you see fit.

`uglify-es` is pretty much in the alpha stage, without any extensive test coverage etc. so won't be used as the default minifier here.

**Comment by drmrbrewer** [comment]
@alexlamsl what is the `inline` argument?  Do you have a simple example (even pseudo-example) to help me implement this?

**Comment by alexlamsl** [comment]
`inline=true` is for things like `<a onclick="doIt()">` - normal `<script>alert(42);</script>` has `inline=false`

**Comment by drmrbrewer** [comment]
@alexlamsl  sorry I need a bit more hand-holding.  At present I'm specifying a config file via the `-c` switch.  And in the config file I have a bunch of settings like the following:

    {
      "caseSensitive": false,
      "minifyJS": true,
      "minifyCSS": true
    }

So just to test this, I tried providing a function for `minifyJS` that just returns `text` unaltered:

    {
      "caseSensitive": false,
      "minifyJS": "function(text, inline) { return text }",
      "minifyCSS": true
    }

But when I run `html-minifier` with the above config, it seems like it is still using the default js minifier?

**Comment by alexlamsl** [comment]
You'll need to use the API rather than CLI to specify `function` as parameter values.

**Comment by drmrbrewer** [comment]
Ah, therein lies the problem.  I need to use it via the CLI.  Is it not possible to add a simple option to `minifyJS` to allow you to specify es6 minification so that it's usable via the CLI?  

And is `uglify-es` really basically alpha?  I note that you're the author / publisher on that one too.  And I note that there are 170,000 downloads of `uglify-es` every month, without any mention or warning in the README that it's only alpha quality...

**Comment by alexlamsl** [comment]
I don't actively support `uglify-es` - it is there to make it easier for other people to test and develop, which hasn't really happened much so far.

Feel free to make a pull request to extend CLI support for `function` type parameter values.

**Comment by kzc** [comment]
@drmrbrewer Regarding the `minifyJS` function for `uglify-es` you'd basically have to reimplement the following wrapper to get `inline` working:

https://github.com/kangax/html-minifier/blob/v3.5.3/src/htmlminifier.js#L678-L688

AFAICT this uglify minify wrapper handles html comments, sets the uglify parse option `bare_returns` and strips the final semicolon if present.

**Comment by kzc** [comment]
@alexlamsl Do you still find that all major websites are ES5?

> I don't actively support uglify-es

That's a good one! :-) 

> it is there to make it easier for other people to test and develop, which hasn't really happened much so far.

FWIW, `uglify-es` is at least as stable as `babel-minify` (formerly `babili`) for minifying ES6. With 50,000 downloads per week you'd expect more bug reports if it were not.

`uglify-es` might only have 1% of the downloads of `uglify-js` at the moment but as soon as [uglifyjs-webpack-plugin@1.0.0](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) is released that ratio will change pretty quickly - and probably more bug reports will follow.

**Comment by kzc** [comment]
I guess this line ensures if `uglify-js` cannot parse+minify the code it will return the original:

https://github.com/kangax/html-minifier/blob/v3.5.3/src/htmlminifier.js#L685

**Comment by alexlamsl** [comment]
> Do you still find that all major websites are ES5?

@kzc none of the sites I frequent use ES6 even in separate files, let alone embedded within HTML.

But as you noticed, any malformed JS will be untouched by `html-minifier`, so ES6 isn't a showstopper per se.

> That's a good one! :-)

I'll revisit the issue when the compatibility/performance story changes - AFAICT majority of code pushed to the client browser are still pretty much good old JavaScript.

I do concur the state of ES6+ has improved over the years, however :wink:

**Comment by kzc** [comment]
> none of the sites I frequent use ES6 even in separate files, let alone embedded within HTML.

It's ironic that the success of Babel converting ES6+ to ES5 actually encourages old obsolete browsers to live on. I wonder - what year will the majority of websites make the cutover to ES6? 2020?

**Comment by drmrbrewer** [comment]
@alexlamsl can you at least make `html-minifier` remove comments from script blocks that include ES6?  I have moved any ES6 code into a separate script block, to allow the rest of it to be minified, but I now see that even comments are left alone.  I know that the idea is that you leave any ES6 stuff alone, but surely removing comments is pretty uncontroversial?  I'm a bit of a comment freak and have lots of comments...

**Comment by drmrbrewer** [comment]
@alexlamsl what about it?  Just removing comments might be OK?

**Comment by drmrbrewer** [comment]
@alexlamsl nevermind, I'm now just running the following on the output from html-minifier as a quick and dirty way of removing comment lines from the untouched ES6 parts:

    sed -i '/^[[:blank:]]*\/\//d' index.html

**Comment by cloudspeech** [comment]
This issue should not be closed prematurely.

Inlined ES6 in HTML document has a perfectly natural use case: Custom Elements a.k.a. Web Components. These will frequently be packaged as .html files, and loaded via HTML imports or their polyfilled equivalents.

Therefore html-minifier should support ES6 minification. It is immaterial whether those cases are frequent or rare, as counted by some unscientific sample. The use case is supported by web standards, and that's what matters.

FWIW, here's a simple Node.js script for ES6-aware minification using the API, as indicated by @alexlamsl in the above discussion:

`#!/usr/local/bin/node

// reads HTML from stdin and writes minified HTML/CSS/ES6 Javascript to stdout

var UglifyJS = require('uglify-es'); // ES6-capable JS minifier
var minify = require('html-minifier').minify;

var stdin = process.stdin,
	stdout = process.stdout,
	inputChunks = [];

stdin.resume();
stdin.setEncoding('utf8');

stdin.on('data', function(chunk) {
	inputChunks.push(chunk);
});

var uglifyEsOptions = { parse: {} };

// adapted from https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js:676 onwards
function minify_es6(text, inline) {
	var start = text.match(/^\s*\s*$/, '') : text;
	uglifyEsOptions.parse.bare_returns = inline;
	var result = UglifyJS.minify(code, uglifyEsOptions);
	if (result.error) {
		console.log('Uglify-es error:', result.error);
		return text;
	}
	return result.code.replace(/;$/, '');
}

var options = {
	collapseBooleanAttributes: true,
	collapseWhitespace: true,
	decodeEntities: true,
	minifyCSS: true,
	html5: true,
	minifyJS: minify_es6,
	removeAttributeQuotes: true,
	removeComments: true
};

stdin.on('end', function() {
	var input = inputChunks.join('');

	var output = minify(input, options);

	stdout.write(output);
	stdout.write('\n');
});`

**Comment by drmrbrewer** [comment]
Thanks so much @cloudspeech for the code.  Works well, with just one correction...

I assume you meant something like:

    var code = text.match(/^\s*\s*$/) ? '' : text;

instead of:

    var start = text.match(/^\s*\s*$/, '') : text;

**Comment by jimmywarting** [comment]
is uglify-es still alpha or can we make a switch to use it now?

**Comment by kzc** [comment]
`uglify-es` is no longer maintained. You could use `yarn` resolutions to replace `uglify-js` with `terser`.

```
$ cat package.json 
{
  "resolutions": {
    "uglify-js": "npm:terser"
  },
  "dependencies": {
    "html-minifier": "3.5.20"
  }
}

$ rm -rf node_modules yarn.lock 

$ yarn --silent --no-progress
warning package.json: No license field
warning No license field

$ cat doc.html 
<!DOCTYPE html>
<html><body>
<pre>
<script>
    document.write(`Hello ES${5 + 1}.`);
</script>
</pre>
</body></html>

$ node_modules/.bin/html-minifier doc.html --minify-js --collapse-whitespace && echo
<!DOCTYPE html><html><body><pre>
<script>document.write("Hello ES6.")</script>
</pre></body></html>
```

**Comment by cekvenich** [comment]
working code:
 
 function minify_es6(text, inline) {
      var uglifyEsOptions = { parse: { bare_returns: {}},
         mangle: false,
         keep_classnames: true,
         keep_fnames: true,
         safari10: true
      }

      var code = text.match(/^\s*\s*$/) ? '' : text
      uglifyEsOptions.parse.bare_returns = inline

      var result = Terser.minify(code, uglifyEsOptions)
      if (result.error) {
      console.log('Uglify-es error:', result.error)
      return text
      }
      return result.code.replace(/;$/, '')
   }//()

**Comment by vitaliytv** [comment]
https://www.npmjs.com/package/html-minifier-terser

**Comment by Nastromo** [comment]
> https://www.npmjs.com/package/html-minifier-terser

Thanks! It does the job!

**Comment by aminnairi** [comment]
For those of you that want to use [Terser](https://github.com/terser/terser) with [Gulp](https://github.com/gulpjs/gulp) but are not sure on how to do it, here is an example.

## Context

I am using `html-minifier` through the `gulp-htmlmin` plugin. That way, I have the possibility to use a JavaScript file to require Terser and use its API.

## Solution

```console
$ touch htmlmin.config.js
```

```javascript
"use strict";

const Terser = require("terser");

module.exports = {
    caseSensitive: false,
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: true,
    collapseWhitespace: true,
    conservativeCollapse: false,
    continueOnParseError: false,
    html5: true,
    includeAutoGeneratedTags: false,
    keepClosingSlash: false,
    minifyCSS: true,
    minifyJS: (text, inline) => Terser.minify(text).code,
    minifyURLs: true,
    preserveLineBreaks: false,
    preventAttributesEscaping: false,
    processConditionalComments: false,
    processScripts: false,
    quoteCharacter: "'",
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeEmptyElements: true,
    removeOptionalTags: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    removeTagWhitespace: false,
    sortAttributes: false,
    sortClassName: false,
    trimCustomFragments: true,
    useShortDoctype: true
};
```

```console
$ touch gulpfile.js
```

```javascript
const htmlmin = require("gulp-htmlmin");
const {src, dest} = require("gulp");
const {resolve} = require("path");
const htmlminConfig = require("./htmlmin.config.js");

const html = () => {
    return src(resolve("sources", "index.html"))
        .pipe(htmlmin(htmlminConfig))
        .pipe(dest(resolve("release")));
};

module.exports = {html};
```

Now, you are able to minify ECMAScript syntax in your HTML files.
