### ISSUE TITLE
Attribute sorting niggle

### ISSUE THREAD

**Issue by DamonHD** [kangax/html-minifier#845]
Firstly, thanks for a great tool!

Secondly, have you noticed how when you sort attributes and the original final value did NOT end in / but the sorted-final one DOES, that you now have to insert an extra space before the final `>` to avoid ambiguity with a self-closing form, and thus expand the HTML document by a byte in this case?

Could there be an option to suppress sorting such a /-ended attribute value to the end of the tag, or alternatively force a non-/-ending or quoted attribute to the end instead to avoid this tiny expansion in HTML output size?

Rgds

Damon

**Comment by alexlamsl** [comment]
You'll need to investigate whether the uncompressed byte saved is worth the disruption to `gzip`, which may result in more than a single byte lost in suboptimal compression.

Otherwise, feel free to put together a pull request to make your case :wink:

**Comment by DamonHD** [comment]
Sometimes I care about optimising the uncompressed size, though I agree that most of the time the size after gzip/zopfli is what matters.

Rgds

Damon
