### ISSUE TITLE
CSS File Inlining Is Sensitive to the Current Working Directory of html-minifier

### ISSUE THREAD

**Issue by robliao** [kangax/html-minifier#847]
# Summary
The html-minifier CSS file inliner use the current working directory to resolve paths to CSS files. The impact here is that html-minifier produces different results depending on the current directory. 

The HTML's directory should instead be used to resolve these paths.

# Repro and Discussion
Consider the following path structure:
* `src/`
  * `index.html`
  * `index.css`
  * `builddir/`

With the following file contents:
* `src/index.html`
  ```html
  <!DOCTYPE html>
  <html>
  <head>
    <style type="text/css">
      @import url("index.css");
    </style>
  </head>
  </html>
  ```
* `src/index.css`
  ```css
  body {
    background-color: #000000;
  }
  ```

Running the following command from `src/builddir/` provides the following results:
```
[hostname ~/src/builddir]$ html-minifier --minify-css --collapse-whitespace ../index.html
```

**EXPECTED**
```html
<!DOCTYPE html><html><head><style type="text/css">body{background-color:#000}</style></head></html>
```

**ACTUAL**
```html
<!DOCTYPE html><html><head><style type="text/css"></style></head></html>
```
Note the empty `style` node in **ACTUAL**. 

The only workaround here is to change `@import url("index.css");` to `@import url("../index.css");` and make the HTML aware of the current working directory of `html-minifier`.

Instead, `html-minifier` should use the directory of the HTML file to resolve `index.css`.

# Version Info
```
+-- html-minifier@3.5.3
| +-- camel-case@3.0.0
| | +-- no-case@2.3.1
| | | `-- lower-case@1.1.4
| | `-- upper-case@1.1.3
| +-- clean-css@4.1.8
| | `-- source-map@0.5.7
| +-- commander@2.11.0
| +-- he@1.1.1
| +-- ncname@1.0.0
| | `-- xml-char-classes@1.0.0
| +-- param-case@2.1.1
| +-- relateurl@0.2.7
| `-- uglify-js@3.0.28
```

**Comment by alexlamsl** [comment]
`clean-css` rather than `html-minifier` is performing the file inlining - you can pass the necessary options to `minifyCSS`.

**Comment by robliao** [comment]
What are the necessary options? I couldn't find them in the clean-css documentation. 
The inlining options (https://github.com/jakubpawlowicz/clean-css#inlining-options) do not seem to apply here.
