### ISSUE TITLE
Use something like purify-css to strip all inline css that cannot be used (after minification)

### ISSUE THREAD

**Issue by DamonHD** [kangax/html-minifier#848]
This could save substantial document weight, to trim out parts of the inlined above-the-fold CSS that happen not to be used in the full document.  The advantage here is that you see the full HTML.

May have to be enabled and only used where (eg) there is no linked CSS file, unless html-minifier can also see it.

Absent this, I will probably do a pass before html-minifier where I apply purify-css to pare back the CSS.

**Comment by alexlamsl** [comment]
You can use any custom CSS processor via `minifyCSS: function(style) { ... }`

Bear in mind styles that aren't directly referenced in HTML might be used by dynamic scripts.

**Comment by DamonHD** [comment]
Thank you.

Can that function look over the entire document?

Yes, I understand that there are various clear limitations, but for simple cases possibly with some whitelisting of difficult cases, there is likely to be value.  I can see scope to rip another 1% or more out of even my already tight CSS this way, safely.

**Comment by alexlamsl** [comment]
Personally I can't see any easy way or interface to implement this feature.

You are of course welcomed to put together a Pull Request to get this done.

**Comment by DamonHD** [comment]
My JS skills may well not be up to such a thing!

For reference, I have done the purifycss thing today as a test, and even though it's failing to remove everything that it could, it is removing over 1% of the entire document weight, and all in the critical initial first-paint rendering path.

http://www.earth.org.uk/note-on-site-technicals-4.html#purifycss

**Comment by alexlamsl** [comment]
Closing as workaround exists - any enchancement proposals in the form of Pull Request is welcomed.
