### ISSUE TITLE
Breaks Bootstrap 3.0 Input Groups

### ISSUE THREAD

**Issue by tdrozdowski** [kangax/html-minifier#85]
The html-minifier (when run via Grunt htmlmin) - breaks Input Groups for Twitter Bootstrap 3.0

Before run through html-minfier:

![screen shot 2013-09-16 at 11 42 53 am](https://f.cloud.github.com/assets/1784034/1153334/76040954-1f1f-11e3-955b-78061f96677c.png)

After run through html-minifier:

![screen shot 2013-09-16 at 11 42 25 am](https://f.cloud.github.com/assets/1784034/1153331/6d45b8f8-1f1f-11e3-9a96-2a75368c897b.png)

Note that it moved the button out of the span.

Markup matches prescribed markup from Bootstrap docs on Input Groups:

http://getbootstrap.com/components/#input-groups-buttons

**Comment by kangax** [comment]
Works in latest version; I also added this specific markup to a test suite.
