### ISSUE TITLE
Allow passing of options to clean-css from command-line invokation to increase optimisation level

### ISSUE THREAD

**Issue by DamonHD** [kangax/html-minifier#850]
(I've looked at the source; I don't think that this is currently possible.)

After some stripping of unused CSS with purifycss or UnCSS I'm left with fragments such as

    .colD{display:inline-block;margin:2px;padding:2px;text-align:left;vertical-align:top}.colD{width:48%;max-width:310px}

which should be further minified but isn't, and which clean-css should be capable of if I pass it the right optimisations or even just ask for 'O2'.  (For my code O2 does do much and strips some stuff needed as fallbacks for older browsers, but the idea is the same.)

Could you please at least better document what the 'value' to the --minify-css argument can be?

**Comment by alexlamsl** [comment]
https://github.com/kangax/html-minifier#options-quick-reference

`minifyCSS: {...}` to pass options to `clean-css`

**Comment by DamonHD** [comment]
From the command-line?  Eg:

    --minify-css "O2"

seems to have no effect and gives no error.
