### ISSUE TITLE
Option for executableScriptsMimetypes?

### ISSUE THREAD

**Issue by ysc3839** [kangax/html-minifier#853]
Cloud you add an option for `executableScriptsMimetypes`? Like `processScripts`.

https://github.com/kangax/html-minifier/blob/e0108f930da53d6ac3e2867efce4d8304e2bab94/src/htmlminifier.js#L160

**Comment by alexlamsl** [comment]
Pull Request to illustrate your use case is welcomed.

**Comment by ysc3839** [comment]
I have scripts with custom mine type in html. For example:
```html
<script type="text/ls-javascript" id="...">
// scripts
</script>
```
I want them to be uglify.
