### ISSUE TITLE
Strings with less-then are not correctly parsed.

### ISSUE THREAD

**Issue by Michaelangel007** [kangax/html-minifier#855]
Apparently someone failed their compiler / parsing Comp. Sci. course.  Strings with less-then are not being correctly parsed.  :-/

First, verification that JavaScript is being parsed correctly, with `pass.js`:

```
var foo = 0;
var bar = 1;
```

However, adding a string with less-then does not parse with `fail.js`

```Javascript
console.log( ">>> OK <<<" );
var foo = 0;
var bar = 1;
```

Compare incorrect output and contrast to correct [Google Closure Minifier](https://developers.google.com/closure/compiler/) output:

|  | html-minifier | Google Closure |
|:--|:--|:--|
| Command: | `html-minifier fail.js` | `java -jar closure/compiler.jar --js fail.js` |
| Output: | `Minification error:` <br>`Parse Error: <<<" );` | `console.log(">>> OK <<<");var foo=0,bar=1;`

# Version

```
$ html-minifier -V
3.5.5
```

**Comment by alexlamsl** [comment]
This project goes by the name of **html**-minifier - example code doesn't look like HTML to me.

**Comment by Michaelangel007** [comment]
Whew, glad it isn't a bug!  (I could of swore I tested that code snippet with tags.)  

Solution _requires_ `<script>` and `</script>` prefix and suffix.
