### ISSUE TITLE
Some html string parse error

### ISSUE THREAD

**Issue by Tinyuen** [kangax/html-minifier#859]
```
const minify = require('html-minifier').minify

let html = '<a href="" title="there is "some" text">some text</a>'
minify(html, {
     collapseWhitespace: true
})
```

Then  I got this : 
**Parse Error: <a href="" title="there is "some" text">some text</a> ....** 

The html attribute cannot contain the double quotes,  what should I do?

need help   Thx!

**Comment by alexlamsl** [comment]
https://stackoverflow.com/questions/4015345/how-to-properly-escape-quotes-inside-html-attributes

**Comment by Tinyuen** [comment]
@alexlamsl  Thx!
