### ISSUE TITLE
HTMLParser : Parse Error: <# name/>

### ISSUE THREAD

**Issue by nathan-pichon** [kangax/html-minifier#863]
Hello,

## Description
I use RactiveJS as UI library and in its features, it has ["Anchors"](https://ractive.js.org/api/#anchors) written with this syntax: "<# ... />".

## Problem
When I want to use my webpack in production mode (`webpack -p`) it use HTMLParser on my html, and it throw an error on this HTML custom tag.
```
Module build failed: Error: Parse Error: <# name/>
</div>
    at new HTMLParser (/node_modules/html-minifier/src/htmlparser.js:235:13)
```

## Version
3.5.6

**Comment by alexlamsl** [comment]
That's not valid HTML syntax at all - consider using `ignoreCustomFragments` as workaround.
