### ISSUE TITLE
keepClosingSlash not working

### ISSUE THREAD

**Issue by chechengpeng** [kangax/html-minifier#864]
![image](https://user-images.githubusercontent.com/13061663/32040838-aee70394-b9f7-11e7-9b58-192c21d3d903.png)
![image](https://user-images.githubusercontent.com/13061663/32040942-0ab77776-b9f8-11e7-9801-eaa14a80f0f2.png)

**Comment by alexlamsl** [comment]
Works in [online minifier](http://kangax.github.io/html-minifier/) when trying with `<meta charset=""/>`

Please provide an actual reproducible test case when reporting bugs.
