### ISSUE TITLE
Minify EJS file

### ISSUE THREAD

**Issue by Akshaykalola** [kangax/html-minifier#867]
I am trying to minified EJS file but I am receiving HTML Parse error. 
A file contains **<% if(inlineEdit){ %>** this kind of code and I think due to this it is throwing an error.
Please help me to resolve

**Comment by alexlamsl** [comment]
That's invalid HTML – try `ignoreCustomFragments`

**Comment by Akshaykalola** [comment]
options: {                                 // Target options
					collapseBooleanAttributes: true,
					decodeEntities: true,
					html5: true,
					minifyCSS	: true,
					minifyJS	: true,
					processConditionalComments	: true,
					removeAttributeQuotes	: true,
					removeComments: true,
					removeEmptyAttributes: true,
					removeOptionalTags: true,
					removeRedundantAttributes: true,
					removeScriptTypeAttributes: true,
					removeStyleLinkTypeAttributes: true,
					removeTagWhitespace: true,
					sortAttributes: true,
					sortClassName: true,
					trimCustomFragments: true,
					useShortDoctype: true,
					collapseWhitespace: true,
					ignoreCustomFragments: true

				}
I am using this options

**Comment by AndyOGo** [comment]
@alexlamsl 
Unfortunately ignoring `ignoreCustomFragments ` doesn't work 😞

**Comment by xiaoice** [comment]
htmlmin({
    ignoreCustomFragments: [ /\{\{[\s\S]*?\}\}/, /\<\%[\s\S]*?\%\>/ ]
}))

try like this
