### ISSUE TITLE
Incorrect <inline><block /></inline>

### ISSUE THREAD

**Issue by Cap32** [kangax/html-minifier#868]
Source:

```html
<span><div></div></span>
```

Expected:

```html
<span><div></div></span>
```

Current:

```html
<span></span><div></div>
```

I'm using `v3.5.6`

I don't know if it is a feature or a bug. If it is a feature, is there any option to parse to `<span><div></div></span>` ?

**Comment by alexlamsl** [comment]
Block tags are not allowed inside an inline tag:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

**Comment by Cap32** [comment]
Thanks for replying.

But IMO this job should not be taken by minifier, but by some module like `html-corrector`. Or at least it should provide an option to disable this feature.
