### ISSUE TITLE
Problem with angularjs ng-required since 0.5.3

### ISSUE THREAD

**Issue by clakech** [kangax/html-minifier#87]
Hi,

For you information, since upgraded to 0.5.4 throught our use of grunt-contrib-htmlmin 0.1.3 we face a problem with our angular app.

One of our ng-required attribute is not working anymore. Why really understand why but after changing collapseBooleanAttributes to false (was true before) in grunt-contrib-htmlmin this problem disapears.

You may have a problem with AngularJS application if they user htmlminifier and collapseBooleanAttributes: true.

Regards

**Comment by iameli** [comment]
It seems like using collapseBooleanAttributes with an "HTML plus" kind of framework like Angular is a really bad idea to start with... if you ever have an ng-model named ng-model (or something) it will break.
