### ISSUE TITLE
Only allow specified attribute names for given tags?

### ISSUE THREAD

**Issue by lazharichir** [kangax/html-minifier#871]
Hello,

I am getting the html content from a `node-readability` to first only get the article part of a webpage, and I then need to minimize this article to its minimal HTML structure. Therefore, using `html-minifier`, is it possible to (and how can I):

1. Only keep specific attributes (href, src, alt, title)
2. Remove some blocks by tags (`aside`, `footer`, `table`, `pre`, `code`, `iframe`, `sup`, `sub`)
3. Remove blocks by regexp pattern for an attribute (for example if `class` contains `amzn`)

Not sure if I missed these in the options :)

**Comment by alexlamsl** [comment]
That's out of scope for `html-minifier` - you can perform direct manipulation via `HTMLParser`

https://github.com/kangax/html-minifier/blob/v3.5.7/src/htmlparser.js#L114
