### ISSUE TITLE
minifiy:collapseWhiteSpace,preserveLineBreaks line ending control

### ISSUE THREAD

**Issue by markfaine** [kangax/html-minifier#875]
html-minifier-3.5.7

If I use option:

```javascript
 minify: {
        collapseWhitespace: true,
        preserveLineBreaks: false
      },
```
when used with HtmlWebpackPlugin

```javascript
    new HtmlWebpackPlugin({
      title: 'Project',
      minify: {
        collapseWhitespace: true,
        preserveLineBreaks: false
      },
      hash: true,
      template: './src/index.html',
    })
```

The resulting file fails my HTML linter rule that requires LF line endings.

```
local htmllint version is not supported: 0.7.0 != ^0.6.0
using builtin version of htmllint
dist/index.html: line 1, col 477, line ending does not match format: lf
```

The template file has LF line endings but the resulting file apparently does not.

Is there some way to control the EOL setting for the minified file?  

If preserveLineBreaks is true, this does not happen.

I suspect all that needs to happen is one new line (lf) inserted at the end of the file.

**Comment by alexlamsl** [comment]
If `preserveLineBreaks` is disabled, line breaks get optimised away whenever possible - seems pretty reasonable to me.
