### ISSUE TITLE
Incomplete list of inline elements

### ISSUE THREAD

**Issue by kaidjohnson** [kangax/html-minifier#878]
Thanks for this tool! It's been very useful.

I'm noticing, however, that some inline elements are treated differently than others, namely `<label>`, which is creating some unexpected results in my output.

Example:

test.html:
```
<span>Foo</span>
<span>Bar</span>
<br>
<label>Foo</label>
<span>Bar</span>
```

`html-minifier --collapse-whitespace test.html`

Expected result:
`<span>Foo</span> <span>Bar</span> <br> <label>Foo</label> <span>Bar</span>`

Actual result:
`<span>Foo</span> <span>Bar</span><br><label>Foo</label><span>Bar</span>`

Notice the lack of space between `</label>` and `<span>` in the actual result.

I realize to get the result I want, I can use the `--conservative-collapse` option, but the default behavior is unexpected. Digging in, it appears that the list of inline elements is constrained to 

```
var inlineTags = createMapFromString('a,abbr,acronym,b,bdi,bdo,big,button,cite,code,del,dfn,em,font,i,ins,kbd,mark,math,nobr,q,rt,rp,s,samp,small,span,strike,strong,sub,sup,svg,time,tt,u,var');
...
var selfClosingInlineTags = createMapFromString('comment,img,input,wbr');
```

(https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js lines 70-74)

Based on https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements, I would expect that list to include:

`label,br,map,object,script,select,textarea`

Is there a reason for the discrepancy in the inline elements chosen vs the inline elements from spec?

**Comment by alexlamsl** [comment]
First of all, I can't reproduce your "actual" result:
```sh
$ html-minifier test.html --collapse-whitespace
<span>Foo</span> <span>Bar</span><br><label>Foo</label><span>Bar</span>
```
And it doesn't seem to match your "expected" result either.

As for your proposed list of additions:
- `br` is making a new line
- `map` only overlays on top of other items
- `script` is not visible

The rest looks good to me.

Please file a Pull Request alongside new tests to address this issue.

**Comment by kaidjohnson** [comment]
Thanks for the quick response!

Your actual result and mine are the same. Setting `<br>` aside for a moment, I'm definitely expecting a space between `</label>` and `<span>` since they are both inline elements and I am not using the `collapseInlineTagWhitespace` option.

I would expect the same with `<br>` since it, too, is technically an inline element.

I'll try to put together a PR with updated tests in the next day or two. Cheers!

**Comment by alexlamsl** [comment]
I see - thanks in advance and looking forward to your PR :+1:

**Comment by chris-morgan** [comment]
Observation: this isn’t the first time the collapsing of whitespace around `<br>` has been remarked upon. I myself have to use `conservativeCollapse` because of responsive line breaks that are hidden at certain sizes. Sure, for many people the whitespace around line breaks isn’t significant, but it’s quite common for it to be significant, and so it’s dangerous to completely collapse whitespace around line breaks. It’s semantically an inline element.

#710 was correct and should be revived.
