### ISSUE TITLE
Use html-minifier on site without node.js

### ISSUE THREAD

**Issue by Zo4inec** [kangax/html-minifier#881]
Good day.
I need to make on-line html minifier on my site.
Server use nginx.
How to install html-minifier without node.js, only with javascript/jquery?

**Comment by tomap** [comment]
just grab what is inside https://github.com/kangax/html-minifier/tree/gh-pages/dist and look at the source code in https://github.com/kangax/html-minifier/blob/gh-pages/index.html and you should be good :)
