### ISSUE TITLE
keepClosingSlash not working

### ISSUE THREAD

**Issue by steviemo** [kangax/html-minifier#886]
I have some html with a bunch of closing <img .. />, <br /> tags and html-minifier is still stripping out the closing tags after executing the following options:

`.pipe($.htmlmin, {
            keepClosingSlash: true,
            collapseWhitespace: false,
            minifyCSS: true
        });`

Cheers,
Stephen

**Comment by alexlamsl** [comment]
Not reproducible using online minifier.
```html
<img src="photo.png"/>
```
with default options plus `keepClosingSlash` gives:
```html
<img src=photo.png />
```
