### ISSUE TITLE
'ul' should belongs to non-Phrasing Content

### ISSUE THREAD

**Issue by weixu365** [kangax/html-minifier#888]
ul is missing in non-Phrasing Content in https://github.com/kangax/html-minifier/blob/0f2a67faf4b347bfd6f8bf56ff43847547882ebb/src/htmlparser.js#L83

Here's the testing html
```
const html = `
<p>
  before ul
<ul>
  <li>item1</li>
  <li>item2</li>
</ul>
</p>`;
console.log(minify(html, { collapseWhitespace: true, conservativeCollapse: true }));
```

**Should return**
```
 <p> before ul </p><ul> <li>item1</li> <li>item2</li> </ul> <p></p>
```
This is also the default browser behaviour, and python beautifulSoup has the same logic

**But currently get**
```
<p> before ul <ul> <li>item1</li> <li>item2</li> </ul> </p>
```

I'm happy to create a pull request if you think it's a valid issue.

**Comment by alexlamsl** [comment]
The current output renders exactly the same on the browser:
```html
<html>
<body>
<table border=1>
<tr>
<th>Input</th>
<th>Output</th>
</tr>
<tr>
<td>

<p>
  before ul
<ul>
  <li>item1</li>
  <li>item2</li>
</ul>
</p>

</td>
<td>

<p> before ul <ul> <li>item1</li> <li>item2</li> </ul> </p>

</td>
</tr>
</table>
```
![render](https://user-images.githubusercontent.com/1898413/36774279-44f1899e-1c55-11e8-8a29-d086d6fe9d08.png)

**Comment by weixu365** [comment]
It would be easier to check the browser result if you **add some styles** or **using the inspector** to check the element tree. Here's example code:
```
<p style="margin: 50px;">
  testing ul in p
<ul>
  <li>item</li>
</ul>
after ul
</p>
```
It has the same behaviour on Chrome, Firefox and Safari under MacOSX, here's the screen shot and element tree
<img width="337" alt="ul-inside-p" src="https://user-images.githubusercontent.com/20695333/36778416-bf001820-1cc0-11e8-9eeb-508a7b3cf2dd.png">

The style only applied to the first part of **p** tag.

**Comment by DamonHD** [comment]
The W3C validator does not like &lt;ul>&lt;/ul> inside &lt;p> ... &lt;/p> and it is regarded as incorrect, so should likely behave as @weixu365 expects, IMHO.

Rgds

Damon

**Comment by alexlamsl** [comment]
@weixu365 I see - in which case, please file the PR as you mentioned :+1: 

Please also double-check that the output is/remains valid when `removeOptionalTags` is also enabled.
