### ISSUE TITLE
Possible improvement - Use comment block to ignore a block of html

### ISSUE THREAD

**Issue by devert** [kangax/html-minifier#89]
Would it be possible to ignore a section of an html doc by surrounding that section with a specific comment like `<!-- htmlmin:ignore -->`?

**Comment by kangax** [comment]
You can sort of ignore things already by [wrapping them with `<%` or `<?`](https://github.com/kangax/html-minifier/pull/82) but a proper, standalone directive would make sense of course.

**Comment by ain** [comment]
Good request. Vote.

**Comment by ain** [comment]
I'm adding a very practical illustration here:

``` html
<!-- build:js /scripts/main.js -->
    <script type="text/javascript" src="../../scripts/jquery.flexslider.js"></script>
    <script type="text/javascript" src="../../scripts/functions.js"></script>
<!-- endbuild -->
```

where using negation is not an option as it would break the build:

``` html
<!--! build:js /scripts/main.js -->
    <script type="text/javascript" src="../../scripts/jquery.flexslider.js"></script>
    <script type="text/javascript" src="../../scripts/functions.js"></script>
<!--! endbuild -->
```

**Comment by xdhmoore** [comment]
This would also provide a decent workaround for #45.

**Comment by mgcrea** [comment]
Need this too, in my case for docs where some partial code should not be minified.

**Comment by XhmikosR** [comment]
@kangax: so is there any way currently to make html-minifier keep a specific comment in a valid HTML way? In my case I need to keep `<!--googleoff: all-->` and `<!--googleon: all-->`.

**Comment by kangax** [comment]
@XhmikosR you can wrap them with <% and %> for now

**Comment by XhmikosR** [comment]
I have already tried that but it's not valid html. I might work around it with grunt-includereplace.

**Comment by Globegitter** [comment]
Yeah, it would be really nice if there was a valid html way for ignoring blocks of html. Making things a bit more 'complicated' for one of my uses.

**Comment by kangax** [comment]
Added support for `<!-- htmlmin:ignore -->`. Let me know how it works for you folks.

**Comment by kalinichenko** [comment]
Maybe I got it wrong. In what way should I wrap my bunch of code? I tried that way

```
<!-- htmlmin:ignore -->
<td class="check widescreen"><input type="checkbox" <%= check %> /><span class="checkbox"></span></td>
<!-- htmlmin:ignore -->
```

but still got a parse error. 

Thanks in advance for more comprehensive explanation.

**Comment by jordanburke** [comment]
Seeing the same problem as @kalinichenko

**Comment by S3ak** [comment]
+1 @kalinichenko

**Comment by icd2k3** [comment]
+1 @kalinichenko - same problem
