### ISSUE TITLE
Can we use dependency uglify-es instead of uglify-js

### ISSUE THREAD

**Issue by sahaam** [kangax/html-minifier#890]
Hi,

According to the guild of UglifyJS2
uglify-js only supports ECMAScript 5 (ES5).
Those wishing to minify ES2015+ (ES6+) should use the npm package uglify-es.

Can we move to uglify-es?

**Comment by alexlamsl** [comment]
Duplicate of #843

Contains a solution on how to use custom proccessor in `minifyJS`.
