### ISSUE TITLE
Cannot use async functions for minifyCSS and minifyJS.

### ISSUE THREAD

**Issue by RebeccaStevens** [kangax/html-minifier#900]
The following fails due to html-minifier not waiting for the promise to resolve before trying to use it:

```js
const minify = require('html-minifier').minify;
const postcss = require('postcss');
const postcssPlugins = [/* plugins */];
const html = '<html><head><style>body { margin: 0; display: flex; }</style></head></html>';

const result = minify(html, {
  minifyCSS: async css => {
    const result = await postcss(postcssPlugins).process(css);
    return result.css;
  }
});
```

**Error output:**
`str.match is not a function`

*`minifyURLs` may also be affected by this issue.*

**Comment by RebeccaStevens** [comment]
**Possible Solution**

Make the `chars` function async and await the `minifyCSS`/`minifyJS` functions.

Change this line:

https://github.com/kangax/html-minifier/blob/f8f755936be00dcb7f25cb7d46807cb9dd6e2880/src/htmlminifier.js#L1109

to:

```js
chars: async function(text, prevTag, nextTag) {
```

and these lines:

https://github.com/kangax/html-minifier/blob/f8f755936be00dcb7f25cb7d46807cb9dd6e2880/src/htmlminifier.js#L1164

https://github.com/kangax/html-minifier/blob/f8f755936be00dcb7f25cb7d46807cb9dd6e2880/src/htmlminifier.js#L1167

to:

```js
text = await options.minifyJS(text);
```

```js
text = await options.minifyCSS(text);
```

**Issues with this solution**

* The library will no longer be es5 compatible. It will instead be using es8.

**Comment by alexlamsl** [comment]
This library only supports JavaScript, and the API is synchronous.

**Comment by RebeccaStevens** [comment]
How can I use postcss to minify css in html with this library when postcss is asynchronous only?
