### ISSUE TITLE
Not working in browser environment: required `fs` module and another problems

### ISSUE THREAD

**Issue by finethanks** [kangax/html-minifier#902]
Library not working in a browser with zero configuration. 
I tried to build my app with webpack and your library. Then I have disabled fs module in webpack config, but I got another issue.

Can you give some working example for a browser?

**Comment by alexlamsl** [comment]
We use `browserify` which works.

http://kangax.github.io/html-minifier/

**Comment by GeorgeTaveras1231** [comment]
I am having the same issue as @finethanks. Would be nice if this library required no configuration to work in the browser. 

It seems like [this module](https://raw.githubusercontent.com/kangax/html-minifier/gh-pages/dist/htmlminifier.js) 
1. needs to be included in the npm package
2. needs to export the HtmlMinifier object
3. needs to be referenced by the [browser key](https://docs.npmjs.com/files/package.json#browser) in the package.json file
