### ISSUE TITLE
Unable to use html-minifier due to unresolvable dependency of clean-css

### ISSUE THREAD

**Issue by deejain** [kangax/html-minifier#903]
### Environment

* clean-css version - `npm ls clean-css`:
```
├─┬ html-minifier@3.5.13
│ └── clean-css@4.1.11 
```
* node.js version - `node -v`: `v7.10.1`
* operating system: OS X 10.13.4

### Steps
- Install html-minifier via `npm install html-minifier --save-dev` (I suspect 
- Try to use html-minifier within an Angular test: `ng test`

### Results

Error indicating the following.
```
ERROR in ./node_modules/clean-css/lib/reader/read-sources.js
Module not found: Error: Can't resolve 'fs' in '/Users/dj.jain/git/signal-unity/node_modules/clean-css/lib/reader'
 @ ./node_modules/clean-css/lib/reader/read-sources.js 1:9-22
 @ ./node_modules/clean-css/lib/clean.js
 @ ./node_modules/clean-css/index.js
 @ ./node_modules/html-minifier/src/htmlminifier.js
 @ ./src/app/services/markdown.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts
```

I manually installed `fs` via `npm install fs --save-dev`.   However, that didn't resolve the issue.   Is there something I'm missing?

**Comment by deejain** [comment]
I just realized that `fs` is likely part of `node`.  So, using html-minifier within Angular for minification within my unit tests (to test output of a markdown library) is likely not a use case that's supported.

Is there any way that I can workaround this limitation?  It would be great if I could use your library for my use case.

**Comment by alexlamsl** [comment]
Try the browser bundle which is used within http://kangax.github.io/html-minifier/

https://github.com/kangax/html-minifier/tree/gh-pages/dist
