### ISSUE TITLE
Whitespace around <ruby> is removed

### ISSUE THREAD

**Issue by YodasWs** [kangax/html-minifier#904]
`<ruby>` is an inline tag, yet the minifier is removing all whitespace that surrounds it.

### Input
```html
<p>I love to eat <ruby lang="fr">pain au chocolat<rt lang="en-US">chocolate croissants</rt></ruby> and éclairs.</p>
```

### Expected
I would not expect the above line to have any changes.

### Actual
I am actually getting this output:
```html
<p>I love to eat<ruby lang="fr">pain au chocolat<rt lang="en-US">chocolate croissants</rt></ruby> and éclairs.</p>
```
Which would get displayed like this in a browser:
```txt
I love to eatpain au chocolatand éclairs.
```

## `<rp>`
:warning: You will also need to test and potentially correct whitespace in/around `<rp>`. E.g.:
```html
<p>I love to eat <ruby lang="fr">pain au chocolat<rp> (</rp><rt lang="en-US">chocolate croissants</rt><rp>)</rp></ruby> and éclairs.</p>
```
ℹ️ Notice the space before the opening parenthesis in the first `<rp>`.

## also
This was found in `html-minifier` version `3.5.6`.

**Comment by alexlamsl** [comment]
Pull Request welcomed.
