### ISSUE TITLE
Minifying leaves spaces

### ISSUE THREAD

**Issue by samuelt1** [kangax/html-minifier#912]
If you minify an img tage like this: 
```
<div>
<img>
<img>
</div>
```
You will get `<div><img> <img></div>`. This is a problem if your div is inline because the extra space could cause your perfectly spaced inline elements to be pushed onto two lines rather than one.

**Comment by alexlamsl** [comment]
Please demonstrate how the minified result is different from the original input.

**Comment by samuelt1** [comment]
I did...?
Original:
```
<div>
<img>
<img>
</div>
```
minified:
```
<div><img> <img></div>
```
