### ISSUE TITLE
javascript inside <script> tag is not minified

### ISSUE THREAD

**Issue by tomerb15** [kangax/html-minifier#917]
Hi,
I have the following configuration object:
```
{
    collapseWhitespace: true,
    conservativeCollapse: true,
    keepClosingSlash: true,
    minifyCSS: true,
    minifyJS: true,
    minifyURLs: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes:true,
    removeComments: true
}
```

For some reason a `<script>` tag which is located at the very end of the `<body>` tag, is not minified.

Am i doing something wrong here? If not i'll be happy to upload the entire HTML.

**Comment by alexlamsl** [comment]
Most likely because you have ES6 instead of JavaScript within the `<script>`.

**Comment by tomerb15** [comment]
Thanks, I'll check it out

**Comment by alexlamsl** [comment]
Closing as answered - if you still have problems afterwards, please upload the file in question.

**Comment by ynwd** [comment]
I have same problem

https://github.com/kangax/html-minifier/issues/1076
