### ISSUE TITLE
how to set minify-css value in the html-minifier command?

### ISSUE THREAD

**Issue by anlexN** [kangax/html-minifier#919]
i want clean-css optionmize level 2, how to do ?
```html-minifier --minifier-css { level: 2 } index.html```
or
```html-minifier --minifier-css -o2 index.html```
or
```html-minifier --minifier-css --level 2 index.html```

**Comment by alexlamsl** [comment]
Use `--config-file` with JSON

**Comment by anlexN** [comment]
please update document ! i can not see `--config-file` usage.

**Comment by alexlamsl** [comment]
Please learn the basics of using command line tools: `html-minifier --help`
