### ISSUE TITLE
Readme is not updated to recent option change from html5 -> no-html5

### ISSUE THREAD

**Issue by gnani-g** [kangax/html-minifier#925]
You have changed the flag -html5 to -no-html5. Doc files are not updated to reflect this.

**Comment by alexlamsl** [comment]
https://github.com/kangax/html-minifier/issues/919#issuecomment-386233733

**Comment by agross** [comment]
This was a breaking change for me as I call html-minifier from an external script. In case you follow semver this would have warranted to be released as 4.x as it is a breaking change to the command line "API".

**Comment by mindhaq** [comment]
same here. changing this in a minor version broke my build.

Also, now I don't know what this flag really does. The help documentation does not really make any sense now.

    --no-html5                           Parse input according to HTML5 specifications
