### ISSUE TITLE
Tags removed from conditionals

### ISSUE THREAD

**Issue by ghost** [kangax/html-minifier#926]
Some attributes have been omitted for brevity. Have I misconfigured the options or is this a bug?

---

**Unminified**

```
<!--[if mso]><v:roundrect><w:anchorlock/><center><![endif]-->
  <a href="##" style="">
    Click here
  </a>
<!--[if mso]></center></v:roundrect><![endif]-->
```

**Minified (notice the removed closing `</center></v:roundrect>`)**

```
<!--[if mso]><v:roundrect><w:anchorlock/><center><![endif]-->
  <a href="##" style="">
    Click here
  </a>
<!--[if mso]><![endif]-->
```

Using these options from within Gulp

```
.pipe(htmlmin({ collapseWhitespace: true, removeComments: true, sortAttributes: true, sortClassName: true, minifyCSS: true, processConditionalComments: true, removeRedundantAttributes: false, keepClosingSlash: true, html5: false }))`
```

With this version in package.json

`"gulp-htmlmin": "^4.0.0",`

**Comment by alexlamsl** [comment]
`processConditionalComments` assumes complete HTML snippets within each Conditional Comment, and may give undesirable results when given unmatched fragments.
