### ISSUE TITLE
Removing white spacing in custom fragment.

### ISSUE THREAD

**Issue by ghost** [kangax/html-minifier#927]
Hello, how to remove before the `<!DOCTYPE html>` whitespace ? I'm using when `trimCustomFragments` removing all whitespaces in document.

My fragment for php tags.
`ignoreCustomFragments: [ /<\?[\s\S]*?\?>/ ]`

Source file:

```
<?php 
  require 'lib/db.php';
?>
<!DOCTYPE html>

<html>
      <span>This <?php echo 'Man' ?> Online!</span>
</html>
```

Dist file:

```
<?php 
  require 'lib/db.php';
?> <!DOCTYPE html><html><span>This <?php echo 'Man' ?> Online!</span></html>

```

**Comment by alexlamsl** [comment]
`trimCustomFragments` works for me:
```html
$ cat test.html
<?php
  require 'lib/db.php';
?>
<!DOCTYPE html>

<html>
      <span>This <?php echo 'Man' ?> Online!</span>
</html>
```
```html
$ html-minifier test.html --collapse-whitespace --trim-custom-fragments
<?php
  require 'lib/db.php';
?><!DOCTYPE html><html><span>This<?php echo 'Man' ?>Online!</span></html>
```

**Comment by ghost** [comment]
Works but removing all white spaces :) You can look this: ```<span>This<?php echo 'Man' ?>Online!</span>``` This likes "ThisManOnline" output.
We need remove only before the doctype white space.
