### ISSUE TITLE
Values of boolean attributes should not be removed if they are ignored fragments.

### ISSUE THREAD

**Issue by coreyfarrell** [kangax/html-minifier#931]
I'm working on a babel plugin to help minify [lit-html](https://github.com/Polymer/lit-html) templates.  Minimized example of incorrect translation:
```js
import {html} from 'lit-html';

export default function(disabled) {
  return html`<input readonly="readonly" disabled="${disabled}">`;
}
```

The script is processed by a babel plugin which finds the `html` template, rewrites it to `<input readonly="readonly" disabled="${__BABEL HTML MINIFIER PLACEHOLDER__}">`.  This string is then processed with html-minifier.  I'm using the following html-minifier options:
```js
{
	collapseBooleanAttributes: true,
	collapseWhitespace: true,
	ignoreCustomFragments: [/\$\{__BABEL HTML MINIFIER PLACEHOLDER__\}/g],
}
```
This correctly removes the value of `readonly`, but (IMO) incorrect removes the value of `disabled`.  My goal is to have html-minifier collapseBooleanAttributes apply to static attributes only, since `lit-html` uses `disabled="${disabled}" to set/unset the property based on the value of the `disabled` argument.

**Comment by alexlamsl** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/disabled):

> Do not set the attribute to `true`, as this will suggest you can set it to `false` to enable the element again, which is not the case.

**Comment by coreyfarrell** [comment]
That's not how `lit-html` uses this type of dynamic attribute in a template.  When a Javascript template contains `disabled="${disabled}"` lit-html does not include the attribute in the HTML generated. It creates the HTML element without the `disabled` attribute then sets the `element.disabled` property (and resets it each time the disabled variable changes).

**Comment by alexlamsl** [comment]
`lit-html` isn't HTML, which is what this library aims to support.

If you are using boolean tags in a non-standard-compliant way, then avoid the use of `collapseBooleanAttributes`
