### ISSUE TITLE
Always has a space between this

### ISSUE THREAD

**Issue by labuboco** [kangax/html-minifier#933]
![image](https://user-images.githubusercontent.com/17706128/40820103-27a7b6ee-6591-11e8-8f2d-2f85b673e0bb.png)

Any suggestions？

**Comment by alexlamsl** [comment]
Custom fragments have more conservative whitespace preservation rules by default.

You can remove those from the input, or you can try `trimCustomFragments` (refer to https://github.com/kangax/html-minifier/blob/gh-pages/README.md)
