### ISSUE TITLE
Add support for ES6.

### ISSUE THREAD

**Issue by ghost** [kangax/html-minifier#934]
`The requested module 'html-minifier' does not provide an export named 'minify'`

Time for some https://github.com/lebab/lebab 🤙

**Comment by damianobarbati** [comment]
+1 for this: how come this was closed?

On Node with ESM enabled:
```
import { minify as htmlMinify } from 'html-minifier';
=>
SyntaxError: The requested module 'html-minifier' does not provide an export named 'minify'
```

**Comment by ghost** [comment]
Could you open this issue back, it's been a year and I still can't use this project because of the non-existent ES6 support. 
Current solution is to use this right now: https://node-minify.2clics.net/compressors/html-minifier.html
