### ISSUE TITLE
ignoreCustomFragments option added a space

### ISSUE THREAD

**Issue by tim-bradley** [kangax/html-minifier#935]
I wanted custom data attribute `data-srcset` values to be processed like normal `srcset` attribute values.

So I ignored the `data-` prefix with option `ignoreCustomFragments: [/data-/],` (this was in a gruntfile using the grunt-contrib-htmlmin package which uses html-minifier).

The values were processed as I had hoped, but the ignored prefix was returned with a space on the end.

I expected:

`data-srcset="<minified values>"`

I got:

`data- srcset="<minified values>"`

Any help would be appreciated.

Thank you.

**Comment by alexlamsl** [comment]
That's not a use case `ignoreCustomFragments` supports.

Your best bet would be to submit a Pull Request enhancing existing `srcset` related optimisation, but you will also need to provide references in the HTML specification that shows `data-srcset` is being processed that way.

**Comment by tim-bradley** [comment]
Thank you @alexlamsl - I'll try figure out how to do a pull request.
