### ISSUE TITLE
some characters prevent minify

### ISSUE THREAD

**Issue by programmersharp** [kangax/html-minifier#936]
`htmlMinifier.minify('<!-->a<-->', {})`  aborts the whole minifying

**Comment by alexlamsl** [comment]
https://www.w3.org/TR/html5/syntax.html#comments

**Comment by programmersharp** [comment]
but it's not a comment, but just html. so, it's intentionally made this way.

**Comment by DamonHD** [comment]
I don't believe the syntax that you have used is valid HTML (The -- is a rather special sequence).  The W3C tool agrees with me, it seems:

Premature end of comment. Use --> to end a comment properly.
