### ISSUE TITLE
Stop protocol insertion in script src

### ISSUE THREAD

**Issue by dirq** [kangax/html-minifier#940]
I have my scripts set up as protocol agnostic, but html-minifer keeps inserting **http:** in front.

For instance, I have: 
`<script src="//cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js"></script>`

but the minifer outputs:
`<script src="http://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js"></script>`

This is breaking things when I publish to the server (page under httpS, and then this is mixed content).

**Comment by alexlamsl** [comment]
Not reproducible using latest version of `html-minifier`
```
$ cat test.html
<script src="//cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js"></script>
```
```
$ html-minifier test.html
<script src="//cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js"></script>
```
