### ISSUE TITLE
html-minifier stopped working all of sudden

### ISSUE THREAD

**Issue by brunoaugusto** [kangax/html-minifier#941]
Until yesterday, I used to have `html-minifier` working with the following line:

````
html-minifier --input-dir "path/to/input/dir" --output-dir "path/to/input/dir" --collapse-whitespace --file-ext html
````
And it always worked.

Then I decided to test two more options, to remove empty elements, mostly to remove empty `<p>` tags wrongly parsed by Hugo; and to minify LD+JSON Structured Data:

````
html-minifier --input-dir "path/to/input/dir" --output-dir "path/to/input/dir" --collapse-whitespace --remove-empty-elements --process-scripts [\"application\/ld+json\"]  file-ext html
````

And it also worked as expected. But at later night it stopped working all of sudden, outputting an HTML source code I can't identify which one because of the shitty little window of Windows prompt. But regardless the file, none of the files in the directory is being affected as they usually were.

I thought the package could be auto-updating itself — that's speculation, my knowledge of Node/NPM is very, very limited — but in any event, I ran:

    npm update -g html-minifier

And "something" happened, I mean, I noticed something being downloaded, but I could see exactly what as it was too fast.

What could possibly be wrong?

**Comment by alexlamsl** [comment]
No idea - try asking `npm` about that.

**Comment by brunoaugusto** [comment]
So, you "have no idea", points me to "npm", which, even though I could search about, right now, I have no idea what it could be — a site, a forum, their own GitHub... — which was hinted by mentioning my little knowledge on the matter and then you simply close the issue. What? Is opened issues bad for business?

Sigh... NPM was only the cancer I subject myself in order to use this project but, nevertheless, it was this project.

**Comment by mohe2015** [comment]
@brunoaugusto I don't know if it helps but maybe try to install from source (see README)
