### ISSUE TITLE
[bug] SVG tags should retain attribute quotes

### ISSUE THREAD

**Issue by ZSkycat** [kangax/html-minifier#948]
version: `"html-minifier": "^3.5.19"`

option
```js
{ removeAttributeQuotes: true }
```

This is the original SVG
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M436 160c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20V48c0-26.5-21.5-48-48-48H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h320c26.5 0 48-21.5 48-48v-48h20c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20v-64h20c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20v-64h20zm-228-32c35.3 0 64 28.7 64 64s-28.7 64-64 64-64-28.7-64-64 28.7-64 64-64zm112 236.8c0 10.6-10 19.2-22.4 19.2H118.4C106 384 96 375.4 96 364.8v-19.2c0-31.8 30.1-57.6 67.2-57.6h5c12.3 5.1 25.7 8 39.8 8s27.6-2.9 39.8-8h5c37.1 0 67.2 25.8 67.2 57.6v19.2z"/></svg>
<!--
Font Awesome Free 5.2.0 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
-->
```

And here is the result after html-minifier:
```xml
<svg xmlns=http://www.w3.org/2000/svg viewBox="0 0 448 512"><path d="M436 160c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20V48c0-26.5-21.5-48-48-48H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h320c26.5 0 48-21.5 48-48v-48h20c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20v-64h20c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20v-64h20zm-228-32c35.3 0 64 28.7 64 64s-28.7 64-64 64-64-28.7-64-64 28.7-64 64-64zm112 236.8c0 10.6-10 19.2-22.4 19.2H118.4C106 384 96 375.4 96 364.8v-19.2c0-31.8 30.1-57.6 67.2-57.6h5c12.3 5.1 25.7 8 39.8 8s27.6-2.9 39.8-8h5c37.1 0 67.2 25.8 67.2 57.6v19.2z"/></svg>
```

result in chrome open
```
This page contains the following errors:
error on line 1 at column 12: AttValue: " or ' expected
Below is a rendering of the page up to the first error.
```

**Comment by alexlamsl** [comment]
This is a Chrome conformance bug.

**Comment by ZSkycat** [comment]
@alexlamsl 
result in Firefox open
```
XML parsing error: poor format
Location: file:///C:/Users/Cat/Desktop/svg.svg
Line 1, column 12:
<svg xmlns=http://www.w3.org/2000/svg viewBox="0 0 448 512"><path d="M436 160c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12 -12-12h-20V48c0-26.5-21.5-48-48-48H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h320c26.5 0 48-21.5 48-48v-48h20c6.6 0 12-5.4 12-12v-40c0 -6.6-5.4-12-12-12h-20v-64h20c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20v-64h20zm-228-32c35.3 0 64 28.7 64 64s -28.7 64-64 64-64-28.7-64-64 28.7-64 64-64zm112 236.8c0 10.6-10 19.2-22.4 19.2H118.4C106 384 96 375.4 96 364.8v-19.2c0-31.8 30.1-57.6 67.2-57.6h5c12 .3 5.1 25.7 8 39.8 8s27.6-2.9 39.8-8h5c37.1 0 67.2 25.8 67.2 57.6v19.2z"/></svg>
-----------^
```

result in Edge open
```
XML5610: Missing quote characters.     svg.svg (1,12)
```

IE11 also can't work.

**Comment by alexlamsl** [comment]
> IE11 also can't work.

I just tested IE11 and I can see an SVG image rendered in front of me.

**Comment by ZSkycat** [comment]
IE
version: 11.165.17134.0
output:
```
XML5610: Missing quote characters.     svg.svg (1,12)
```
![tim 20180808140403](https://user-images.githubusercontent.com/20368649/43819044-f4ee72d4-9b13-11e8-8be3-7b4be091c739.png)

**Comment by ZSkycat** [comment]
`removeAttributeQuotes` need to handle svg tags like `caseSensitive` and `keepClosingSlash`

**Comment by alexlamsl** [comment]
![test](https://user-images.githubusercontent.com/1898413/43819409-589b1b8a-9ad2-11e8-837f-e57aeda3811e.png)

**Comment by ZSkycat** [comment]
Can't think this is a normal behavior because of the wrong implementation of the old IE.
svg is standard xml, but html is not.

**Comment by DamonHD** [comment]
SVG in HTML5 is not vanilla XML as I understand it.  See for example:

http://www.earth.org.uk/note-on-site-technicals-11.html

and:

http://m.earth.org.uk/note-on-site-technicals-11.html

where attributes without quotes for the embedded SVG work fine in all browsers that I can find, and seem to be 'standard' (I can't at this moment find my reference).

Rgds

Damon

**Comment by alexlamsl** [comment]
@DamonHD thanks for the confirmation :+1:

FWIW, Firefox also works with the example in this report:

![test](https://user-images.githubusercontent.com/1898413/43821180-e23e1c70-9ad7-11e8-9973-6663a10d2996.png)

**Comment by ZSkycat** [comment]
Sorry, I found the reason why I can't work.

`*.svg` and `*.html` are not the same.
Can't work in `*.svg`.
Can work in `*.html` 

Thanks for instructions. @DamonHD
