### ISSUE TITLE
Command line documentation?

### ISSUE THREAD

**Issue by JayHoltslander** [kangax/html-minifier#951]
From the docs: 

>For command line usage please see html-minifier --help

I looked there. But it wasn't much help in figuring out why...

``$ html-minifier --file-ext html --input-dir src --output-dir dist``

...results in a new index.html file being generated in my dist folder that's completely unminified and pretty.

Would be nice if there were some better documentation on this. Google was no help either.

**Comment by petervanderdoes** [comment]
I was confused as well, but almost all options are disabled by default.
with some playing around, these options work for me `html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true` The first option is what you would think was on by default, judging by the name of program being minifier. :)

**Comment by JayHoltslander** [comment]
Ugh. Thanks for that. Will try again.

**Comment by alexlamsl** [comment]
Closing as answered.
