### ISSUE TITLE
Bug: Extra space being added before PHP tag

### ISSUE THREAD

**Issue by richardbushell** [kangax/html-minifier#952]
Hi

html-minifier is adding an additional space within a CSS style block before a PHP tag.

We are using the settings:-
collapseWhitespace: true,
removeComments: true,
minifyCSS: true,
minifyJS: {output: {beautify: false, quote_style: 3

Which causes:
color:#PHP_TAG_HERE;
(sorry, couldn't show the PHP Syntax as it is being stripped in this issue panel)
to output:
color:# 123456
(note the space between # and 1)

This bug breaks valid CSS syntax, and therefore the CSS doesn't get applied by the browser.

Obviously this additional space should not be added when minifying CSS.

**Comment by alexlamsl** [comment]
Use ` ``` ` around your example code and they won't get stripped.

**Comment by alexlamsl** [comment]
Whitespace not observed from the output of `html-minifier` - most likely inserted by PHP code instead:
```js
$ node
> var minify = require('html-minifer').minify;
> var options = {
    collapseWhitespace: true,
    removeComments: true,
    minifyCSS: true
  };

> minify('<style>body{color:#<?=bg?>"}</style>', options);
'<style>body{color:#<?=bg?>"}</style>'

> minify('<i style="color:#<?=bg?>"></i>', options);
'<i style="color:#<?=bg?>"></i>'
```
