### ISSUE TITLE
CleanCSS errors are ignored

### ISSUE THREAD

**Issue by felipemsantana** [kangax/html-minifier#953]
[CleanCSS minify method returns an array of errors](https://github.com/jakubpawlowicz/clean-css#minify-method) and it's ignored, should be logged.

https://github.com/kangax/html-minifier/blob/b61dfccfd557167bd97db13091c8fdf7f0f9652a/src/htmlminifier.js#L668

**Comment by alexlamsl** [comment]
Looks like `clean-css` may have changed its error handling behaviour from the older versions:
https://github.com/kangax/html-minifier/blob/6c237eb80858b810aea9086973b30104709cefdc/src/htmlminifier.js#L671

PR is welcome.
