### ISSUE TITLE
How to use html-minifier on Java based projects 

### ISSUE THREAD

**Issue by dryleaf** [kangax/html-minifier#962]
Maybe I am still naive or I simply don't know.

I am trying to use this tool to minify my jsp->html output, 
I need to know how can I can set this up to filter output html for minification.

Can this be achieved for a Java based project?

Any help is welcome.

**Comment by DamonHD** [comment]
If you can run a script, as you can from Java, then you can run this tool, though you may be able to avoid the shell and run NPM JavaScript more directly from the JVM.

Here's the script I use to drive this tool from my makefile (in the directory) above, in case it helps:

http://www.earth.org.uk/script/html5-minify.sh

Rgds

Damon

**Comment by dryleaf** [comment]
@DamonHD thanks, I will try that approach.

**Comment by alexlamsl** [comment]
Closing as answered.
