### ISSUE TITLE
html file with mustache template error

### ISSUE THREAD

**Issue by HCorte** [kangax/html-minifier#968]
using the command line to minifie a html file: 

html-minifier --collapse-whitespace --remove-comments --ignore-custom-fragments "<.*?{{.*?}}.*?>"  --minify-css true --minify-js true --input-dir Minify --output-dir Minify

without the option  --ignore-custom-fragments "<.*?{{.*?}}.*?>"  gives error in the follow div (using mustache template).

`<div class="{{itensgalleryclass}} {{#ShowFadeEffects}}aos-item{{/ShowFadeEffects}} " {{#ShowFadeEffects}}data-aos="{{FadeEffectName}}" data-aos-once="true" data-aos-duration="800"{{/ShowFadeEffects}}>`

the problem is that with that option it doesn't seem to minifie well...

[beforeafther.zip](https://github.com/kangax/html-minifier/files/2419463/beforeafther.zip)

**Comment by HCorte** [comment]
any feedback on this issue? is the command given wrong or is it a html-minifier bug?

**Comment by alexlamsl** [comment]
`--ignoreCustomFragments (?:{{[\s\S]*?}})` works fine for the example above.
