### ISSUE TITLE
Minify <!doctype html> into <!doctypehtml>

### ISSUE THREAD

**Issue by mathiasbynens** [kangax/html-minifier#969]
@krijnhoetmer pointed out that per https://html.spec.whatwg.org/multipage/parsing.html#parse-error-missing-whitespace-before-doctype-name, `<!doctypehtml>` behaves just like `<!doctype html>`. It’s a parse error and thus technically invalid HTML, but it still successfully triggers standards mode!

> This error occurs if the parser encounters a DOCTYPE whose "DOCTYPE" keyword and name are not separated by ASCII whitespace. In this case the parser behaves as if ASCII whitespace is present.

**Comment by mathiasbynens** [comment]
This could be done if the `removeTagWhitespace` setting is enabled. The docs already warn that this can result in invalid HTML.

**Comment by Billybangleballs** [comment]
It needlessly 'converts' 
<link rel="canonical" href="https://www.example.com">
 to 
<link href=https://www.example.com rel=canonical>
