### ISSUE TITLE
No longer able to pipe using shell since 3.5.20

### ISSUE THREAD

**Issue by thinkloop** [kangax/html-minifier#973]
I pipto html-minifier in package.json like so: 

`cat $npm_package_config_src_html | html-minifier --remove-comments > index.html`

Ever since 3.5.20 it outputs an empty <html></html> file. If I downgrade back to 3.5.19 piping works again.

**Comment by DamonHD** [comment]
I also am seeing this and have had to remove @latest and install @3.5.19.

(Host RPi3 / Raspbian based on stretch.)

**Comment by thinkloop** [comment]
It seems to have been fixed in v3.5.21, closing.
