### ISSUE TITLE
Removing new lines from non-standard attribute's value (e.g. ng-class)

### ISSUE THREAD

**Issue by yahyaKacem** [kangax/html-minifier#98]
HI, I'm using [AngularJS](http://angularjs.org) when I put this code into your [online minifire](http://kangax.github.io/html-minifier/) or with [grunt-contrib-htmlmin](https://github.com/gruntjs/grunt-contrib-htmlmin):

```
<div 
  class="fragment square"
  ng-hide="square1.hide"
  ng-class="{
    'bounceInDown': !square1.hide,
    'bounceOutDown': square1.hide
  }"
>
</div>
<img
  class="pull-left"
  alt="First image test"
  src="http://placehold.it/400x200&text=first image test"
>
```

I get this:

```
<div class="fragment square" ng-hide=square1.hide ng-class="{
    'bounceInDown': !square1.hide,
    'bounceOutDown': square1.hide
  }"></div><img class=pull-left alt="First image test" src="http://placehold.it/400x200&text=first image test">
```

As shown the content of the [ng-class](http://code.angularjs.org/1.2.2/docs/api/ng.directive:ngClass) is not minified.

**Comment by kangax** [comment]
The problem is that minifier doesn't know how to handle (=clean) "ng-class" attribute. It strips newlines from standard "class", but obviously doesn't know anything about "ng-class".

We could add support for specifying which other attributes to "clean", but there's 2 types of cleaning: `trimWhitespace` and `collapseWhitespace`. Moreover, some attributes might require even more specific handling (e.g. removing quotes or stripping some kind of prefixes (e.g. "javascript:"), etc.).

Thoughts?

**Comment by XhmikosR** [comment]
I guess it makes sense to allow specifying custom attributes for both types. Not sure how hard this will be to add though.

If there's any request in the future you can always add more features :)

**Comment by mhulse** [comment]
Angular has some interesting syntax. I've been meaning to check it out, just haven't had the opportunity.

Honestly, I don't really understand why Angular isn't using `data-` prefixes for attributes. Additionally, does Angular recommend that people use multiple lines for attributes? Personally, I rarely spread a tag across multiple lines for the sake of the attribute value.

With that said (keep in mind, I'm not familiar with AngularJS needs/requirements/syntax-specifics) ...

I'm reminded of HTML5 `data-` attributes. For example, this:

``` html
<input id="bigglesworth" type="search" name="q" placeholder="&hellip; search &hellip;" autocomplete="off" data-bigglesworth-options='{
    "feed" : "feeds/search.json"
}'>
```

... get's converted to:

``` html
<input id=bigglesworth type=search name=q placeholder="&hellip; search &hellip;" autocomplete=off data-bigglesworth-options="{
    \"feed\" : \"feeds/search.json\"
}">
```

#### A few observations:
1. The JSON outer quotes are modified and the inner quotes are escaped.
2. As you can see above, my indentation is left alone.

#### My thoughts:

**Thought `#1`:**

Looking at the original example, one could easily do:

``` html
<div class="fragment square" ng-hide="square1.hide" ng-class="{ 'bounceInDown': !square1.hide, 'bounceOutDown': square1.hide }"></div>
<img class="pull-left" alt="First image test" src="http://placehold.it/400x200&text=first image test">
```

... and get this output:

``` html
<div class="fragment square" ng-hide=square1.hide ng-class="{ 'bounceInDown': !square1.hide, 'bounceOutDown': square1.hide }"></div><img class=pull-left alt="First image test" src="http://placehold.it/400x200&text=first image test">
```

While having all the attributes, and their values, on one line might be less readable, it's definitely not out of the ordinary (at the very minimum, it would be a quick fix for the OP). :+1: 

**Thought `#2`:**

Looking at the example I posted above, before having run it in the minifier, I personally would have assumed the minifier would've ignored my `data-` attribute value.

I guess I'd prefer that custom `data-` attributes be left alone. I just have never been in a situation where I've needed minification of `data-` attribute values (which are similar to Angular's implementation).

---

With that said, I suppose there's nothing wrong with adding a new option(s).

Perhaps an attribute "whitelist" option? Where, if an attribute is in the whitelist, then it's included in the `trimWhitespace` and `collapseWhitespace` functionality?

Honestly, I'll have to look at the code to refresh my memory, but it seems like a whitelist option (with regex capabilities) would be the way to go ... no?

Going back to my first comments, I wonder why AngularJS doesn't use `data-` as a prefix for the attributes? I could be wrong, but I've always been under the assumption that prefixing `data-` was the official way of writing custom HTML5 attributes? It would be easier for us to whitelist anything that starts with `data-` than to account for regex. Not impossible, just more juggling needs to be done when allowing the end user that type of freedom.

**Comment by mhulse** [comment]
Really though, if you think about it, the AngularJS attributes, and the example I posted, are just ways of passing objects into Javascript, no? I suppose there's less of a chance that these attributes will contain anything more complex than JSON strings or javascript object syntax ... It'd boil down to the end user knowing their markup to make that decision I suppose. Just thought it was worth pointing this out, because the minifier avoids minifying embeded JS blocks, for good reasons ... These attributes are similar in that they contain a whole new level of syntax requirements. Isn't there an issue for JS minification? #56 right? Maybe this issue could be rolled into that issue?

It might even be a good time to talk about bringing in a new library for the JS/CSS minification support?

**Comment by XhmikosR** [comment]
There is grunt-htmlcompressor but requires Java since YUI and Closure require Java.

**Comment by kangax** [comment]
@mhulse Yep, I was thinking about additional whitelist-like properties as well. Just realized there's 3rd option, and so we can have 3 additional properties:

```
trimAttrs, collapseAttrs, booleanAttrs
```

For example:

```
minify('...', {
  trimAttrs: 'ng-class',
  collapseAttrs: 'ng-something-else',
  booleanAttrs: 'ng-disabled'
});
```

`trimAttrs` would trim attribute value, `collapseAttrs` would collapse it, and `booleanAttrs` would remove it altogether.

On the other hand... I can see quite a bit of repetition with this kind of approach:

```
minify('...', {
  trimAttrs: 'ng-class, ng-disabled, ng-something-else',
  collapseAttrs: 'ng-class, ng-disabled, ng-something-else',
  booleanAttrs: 'ng-class, ng-disabled, ng-something-else'
});
```

.. which means that we could have alternative like this:

```
minify('...', {
  attrValueRules: {
    'ng-class': 'trim,collapse',
    'ng-disabled': 'remove',
    'ng-something-else': 'trim'
  }
});
```

I rather like this last option; feels concise and flexible. The only thing it wouldn't take care of is redundant attributes (where minifier deletes not only attribute value — as in boolean attribute — but also attribute name itself; e.g. default `method="get"` on forms, or default `type="text/javascript"` on scripts, etc.).

**Update**: thinking more about this, we would probably want regex support to allow for something like "ng-*" and avoid listing all of ng-... attributes. In that case, perhaps tag name as a key in a "hash" is not the best way to go.

Perhaps:

```
minify('...', {
  attrValueRules: [
    [ /ng-*/, 'trim,collapse' ],
    [ 'data-disabled', 'remove' ]
  ]
});
```

**Comment by mhulse** [comment]
@kangax I really like the looks of your last example. Thanks for the feedback. :+1: 

This logic would be related to the work I started over here: #83. I've been meaning to get back to that issue ... Other things have gotten in the way since I last left off there.

I need to refresh my memory in terms of the minifier code. I'll take a look at both issues to see where I can help. If it looks like something I can tackle, I post back here with my thoughts and potentially a PR (or soon there after).

**Comment by mhulse** [comment]
Sorry I haven't gotten back to ya'll lately. I've been very busy with my day job. I'm not sure when I'll be able to get to this. I would not be opposed to someone else working on this PR. I'm on vacation for the next few weeks ... I hate to keep postponing work on this PR, but I'm hopeful to find the free time when I get back to do a PR. :+1:

**Comment by kangax** [comment]
No worries.

**Comment by remcohaszing** [comment]
Since in most cases these attributes are JavaScript, why not simply pass these values to uglify? It has been implemented for on-\* attributes, so it could be optional to pass a list of custom uglifiable attributes through the options.

**Comment by kangax** [comment]
@remcohaszing it might work for Angular but there might be other cases. I'd want to have more generic solution.

**Comment by ahoereth** [comment]
Whats the status on this one?

**Comment by kangax** [comment]
If @mhulse can finish this one, that would be super awesome! :)

**Comment by anymos** [comment]
+1, no a big priority but could be a good cherry on the cake to have

**Comment by jessehattabaugh** [comment]
Just to give you a couple more use cases for this;

Knockout's data-bind attrs are essentially JSON as well. I'm not sure they recommend it but breaking them into new lines and indenting sure does make them easier to read.

```
<div data-bind="
  css: {
    fadeIn: selected(),
    fadeOut: !selected()
  },
  visible: function () {
    // yes sometimes there are function literals
    return pageWeAreOn() == 'home';
  }
">foo</div>
```

Also, style attributes really benefit from newlines.

```
<div style="
  color: red;
  font-size: 100em;
">bar</div>
```

**Comment by kangax** [comment]
@jessehattabaugh what about JS single-line comments?

Striping newlines from your 1st example gives this:

``` html
<div data-bind="css: {fadeIn: selected(),fadeOut: !selected()},visible: function () {// yes sometimes there are function literalsreturn pageWeAreOn() == 'home';}">foo</div>
```

.. which is no good.

**Comment by kangax** [comment]
Another example is string literals:

``` html
<div data-bind="visible: function () { return smth() == 'spaces   in between' }">foo</div>
```

If we collapse whitespace in that attribute value, it will give us:

``` html
<div data-bind="visible:function(){returnsmth()=='spacesinbetween'}">foo</div>
```

.. which is completely incorrect. In this case, collapsing all spaces to 1 could make more sense:

``` html
<div data-bind="visible: function () { return smth() == 'spaces in between' }">foo</div>
```

..but it would still be a problem with string literals — notice 3 spaces in there, which would collapse into 1.

**Comment by kangax** [comment]
I've added support for `customAttrCollapse` for now, which simply removes newlines from attributes specified via regex. I think this will cover at least 90% of the cases and if more granularity is needed, we can revisit it in the future.

**Comment by jessehattabaugh** [comment]
Thanks!
