### ISSUE TITLE
not working-Failed to construct 'Worker'

### ISSUE THREAD

**Issue by datepickerUser** [kangax/html-minifier#981]
I am totally new to this...I opened the Index.html in the main directory--pasted my HTML code and clicked on the minify button
Nothing happens
In console it shows error:

master.js:21 Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///C:/aPORTABLE%20Programs/html-minifier-gh-pages/assets/worker.js' cannot be accessed from origin 'null'.
    at file:///C:/aPORTABLE%20Programs/html-minifier-gh-pages/assets/master.js:21:18
    at file:///C:/aPORTABLE%20Programs/html-minifier-gh-pages/assets/master.js:138:3

**Comment by alexlamsl** [comment]
That's not how things work.

I guess for you the easiest way is to go to https://kangax.github.io/html-minifier/ and use it there.
