### ISSUE TITLE
close tag `</meta>` got remove

### ISSUE THREAD

**Issue by bluelovers** [kangax/html-minifier#982]
epub need use `</meta>`

https://idpf.github.io/epub-vocabs/package/meta/meta.html#ex-6-example-6-the-following-examples-shows-that-a-publication-is-second-in-the-lord-of-the-rings-set-of-books-metadata-meta-property-belongs-to-collection-id-c01-the-lord-of-the-rings-meta-meta-refines-c01-property-collection-type-set-meta-meta-refines-c01-property-group-position-2-meta-metadata

```html
<meta refines="#c01" property="group-position">2</meta>
```

Expected behavior:

```html
<meta refines="#c01" property="group-position">2</meta>
```

Actual behavior:

```html
<meta refines="#c01" property="group-position">2
```

**Comment by alexlamsl** [comment]
What you have isn't HTML - according to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
> As it is a void element, the start tag must be present and the **end tag must not be present**.
