### ISSUE TITLE
html-minifier is get different results on linux and MAC

### ISSUE THREAD

**Issue by mailylqj** [kangax/html-minifier#984]
I have a Html template as this:

        <div class="user_s00000">

		<style>
		.J_ModuleWrap .user_s00000{ position:relative; z-index:5; background:url(//img13.360buyimg.com/zx/jfs/t1/22150/12/191/83743/5c07ab1bEdeb1f8e7/2be805357908913d.jpg) center center repeat; height:60px; }

		/*-----  标题颜色 !固定的!  -----*/
		.user_title_1{ color:#888888}
		
		/*-----  白色背景 !固定的!  -----*/
		.user_bgcolor_3{ background-color:#ffff}
		
		/*-----  白色字体 !固定的!  -----*/
		.user_color_3{color:#ffffff;}
		
		/*-----  一般无连接字体 !固定的!  -----*/
		.user_color_5{color:#888888;}
				
		/*-----  标签颜色 !固定的!  -----*/
		.user_color_6{color:#666666;}
		
		/*-----  边框颜色 !固定的!  -----*/
		.user_border_1{border:1px solid #dedede;transition:all 0.4s ease;}
		
		 .user_border_bottom{ border-bottom:1px solid #dedede;}
             </style>
        </div>

I use art-template to render this template, in my owen MAC it' s result is goods, but in my linux server online it's result is false;

**Comment by alexlamsl** [comment]
Check you have the same version of `html-minifier` or that you don't have any character encoding issues.

It is unlikely an issue with this project.
