### ISSUE TITLE
closing slash not work well with <input></input>

### ISSUE THREAD

**Issue by YikaJ** [kangax/html-minifier#988]
![image](https://user-images.githubusercontent.com/8725110/51319171-503bf000-1a97-11e9-9bd7-82cebf43b2a6.png)

Every customer element works well except `<input></input>`.

**Comment by NewFuture** [comment]
+1

**Comment by alexlamsl** [comment]
Working as per specification.

**Comment by tyonly** [comment]
+1 I has the same 'input' error.

**Comment by tyonly** [comment]
I have fix it when I modify some code
