### ISSUE TITLE
tensor

### ISSUE THREAD

**Issue by ra-esmith** [kangax/html-minifier#989]
terser not tensor :-)

**Comment by C-Lodder** [comment]
@ra-esmith Are you referring to `Terser` (https://www.npmjs.com/package/terser) ?

**Comment by ra-esmith** [comment]
right terser, thanks ... :-)

**Comment by C-Lodder** [comment]
I've just tested it and it's working perfectly fine. I'll submit a PR

**Comment by C-Lodder** [comment]
PR: https://github.com/kangax/html-minifier/pull/993
