### ISSUE TITLE
How to remove the console.log statements?

### ISSUE THREAD

**Issue by qiuyu303** [kangax/html-minifier#991]
How to remove the console.log statements?

**Comment by leem32** [comment]
@zhouyupeng You can remove console.log statements with:
`--minify-js {\"compress\":{\"pure_funcs\":[\"console.log\"]}}`

From my testing, this will remove logs containing a string e.g `console.log("foo")`, but not variables. 
Logs containing variables e.g `console.log(arg)` will become `arg`.
So although the `console.log()` is removed, the variable remains.

**Comment by qiuyu303** [comment]
> @zhouyupeng You can remove console.log statements with:
> `--minify-js {\"compress\":{\"pure_funcs\":[\"console.log\"]}}`
> 
> From my testing, this will remove logs containing a string e.g `console.log("foo")`, but not variables.
> Logs containing variables e.g `console.log(arg)` will become `arg`.
> So although the `console.log()` is removed, the variable remains.
tkx i get it
