### ISSUE TITLE
found 3 vulnerabilities (2 low, 1 high)

### ISSUE THREAD

**Issue by PrabhanshuAttri** [kangax/html-minifier#992]
npm run audit shows `found 3 vulnerabilities (2 low, 1 high)`

Found in `hexo-html-minifier` which has a dependency on `html-minifier`

![screenshot 2019-01-24 at 4 14 24 pm](https://user-images.githubusercontent.com/4739486/51673529-3436d200-1ff4-11e9-8b33-51e492c07450.png)

**Comment by alexlamsl** [comment]
They are probably using an old version of `html-minifier` - we don't use `uglify-js@2.x` for a very long time now.
