### ISSUE TITLE
Why does defer become defer="defer"? How to remain it unchanged?

### ISSUE THREAD

**Issue by sgon00** [kangax/html-minifier#997]
Hi, I am executing the following command

```
html-minifier --collapse-whitespace --remove-comments index.html -o index.min.html
```

After the execution, html-minifier modifies my `<script defer` to become `<script defer="defer"`. Why? Any reasons? I want to remain `defer` unchanged. Thanks a lot.

**Comment by DamonHD** [comment]
Also use:

     --collapse-boolean-attributes

Rgds

Damon

**Comment by alexlamsl** [comment]
Closing as answered.
