### ISSUE TITLE
minify-js not working?

### ISSUE THREAD

**Issue by cgthayer** [kangax/html-minifier#999]
Probably user error, but "--minify-js true" isn't working even though I have **uglifyjs** installed (npm install uglify-js -g).  I'm sure this was working about 4 months ago when I last minified.

```
html-minifier \
                --collapse-whitespace --remove-comments --remove-optional-tags \
                --remove-redundant-attributes --remove-script-type-attributes \
                --remove-tag-whitespace --use-short-doctype --minify-css true \
                --minify-js true chooser.html-source > chooser.html

```
Output seems to still have <script> block un-minified:

```
</div></div></div><script>// test with:
  console.log("Starting")


  window.fbAsyncInit = function() {
    // console.log('FB init')
    FB.init({
      appId            : 'XXXX',
      autoLogAppEvents : true,
      xfbml            : true,
      version          : 'v3.1'
    });
    // console.log('FB check')

```

**Comment by arpowers** [comment]
Having the same issue.

**Comment by XhmikosR** [comment]
It doesn't matter if you have installed uglify-js globally, because it's installed when you install html-minifier.

My suggestion is to just reinstall the latest html-minifier version and it should work.

**Comment by adriaandotcom** [comment]
I have the same issue. Running:

```
html-minifier --minify-js true index2.html > index.html
```

```
$ html-minifier --version
4.0.0
```

**Comment by JosefJezek** [comment]
@XhmikosR Having the same issue.

**Comment by cgthayer** [comment]
Thanks. I'll retry when I have a sec

**Comment by movahhedi** [comment]
I'm still having this issue. I'm running it on a PHP-HTML-JS file with `ignoreCustomFragments: [ /(<[%\?])([\s\S]*?)(([%|\?]>)|$(?![\r\n]))/ ]`.
